import type { RuntimeMessageId, RuntimeMessages } from "../i18n";

export const EN_RUNTIME_MESSAGES = {
    "app.loading.eyebrow": "Loading",
    "app.loading.title": "Preparing dashboard state",
    "app.loading.detail": "Initializing the dashboard store and message bus.",
    "app.error.eyebrow": "State Unavailable",
    "app.error.title": "Initialization did not complete",
    "app.error.detail_fallback": "The app state could not be loaded from extension storage or local preview storage.",
    "common.actions.retry": "Retry",
    "common.actions.settings": "Settings",
    "common.actions.refresh": "Refresh",
    "common.actions.refresh_all": "Refresh All",
    "common.actions.back": "Back",
    "common.actions.open_dashboard": "Open dashboard",
    "common.actions.open_settings": "Open settings",
    "common.actions.open_dashboard_tab": "Open dashboard tab",
    "common.actions.open_settings_tab": "Open settings tab",
    "common.actions.tab": "Tab",
    "common.actions.sidebar": "Sidebar",
    "common.actions.open_sidebar": "Open sidebar",
    "common.actions.save": "Save",
    "common.theme.toggle_to_dark_label": "Dark",
    "common.theme.toggle_to_dark_title": "Switch to dark mode",
    "common.theme.toggle_to_light_label": "Light",
    "common.theme.toggle_to_light_title": "Switch to light mode",
    "dashboard.topbar.title": "AI Usage Dashboard",
    "dashboard.topbar.subtitle": "Usage, credits, and sync health",
    "dashboard.hero.eyebrow": "Overview",
    "dashboard.hero.title": "AI coding quota overview",
    "dashboard.hero.detail": "Official APIs, documented quota policies, and guarded page-parse sources are collected into one release-ready dashboard for refreshes, settings, and provider drill-downs.",
    "dashboard.hero.release_chip": "Material 3 · Release Candidate",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Provider cards",
    "dashboard.providers.detail": "Cards are ordered by severity first, then current access gaps, so the highest-risk providers stay at the top of the dashboard while still exposing the current product contract at a glance.",
    "dashboard.providers.aria": "Provider cards",
    "dashboard.empty.eyebrow": "No Visible Providers",
    "dashboard.empty.detail": "Start in Quick Setup to enable your first provider, then follow the access and usage-page steps before returning to the dashboard.",
    "dashboard.empty.action": "Open Quick Setup",
    "dashboard.summary.aria": "Dashboard summary",
    "dashboard.summary.visible": "Visible",
    "dashboard.summary.healthy": "Healthy",
    "dashboard.summary.needs_access": "Needs Access",
    "dashboard.summary.needs_attention": "Needs Attention",
    "popup.loading.eyebrow": "Toolbar Popup",
    "popup.loading.title": "Loading cached dashboard state",
    "popup.loading.detail": "Preparing the shared quota snapshot for this browser profile.",
    "popup.error.eyebrow": "Toolbar Popup",
    "popup.error.title": "Popup load failed",
    "popup.header.eyebrow": "Toolbar Popup",
    "popup.header.title": "Quick glance",
    "popup.summary.aria": "Popup top summary",
    "popup.guidance.eyebrow": "Popup Guidance",
    "popup.snapshot_status.eyebrow": "Snapshot Status",
    "popup.actions.eyebrow": "Other route",
    "popup.actions.refresh": "Refresh",
    "popup.actions.refreshing": "Refreshing",
    "popup.actions.refresh_title": "Refresh now",
    "popup.actions.refresh_drift_note": "Automatic sync timing is approximate because Chrome alarms may drift while the browser sleeps or the service worker idles.",
    "popup.actions.hide_header_actions": "Hide top actions",
    "popup.actions.show_header_actions": "Show top actions",
    "popup.featured.eyebrow": "Featured providers",
    "popup.featured.single_eyebrow": "Featured provider",
    "popup.triage.eyebrow": "Popup Triage",
    "popup.summary.visible": "Visible",
    "popup.summary.live_ready": "Live ready",
    "popup.summary.setup_blockers": "Setup blockers",
    "popup.summary.policy_only": "Policy-only",
    "settings.topbar.title": "Settings",
    "settings.topbar.subtitle": "Quick setup, appearance, and advanced provider controls",
    "settings.overview.eyebrow": "Settings Overview",
    "settings.overview.title": "Control surface summary",
    "settings.overview.detail": "Use this screen to manage visibility, permissions, credentials, and hybrid source controls. Jump directly to the section you need instead of scanning the full page top to bottom.",
    "settings.overview.aria": "Settings overview",
    "settings.sections.aria": "Settings sections",
    "settings.sections.preferences": "Preferences",
    "settings.sections.visibility": "Visibility",
    "settings.sections.credentials": "Credentials",
    "settings.sections.sources": "Sources",
    "settings.sections.permissions": "Permissions",
    "settings.actions.back_to_top": "Back to top",
    "settings.actions.back_to_top_short": "Top",
    "settings.summary.visible": "Visible",
    "settings.summary.stored_secrets": "Stored Secrets",
    "settings.summary.bound_pages": "Bound Pages",
    "settings.summary.needs_access": "Needs Access",
    "settings.preferences.eyebrow": "Appearance & Sync",
    "settings.preferences.sync_interval_label": "Default sync interval",
    "settings.preferences.seconds": "seconds",
    "settings.preferences.warning_threshold_label": "Warning threshold",
    "settings.preferences.locale_label": "App language",
    "settings.preferences.theme_mode_label": "Theme mode",
    "settings.preferences.motion_mode_label": "Animation effects",
    "settings.preferences.accent_preset_label": "Accent preset",
    "settings.preferences.popup_progress_style_label": "Popup quota style",
    "settings.preferences.popup_circular_row_count_label": "Circular items per row",
    "settings.preferences.popup_circular_row_count_helper": "Applies to popup circle, soft circle, and gauge styles. Line progress stays one item per row.",
    "settings.preferences.popup_circular_row_count.one": "1 per row",
    "settings.preferences.popup_circular_row_count.two": "2 per row",
    "settings.preferences.popup_circular_row_count.three": "3 per row",
    "settings.preferences.popup_circular_row_count.four": "4 per row",
    "settings.preferences.sidebar_progress_style_label": "Sidebar quota style",
    "settings.preferences.full_page_progress_style_label": "Tab quota style",
    "settings.preferences.progress_style.line": "Line",
    "settings.preferences.progress_style.circle": "Circle",
    "settings.preferences.progress_style.circle_soft": "Soft circle",
    "settings.preferences.progress_style.circle_gauge": "Gauge circle",
    "settings.preferences.popup_size_label": "Popup size",
    "settings.preferences.popup_size.compact": "Compact",
    "settings.preferences.popup_size.balanced": "Balanced",
    "settings.preferences.popup_size.wide": "Wide",
    "settings.preferences.popup_corner_label": "Popup corners",
    "settings.preferences.popup_corner.square": "Square",
    "settings.preferences.popup_corner.soft": "Soft",
    "settings.preferences.popup_corner.rounded": "Rounded",
    "settings.preferences.popup_shadow_label": "Popup shadow",
    "settings.preferences.popup_shadow.none": "None",
    "settings.preferences.popup_shadow.soft": "Soft",
    "settings.preferences.popup_shadow.elevated": "Elevated",
    "settings.preferences.action_badge_label": "Toolbar badge",
    "settings.preferences.action_badge_helper": "Choose one or more toolbar badge sources. The visible badge rotates through the selected sources.",
    "settings.preferences.action_badge_mode_label": "Badge selection mode",
    "settings.preferences.action_badge_mode_helper": "Automatic mode shows attention count until provider quota badges are available, then rotates through displayed provider quota badges. Manual mode keeps exactly the badge sources you choose.",
    "settings.preferences.action_badge_mode_auto": "Automatic",
    "settings.preferences.action_badge_mode_manual": "Manual",
    "settings.preferences.action_badge_restore_auto": "Restore automatic",
    "settings.preferences.action_badge_rotation_label": "Badge rotation interval",
    "settings.preferences.action_badge_rotation_helper": "Controls how often the toolbar badge and matching toolbar icon move to the next selected badge source.",
    "settings.preferences.action_badge_rotation_menu_button": "Expand badge rotation presets",
    "settings.preferences.toolbar_icon_label": "Toolbar icon",
    "settings.preferences.toolbar_icon.default": "Default",
    "settings.preferences.toolbar_icon.match_badge": "Match toolbar badge",
    "settings.preferences.toolbar_icon.provider": "Provider icon",
    "settings.preferences.toolbar_icon.custom": "Custom image",
    "settings.preferences.toolbar_icon_provider_label": "Icon provider",
    "settings.preferences.toolbar_icon_custom_label": "Custom toolbar icon",
    "settings.preferences.toolbar_icon_custom_empty": "No custom image",
    "settings.preferences.toolbar_icon_custom_selected": "Custom image selected",
    "settings.preferences.toolbar_icon_custom_clear": "Clear",
    "settings.preferences.ui_font_label": "UI font",
    "settings.preferences.ui_font_helper": "Uses safe local system font stacks across the popup, side panel, full-page tab, and provider detail. No remote fonts are loaded.",
    "settings.preferences.ui_font.default": "Default",
    "settings.preferences.ui_font.system": "System UI",
    "settings.preferences.ui_font.serif": "Serif",
    "settings.preferences.ui_font.mono": "Mono",
    "settings.popup_appearance_preview.eyebrow": "Toolbar popup preview",
    "settings.popup_appearance_preview.title": "Toolbar popup preview",
    "settings.popup_appearance_preview.detail": "Preview the selected popup width, corner, shadow, and quota style before reopening the toolbar popup.",
    "settings.popup_appearance_preview.remaining_label": "Preview remaining",
    "settings.popup_appearance_preview.remaining_error": "Enter a value from 0 to 100.",
    "settings.popup_appearance_preview.open_test_popup": "Open toolbar popup preview",
    "settings.popup_appearance_preview.close_test_popup": "Close toolbar popup preview",
    "settings.popup_appearance_preview.drag_test_popup": "Drag toolbar popup preview",
    "settings.popup_appearance_preview.sample_refresh": "Refresh",
    "settings.popup_appearance_preview.sample_tab": "Tab",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Weekly usage window",
    "settings.preferences.minutes": "minutes",
    "settings.preferences.locale.system": "System",
    "settings.preferences.locale.en": "English",
    "settings.preferences.locale.zh_cn": "Simplified Chinese",
    "settings.preferences.theme_mode.system": "System",
    "settings.preferences.theme_mode.light": "Light",
    "settings.preferences.theme_mode.dark": "Dark",
    "settings.preferences.motion_mode.system": "Follow system",
    "settings.preferences.motion_mode.full": "On",
    "settings.preferences.motion_mode.reduced": "Reduced",
    "settings.preferences.theme_preset.default": "Default Blue",
    "settings.preferences.theme_preset.meadow": "Meadow",
    "settings.preferences.theme_preset.sunset": "Sunset",
    "settings.preferences.theme_preset.custom": "Custom Seed",
    "settings.theme_customization.eyebrow": "Custom Seed",
    "settings.theme_customization.title": "Validated accent seed",
    "settings.theme_customization.detail": "Use one validated #RRGGBB seed instead of editing individual theme tokens. The generated accent roles stay shared across the side panel, popup, and audit hub.",
    "settings.theme_customization.seed_label": "Custom seed color",
    "settings.theme_customization.apply": "Apply custom seed",
    "settings.theme_customization.reset": "Reset to default",
    "settings.theme_customization.preview.aria": "Custom seed preview",
    "settings.theme_customization.preview.primary": "Primary",
    "settings.theme_customization.preview.secondary_container": "Secondary container",
    "settings.theme_customization.preview.tertiary": "Tertiary",
    "settings.visibility.eyebrow": "Provider Visibility",
    "settings.visibility.displayEnabled_detail": "Visible in the dashboard.",
    "settings.visibility.disabled_detail": "Hidden from the dashboard.",
    "settings.credentials.eyebrow": "Credentials",
    "settings.credentials.title": "Stored secrets and workspace config",
    "settings.credentials.detail": "These cards manage extension-local secrets for supported admin and enterprise paths. Personal session-page routes still avoid cookie export and do not ask for manual auth-header paste.",
    "settings.sources.eyebrow": "Source Connections",
    "settings.sources.title": "Hybrid source contracts",
    "settings.sources.detail": "These cards explain whether each provider currently syncs from an official API, a logged-in page session, or documented quota policy, plus the explicit shipped or deferred product contract for each path.",
    "settings.permissions.eyebrow": "Host Access",
    "settings.permissions.title": "Permission controls",
    "settings.permissions.detail": "In extension mode these actions use chrome.permissions. In browser preview mode they fall back to local state simulation.",
    "settings.toast.preferences_saved_title": "Preferences saved",
    "settings.toast.preferences_saved_detail": "Settings are now persisted in local dashboard state for the preview.",
} satisfies RuntimeMessages;

export const RUNTIME_SHELL_MESSAGE_IDS = [
  "app.loading.eyebrow",
  "app.loading.title",
  "app.loading.detail",
  "app.error.eyebrow",
  "app.error.title",
  "app.error.detail_fallback",
  "common.actions.retry",
  "common.actions.settings",
  "common.actions.refresh",
  "common.actions.refresh_all",
  "common.actions.back",
  "common.actions.open_dashboard",
  "common.actions.open_settings",
  "common.actions.open_dashboard_tab",
  "common.actions.open_settings_tab",
  "common.actions.tab",
  "common.actions.sidebar",
  "common.actions.open_sidebar",
  "common.actions.save",
  "common.theme.toggle_to_dark_label",
  "common.theme.toggle_to_dark_title",
  "common.theme.toggle_to_light_label",
  "common.theme.toggle_to_light_title",
  "dashboard.topbar.title",
  "dashboard.topbar.subtitle",
  "dashboard.hero.eyebrow",
  "dashboard.hero.title",
  "dashboard.hero.detail",
  "dashboard.hero.release_chip",
  "dashboard.providers.eyebrow",
  "dashboard.providers.title",
  "dashboard.providers.detail",
  "dashboard.providers.aria",
  "dashboard.empty.eyebrow",
  "dashboard.empty.detail",
  "dashboard.empty.action",
  "dashboard.summary.aria",
  "dashboard.summary.visible",
  "dashboard.summary.healthy",
  "dashboard.summary.needs_access",
  "dashboard.summary.needs_attention",
  "popup.loading.eyebrow",
  "popup.loading.title",
  "popup.loading.detail",
  "popup.error.eyebrow",
  "popup.error.title",
  "popup.header.eyebrow",
  "popup.header.title",
  "popup.summary.aria",
  "popup.guidance.eyebrow",
  "popup.snapshot_status.eyebrow",
  "popup.actions.eyebrow",
  "popup.actions.refresh",
  "popup.actions.refreshing",
  "popup.actions.refresh_title",
  "popup.actions.refresh_drift_note",
  "popup.actions.hide_header_actions",
  "popup.actions.show_header_actions",
  "popup.featured.eyebrow",
  "popup.featured.single_eyebrow",
  "popup.triage.eyebrow",
  "popup.summary.visible",
  "popup.summary.live_ready",
  "popup.summary.setup_blockers",
  "popup.summary.policy_only",
  "settings.topbar.title",
  "settings.topbar.subtitle",
  "settings.overview.eyebrow",
  "settings.overview.title",
  "settings.overview.detail",
  "settings.overview.aria",
  "settings.sections.aria",
  "settings.sections.preferences",
  "settings.sections.visibility",
  "settings.sections.credentials",
  "settings.sections.sources",
  "settings.sections.permissions",
  "settings.actions.back_to_top",
  "settings.actions.back_to_top_short",
  "settings.summary.visible",
  "settings.summary.stored_secrets",
  "settings.summary.bound_pages",
  "settings.summary.needs_access",
  "settings.preferences.eyebrow",
  "settings.preferences.sync_interval_label",
  "settings.preferences.warning_threshold_label",
  "settings.preferences.locale_label",
  "settings.preferences.theme_mode_label",
  "settings.preferences.motion_mode_label",
  "settings.preferences.accent_preset_label",
  "settings.preferences.popup_progress_style_label",
  "settings.preferences.popup_circular_row_count_label",
  "settings.preferences.popup_circular_row_count_helper",
  "settings.preferences.popup_circular_row_count.one",
  "settings.preferences.popup_circular_row_count.two",
  "settings.preferences.popup_circular_row_count.three",
  "settings.preferences.popup_circular_row_count.four",
  "settings.preferences.sidebar_progress_style_label",
  "settings.preferences.full_page_progress_style_label",
  "settings.preferences.progress_style.line",
  "settings.preferences.progress_style.circle",
  "settings.preferences.progress_style.circle_soft",
  "settings.preferences.progress_style.circle_gauge",
  "settings.preferences.popup_size_label",
  "settings.preferences.popup_size.compact",
  "settings.preferences.popup_size.balanced",
  "settings.preferences.popup_size.wide",
  "settings.preferences.popup_corner_label",
  "settings.preferences.popup_corner.square",
  "settings.preferences.popup_corner.soft",
  "settings.preferences.popup_corner.rounded",
  "settings.preferences.popup_shadow_label",
  "settings.preferences.popup_shadow.none",
  "settings.preferences.popup_shadow.soft",
  "settings.preferences.popup_shadow.elevated",
  "settings.preferences.action_badge_label",
  "settings.preferences.toolbar_icon_label",
  "settings.preferences.toolbar_icon.default",
  "settings.preferences.toolbar_icon.match_badge",
  "settings.preferences.toolbar_icon.provider",
  "settings.preferences.toolbar_icon.custom",
  "settings.preferences.toolbar_icon_provider_label",
  "settings.preferences.toolbar_icon_custom_label",
  "settings.preferences.toolbar_icon_custom_empty",
  "settings.preferences.toolbar_icon_custom_selected",
  "settings.preferences.toolbar_icon_custom_clear",
  "settings.preferences.ui_font_label",
  "settings.preferences.ui_font_helper",
  "settings.preferences.ui_font.default",
  "settings.preferences.ui_font.system",
  "settings.preferences.ui_font.serif",
  "settings.preferences.ui_font.mono",
  "settings.preferences.minutes",
  "settings.preferences.locale.system",
  "settings.preferences.locale.en",
  "settings.preferences.locale.zh_cn",
  "settings.preferences.theme_mode.system",
  "settings.preferences.theme_mode.light",
  "settings.preferences.theme_mode.dark",
  "settings.preferences.motion_mode.system",
  "settings.preferences.motion_mode.full",
  "settings.preferences.motion_mode.reduced",
  "settings.preferences.theme_preset.default",
  "settings.preferences.theme_preset.meadow",
  "settings.preferences.theme_preset.sunset",
  "settings.preferences.theme_preset.custom",
  "settings.toast.preferences_saved_title",
  "settings.toast.preferences_saved_detail",
] as const satisfies readonly RuntimeMessageId[];
