import type { ResolvedAppLocale, RuntimeMessages } from "../i18n";

export const CODEX_SESSION_RUNTIME_MESSAGE_OVERRIDES = {
  "zh-TW": {
    "settings.credentials.codex_session_title": "Codex 臨時工作階段 token",
    "settings.credentials.codex_session_state": "僅限目前工作階段",
    "settings.credentials.codex_session_help": "僅供進階復原。只有本機自動探索 ChatGPT 工作階段失敗時，才貼上裸 access token。",
    "settings.credentials.codex_session_input": "臨時 access token",
    "settings.credentials.codex_session_placeholder": "只貼上 token 本身",
    "settings.credentials.codex_session_save": "用於目前瀏覽器工作階段",
    "settings.credentials.codex_session_clear": "清除臨時 token",
    "settings.credentials.codex_session_footer": "token 僅保存在 chrome.storage.session，只會傳送到 chatgpt.com，並會隨瀏覽器工作階段或擴充功能生命週期結束而清除。請勿貼上 Cookie、JSON、refresh token 或 Authorization header。",
  },
  ja: {
    "settings.credentials.codex_session_title": "Codex 一時セッショントークン",
    "settings.credentials.codex_session_state": "このセッションのみ",
    "settings.credentials.codex_session_help": "高度な復旧専用です。ローカルの ChatGPT セッション自動検出が使えない場合に限り、access token 本体を貼り付けます。",
    "settings.credentials.codex_session_input": "一時 access token",
    "settings.credentials.codex_session_placeholder": "token の値だけを貼り付ける",
    "settings.credentials.codex_session_save": "このブラウザセッションで使用",
    "settings.credentials.codex_session_clear": "一時 token を消去",
    "settings.credentials.codex_session_footer": "token は chrome.storage.session にだけ保持され、chatgpt.com にだけ送信されます。ブラウザセッションまたは拡張機能のライフサイクル終了時に消去されます。Cookie、JSON、refresh token、Authorization header は貼り付けないでください。",
  },
  ko: {
    "settings.credentials.codex_session_title": "Codex 임시 세션 토큰",
    "settings.credentials.codex_session_state": "현재 세션 전용",
    "settings.credentials.codex_session_help": "고급 복구 전용입니다. 로컬 ChatGPT 세션 자동 검색을 사용할 수 없을 때만 순수 access token을 붙여 넣으세요.",
    "settings.credentials.codex_session_input": "임시 access token",
    "settings.credentials.codex_session_placeholder": "token 값만 붙여 넣기",
    "settings.credentials.codex_session_save": "현재 브라우저 세션에서 사용",
    "settings.credentials.codex_session_clear": "임시 token 지우기",
    "settings.credentials.codex_session_footer": "token은 chrome.storage.session에만 보관되고 chatgpt.com으로만 전송되며 브라우저 세션 또는 확장 프로그램 수명 주기가 끝나면 삭제됩니다. Cookie, JSON, refresh token 또는 Authorization header를 붙여 넣지 마세요.",
  },
  "es-419": {
    "settings.credentials.codex_session_title": "Token temporal de sesión de Codex",
    "settings.credentials.codex_session_state": "Solo esta sesión",
    "settings.credentials.codex_session_help": "Solo para recuperación avanzada. Pega un access token sin prefijos cuando no esté disponible la detección local automática de la sesión de ChatGPT.",
    "settings.credentials.codex_session_input": "Access token temporal",
    "settings.credentials.codex_session_placeholder": "Pega solo el valor del token",
    "settings.credentials.codex_session_save": "Usar en esta sesión del navegador",
    "settings.credentials.codex_session_clear": "Borrar token temporal",
    "settings.credentials.codex_session_footer": "El token permanece solo en chrome.storage.session, se envía únicamente a chatgpt.com y se borra al finalizar la sesión del navegador o el ciclo de vida de la extensión. No pegues cookies, JSON, refresh tokens ni un encabezado Authorization.",
  },
  "pt-BR": {
    "settings.credentials.codex_session_title": "Token temporário de sessão do Codex",
    "settings.credentials.codex_session_state": "Somente nesta sessão",
    "settings.credentials.codex_session_help": "Somente para recuperação avançada. Cole um access token puro quando a descoberta local automática da sessão do ChatGPT não estiver disponível.",
    "settings.credentials.codex_session_input": "Access token temporário",
    "settings.credentials.codex_session_placeholder": "Cole somente o valor do token",
    "settings.credentials.codex_session_save": "Usar nesta sessão do navegador",
    "settings.credentials.codex_session_clear": "Limpar token temporário",
    "settings.credentials.codex_session_footer": "O token fica apenas em chrome.storage.session, é enviado somente para chatgpt.com e é apagado ao fim da sessão do navegador ou do ciclo de vida da extensão. Não cole cookies, JSON, refresh tokens ou um cabeçalho Authorization.",
  },
  fr: {
    "settings.credentials.codex_session_title": "Token de session Codex temporaire",
    "settings.credentials.codex_session_state": "Session actuelle uniquement",
    "settings.credentials.codex_session_help": "Réservé à la récupération avancée. Collez un access token brut uniquement lorsque la détection locale automatique de la session ChatGPT est indisponible.",
    "settings.credentials.codex_session_input": "Access token temporaire",
    "settings.credentials.codex_session_placeholder": "Collez uniquement la valeur du token",
    "settings.credentials.codex_session_save": "Utiliser pour cette session du navigateur",
    "settings.credentials.codex_session_clear": "Effacer le token temporaire",
    "settings.credentials.codex_session_footer": "Le token reste uniquement dans chrome.storage.session, n'est envoyé qu'à chatgpt.com et est effacé à la fin de la session du navigateur ou du cycle de vie de l'extension. Ne collez pas de cookies, de JSON, de refresh token ni d'en-tête Authorization.",
  },
  de: {
    "settings.credentials.codex_session_title": "Temporäres Codex-Sitzungstoken",
    "settings.credentials.codex_session_state": "Nur diese Sitzung",
    "settings.credentials.codex_session_help": "Nur zur erweiterten Wiederherstellung. Füge ein reines access token nur ein, wenn die automatische lokale Erkennung der ChatGPT-Sitzung nicht verfügbar ist.",
    "settings.credentials.codex_session_input": "Temporäres access token",
    "settings.credentials.codex_session_placeholder": "Nur den Tokenwert einfügen",
    "settings.credentials.codex_session_save": "Für diese Browsersitzung verwenden",
    "settings.credentials.codex_session_clear": "Temporäres Token löschen",
    "settings.credentials.codex_session_footer": "Das Token bleibt nur in chrome.storage.session, wird ausschließlich an chatgpt.com gesendet und am Ende der Browsersitzung oder des Erweiterungslebenszyklus gelöscht. Füge keine Cookies, JSON-Daten, refresh tokens oder Authorization-Header ein.",
  },
  it: {
    "settings.credentials.codex_session_title": "Token temporaneo di sessione Codex",
    "settings.credentials.codex_session_state": "Solo questa sessione",
    "settings.credentials.codex_session_help": "Solo per il recupero avanzato. Incolla un access token semplice quando il rilevamento locale automatico della sessione ChatGPT non è disponibile.",
    "settings.credentials.codex_session_input": "Access token temporaneo",
    "settings.credentials.codex_session_placeholder": "Incolla solo il valore del token",
    "settings.credentials.codex_session_save": "Usa per questa sessione del browser",
    "settings.credentials.codex_session_clear": "Cancella token temporaneo",
    "settings.credentials.codex_session_footer": "Il token resta solo in chrome.storage.session, viene inviato esclusivamente a chatgpt.com e viene cancellato al termine della sessione del browser o del ciclo di vita dell'estensione. Non incollare cookie, JSON, refresh token o un header Authorization.",
  },
  ru: {
    "settings.credentials.codex_session_title": "Временный токен сеанса Codex",
    "settings.credentials.codex_session_state": "Только текущий сеанс",
    "settings.credentials.codex_session_help": "Только для расширенного восстановления. Вставляйте чистый access token, лишь когда автоматическое локальное обнаружение сеанса ChatGPT недоступно.",
    "settings.credentials.codex_session_input": "Временный access token",
    "settings.credentials.codex_session_placeholder": "Вставьте только значение токена",
    "settings.credentials.codex_session_save": "Использовать в текущем сеансе браузера",
    "settings.credentials.codex_session_clear": "Удалить временный токен",
    "settings.credentials.codex_session_footer": "Токен хранится только в chrome.storage.session, отправляется только на chatgpt.com и удаляется по завершении сеанса браузера или жизненного цикла расширения. Не вставляйте Cookie, JSON, refresh token или заголовок Authorization.",
  },
  ar: {
    "settings.credentials.codex_session_title": "رمز جلسة Codex مؤقت",
    "settings.credentials.codex_session_state": "لهذه الجلسة فقط",
    "settings.credentials.codex_session_help": "للاسترداد المتقدم فقط. الصق access token مجردا فقط عند تعذر الاكتشاف المحلي التلقائي لجلسة ChatGPT.",
    "settings.credentials.codex_session_input": "access token مؤقت",
    "settings.credentials.codex_session_placeholder": "الصق قيمة token فقط",
    "settings.credentials.codex_session_save": "استخدامه في جلسة المتصفح هذه",
    "settings.credentials.codex_session_clear": "مسح token المؤقت",
    "settings.credentials.codex_session_footer": "يبقى token في chrome.storage.session فقط، ويرسل إلى chatgpt.com فقط، ويمسح عند انتهاء جلسة المتصفح أو دورة حياة الإضافة. لا تلصق Cookie أو JSON أو refresh token أو ترويسة Authorization.",
  },
  hi: {
    "settings.credentials.codex_session_title": "अस्थायी Codex session token",
    "settings.credentials.codex_session_state": "केवल यह session",
    "settings.credentials.codex_session_help": "केवल उन्नत recovery के लिए। स्थानीय ChatGPT session की स्वचालित खोज उपलब्ध न हो तभी केवल access token चिपकाएं।",
    "settings.credentials.codex_session_input": "अस्थायी access token",
    "settings.credentials.codex_session_placeholder": "केवल token value चिपकाएं",
    "settings.credentials.codex_session_save": "इस browser session में उपयोग करें",
    "settings.credentials.codex_session_clear": "अस्थायी token साफ करें",
    "settings.credentials.codex_session_footer": "token केवल chrome.storage.session में रहता है, केवल chatgpt.com को भेजा जाता है और browser session या extension lifecycle समाप्त होने पर मिट जाता है। Cookie, JSON, refresh token या Authorization header न चिपकाएं।",
  },
  id: {
    "settings.credentials.codex_session_title": "Token sesi Codex sementara",
    "settings.credentials.codex_session_state": "Hanya sesi ini",
    "settings.credentials.codex_session_help": "Hanya untuk pemulihan lanjutan. Tempel access token mentah hanya saat penemuan otomatis sesi ChatGPT lokal tidak tersedia.",
    "settings.credentials.codex_session_input": "Access token sementara",
    "settings.credentials.codex_session_placeholder": "Tempel hanya nilai token",
    "settings.credentials.codex_session_save": "Gunakan untuk sesi browser ini",
    "settings.credentials.codex_session_clear": "Hapus token sementara",
    "settings.credentials.codex_session_footer": "Token hanya disimpan di chrome.storage.session, hanya dikirim ke chatgpt.com, dan dihapus saat sesi browser atau siklus hidup ekstensi berakhir. Jangan tempel Cookie, JSON, refresh token, atau header Authorization.",
  },
} satisfies Partial<Record<ResolvedAppLocale, Partial<RuntimeMessages>>>;
