import type { ResolvedAppLocale, RuntimeMessages } from "../i18n";

export const CJK_RUNTIME_MESSAGE_OVERRIDES = {
  "zh-CN": {
    "app.loading.eyebrow": "加载中",
    "app.loading.title": "正在准备仪表板状态",
    "app.loading.detail": "正在初始化仪表板存储和消息总线。",
    "app.error.eyebrow": "状态不可用",
    "app.error.title": "初始化未完成",
    "app.error.detail_fallback": "无法从扩展存储或本地预览存储加载应用状态。",
    "common.actions.retry": "重试",
    "common.actions.settings": "设置",
    "common.actions.refresh": "刷新",
    "common.actions.refresh_all": "全部刷新",
    "common.actions.back": "返回",
    "common.actions.open_dashboard": "打开仪表板",
    "common.actions.open_settings": "打开设置",
    "common.actions.open_dashboard_tab": "打开仪表板标签页",
    "common.actions.open_settings_tab": "打开设置标签页",
    "common.actions.tab": "标签页",
    "common.actions.save": "保存",
    "common.theme.toggle_to_dark_label": "夜间",
    "common.theme.toggle_to_dark_title": "切换到夜间模式",
    "common.theme.toggle_to_light_label": "白天",
    "common.theme.toggle_to_light_title": "切换到白天模式",
    "dashboard.topbar.title": "AI 用量仪表板",
    "dashboard.topbar.subtitle": "用量、额度与同步健康",
    "dashboard.hero.eyebrow": "概览",
    "dashboard.hero.title": "一个面板掌握 AI 编码配额",
    "dashboard.hero.detail": "官方 API、文档化配额策略与受控页面解析路径，被收敛到一个可发布的仪表板里，用于刷新、设置和 Provider 深入查看。",
    "dashboard.hero.release_chip": "Material 3 · 发布候选",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 卡片",
    "dashboard.providers.detail": "卡片先按严重程度排序，再按当前访问缺口排序，让高风险 provider 保持在顶部，同时保留当前产品合同的一眼可见性。",
    "dashboard.providers.aria": "Provider 卡片",
    "dashboard.empty.eyebrow": "没有可见 Provider",
    "dashboard.empty.detail": "请先进入 Quick Setup 启用第一个 Provider，再按提示完成授权和用量页面步骤，然后回到仪表板。",
    "dashboard.empty.action": "打开 Quick Setup",
    "dashboard.summary.aria": "仪表板摘要",
    "dashboard.summary.visible": "可见",
    "dashboard.summary.healthy": "健康",
    "dashboard.summary.needs_access": "需授权",
    "dashboard.summary.needs_attention": "需关注",
    "popup.loading.eyebrow": "工具栏弹窗",
    "popup.loading.title": "正在加载缓存的仪表板状态",
    "popup.loading.detail": "正在为此浏览器配置文件准备共享配额快照。",
    "popup.error.eyebrow": "工具栏弹窗",
    "popup.error.title": "弹窗加载失败",
    "popup.header.eyebrow": "工具栏弹窗",
    "popup.header.title": "快速概览",
    "popup.summary.aria": "弹窗顶部摘要",
    "popup.guidance.eyebrow": "弹窗引导",
    "popup.snapshot_status.eyebrow": "快照状态",
    "popup.actions.eyebrow": "其他入口",
    "popup.actions.refresh": "刷新",
    "popup.actions.refreshing": "刷新中",
    "popup.featured.eyebrow": "重点 Provider",
    "popup.featured.single_eyebrow": "重点 Provider",
    "popup.triage.eyebrow": "弹窗分诊",
    "popup.summary.visible": "可见",
    "popup.summary.live_ready": "可实时同步",
    "popup.summary.setup_blockers": "配置阻塞",
    "popup.summary.policy_only": "仅策略",
    "settings.topbar.title": "设置",
    "settings.topbar.subtitle": "快速设置、外观与高级 Provider 控制",
    "settings.overview.eyebrow": "设置概览",
    "settings.overview.title": "控制面摘要",
    "settings.overview.detail": "用这个页面管理可见性、权限、凭据和混合 source 控制。直接跳到你需要的部分，而不是从上到下通读整页。",
    "settings.overview.aria": "设置概览",
    "settings.sections.aria": "设置分区",
    "settings.sections.preferences": "偏好",
    "settings.sections.visibility": "可见性",
    "settings.sections.credentials": "凭据",
    "settings.sections.sources": "来源",
    "settings.sections.permissions": "权限",
    "settings.actions.back_to_top": "返回顶部",
    "settings.actions.back_to_top_short": "顶部",
    "settings.summary.visible": "可见",
    "settings.summary.stored_secrets": "已存密钥",
    "settings.summary.bound_pages": "已绑定页面",
    "settings.summary.needs_access": "需授权",
    "settings.preferences.eyebrow": "外观与同步",
    "settings.preferences.sync_interval_label": "默认同步间隔",
    "settings.preferences.warning_threshold_label": "告警阈值",
    "settings.preferences.locale_label": "应用语言",
    "settings.preferences.theme_mode_label": "主题模式",
    "settings.preferences.accent_preset_label": "强调色预设",
    "settings.preferences.popup_progress_style_label": "Popup 额度样式",
    "settings.preferences.sidebar_progress_style_label": "侧栏额度样式",
    "settings.preferences.full_page_progress_style_label": "标签页额度样式",
    "settings.preferences.progress_style.line": "直线",
    "settings.preferences.progress_style.circle": "圆圈",
    "settings.preferences.progress_style.circle_soft": "柔和圆环",
    "settings.preferences.progress_style.circle_gauge": "仪表圆环",
    "settings.preferences.popup_size_label": "Popup 尺寸",
    "settings.preferences.popup_size.compact": "紧凑",
    "settings.preferences.popup_size.balanced": "均衡",
    "settings.preferences.popup_size.wide": "宽版",
    "settings.preferences.popup_corner_label": "Popup 圆角",
    "settings.preferences.popup_corner.square": "直角",
    "settings.preferences.popup_corner.soft": "柔和",
    "settings.preferences.popup_corner.rounded": "圆润",
    "settings.preferences.popup_shadow_label": "Popup 阴影",
    "settings.preferences.popup_shadow.none": "无",
    "settings.preferences.popup_shadow.soft": "轻微",
    "settings.preferences.popup_shadow.elevated": "加强",
    "settings.preferences.action_badge_label": "工具栏图标标记",
    "settings.popup_appearance_preview.eyebrow": "Popup 预览",
    "settings.popup_appearance_preview.title": "工具栏弹窗形态",
    "settings.popup_appearance_preview.detail": "在重新打开 Chrome action 前，先预览当前 popup 宽度、圆角和阴影组合。",
    "settings.popup_appearance_preview.sample_refresh": "刷新",
    "settings.popup_appearance_preview.sample_tab": "标签页",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "每周使用窗口",
    "settings.preferences.minutes": "分钟",
    "settings.preferences.locale.system": "跟随系统",
    "settings.preferences.locale.en": "英语",
    "settings.preferences.locale.zh_cn": "简体中文",
    "settings.preferences.theme_mode.system": "跟随系统",
    "settings.preferences.theme_mode.light": "白天",
    "settings.preferences.theme_mode.dark": "夜间",
    "settings.preferences.theme_preset.default": "默认蓝",
    "settings.preferences.theme_preset.meadow": "草地",
    "settings.preferences.theme_preset.sunset": "日落",
    "settings.preferences.theme_preset.custom": "自定义种子",
    "settings.theme_customization.eyebrow": "自定义种子",
    "settings.theme_customization.title": "已校验的强调色种子",
    "settings.theme_customization.detail": "使用一个经过校验的 #RRGGBB 种子，而不是直接编辑单个主题 token。生成出的强调色角色会在侧栏、popup 和 audit hub 中共享。",
    "settings.theme_customization.seed_label": "自定义种子颜色",
    "settings.theme_customization.apply": "应用自定义种子",
    "settings.theme_customization.reset": "恢复默认",
    "settings.theme_customization.preview.aria": "自定义种子预览",
    "settings.theme_customization.preview.primary": "主色",
    "settings.theme_customization.preview.secondary_container": "次级容器",
    "settings.theme_customization.preview.tertiary": "第三色",
    "settings.visibility.eyebrow": "Provider 可见性",
    "settings.visibility.enabled_detail": "在仪表板中可见。",
    "settings.visibility.disabled_detail": "已从仪表板隐藏。",
    "settings.credentials.eyebrow": "凭据",
    "settings.credentials.title": "已存密钥与工作区配置",
    "settings.credentials.detail": "这些卡片管理扩展本地保存的 admin 和 enterprise 路径凭据。个人 session-page 路径仍然避免 cookie 导出，也不会要求手动粘贴 auth header。",
    "settings.sources.eyebrow": "来源连接",
    "settings.sources.title": "混合来源合同",
    "settings.sources.detail": "这些卡片说明每个 provider 当前是通过官方 API、已登录页面会话，还是文档化 quota policy 同步，同时明确每条路径当前是 shipped 还是 deferred 的产品合同。",
    "settings.permissions.eyebrow": "Host 访问",
    "settings.permissions.title": "权限控制",
    "settings.permissions.detail": "在扩展模式下，这些操作使用 chrome.permissions；在浏览器预览模式下，它们会回退到本地状态模拟。",
    "settings.toast.preferences_saved_title": "偏好已保存",
    "settings.toast.preferences_saved_detail": "当前预览的设置已经持久化到本地仪表板状态。",
  },
  "zh-TW": {
    "app.loading.eyebrow": "載入中",
    "app.loading.title": "正在準備儀表板狀態",
    "app.loading.detail": "正在初始化儀表板儲存與訊息匯流排。",
    "app.error.eyebrow": "狀態無法使用",
    "app.error.title": "初始化未完成",
    "app.error.detail_fallback": "無法從擴充功能儲存空間或本機預覽儲存空間載入應用程式狀態。",
    "common.actions.retry": "重試",
    "common.actions.settings": "設定",
    "common.actions.refresh": "重新整理",
    "common.actions.refresh_all": "全部重新整理",
    "common.actions.back": "返回",
    "common.actions.open_dashboard": "開啟儀表板",
    "common.actions.open_settings": "開啟設定",
    "common.actions.open_dashboard_tab": "開啟儀表板分頁",
    "common.actions.open_settings_tab": "開啟設定分頁",
    "common.actions.tab": "分頁",
    "common.actions.save": "儲存",
    "common.theme.toggle_to_dark_label": "夜間",
    "common.theme.toggle_to_dark_title": "切換到夜間模式",
    "common.theme.toggle_to_light_label": "白天",
    "common.theme.toggle_to_light_title": "切換到白天模式",
    "dashboard.topbar.title": "AI 用量儀表板",
    "dashboard.topbar.subtitle": "用量、額度與同步健康",
    "dashboard.hero.eyebrow": "概覽",
    "dashboard.hero.title": "一個面板掌握 AI 編碼配額",
    "dashboard.hero.detail": "官方 API、文件化配額策略與受控頁面解析路徑，會收斂到一個可發布的儀表板中，用於重新整理、設定和 Provider 深入查看。",
    "dashboard.hero.release_chip": "Material 3 · 發布候選",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 卡片",
    "dashboard.providers.detail": "卡片先按嚴重程度排序，再按目前存取缺口排序，讓高風險 provider 保持在頂部，同時保留目前產品合約的一眼可見性。",
    "dashboard.providers.aria": "Provider 卡片",
    "dashboard.empty.eyebrow": "沒有可見 Provider",
    "dashboard.empty.detail": "請先進入 Quick Setup 啟用第一個 Provider，再依提示完成授權與用量頁面步驟，然後回到儀表板。",
    "dashboard.empty.action": "開啟 Quick Setup",
    "dashboard.summary.aria": "儀表板摘要",
    "dashboard.summary.visible": "可見",
    "dashboard.summary.healthy": "健康",
    "dashboard.summary.needs_access": "需授權",
    "dashboard.summary.needs_attention": "需關注",
    "popup.loading.eyebrow": "工具列彈窗",
    "popup.loading.title": "正在載入快取的儀表板狀態",
    "popup.loading.detail": "正在為此瀏覽器設定檔準備共享配額快照。",
    "popup.error.eyebrow": "工具列彈窗",
    "popup.error.title": "彈窗載入失敗",
    "popup.header.eyebrow": "工具列彈窗",
    "popup.header.title": "快速概覽",
    "popup.summary.aria": "彈窗頂部摘要",
    "popup.guidance.eyebrow": "彈窗引導",
    "popup.snapshot_status.eyebrow": "快照狀態",
    "popup.actions.eyebrow": "其他入口",
    "popup.actions.refresh": "重新整理",
    "popup.actions.refreshing": "重新整理中",
    "popup.featured.eyebrow": "重點 Provider",
    "popup.featured.single_eyebrow": "重點 Provider",
    "popup.triage.eyebrow": "彈窗分診",
    "popup.summary.visible": "可見",
    "popup.summary.live_ready": "可即時同步",
    "popup.summary.setup_blockers": "設定阻礙",
    "popup.summary.policy_only": "僅策略",
    "settings.topbar.title": "設定",
    "settings.topbar.subtitle": "快速設定、外觀與進階 Provider 控制",
    "settings.overview.eyebrow": "設定概覽",
    "settings.overview.title": "控制面摘要",
    "settings.overview.detail": "使用此頁面管理可見性、權限、憑據和混合 source 控制。直接跳到需要的區段，而不是從上到下通讀整頁。",
    "settings.overview.aria": "設定概覽",
    "settings.sections.aria": "設定區段",
    "settings.sections.preferences": "偏好",
    "settings.sections.visibility": "可見性",
    "settings.sections.credentials": "憑據",
    "settings.sections.sources": "來源",
    "settings.sections.permissions": "權限",
    "settings.actions.back_to_top": "返回頂部",
    "settings.actions.back_to_top_short": "頂部",
    "settings.summary.visible": "可見",
    "settings.summary.stored_secrets": "已存密鑰",
    "settings.summary.bound_pages": "已綁定頁面",
    "settings.summary.needs_access": "需授權",
    "settings.preferences.eyebrow": "外觀與同步",
    "settings.preferences.sync_interval_label": "預設同步間隔",
    "settings.preferences.warning_threshold_label": "警示閾值",
    "settings.preferences.locale_label": "應用程式語言",
    "settings.preferences.theme_mode_label": "主題模式",
    "settings.preferences.accent_preset_label": "強調色預設",
    "settings.preferences.popup_progress_style_label": "Popup 額度樣式",
    "settings.preferences.sidebar_progress_style_label": "側欄額度樣式",
    "settings.preferences.full_page_progress_style_label": "分頁額度樣式",
    "settings.preferences.progress_style.line": "直線",
    "settings.preferences.progress_style.circle": "圓圈",
    "settings.preferences.progress_style.circle_soft": "柔和圓環",
    "settings.preferences.progress_style.circle_gauge": "儀表圓環",
    "settings.preferences.popup_size_label": "Popup 尺寸",
    "settings.preferences.popup_size.compact": "緊湊",
    "settings.preferences.popup_size.balanced": "均衡",
    "settings.preferences.popup_size.wide": "寬版",
    "settings.preferences.popup_corner_label": "Popup 圓角",
    "settings.preferences.popup_corner.square": "直角",
    "settings.preferences.popup_corner.soft": "柔和",
    "settings.preferences.popup_corner.rounded": "圓潤",
    "settings.preferences.popup_shadow_label": "Popup 陰影",
    "settings.preferences.popup_shadow.none": "無",
    "settings.preferences.popup_shadow.soft": "輕微",
    "settings.preferences.popup_shadow.elevated": "加強",
    "settings.preferences.action_badge_label": "工具列圖示標記",
    "settings.preferences.minutes": "分鐘",
    "settings.preferences.locale.system": "跟隨系統",
    "settings.preferences.locale.en": "英文",
    "settings.preferences.locale.zh_cn": "簡體中文",
    "settings.preferences.theme_mode.system": "跟隨系統",
    "settings.preferences.theme_mode.light": "白天",
    "settings.preferences.theme_mode.dark": "夜間",
    "settings.preferences.theme_preset.default": "預設藍",
    "settings.preferences.theme_preset.meadow": "草地",
    "settings.preferences.theme_preset.sunset": "日落",
    "settings.preferences.theme_preset.custom": "自訂種子",
    "settings.toast.preferences_saved_title": "偏好已儲存",
    "settings.toast.preferences_saved_detail": "目前預覽的設定已持久化到本機儀表板狀態。",
  },
  ja: {
    "app.loading.eyebrow": "読み込み中",
    "app.loading.title": "ダッシュボード状態を準備中",
    "app.loading.detail": "ダッシュボードストアとメッセージバスを初期化しています。",
    "app.error.eyebrow": "状態を利用できません",
    "app.error.title": "初期化が完了しませんでした",
    "app.error.detail_fallback": "拡張機能ストレージまたはローカルプレビューのストレージからアプリ状態を読み込めませんでした。",
    "common.actions.retry": "再試行",
    "common.actions.settings": "設定",
    "common.actions.refresh": "更新",
    "common.actions.refresh_all": "すべて更新",
    "common.actions.back": "戻る",
    "common.actions.open_dashboard": "ダッシュボードを開く",
    "common.actions.open_settings": "設定を開く",
    "common.actions.open_dashboard_tab": "ダッシュボードタブを開く",
    "common.actions.open_settings_tab": "設定タブを開く",
    "common.actions.tab": "タブ",
    "common.actions.save": "保存",
    "common.theme.toggle_to_dark_label": "ダーク",
    "common.theme.toggle_to_dark_title": "ダークモードに切り替える",
    "common.theme.toggle_to_light_label": "ライト",
    "common.theme.toggle_to_light_title": "ライトモードに切り替える",
    "dashboard.topbar.title": "AI 使用状況ダッシュボード",
    "dashboard.topbar.subtitle": "使用状況、クレジット、同期状態",
    "dashboard.hero.eyebrow": "概要",
    "dashboard.hero.title": "AI コーディングクォータを一画面で把握",
    "dashboard.hero.detail": "公式 API、ドキュメント化されたクォータポリシー、保護されたページ解析ソースを、更新、設定、Provider 詳細確認のためのリリース対応ダッシュボードに集約します。",
    "dashboard.hero.release_chip": "Material 3 · リリース候補",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider カード",
    "dashboard.providers.detail": "カードは重要度を優先し、その次に現在のアクセス不足で並びます。リスクの高い provider をダッシュボード上部に保ちながら、現在のプロダクト契約を一目で確認できます。",
    "dashboard.providers.aria": "Provider カード",
    "dashboard.empty.eyebrow": "表示中の Provider なし",
    "dashboard.empty.detail": "Quick Setup で最初の Provider を有効にし、アクセスと使用状況ページの手順を完了してからダッシュボードに戻ってください。",
    "dashboard.empty.action": "Quick Setup を開く",
    "dashboard.summary.aria": "ダッシュボード概要",
    "dashboard.summary.visible": "表示中",
    "dashboard.summary.healthy": "正常",
    "dashboard.summary.needs_access": "アクセスが必要",
    "dashboard.summary.needs_attention": "要確認",
    "popup.loading.eyebrow": "ツールバーポップアップ",
    "popup.loading.title": "キャッシュ済みダッシュボード状態を読み込み中",
    "popup.loading.detail": "このブラウザプロファイル用の共有クォータスナップショットを準備しています。",
    "popup.error.eyebrow": "ツールバーポップアップ",
    "popup.error.title": "ポップアップの読み込みに失敗しました",
    "popup.header.eyebrow": "ツールバーポップアップ",
    "popup.header.title": "クイック確認",
    "popup.summary.aria": "ポップアップ上部の概要",
    "popup.guidance.eyebrow": "ポップアップガイダンス",
    "popup.snapshot_status.eyebrow": "スナップショット状態",
    "popup.actions.eyebrow": "その他の入口",
    "popup.actions.refresh": "更新",
    "popup.actions.refreshing": "更新中",
    "popup.featured.eyebrow": "注目 Provider",
    "popup.featured.single_eyebrow": "注目 Provider",
    "popup.triage.eyebrow": "ポップアップ優先確認",
    "popup.summary.visible": "表示中",
    "popup.summary.live_ready": "ライブ準備済み",
    "popup.summary.setup_blockers": "設定ブロッカー",
    "popup.summary.policy_only": "ポリシーのみ",
    "settings.topbar.title": "設定",
    "settings.topbar.subtitle": "Quick Setup、外観、高度な Provider 管理",
    "settings.overview.eyebrow": "設定の概要",
    "settings.overview.title": "コントロール画面の概要",
    "settings.overview.detail": "この画面で表示、権限、認証情報、ハイブリッド source 管理を扱います。ページ全体を上から下まで探す代わりに、必要なセクションへ直接移動できます。",
    "settings.overview.aria": "設定の概要",
    "settings.sections.aria": "設定セクション",
    "settings.sections.preferences": "環境設定",
    "settings.sections.visibility": "表示",
    "settings.sections.credentials": "認証情報",
    "settings.sections.sources": "ソース",
    "settings.sections.permissions": "権限",
    "settings.actions.back_to_top": "トップに戻る",
    "settings.actions.back_to_top_short": "トップ",
    "settings.summary.visible": "表示中",
    "settings.summary.stored_secrets": "保存済みシークレット",
    "settings.summary.bound_pages": "バインド済みページ",
    "settings.summary.needs_access": "アクセスが必要",
    "settings.preferences.eyebrow": "外観と同期",
    "settings.preferences.sync_interval_label": "既定の同期間隔",
    "settings.preferences.warning_threshold_label": "警告しきい値",
    "settings.preferences.locale_label": "アプリの言語",
    "settings.preferences.theme_mode_label": "テーマモード",
    "settings.preferences.accent_preset_label": "アクセントプリセット",
    "settings.preferences.popup_progress_style_label": "Popup クォータ表示",
    "settings.preferences.sidebar_progress_style_label": "サイドバーのクォータ表示",
    "settings.preferences.full_page_progress_style_label": "タブのクォータ表示",
    "settings.preferences.progress_style.line": "ライン",
    "settings.preferences.progress_style.circle": "円形",
    "settings.preferences.progress_style.circle_soft": "ソフト円形",
    "settings.preferences.progress_style.circle_gauge": "ゲージ円形",
    "settings.preferences.popup_size_label": "Popup サイズ",
    "settings.preferences.popup_size.compact": "コンパクト",
    "settings.preferences.popup_size.balanced": "バランス",
    "settings.preferences.popup_size.wide": "ワイド",
    "settings.preferences.popup_corner_label": "Popup の角",
    "settings.preferences.popup_corner.square": "四角",
    "settings.preferences.popup_corner.soft": "ソフト",
    "settings.preferences.popup_corner.rounded": "丸め",
    "settings.preferences.popup_shadow_label": "Popup の影",
    "settings.preferences.popup_shadow.none": "なし",
    "settings.preferences.popup_shadow.soft": "ソフト",
    "settings.preferences.popup_shadow.elevated": "強調",
    "settings.preferences.action_badge_label": "ツールバーバッジ",
    "settings.preferences.minutes": "分",
    "settings.preferences.locale.system": "システムに従う",
    "settings.preferences.locale.en": "英語",
    "settings.preferences.locale.zh_cn": "簡体字中国語",
    "settings.preferences.theme_mode.system": "システムに従う",
    "settings.preferences.theme_mode.light": "ライト",
    "settings.preferences.theme_mode.dark": "ダーク",
    "settings.preferences.theme_preset.default": "デフォルトブルー",
    "settings.preferences.theme_preset.meadow": "メドウ",
    "settings.preferences.theme_preset.sunset": "サンセット",
    "settings.preferences.theme_preset.custom": "カスタムシード",
    "settings.toast.preferences_saved_title": "設定を保存しました",
    "settings.toast.preferences_saved_detail": "現在のプレビュー設定をローカルダッシュボード状態に保存しました。",
  },
  ko: {
    "app.loading.eyebrow": "로딩 중",
    "app.loading.title": "대시보드 상태 준비 중",
    "app.loading.detail": "대시보드 저장소와 메시지 버스를 초기화하는 중입니다.",
    "app.error.eyebrow": "상태를 사용할 수 없음",
    "app.error.title": "초기화가 완료되지 않았습니다",
    "app.error.detail_fallback": "확장 프로그램 저장소 또는 로컬 미리보기 저장소에서 앱 상태를 불러오지 못했습니다.",
    "common.actions.retry": "다시 시도",
    "common.actions.settings": "설정",
    "common.actions.refresh": "새로 고침",
    "common.actions.refresh_all": "모두 새로 고침",
    "common.actions.back": "뒤로",
    "common.actions.open_dashboard": "대시보드 열기",
    "common.actions.open_settings": "설정 열기",
    "common.actions.open_dashboard_tab": "대시보드 탭 열기",
    "common.actions.open_settings_tab": "설정 탭 열기",
    "common.actions.tab": "탭",
    "common.actions.save": "저장",
    "common.theme.toggle_to_dark_label": "다크",
    "common.theme.toggle_to_dark_title": "다크 모드로 전환",
    "common.theme.toggle_to_light_label": "라이트",
    "common.theme.toggle_to_light_title": "라이트 모드로 전환",
    "dashboard.topbar.title": "AI 사용량 대시보드",
    "dashboard.topbar.subtitle": "사용량, 크레딧, 동기화 상태",
    "dashboard.hero.eyebrow": "개요",
    "dashboard.hero.title": "AI 코딩 할당량을 한 화면에서 확인",
    "dashboard.hero.detail": "공식 API, 문서화된 할당량 정책, 보호된 페이지 파싱 소스를 새로 고침, 설정, Provider 상세 확인을 위한 릴리스 준비 대시보드에 모읍니다.",
    "dashboard.hero.release_chip": "Material 3 · 릴리스 후보",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 카드",
    "dashboard.providers.detail": "카드는 먼저 심각도, 그다음 현재 접근 공백 순서로 정렬됩니다. 위험이 큰 provider를 대시보드 상단에 유지하면서 현재 제품 계약도 한눈에 볼 수 있습니다.",
    "dashboard.providers.aria": "Provider 카드",
    "dashboard.empty.eyebrow": "표시 중인 Provider 없음",
    "dashboard.empty.detail": "Quick Setup에서 첫 Provider를 활성화한 뒤 접근 권한과 사용량 페이지 단계를 마치고 대시보드로 돌아오세요.",
    "dashboard.empty.action": "Quick Setup 열기",
    "dashboard.summary.aria": "대시보드 요약",
    "dashboard.summary.visible": "표시됨",
    "dashboard.summary.healthy": "정상",
    "dashboard.summary.needs_access": "접근 필요",
    "dashboard.summary.needs_attention": "확인 필요",
    "popup.loading.eyebrow": "도구 모음 팝업",
    "popup.loading.title": "캐시된 대시보드 상태를 불러오는 중",
    "popup.loading.detail": "이 브라우저 프로필의 공유 할당량 스냅샷을 준비하고 있습니다.",
    "popup.error.eyebrow": "도구 모음 팝업",
    "popup.error.title": "팝업을 불러오지 못했습니다",
    "popup.header.eyebrow": "도구 모음 팝업",
    "popup.header.title": "빠른 보기",
    "popup.summary.aria": "팝업 상단 요약",
    "popup.guidance.eyebrow": "팝업 가이드",
    "popup.snapshot_status.eyebrow": "스냅샷 상태",
    "popup.actions.eyebrow": "다른 경로",
    "popup.actions.refresh": "새로 고침",
    "popup.actions.refreshing": "새로 고치는 중",
    "popup.featured.eyebrow": "주요 Provider",
    "popup.featured.single_eyebrow": "주요 Provider",
    "popup.triage.eyebrow": "팝업 우선 확인",
    "popup.summary.visible": "표시됨",
    "popup.summary.live_ready": "라이브 준비됨",
    "popup.summary.setup_blockers": "설정 차단 항목",
    "popup.summary.policy_only": "정책만",
    "settings.topbar.title": "설정",
    "settings.topbar.subtitle": "Quick Setup, 모양, 고급 Provider 관리",
    "settings.overview.eyebrow": "설정 개요",
    "settings.overview.title": "제어 화면 요약",
    "settings.overview.detail": "이 화면에서 표시 여부, 권한, 인증 정보, 하이브리드 source 제어를 관리합니다. 페이지 전체를 훑지 않고 필요한 섹션으로 바로 이동할 수 있습니다.",
    "settings.overview.aria": "설정 개요",
    "settings.sections.aria": "설정 섹션",
    "settings.sections.preferences": "환경설정",
    "settings.sections.visibility": "표시",
    "settings.sections.credentials": "인증 정보",
    "settings.sections.sources": "소스",
    "settings.sections.permissions": "권한",
    "settings.actions.back_to_top": "맨 위로",
    "settings.actions.back_to_top_short": "맨 위",
    "settings.summary.visible": "표시됨",
    "settings.summary.stored_secrets": "저장된 비밀 정보",
    "settings.summary.bound_pages": "연결된 페이지",
    "settings.summary.needs_access": "접근 필요",
    "settings.preferences.eyebrow": "모양 및 동기화",
    "settings.preferences.sync_interval_label": "기본 동기화 간격",
    "settings.preferences.warning_threshold_label": "경고 임계값",
    "settings.preferences.locale_label": "앱 언어",
    "settings.preferences.theme_mode_label": "테마 모드",
    "settings.preferences.accent_preset_label": "강조 색상 프리셋",
    "settings.preferences.popup_progress_style_label": "Popup 할당량 표시",
    "settings.preferences.sidebar_progress_style_label": "사이드바 할당량 표시",
    "settings.preferences.full_page_progress_style_label": "탭 할당량 표시",
    "settings.preferences.progress_style.line": "선",
    "settings.preferences.progress_style.circle": "원형",
    "settings.preferences.progress_style.circle_soft": "부드러운 원형",
    "settings.preferences.progress_style.circle_gauge": "게이지 원형",
    "settings.preferences.popup_size_label": "Popup 크기",
    "settings.preferences.popup_size.compact": "컴팩트",
    "settings.preferences.popup_size.balanced": "균형",
    "settings.preferences.popup_size.wide": "넓게",
    "settings.preferences.popup_corner_label": "Popup 모서리",
    "settings.preferences.popup_corner.square": "각진",
    "settings.preferences.popup_corner.soft": "부드럽게",
    "settings.preferences.popup_corner.rounded": "둥글게",
    "settings.preferences.popup_shadow_label": "Popup 그림자",
    "settings.preferences.popup_shadow.none": "없음",
    "settings.preferences.popup_shadow.soft": "부드럽게",
    "settings.preferences.popup_shadow.elevated": "강조",
    "settings.preferences.action_badge_label": "도구 모음 배지",
    "settings.preferences.minutes": "분",
    "settings.preferences.locale.system": "시스템 따름",
    "settings.preferences.locale.en": "영어",
    "settings.preferences.locale.zh_cn": "중국어 간체",
    "settings.preferences.theme_mode.system": "시스템 따름",
    "settings.preferences.theme_mode.light": "라이트",
    "settings.preferences.theme_mode.dark": "다크",
    "settings.preferences.theme_preset.default": "기본 파란색",
    "settings.preferences.theme_preset.meadow": "메도우",
    "settings.preferences.theme_preset.sunset": "선셋",
    "settings.preferences.theme_preset.custom": "사용자 지정 시드",
    "settings.toast.preferences_saved_title": "환경설정이 저장됨",
    "settings.toast.preferences_saved_detail": "현재 미리보기 설정이 로컬 대시보드 상태에 저장되었습니다.",
  },
} satisfies Partial<Record<ResolvedAppLocale, Partial<RuntimeMessages>>>;
