import type { ResolvedAppLocale, RuntimeMessages } from "../i18n";

export const COMPLETION_RUNTIME_MESSAGE_OVERRIDES = {
  "zh-TW": {
    "settings.preferences.seconds": "秒",
    "settings.preferences.action_badge_helper": "選擇一個或多個工具列標記來源。實際顯示的標記會在已選來源之間輪轉。",
    "settings.preferences.action_badge_rotation_label": "標記輪轉間隔",
    "settings.preferences.action_badge_rotation_helper": "控制工具列標記以及匹配標記的工具列圖示多久切換到下一個已選來源。",
    "settings.preferences.action_badge_rotation_menu_button": "展開標記輪轉預設",
    "settings.popup_appearance_preview.eyebrow": "工具列彈窗預覽",
    "settings.popup_appearance_preview.title": "工具列彈窗預覽",
    "settings.popup_appearance_preview.detail": "在重新開啟工具列彈窗前，先預覽目前 popup 寬度、圓角、陰影和額度樣式。",
    "settings.popup_appearance_preview.remaining_label": "預覽剩餘額度",
    "settings.popup_appearance_preview.remaining_error": "請輸入 0 到 100 的數值。",
    "settings.popup_appearance_preview.open_test_popup": "開啟工具列彈窗預覽",
    "settings.popup_appearance_preview.close_test_popup": "關閉工具列彈窗預覽",
    "settings.popup_appearance_preview.drag_test_popup": "拖曳工具列彈窗預覽",
    "settings.popup_appearance_preview.sample_refresh": "重新整理",
    "settings.popup_appearance_preview.sample_tab": "分頁",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "每週使用窗口",
    "settings.theme_customization.eyebrow": "自訂種子",
    "settings.theme_customization.title": "已驗證的強調色種子",
    "settings.theme_customization.detail": "使用一個已驗證的 #RRGGBB 種子，而不是編輯個別主題 token。產生的強調色角色會在側欄、popup 和 audit hub 共用。",
    "settings.theme_customization.seed_label": "自訂種子顏色",
    "settings.theme_customization.apply": "套用自訂種子",
    "settings.theme_customization.reset": "恢復預設",
    "settings.theme_customization.preview.aria": "自訂種子預覽",
    "settings.theme_customization.preview.primary": "主色",
    "settings.theme_customization.preview.secondary_container": "次級容器",
    "settings.theme_customization.preview.tertiary": "第三色",
    "settings.visibility.eyebrow": "Provider 可見性",
    "settings.visibility.displayEnabled_detail": "在儀表板中可見。",
    "settings.visibility.disabled_detail": "已從儀表板隱藏。",
    "settings.credentials.eyebrow": "憑據",
    "settings.credentials.title": "已存密鑰與工作區設定",
    "settings.credentials.detail": "這些卡片管理擴充功能本機儲存的 admin 和 enterprise 路徑密鑰。個人 session-page 路徑仍避免匯出 cookie，也不要求手動貼上 auth header。",
    "settings.sources.eyebrow": "來源連線",
    "settings.sources.title": "混合來源合約",
    "settings.sources.detail": "這些卡片說明每個 provider 目前透過官方 API、已登入頁面工作階段，或文件化 quota policy 同步，並標明每條路徑目前是 shipped 還是 deferred 的產品合約。",
    "settings.permissions.eyebrow": "Host 存取",
    "settings.permissions.title": "權限控制",
    "settings.permissions.detail": "在擴充功能模式下，這些操作使用 chrome.permissions；在瀏覽器預覽模式下，會退回到本機狀態模擬。",
  },
  ja: {
    "settings.preferences.seconds": "秒",
    "settings.preferences.action_badge_helper": "ツールバー badge のソースを 1 つ以上選びます。表示される badge は選択したソース間で切り替わります。",
    "settings.preferences.action_badge_rotation_label": "badge 切替間隔",
    "settings.preferences.action_badge_rotation_helper": "ツールバー badge と、それに合わせるツールバーアイコンが次の選択ソースへ切り替わる間隔を制御します。",
    "settings.preferences.action_badge_rotation_menu_button": "badge 切替プリセットを開く",
    "settings.popup_appearance_preview.eyebrow": "ツールバー popup プレビュー",
    "settings.popup_appearance_preview.title": "ツールバー popup プレビュー",
    "settings.popup_appearance_preview.detail": "ツールバー popup を開き直す前に、選択した幅、角丸、影、クォータ表示スタイルを確認します。",
    "settings.popup_appearance_preview.remaining_label": "残量プレビュー",
    "settings.popup_appearance_preview.remaining_error": "0 から 100 の値を入力してください。",
    "settings.popup_appearance_preview.open_test_popup": "ツールバー popup プレビューを開く",
    "settings.popup_appearance_preview.close_test_popup": "ツールバー popup プレビューを閉じる",
    "settings.popup_appearance_preview.drag_test_popup": "ツールバー popup プレビューをドラッグ",
    "settings.popup_appearance_preview.sample_refresh": "更新",
    "settings.popup_appearance_preview.sample_tab": "タブ",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "週次利用枠",
    "settings.theme_customization.eyebrow": "カスタム seed",
    "settings.theme_customization.title": "検証済みアクセント seed",
    "settings.theme_customization.detail": "個別のテーマ token を編集せず、検証済みの #RRGGBB seed を 1 つ使います。生成されたアクセント role はサイドパネル、popup、audit hub で共有されます。",
    "settings.theme_customization.seed_label": "カスタム seed 色",
    "settings.theme_customization.apply": "カスタム seed を適用",
    "settings.theme_customization.reset": "既定に戻す",
    "settings.theme_customization.preview.aria": "カスタム seed プレビュー",
    "settings.theme_customization.preview.primary": "Primary",
    "settings.theme_customization.preview.secondary_container": "Secondary container",
    "settings.theme_customization.preview.tertiary": "Tertiary",
    "settings.visibility.eyebrow": "Provider 表示",
    "settings.visibility.displayEnabled_detail": "ダッシュボードに表示されます。",
    "settings.visibility.disabled_detail": "ダッシュボードでは非表示です。",
    "settings.credentials.eyebrow": "認証情報",
    "settings.credentials.title": "保存済み secret とワークスペース設定",
    "settings.credentials.detail": "これらのカードは、対応する admin と enterprise パス向けの拡張機能ローカル secret を管理します。個人 session-page パスは cookie export を避け、auth header の手動貼り付けも求めません。",
    "settings.sources.eyebrow": "ソース接続",
    "settings.sources.title": "ハイブリッドソース契約",
    "settings.sources.detail": "各 provider が公式 API、ログイン済みページ session、または文書化された quota policy のどれで同期するかを示し、各パスが shipped か deferred かも明示します。",
    "settings.permissions.eyebrow": "Host アクセス",
    "settings.permissions.title": "権限制御",
    "settings.permissions.detail": "拡張機能モードでは chrome.permissions を使います。ブラウザプレビューモードではローカル状態シミュレーションへフォールバックします。",
  },
  ko: {
    "settings.preferences.seconds": "초",
    "settings.preferences.action_badge_helper": "하나 이상의 툴바 badge 소스를 선택하세요. 표시되는 badge는 선택한 소스 사이를 순환합니다.",
    "settings.preferences.action_badge_rotation_label": "badge 전환 간격",
    "settings.preferences.action_badge_rotation_helper": "툴바 badge와 이에 맞춘 툴바 아이콘이 다음 선택 소스로 이동하는 주기를 제어합니다.",
    "settings.preferences.action_badge_rotation_menu_button": "badge 전환 프리셋 펼치기",
    "settings.popup_appearance_preview.eyebrow": "툴바 popup 미리보기",
    "settings.popup_appearance_preview.title": "툴바 popup 미리보기",
    "settings.popup_appearance_preview.detail": "툴바 popup을 다시 열기 전에 선택한 너비, 모서리, 그림자, 할당량 스타일을 미리 확인합니다.",
    "settings.popup_appearance_preview.remaining_label": "남은 값 미리보기",
    "settings.popup_appearance_preview.remaining_error": "0부터 100까지의 값을 입력하세요.",
    "settings.popup_appearance_preview.open_test_popup": "툴바 popup 미리보기 열기",
    "settings.popup_appearance_preview.close_test_popup": "툴바 popup 미리보기 닫기",
    "settings.popup_appearance_preview.drag_test_popup": "툴바 popup 미리보기 드래그",
    "settings.popup_appearance_preview.sample_refresh": "새로고침",
    "settings.popup_appearance_preview.sample_tab": "탭",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "주간 사용 창",
    "settings.theme_customization.eyebrow": "사용자 seed",
    "settings.theme_customization.title": "검증된 강조색 seed",
    "settings.theme_customization.detail": "개별 theme token을 편집하지 않고 검증된 #RRGGBB seed 하나를 사용합니다. 생성된 강조색 role은 사이드 패널, popup, audit hub에서 공유됩니다.",
    "settings.theme_customization.seed_label": "사용자 seed 색상",
    "settings.theme_customization.apply": "사용자 seed 적용",
    "settings.theme_customization.reset": "기본값으로 재설정",
    "settings.theme_customization.preview.aria": "사용자 seed 미리보기",
    "settings.theme_customization.preview.primary": "Primary",
    "settings.theme_customization.preview.secondary_container": "Secondary container",
    "settings.theme_customization.preview.tertiary": "Tertiary",
    "settings.visibility.eyebrow": "Provider 표시",
    "settings.visibility.displayEnabled_detail": "대시보드에 표시됩니다.",
    "settings.visibility.disabled_detail": "대시보드에서 숨겨졌습니다.",
    "settings.credentials.eyebrow": "자격 증명",
    "settings.credentials.title": "저장된 secret 및 워크스페이스 설정",
    "settings.credentials.detail": "이 카드들은 지원되는 admin 및 enterprise 경로의 확장 로컬 secret을 관리합니다. 개인 session-page 경로는 cookie export를 피하며 수동 auth header 붙여넣기도 요구하지 않습니다.",
    "settings.sources.eyebrow": "소스 연결",
    "settings.sources.title": "하이브리드 소스 계약",
    "settings.sources.detail": "각 provider가 공식 API, 로그인된 페이지 session, 문서화된 quota policy 중 무엇으로 동기화되는지와 각 경로의 shipped/deferred 제품 계약을 설명합니다.",
    "settings.permissions.eyebrow": "Host 접근",
    "settings.permissions.title": "권한 제어",
    "settings.permissions.detail": "확장 모드에서는 chrome.permissions를 사용합니다. 브라우저 미리보기 모드에서는 로컬 상태 시뮬레이션으로 대체됩니다.",
  },
  "es-419": {
    "settings.preferences.seconds": "segundos",
    "settings.preferences.action_badge_helper": "Elige una o más fuentes para la insignia de la barra. La insignia visible rota entre las fuentes seleccionadas.",
    "settings.preferences.action_badge_rotation_label": "Intervalo de rotación de insignia",
    "settings.preferences.action_badge_rotation_helper": "Controla cada cuánto la insignia y el icono coincidente de la barra cambian a la siguiente fuente seleccionada.",
    "settings.preferences.action_badge_rotation_menu_button": "Abrir preajustes de rotación de insignia",
    "settings.popup_appearance_preview.eyebrow": "Vista previa del popup",
    "settings.popup_appearance_preview.title": "Vista previa del popup",
    "settings.popup_appearance_preview.detail": "Previsualiza el ancho, las esquinas, la sombra y el estilo de cuota elegidos antes de reabrir el popup.",
    "settings.popup_appearance_preview.remaining_label": "Restante de prueba",
    "settings.popup_appearance_preview.remaining_error": "Ingresa un valor de 0 a 100.",
    "settings.popup_appearance_preview.open_test_popup": "Abrir vista previa del popup",
    "settings.popup_appearance_preview.close_test_popup": "Cerrar vista previa del popup",
    "settings.popup_appearance_preview.drag_test_popup": "Arrastrar vista previa del popup",
    "settings.popup_appearance_preview.sample_refresh": "Actualizar",
    "settings.popup_appearance_preview.sample_tab": "Pestaña",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Ventana semanal de uso",
    "settings.theme_customization.eyebrow": "Semilla personalizada",
    "settings.theme_customization.title": "Semilla de acento validada",
    "settings.theme_customization.detail": "Usa una semilla #RRGGBB validada en vez de editar tokens de tema individuales. Los roles de acento generados se comparten en la barra lateral, popup y audit hub.",
    "settings.theme_customization.seed_label": "Color de semilla",
    "settings.theme_customization.apply": "Aplicar semilla",
    "settings.theme_customization.reset": "Restablecer predeterminado",
    "settings.theme_customization.preview.aria": "Vista previa de semilla",
    "settings.theme_customization.preview.primary": "Primario",
    "settings.theme_customization.preview.secondary_container": "Contenedor secundario",
    "settings.theme_customization.preview.tertiary": "Terciario",
    "settings.visibility.eyebrow": "Visibilidad de Provider",
    "settings.visibility.displayEnabled_detail": "Visible en el panel.",
    "settings.visibility.disabled_detail": "Oculto del panel.",
    "settings.credentials.eyebrow": "Credenciales",
    "settings.credentials.title": "Secretos guardados y configuración",
    "settings.credentials.detail": "Estas tarjetas administran secretos locales de la extensión para rutas admin y enterprise compatibles. Las rutas personales de session-page siguen evitando exportar cookies y no piden pegar auth headers.",
    "settings.sources.eyebrow": "Conexiones de fuente",
    "settings.sources.title": "Contratos de fuente híbrida",
    "settings.sources.detail": "Estas tarjetas explican si cada provider sincroniza desde una API oficial, una sesión de página iniciada o una política de cuota documentada, además del contrato shipped o deferred de cada ruta.",
    "settings.permissions.eyebrow": "Acceso a host",
    "settings.permissions.title": "Controles de permisos",
    "settings.permissions.detail": "En modo extensión estas acciones usan chrome.permissions. En vista previa del navegador vuelven a una simulación de estado local.",
  },
  "pt-BR": {
    "settings.preferences.seconds": "segundos",
    "settings.preferences.action_badge_helper": "Escolha uma ou mais fontes de badge da barra. O badge visível alterna entre as fontes selecionadas.",
    "settings.preferences.action_badge_rotation_label": "Intervalo de rotação do badge",
    "settings.preferences.action_badge_rotation_helper": "Controla a frequência com que o badge e o ícone correspondente da barra passam para a próxima fonte selecionada.",
    "settings.preferences.action_badge_rotation_menu_button": "Abrir predefinições de rotação do badge",
    "settings.popup_appearance_preview.eyebrow": "Prévia do popup",
    "settings.popup_appearance_preview.title": "Prévia do popup",
    "settings.popup_appearance_preview.detail": "Visualize a largura, os cantos, a sombra e o estilo de cota escolhidos antes de reabrir o popup.",
    "settings.popup_appearance_preview.remaining_label": "Restante da prévia",
    "settings.popup_appearance_preview.remaining_error": "Digite um valor de 0 a 100.",
    "settings.popup_appearance_preview.open_test_popup": "Abrir prévia do popup",
    "settings.popup_appearance_preview.close_test_popup": "Fechar prévia do popup",
    "settings.popup_appearance_preview.drag_test_popup": "Arrastar prévia do popup",
    "settings.popup_appearance_preview.sample_refresh": "Atualizar",
    "settings.popup_appearance_preview.sample_tab": "Aba",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Janela de uso semanal",
    "settings.theme_customization.eyebrow": "Semente personalizada",
    "settings.theme_customization.title": "Semente de destaque validada",
    "settings.theme_customization.detail": "Use uma semente #RRGGBB validada em vez de editar tokens de tema individuais. Os papéis de destaque gerados são compartilhados na barra lateral, popup e audit hub.",
    "settings.theme_customization.seed_label": "Cor da semente",
    "settings.theme_customization.apply": "Aplicar semente",
    "settings.theme_customization.reset": "Restaurar padrão",
    "settings.theme_customization.preview.aria": "Prévia da semente",
    "settings.theme_customization.preview.primary": "Primário",
    "settings.theme_customization.preview.secondary_container": "Contêiner secundário",
    "settings.theme_customization.preview.tertiary": "Terciário",
    "settings.visibility.eyebrow": "Visibilidade do Provider",
    "settings.visibility.displayEnabled_detail": "Visível no painel.",
    "settings.visibility.disabled_detail": "Oculto no painel.",
    "settings.credentials.eyebrow": "Credenciais",
    "settings.credentials.title": "Segredos salvos e configuração",
    "settings.credentials.detail": "Estes cartões gerenciam segredos locais da extensão para caminhos admin e enterprise compatíveis. Caminhos pessoais de session-page continuam sem exportar cookies e não pedem colagem manual de auth headers.",
    "settings.sources.eyebrow": "Conexões de fonte",
    "settings.sources.title": "Contratos de fonte híbrida",
    "settings.sources.detail": "Estes cartões explicam se cada provider sincroniza por API oficial, sessão de página autenticada ou política de cota documentada, além do contrato shipped ou deferred de cada caminho.",
    "settings.permissions.eyebrow": "Acesso a host",
    "settings.permissions.title": "Controles de permissão",
    "settings.permissions.detail": "No modo extensão, estas ações usam chrome.permissions. Na prévia do navegador, elas voltam para simulação de estado local.",
  },
  fr: {
    "settings.preferences.seconds": "secondes",
    "settings.preferences.action_badge_helper": "Choisissez une ou plusieurs sources de badge de barre d'outils. Le badge visible alterne entre les sources sélectionnées.",
    "settings.preferences.action_badge_rotation_label": "Intervalle de rotation du badge",
    "settings.preferences.action_badge_rotation_helper": "Définit la fréquence à laquelle le badge et l'icône associée passent à la source sélectionnée suivante.",
    "settings.preferences.action_badge_rotation_menu_button": "Ouvrir les préréglages de rotation du badge",
    "settings.popup_appearance_preview.eyebrow": "Aperçu du popup",
    "settings.popup_appearance_preview.title": "Aperçu du popup",
    "settings.popup_appearance_preview.detail": "Prévisualisez la largeur, les coins, l'ombre et le style de quota choisis avant de rouvrir le popup.",
    "settings.popup_appearance_preview.remaining_label": "Restant d'aperçu",
    "settings.popup_appearance_preview.remaining_error": "Saisissez une valeur de 0 à 100.",
    "settings.popup_appearance_preview.open_test_popup": "Ouvrir l'aperçu du popup",
    "settings.popup_appearance_preview.close_test_popup": "Fermer l'aperçu du popup",
    "settings.popup_appearance_preview.drag_test_popup": "Faire glisser l'aperçu du popup",
    "settings.popup_appearance_preview.sample_refresh": "Actualiser",
    "settings.popup_appearance_preview.sample_tab": "Onglet",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Fenêtre d'usage hebdo",
    "settings.theme_customization.eyebrow": "Seed personnalisé",
    "settings.theme_customization.title": "Seed d'accent validé",
    "settings.theme_customization.detail": "Utilisez un seed #RRGGBB validé au lieu de modifier des tokens de thème un par un. Les rôles d'accent générés sont partagés par la barre latérale, le popup et l'audit hub.",
    "settings.theme_customization.seed_label": "Couleur du seed",
    "settings.theme_customization.apply": "Appliquer le seed",
    "settings.theme_customization.reset": "Réinitialiser",
    "settings.theme_customization.preview.aria": "Aperçu du seed",
    "settings.theme_customization.preview.primary": "Primaire",
    "settings.theme_customization.preview.secondary_container": "Conteneur secondaire",
    "settings.theme_customization.preview.tertiary": "Tertiaire",
    "settings.visibility.eyebrow": "Visibilité Provider",
    "settings.visibility.displayEnabled_detail": "Visible dans le tableau de bord.",
    "settings.visibility.disabled_detail": "Masqué dans le tableau de bord.",
    "settings.credentials.eyebrow": "Identifiants",
    "settings.credentials.title": "Secrets enregistrés et configuration",
    "settings.credentials.detail": "Ces cartes gèrent les secrets locaux de l'extension pour les chemins admin et enterprise pris en charge. Les chemins personnels session-page évitent toujours l'export de cookies et ne demandent pas de coller un auth header.",
    "settings.sources.eyebrow": "Connexions de source",
    "settings.sources.title": "Contrats de source hybride",
    "settings.sources.detail": "Ces cartes indiquent si chaque provider se synchronise via une API officielle, une session de page connectée ou une politique de quota documentée, ainsi que le contrat shipped ou deferred de chaque chemin.",
    "settings.permissions.eyebrow": "Accès host",
    "settings.permissions.title": "Contrôles d'autorisation",
    "settings.permissions.detail": "En mode extension, ces actions utilisent chrome.permissions. En aperçu navigateur, elles reviennent à une simulation d'état local.",
  },
  de: {
    "settings.preferences.seconds": "Sekunden",
    "settings.preferences.action_badge_helper": "Wählen Sie eine oder mehrere Quellen für das Toolbar-Badge. Das sichtbare Badge wechselt zwischen den ausgewählten Quellen.",
    "settings.preferences.action_badge_rotation_label": "Badge-Wechselintervall",
    "settings.preferences.action_badge_rotation_helper": "Legt fest, wie oft Toolbar-Badge und passendes Toolbar-Icon zur nächsten ausgewählten Quelle wechseln.",
    "settings.preferences.action_badge_rotation_menu_button": "Badge-Wechselvorgaben öffnen",
    "settings.popup_appearance_preview.eyebrow": "Popup-Vorschau",
    "settings.popup_appearance_preview.title": "Popup-Vorschau",
    "settings.popup_appearance_preview.detail": "Prüfen Sie gewählte Popup-Breite, Ecken, Schatten und Kontingentstil, bevor Sie das Toolbar-Popup erneut öffnen.",
    "settings.popup_appearance_preview.remaining_label": "Vorschau-Restwert",
    "settings.popup_appearance_preview.remaining_error": "Geben Sie einen Wert von 0 bis 100 ein.",
    "settings.popup_appearance_preview.open_test_popup": "Popup-Vorschau öffnen",
    "settings.popup_appearance_preview.close_test_popup": "Popup-Vorschau schließen",
    "settings.popup_appearance_preview.drag_test_popup": "Popup-Vorschau ziehen",
    "settings.popup_appearance_preview.sample_refresh": "Aktualisieren",
    "settings.popup_appearance_preview.sample_tab": "Tab",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Wöchentliches Nutzungsfenster",
    "settings.theme_customization.eyebrow": "Eigener Seed",
    "settings.theme_customization.title": "Geprüfter Akzent-Seed",
    "settings.theme_customization.detail": "Nutzen Sie einen geprüften #RRGGBB-Seed statt einzelner Theme-Token. Die erzeugten Akzentrollen gelten für Seitenleiste, Popup und Audit-Hub.",
    "settings.theme_customization.seed_label": "Seed-Farbe",
    "settings.theme_customization.apply": "Seed anwenden",
    "settings.theme_customization.reset": "Standard wiederherstellen",
    "settings.theme_customization.preview.aria": "Seed-Vorschau",
    "settings.theme_customization.preview.primary": "Primär",
    "settings.theme_customization.preview.secondary_container": "Sekundärcontainer",
    "settings.theme_customization.preview.tertiary": "Tertiär",
    "settings.visibility.eyebrow": "Provider-Sichtbarkeit",
    "settings.visibility.displayEnabled_detail": "Im Dashboard sichtbar.",
    "settings.visibility.disabled_detail": "Im Dashboard ausgeblendet.",
    "settings.credentials.eyebrow": "Anmeldedaten",
    "settings.credentials.title": "Gespeicherte Secrets und Workspace-Konfiguration",
    "settings.credentials.detail": "Diese Karten verwalten erweiterungslokale Secrets für unterstützte Admin- und Enterprise-Pfade. Persönliche session-page-Pfade vermeiden weiterhin Cookie-Export und verlangen kein manuelles Einfügen von auth headers.",
    "settings.sources.eyebrow": "Quellenverbindungen",
    "settings.sources.title": "Hybride Quellenverträge",
    "settings.sources.detail": "Diese Karten zeigen, ob jeder provider über offizielle API, angemeldete Seitensession oder dokumentierte quota policy synchronisiert, und ob der jeweilige Pfad shipped oder deferred ist.",
    "settings.permissions.eyebrow": "Host-Zugriff",
    "settings.permissions.title": "Berechtigungssteuerung",
    "settings.permissions.detail": "Im Erweiterungsmodus nutzen diese Aktionen chrome.permissions. In der Browser-Vorschau fallen sie auf lokale Zustandssimulation zurück.",
  },
  it: {
    "settings.preferences.seconds": "secondi",
    "settings.preferences.action_badge_helper": "Scegli una o più fonti per il badge della barra. Il badge visibile ruota tra le fonti selezionate.",
    "settings.preferences.action_badge_rotation_label": "Intervallo di rotazione badge",
    "settings.preferences.action_badge_rotation_helper": "Controlla quanto spesso il badge e l'icona corrispondente passano alla fonte selezionata successiva.",
    "settings.preferences.action_badge_rotation_menu_button": "Apri preset rotazione badge",
    "settings.popup_appearance_preview.eyebrow": "Anteprima popup",
    "settings.popup_appearance_preview.title": "Anteprima popup",
    "settings.popup_appearance_preview.detail": "Visualizza larghezza, angoli, ombra e stile quota scelti prima di riaprire il popup della barra.",
    "settings.popup_appearance_preview.remaining_label": "Rimanente anteprima",
    "settings.popup_appearance_preview.remaining_error": "Inserisci un valore da 0 a 100.",
    "settings.popup_appearance_preview.open_test_popup": "Apri anteprima popup",
    "settings.popup_appearance_preview.close_test_popup": "Chiudi anteprima popup",
    "settings.popup_appearance_preview.drag_test_popup": "Trascina anteprima popup",
    "settings.popup_appearance_preview.sample_refresh": "Aggiorna",
    "settings.popup_appearance_preview.sample_tab": "Scheda",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Finestra uso settimanale",
    "settings.theme_customization.eyebrow": "Seed personalizzato",
    "settings.theme_customization.title": "Seed accento validato",
    "settings.theme_customization.detail": "Usa un seed #RRGGBB validato invece di modificare singoli token tema. I ruoli accento generati sono condivisi tra pannello laterale, popup e audit hub.",
    "settings.theme_customization.seed_label": "Colore seed",
    "settings.theme_customization.apply": "Applica seed",
    "settings.theme_customization.reset": "Ripristina predefinito",
    "settings.theme_customization.preview.aria": "Anteprima seed",
    "settings.theme_customization.preview.primary": "Primario",
    "settings.theme_customization.preview.secondary_container": "Contenitore secondario",
    "settings.theme_customization.preview.tertiary": "Terziario",
    "settings.visibility.eyebrow": "Visibilità Provider",
    "settings.visibility.displayEnabled_detail": "Visibile nella dashboard.",
    "settings.visibility.disabled_detail": "Nascosto dalla dashboard.",
    "settings.credentials.eyebrow": "Credenziali",
    "settings.credentials.title": "Segreti salvati e configurazione",
    "settings.credentials.detail": "Queste schede gestiscono segreti locali dell'estensione per percorsi admin ed enterprise supportati. I percorsi personali session-page evitano ancora l'export cookie e non chiedono di incollare auth header.",
    "settings.sources.eyebrow": "Connessioni fonte",
    "settings.sources.title": "Contratti fonte ibrida",
    "settings.sources.detail": "Queste schede spiegano se ogni provider sincronizza da API ufficiale, sessione pagina autenticata o quota policy documentata, più il contratto shipped o deferred di ogni percorso.",
    "settings.permissions.eyebrow": "Accesso host",
    "settings.permissions.title": "Controlli permessi",
    "settings.permissions.detail": "In modalità estensione queste azioni usano chrome.permissions. In anteprima browser tornano a una simulazione di stato locale.",
  },
  ru: {
    "settings.preferences.seconds": "секунд",
    "settings.preferences.action_badge_helper": "Выберите один или несколько источников badge панели. Видимый badge переключается между выбранными источниками.",
    "settings.preferences.action_badge_rotation_label": "Интервал смены badge",
    "settings.preferences.action_badge_rotation_helper": "Задает, как часто badge панели и соответствующая иконка переходят к следующему выбранному источнику.",
    "settings.preferences.action_badge_rotation_menu_button": "Открыть пресеты смены badge",
    "settings.popup_appearance_preview.eyebrow": "Предпросмотр popup",
    "settings.popup_appearance_preview.title": "Предпросмотр popup",
    "settings.popup_appearance_preview.detail": "Проверьте выбранную ширину, углы, тень и стиль квоты перед повторным открытием toolbar popup.",
    "settings.popup_appearance_preview.remaining_label": "Остаток для предпросмотра",
    "settings.popup_appearance_preview.remaining_error": "Введите значение от 0 до 100.",
    "settings.popup_appearance_preview.open_test_popup": "Открыть предпросмотр popup",
    "settings.popup_appearance_preview.close_test_popup": "Закрыть предпросмотр popup",
    "settings.popup_appearance_preview.drag_test_popup": "Перетащить предпросмотр popup",
    "settings.popup_appearance_preview.sample_refresh": "Обновить",
    "settings.popup_appearance_preview.sample_tab": "Вкладка",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Недельное окно использования",
    "settings.theme_customization.eyebrow": "Свой seed",
    "settings.theme_customization.title": "Проверенный акцентный seed",
    "settings.theme_customization.detail": "Используйте один проверенный #RRGGBB seed вместо правки отдельных theme-token. Созданные акцентные роли общие для боковой панели, popup и audit hub.",
    "settings.theme_customization.seed_label": "Цвет seed",
    "settings.theme_customization.apply": "Применить seed",
    "settings.theme_customization.reset": "Вернуть стандарт",
    "settings.theme_customization.preview.aria": "Предпросмотр seed",
    "settings.theme_customization.preview.primary": "Основной",
    "settings.theme_customization.preview.secondary_container": "Вторичный контейнер",
    "settings.theme_customization.preview.tertiary": "Третичный",
    "settings.visibility.eyebrow": "Видимость Provider",
    "settings.visibility.displayEnabled_detail": "Видим на панели.",
    "settings.visibility.disabled_detail": "Скрыт с панели.",
    "settings.credentials.eyebrow": "Учетные данные",
    "settings.credentials.title": "Сохраненные секреты и конфигурация",
    "settings.credentials.detail": "Эти карточки управляют локальными секретами расширения для поддерживаемых admin и enterprise путей. Личные session-page пути по-прежнему не экспортируют cookie и не требуют вставлять auth header вручную.",
    "settings.sources.eyebrow": "Подключения источников",
    "settings.sources.title": "Гибридные контракты источников",
    "settings.sources.detail": "Эти карточки показывают, синхронизируется ли provider через official API, залогиненную page session или документированную quota policy, а также shipped/deferred контракт каждого пути.",
    "settings.permissions.eyebrow": "Доступ host",
    "settings.permissions.title": "Управление разрешениями",
    "settings.permissions.detail": "В режиме расширения эти действия используют chrome.permissions. В режиме предпросмотра браузера они переходят к локальной симуляции состояния.",
  },
  ar: {
    "settings.preferences.seconds": "ثوان",
    "settings.preferences.action_badge_helper": "اختر مصدرا واحدا أو أكثر لعلامة شريط الأدوات. العلامة المرئية تنتقل بين المصادر المحددة.",
    "settings.preferences.action_badge_rotation_label": "فاصل تدوير العلامة",
    "settings.preferences.action_badge_rotation_helper": "يتحكم في عدد مرات انتقال علامة شريط الأدوات والأيقونة المطابقة إلى المصدر المحدد التالي.",
    "settings.preferences.action_badge_rotation_menu_button": "فتح إعدادات تدوير العلامة",
    "settings.popup_appearance_preview.eyebrow": "معاينة popup",
    "settings.popup_appearance_preview.title": "معاينة popup",
    "settings.popup_appearance_preview.detail": "عاين عرض popup والزوايا والظل ونمط الحصة المحدد قبل إعادة فتح popup شريط الأدوات.",
    "settings.popup_appearance_preview.remaining_label": "المتبقي للمعاينة",
    "settings.popup_appearance_preview.remaining_error": "أدخل قيمة من 0 إلى 100.",
    "settings.popup_appearance_preview.open_test_popup": "فتح معاينة popup",
    "settings.popup_appearance_preview.close_test_popup": "إغلاق معاينة popup",
    "settings.popup_appearance_preview.drag_test_popup": "سحب معاينة popup",
    "settings.popup_appearance_preview.sample_refresh": "تحديث",
    "settings.popup_appearance_preview.sample_tab": "تبويب",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "نافذة استخدام أسبوعية",
    "settings.theme_customization.eyebrow": "Seed مخصص",
    "settings.theme_customization.title": "Seed تمييز موثق",
    "settings.theme_customization.detail": "استخدم seed واحدا موثقا بصيغة #RRGGBB بدلا من تعديل theme tokens منفردة. أدوار التمييز الناتجة مشتركة بين الشريط الجانبي وpopup وaudit hub.",
    "settings.theme_customization.seed_label": "لون seed المخصص",
    "settings.theme_customization.apply": "تطبيق seed المخصص",
    "settings.theme_customization.reset": "استعادة الافتراضي",
    "settings.theme_customization.preview.aria": "معاينة seed المخصص",
    "settings.theme_customization.preview.primary": "أساسي",
    "settings.theme_customization.preview.secondary_container": "حاوية ثانوية",
    "settings.theme_customization.preview.tertiary": "ثالثي",
    "settings.visibility.eyebrow": "ظهور Provider",
    "settings.visibility.displayEnabled_detail": "مرئي في لوحة المعلومات.",
    "settings.visibility.disabled_detail": "مخفي من لوحة المعلومات.",
    "settings.credentials.eyebrow": "بيانات الاعتماد",
    "settings.credentials.title": "أسرار محفوظة وإعدادات مساحة العمل",
    "settings.credentials.detail": "تدير هذه البطاقات أسرار الإضافة المحلية لمسارات admin وenterprise المدعومة. لا تزال مسارات session-page الشخصية تتجنب تصدير cookies ولا تطلب لصق auth header يدويا.",
    "settings.sources.eyebrow": "اتصالات المصدر",
    "settings.sources.title": "عقود المصدر الهجينة",
    "settings.sources.detail": "تشرح هذه البطاقات ما إذا كان كل provider يزامن من API رسمي أو session صفحة مسجلة الدخول أو quota policy موثقة، مع عقد shipped أو deferred لكل مسار.",
    "settings.permissions.eyebrow": "وصول Host",
    "settings.permissions.title": "عناصر تحكم الأذونات",
    "settings.permissions.detail": "في وضع الإضافة تستخدم هذه الإجراءات chrome.permissions. في وضع معاينة المتصفح تعود إلى محاكاة حالة محلية.",
  },
  hi: {
    "settings.preferences.seconds": "सेकंड",
    "settings.preferences.action_badge_helper": "Toolbar badge के लिए एक या अधिक स्रोत चुनें। दिखने वाला badge चुने गए स्रोतों के बीच घूमता है।",
    "settings.preferences.action_badge_rotation_label": "badge बदलने का अंतराल",
    "settings.preferences.action_badge_rotation_helper": "यह नियंत्रित करता है कि toolbar badge और उससे मेल खाता toolbar icon अगली चुनी गई source पर कितनी बार जाएं।",
    "settings.preferences.action_badge_rotation_menu_button": "badge rotation preset खोलें",
    "settings.popup_appearance_preview.eyebrow": "toolbar popup preview",
    "settings.popup_appearance_preview.title": "toolbar popup preview",
    "settings.popup_appearance_preview.detail": "toolbar popup फिर खोलने से पहले चुनी गई चौड़ाई, कोने, shadow और quota style देखें।",
    "settings.popup_appearance_preview.remaining_label": "preview remaining",
    "settings.popup_appearance_preview.remaining_error": "0 से 100 तक का मान दर्ज करें।",
    "settings.popup_appearance_preview.open_test_popup": "toolbar popup preview खोलें",
    "settings.popup_appearance_preview.close_test_popup": "toolbar popup preview बंद करें",
    "settings.popup_appearance_preview.drag_test_popup": "toolbar popup preview खींचें",
    "settings.popup_appearance_preview.sample_refresh": "Refresh",
    "settings.popup_appearance_preview.sample_tab": "Tab",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "साप्ताहिक usage window",
    "settings.theme_customization.eyebrow": "Custom seed",
    "settings.theme_customization.title": "मान्य accent seed",
    "settings.theme_customization.detail": "अलग-अलग theme token संपादित करने के बजाय एक मान्य #RRGGBB seed इस्तेमाल करें। बने हुए accent roles side panel, popup और audit hub में साझा रहते हैं।",
    "settings.theme_customization.seed_label": "Custom seed रंग",
    "settings.theme_customization.apply": "Custom seed लागू करें",
    "settings.theme_customization.reset": "Default पर लौटाएं",
    "settings.theme_customization.preview.aria": "Custom seed preview",
    "settings.theme_customization.preview.primary": "Primary",
    "settings.theme_customization.preview.secondary_container": "Secondary container",
    "settings.theme_customization.preview.tertiary": "Tertiary",
    "settings.visibility.eyebrow": "Provider visibility",
    "settings.visibility.displayEnabled_detail": "Dashboard में दिखता है।",
    "settings.visibility.disabled_detail": "Dashboard से छिपा है।",
    "settings.credentials.eyebrow": "Credentials",
    "settings.credentials.title": "सहेजे गए secrets और workspace config",
    "settings.credentials.detail": "ये cards समर्थित admin और enterprise paths के लिए extension-local secrets संभालते हैं। personal session-page paths अभी भी cookie export से बचते हैं और manual auth-header paste नहीं मांगते।",
    "settings.sources.eyebrow": "Source connections",
    "settings.sources.title": "Hybrid source contracts",
    "settings.sources.detail": "ये cards बताते हैं कि हर provider official API, logged-in page session या documented quota policy से sync करता है, साथ ही हर path का shipped या deferred product contract दिखाते हैं।",
    "settings.permissions.eyebrow": "Host access",
    "settings.permissions.title": "Permission controls",
    "settings.permissions.detail": "Extension mode में ये actions chrome.permissions इस्तेमाल करते हैं। Browser preview mode में ये local state simulation पर लौटते हैं।",
  },
  id: {
    "settings.preferences.seconds": "detik",
    "settings.preferences.action_badge_helper": "Pilih satu atau beberapa sumber badge toolbar. Badge yang terlihat berputar di antara sumber yang dipilih.",
    "settings.preferences.action_badge_rotation_label": "Interval rotasi badge",
    "settings.preferences.action_badge_rotation_helper": "Mengatur seberapa sering badge toolbar dan ikon toolbar yang cocok berpindah ke sumber pilihan berikutnya.",
    "settings.preferences.action_badge_rotation_menu_button": "Buka preset rotasi badge",
    "settings.popup_appearance_preview.eyebrow": "Pratinjau popup toolbar",
    "settings.popup_appearance_preview.title": "Pratinjau popup toolbar",
    "settings.popup_appearance_preview.detail": "Pratinjau lebar, sudut, bayangan, dan gaya kuota terpilih sebelum membuka ulang popup toolbar.",
    "settings.popup_appearance_preview.remaining_label": "Sisa pratinjau",
    "settings.popup_appearance_preview.remaining_error": "Masukkan nilai dari 0 sampai 100.",
    "settings.popup_appearance_preview.open_test_popup": "Buka pratinjau popup toolbar",
    "settings.popup_appearance_preview.close_test_popup": "Tutup pratinjau popup toolbar",
    "settings.popup_appearance_preview.drag_test_popup": "Seret pratinjau popup toolbar",
    "settings.popup_appearance_preview.sample_refresh": "Segarkan",
    "settings.popup_appearance_preview.sample_tab": "Tab",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Jendela penggunaan mingguan",
    "settings.theme_customization.eyebrow": "Seed kustom",
    "settings.theme_customization.title": "Seed aksen tervalidasi",
    "settings.theme_customization.detail": "Gunakan satu seed #RRGGBB tervalidasi, bukan mengedit token tema satu per satu. Peran aksen yang dibuat dibagikan di panel samping, popup, dan audit hub.",
    "settings.theme_customization.seed_label": "Warna seed kustom",
    "settings.theme_customization.apply": "Terapkan seed kustom",
    "settings.theme_customization.reset": "Kembalikan default",
    "settings.theme_customization.preview.aria": "Pratinjau seed kustom",
    "settings.theme_customization.preview.primary": "Primer",
    "settings.theme_customization.preview.secondary_container": "Kontainer sekunder",
    "settings.theme_customization.preview.tertiary": "Tersier",
    "settings.visibility.eyebrow": "Visibilitas Provider",
    "settings.visibility.displayEnabled_detail": "Terlihat di dasbor.",
    "settings.visibility.disabled_detail": "Disembunyikan dari dasbor.",
    "settings.credentials.eyebrow": "Kredensial",
    "settings.credentials.title": "Secret tersimpan dan konfigurasi",
    "settings.credentials.detail": "Kartu ini mengelola secret lokal ekstensi untuk jalur admin dan enterprise yang didukung. Jalur personal session-page tetap menghindari ekspor cookie dan tidak meminta tempel auth header manual.",
    "settings.sources.eyebrow": "Koneksi sumber",
    "settings.sources.title": "Kontrak sumber hibrida",
    "settings.sources.detail": "Kartu ini menjelaskan apakah setiap provider sinkron dari API resmi, sesi halaman yang sudah login, atau kebijakan kuota terdokumentasi, plus kontrak shipped atau deferred untuk tiap jalur.",
    "settings.permissions.eyebrow": "Akses host",
    "settings.permissions.title": "Kontrol izin",
    "settings.permissions.detail": "Dalam mode ekstensi, tindakan ini memakai chrome.permissions. Dalam pratinjau browser, tindakan kembali ke simulasi status lokal.",
  },
} satisfies Partial<Record<ResolvedAppLocale, Partial<RuntimeMessages>>>;
