import type { ResolvedAppLocale, RuntimeMessages } from "../i18n";

export const OTHER_RUNTIME_MESSAGE_OVERRIDES = {
  ru: {
    "app.loading.eyebrow": "Загрузка",
    "app.loading.title": "Подготовка состояния панели",
    "app.loading.detail": "Инициализация хранилища панели и шины сообщений.",
    "app.error.eyebrow": "Состояние недоступно",
    "app.error.title": "Инициализация не завершена",
    "app.error.detail_fallback": "Не удалось загрузить состояние приложения из хранилища расширения или локального хранилища предпросмотра.",
    "common.actions.retry": "Повторить",
    "common.actions.settings": "Настройки",
    "common.actions.refresh": "Обновить",
    "common.actions.refresh_all": "Обновить все",
    "common.actions.back": "Назад",
    "common.actions.open_dashboard": "Открыть панель",
    "common.actions.open_settings": "Открыть настройки",
    "common.actions.open_dashboard_tab": "Открыть вкладку панели",
    "common.actions.open_settings_tab": "Открыть вкладку настроек",
    "common.actions.tab": "Вкладка",
    "common.actions.save": "Сохранить",
    "common.theme.toggle_to_dark_label": "Темная",
    "common.theme.toggle_to_dark_title": "Переключить на темный режим",
    "common.theme.toggle_to_light_label": "Светлая",
    "common.theme.toggle_to_light_title": "Переключить на светлый режим",
    "dashboard.topbar.title": "Панель использования ИИ",
    "dashboard.topbar.subtitle": "Использование, кредиты и состояние синхронизации",
    "dashboard.hero.eyebrow": "Обзор",
    "dashboard.hero.title": "Одна панель для квот AI coding",
    "dashboard.hero.detail": "Официальные API, документированные политики квот и защищенные источники анализа страниц собраны в готовую к выпуску панель для обновлений, настроек и деталей Provider.",
    "dashboard.hero.release_chip": "Material 3 · Кандидат релиза",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Карточки Provider",
    "dashboard.providers.detail": "Карточки сортируются сначала по серьезности, затем по текущим пробелам доступа, чтобы provider с наибольшим риском оставались сверху, а текущий продуктовый контракт был виден сразу.",
    "dashboard.providers.aria": "Карточки Provider",
    "dashboard.empty.eyebrow": "Нет видимых Provider",
    "dashboard.empty.detail": "Начните с Quick Setup, включите первый Provider, выполните шаги доступа и страницы использования, затем вернитесь на панель.",
    "dashboard.empty.action": "Открыть Quick Setup",
    "dashboard.summary.aria": "Сводка панели",
    "dashboard.summary.visible": "Видимые",
    "dashboard.summary.healthy": "В порядке",
    "dashboard.summary.needs_access": "Нужен доступ",
    "dashboard.summary.needs_attention": "Требует внимания",
    "popup.loading.eyebrow": "Popup панели инструментов",
    "popup.loading.title": "Загрузка кэшированного состояния панели",
    "popup.loading.detail": "Подготовка общего снимка квот для этого профиля браузера.",
    "popup.error.eyebrow": "Popup панели инструментов",
    "popup.error.title": "Не удалось загрузить popup",
    "popup.header.eyebrow": "Popup панели инструментов",
    "popup.header.title": "Быстрый обзор",
    "popup.summary.aria": "Верхняя сводка popup",
    "popup.guidance.eyebrow": "Подсказки popup",
    "popup.snapshot_status.eyebrow": "Состояние снимка",
    "popup.actions.eyebrow": "Другой маршрут",
    "popup.actions.refresh": "Обновить",
    "popup.actions.refreshing": "Обновление",
    "popup.featured.eyebrow": "Выбранные Provider",
    "popup.featured.single_eyebrow": "Выбранный Provider",
    "popup.triage.eyebrow": "Разбор popup",
    "popup.summary.visible": "Видимые",
    "popup.summary.live_ready": "Готово к live-данным",
    "popup.summary.setup_blockers": "Блокеры настройки",
    "popup.summary.policy_only": "Только политика",
    "settings.topbar.title": "Настройки",
    "settings.topbar.subtitle": "Quick Setup, внешний вид и расширенное управление Provider",
    "settings.overview.eyebrow": "Обзор настроек",
    "settings.overview.title": "Сводка поверхности управления",
    "settings.overview.detail": "Используйте этот экран для управления видимостью, разрешениями, учетными данными и гибридными source-контролями. Переходите сразу к нужному разделу вместо просмотра всей страницы.",
    "settings.overview.aria": "Обзор настроек",
    "settings.sections.aria": "Разделы настроек",
    "settings.sections.preferences": "Предпочтения",
    "settings.sections.visibility": "Видимость",
    "settings.sections.credentials": "Учетные данные",
    "settings.sections.sources": "Источники",
    "settings.sections.permissions": "Разрешения",
    "settings.actions.back_to_top": "Наверх",
    "settings.actions.back_to_top_short": "Вверх",
    "settings.summary.visible": "Видимые",
    "settings.summary.stored_secrets": "Сохраненные секреты",
    "settings.summary.bound_pages": "Связанные страницы",
    "settings.summary.needs_access": "Нужен доступ",
    "settings.preferences.eyebrow": "Внешний вид и синхронизация",
    "settings.preferences.sync_interval_label": "Интервал синхронизации по умолчанию",
    "settings.preferences.warning_threshold_label": "Порог предупреждения",
    "settings.preferences.locale_label": "Язык приложения",
    "settings.preferences.theme_mode_label": "Режим темы",
    "settings.preferences.accent_preset_label": "Предустановка акцента",
    "settings.preferences.popup_progress_style_label": "Стиль квоты Popup",
    "settings.preferences.sidebar_progress_style_label": "Стиль квоты боковой панели",
    "settings.preferences.full_page_progress_style_label": "Стиль квоты вкладки",
    "settings.preferences.progress_style.line": "Линия",
    "settings.preferences.progress_style.circle": "Круг",
    "settings.preferences.popup_size_label": "Размер Popup",
    "settings.preferences.popup_size.compact": "Компактный",
    "settings.preferences.popup_size.balanced": "Сбалансированный",
    "settings.preferences.popup_size.wide": "Широкий",
    "settings.preferences.popup_corner_label": "Углы Popup",
    "settings.preferences.popup_corner.square": "Прямые",
    "settings.preferences.popup_corner.soft": "Мягкие",
    "settings.preferences.popup_corner.rounded": "Скругленные",
    "settings.preferences.popup_shadow_label": "Тень Popup",
    "settings.preferences.popup_shadow.none": "Нет",
    "settings.preferences.popup_shadow.soft": "Мягкая",
    "settings.preferences.popup_shadow.elevated": "Выраженная",
    "settings.preferences.action_badge_label": "Значок панели инструментов",
    "settings.preferences.minutes": "минут",
    "settings.preferences.locale.system": "Как в системе",
    "settings.preferences.locale.en": "Английский",
    "settings.preferences.locale.zh_cn": "Китайский упрощенный",
    "settings.preferences.theme_mode.system": "Как в системе",
    "settings.preferences.theme_mode.light": "Светлая",
    "settings.preferences.theme_mode.dark": "Темная",
    "settings.preferences.theme_preset.default": "Синий по умолчанию",
    "settings.preferences.theme_preset.meadow": "Луг",
    "settings.preferences.theme_preset.sunset": "Закат",
    "settings.preferences.theme_preset.custom": "Пользовательский seed",
    "settings.toast.preferences_saved_title": "Предпочтения сохранены",
    "settings.toast.preferences_saved_detail": "Текущие настройки предпросмотра сохранены в локальном состоянии панели.",
  },
  ar: {
    "app.loading.eyebrow": "جار التحميل",
    "app.loading.title": "جار تجهيز حالة لوحة المعلومات",
    "app.loading.detail": "جار تهيئة تخزين لوحة المعلومات وناقل الرسائل.",
    "app.error.eyebrow": "الحالة غير متاحة",
    "app.error.title": "لم تكتمل التهيئة",
    "app.error.detail_fallback": "تعذر تحميل حالة التطبيق من تخزين الإضافة أو تخزين المعاينة المحلي.",
    "common.actions.retry": "إعادة المحاولة",
    "common.actions.settings": "الإعدادات",
    "common.actions.refresh": "تحديث",
    "common.actions.refresh_all": "تحديث الكل",
    "common.actions.back": "رجوع",
    "common.actions.open_dashboard": "فتح لوحة المعلومات",
    "common.actions.open_settings": "فتح الإعدادات",
    "common.actions.open_dashboard_tab": "فتح تبويب لوحة المعلومات",
    "common.actions.open_settings_tab": "فتح تبويب الإعدادات",
    "common.actions.tab": "تبويب",
    "common.actions.save": "حفظ",
    "common.theme.toggle_to_dark_label": "داكن",
    "common.theme.toggle_to_dark_title": "التبديل إلى الوضع الداكن",
    "common.theme.toggle_to_light_label": "فاتح",
    "common.theme.toggle_to_light_title": "التبديل إلى الوضع الفاتح",
    "dashboard.topbar.title": "لوحة استخدام الذكاء الاصطناعي",
    "dashboard.topbar.subtitle": "الاستخدام والأرصدة وحالة المزامنة",
    "dashboard.hero.eyebrow": "نظرة عامة",
    "dashboard.hero.title": "لوحة واحدة لحصص AI coding",
    "dashboard.hero.detail": "تجمع اللوحة واجهات API الرسمية وسياسات الحصص الموثقة ومصادر تحليل الصفحات المحمية في تجربة جاهزة للإصدار للتحديثات والإعدادات وتفاصيل Provider.",
    "dashboard.hero.release_chip": "Material 3 · مرشح إصدار",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "بطاقات Provider",
    "dashboard.providers.detail": "تُرتب البطاقات حسب درجة الخطورة أولا، ثم حسب فجوات الوصول الحالية، حتى تبقى provider الأعلى خطرا في أعلى اللوحة مع إبقاء عقد المنتج الحالي واضحا.",
    "dashboard.providers.aria": "بطاقات Provider",
    "dashboard.empty.eyebrow": "لا توجد Provider مرئية",
    "dashboard.empty.detail": "ابدأ من Quick Setup لتفعيل أول Provider، ثم أكمل خطوات الوصول وصفحة الاستخدام قبل الرجوع إلى لوحة المعلومات.",
    "dashboard.empty.action": "فتح Quick Setup",
    "dashboard.summary.aria": "ملخص لوحة المعلومات",
    "dashboard.summary.visible": "مرئية",
    "dashboard.summary.healthy": "سليمة",
    "dashboard.summary.needs_access": "تحتاج وصولا",
    "dashboard.summary.needs_attention": "تحتاج انتباها",
    "popup.loading.eyebrow": "Popup شريط الأدوات",
    "popup.loading.title": "جار تحميل حالة لوحة المعلومات المخزنة",
    "popup.loading.detail": "جار تجهيز لقطة الحصص المشتركة لملف تعريف المتصفح هذا.",
    "popup.error.eyebrow": "Popup شريط الأدوات",
    "popup.error.title": "فشل تحميل popup",
    "popup.header.eyebrow": "Popup شريط الأدوات",
    "popup.header.title": "نظرة سريعة",
    "popup.summary.aria": "ملخص أعلى popup",
    "popup.guidance.eyebrow": "إرشادات popup",
    "popup.snapshot_status.eyebrow": "حالة اللقطة",
    "popup.actions.eyebrow": "مسار آخر",
    "popup.actions.refresh": "تحديث",
    "popup.actions.refreshing": "جار التحديث",
    "popup.featured.eyebrow": "Providers مميزة",
    "popup.featured.single_eyebrow": "Provider مميز",
    "popup.triage.eyebrow": "فرز popup",
    "popup.summary.visible": "مرئية",
    "popup.summary.live_ready": "جاهزة للبيانات الحية",
    "popup.summary.setup_blockers": "عوائق الإعداد",
    "popup.summary.policy_only": "سياسة فقط",
    "settings.topbar.title": "الإعدادات",
    "settings.topbar.subtitle": "Quick Setup والمظهر وعناصر تحكم Provider المتقدمة",
    "settings.overview.eyebrow": "نظرة عامة على الإعدادات",
    "settings.overview.title": "ملخص سطح التحكم",
    "settings.overview.detail": "استخدم هذه الشاشة لإدارة الظهور والأذونات وبيانات الاعتماد وعناصر تحكم source الهجينة. انتقل مباشرة إلى القسم المطلوب بدلا من قراءة الصفحة كلها.",
    "settings.overview.aria": "نظرة عامة على الإعدادات",
    "settings.sections.aria": "أقسام الإعدادات",
    "settings.sections.preferences": "التفضيلات",
    "settings.sections.visibility": "الظهور",
    "settings.sections.credentials": "بيانات الاعتماد",
    "settings.sections.sources": "المصادر",
    "settings.sections.permissions": "الأذونات",
    "settings.actions.back_to_top": "العودة للأعلى",
    "settings.actions.back_to_top_short": "الأعلى",
    "settings.summary.visible": "مرئية",
    "settings.summary.stored_secrets": "أسرار محفوظة",
    "settings.summary.bound_pages": "صفحات مرتبطة",
    "settings.summary.needs_access": "تحتاج وصولا",
    "settings.preferences.eyebrow": "المظهر والمزامنة",
    "settings.preferences.sync_interval_label": "فاصل المزامنة الافتراضي",
    "settings.preferences.warning_threshold_label": "عتبة التحذير",
    "settings.preferences.locale_label": "لغة التطبيق",
    "settings.preferences.theme_mode_label": "وضع السمة",
    "settings.preferences.accent_preset_label": "إعداد لون التمييز",
    "settings.preferences.popup_progress_style_label": "نمط حصة Popup",
    "settings.preferences.sidebar_progress_style_label": "نمط حصة الشريط الجانبي",
    "settings.preferences.full_page_progress_style_label": "نمط حصة التبويب",
    "settings.preferences.progress_style.line": "خط",
    "settings.preferences.progress_style.circle": "دائرة",
    "settings.preferences.popup_size_label": "حجم Popup",
    "settings.preferences.popup_size.compact": "مضغوط",
    "settings.preferences.popup_size.balanced": "متوازن",
    "settings.preferences.popup_size.wide": "واسع",
    "settings.preferences.popup_corner_label": "زوايا Popup",
    "settings.preferences.popup_corner.square": "مربعة",
    "settings.preferences.popup_corner.soft": "ناعمة",
    "settings.preferences.popup_corner.rounded": "مستديرة",
    "settings.preferences.popup_shadow_label": "ظل Popup",
    "settings.preferences.popup_shadow.none": "بدون",
    "settings.preferences.popup_shadow.soft": "ناعم",
    "settings.preferences.popup_shadow.elevated": "بارز",
    "settings.preferences.action_badge_label": "شارة شريط الأدوات",
    "settings.preferences.minutes": "دقائق",
    "settings.preferences.locale.system": "اتباع النظام",
    "settings.preferences.locale.en": "الإنجليزية",
    "settings.preferences.locale.zh_cn": "الصينية المبسطة",
    "settings.preferences.theme_mode.system": "اتباع النظام",
    "settings.preferences.theme_mode.light": "فاتح",
    "settings.preferences.theme_mode.dark": "داكن",
    "settings.preferences.theme_preset.default": "الأزرق الافتراضي",
    "settings.preferences.theme_preset.meadow": "مرج",
    "settings.preferences.theme_preset.sunset": "غروب",
    "settings.preferences.theme_preset.custom": "بذرة مخصصة",
    "settings.toast.preferences_saved_title": "تم حفظ التفضيلات",
    "settings.toast.preferences_saved_detail": "تم حفظ إعدادات المعاينة الحالية في حالة لوحة المعلومات المحلية.",
  },
  hi: {
    "app.loading.eyebrow": "लोड हो रहा है",
    "app.loading.title": "डैशबोर्ड स्थिति तैयार हो रही है",
    "app.loading.detail": "डैशबोर्ड स्टोरेज और message bus शुरू किया जा रहा है।",
    "app.error.eyebrow": "स्थिति उपलब्ध नहीं",
    "app.error.title": "आरंभ पूरा नहीं हुआ",
    "app.error.detail_fallback": "extension storage या local preview storage से app state लोड नहीं हो सकी।",
    "common.actions.retry": "फिर कोशिश करें",
    "common.actions.settings": "सेटिंग्स",
    "common.actions.refresh": "रीफ्रेश",
    "common.actions.refresh_all": "सब रीफ्रेश करें",
    "common.actions.back": "वापस",
    "common.actions.open_dashboard": "डैशबोर्ड खोलें",
    "common.actions.open_settings": "सेटिंग्स खोलें",
    "common.actions.open_dashboard_tab": "डैशबोर्ड टैब खोलें",
    "common.actions.open_settings_tab": "सेटिंग्स टैब खोलें",
    "common.actions.tab": "टैब",
    "common.actions.save": "सहेजें",
    "common.theme.toggle_to_dark_label": "डार्क",
    "common.theme.toggle_to_dark_title": "डार्क मोड पर जाएं",
    "common.theme.toggle_to_light_label": "लाइट",
    "common.theme.toggle_to_light_title": "लाइट मोड पर जाएं",
    "dashboard.topbar.title": "AI उपयोग डैशबोर्ड",
    "dashboard.topbar.subtitle": "उपयोग, credits और sync health",
    "dashboard.hero.eyebrow": "अवलोकन",
    "dashboard.hero.title": "AI coding quotas के लिए एक डैशबोर्ड",
    "dashboard.hero.detail": "Official APIs, documented quota policies और guarded page parsing paths को refresh, settings और Provider details के लिए एक release-ready dashboard में जोड़ा गया है।",
    "dashboard.hero.release_chip": "Material 3 · release candidate",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Provider cards",
    "dashboard.providers.detail": "Cards पहले severity और फिर current access gaps के आधार पर क्रमबद्ध होते हैं, ताकि high-risk provider ऊपर रहें और current product contract तुरंत दिखे।",
    "dashboard.providers.aria": "Provider cards",
    "dashboard.empty.eyebrow": "कोई visible Provider नहीं",
    "dashboard.empty.detail": "पहला Provider सक्षम करने के लिए Quick Setup खोलें, फिर access और usage-page steps पूरे करके डैशबोर्ड पर लौटें।",
    "dashboard.empty.action": "Quick Setup खोलें",
    "dashboard.summary.aria": "डैशबोर्ड सारांश",
    "dashboard.summary.visible": "Visible",
    "dashboard.summary.healthy": "Healthy",
    "dashboard.summary.needs_access": "Access चाहिए",
    "dashboard.summary.needs_attention": "ध्यान चाहिए",
    "popup.loading.eyebrow": "Toolbar Popup",
    "popup.loading.title": "Cached dashboard state लोड हो रही है",
    "popup.loading.detail": "इस browser profile के लिए shared quota snapshot तैयार हो रहा है।",
    "popup.error.eyebrow": "Toolbar Popup",
    "popup.error.title": "Popup लोड नहीं हुआ",
    "popup.header.eyebrow": "Toolbar Popup",
    "popup.header.title": "त्वरित झलक",
    "popup.summary.aria": "Popup शीर्ष सारांश",
    "popup.guidance.eyebrow": "Popup guidance",
    "popup.snapshot_status.eyebrow": "Snapshot status",
    "popup.actions.eyebrow": "अन्य रास्ता",
    "popup.actions.refresh": "रीफ्रेश",
    "popup.actions.refreshing": "रीफ्रेश हो रहा है",
    "popup.featured.eyebrow": "Featured Providers",
    "popup.featured.single_eyebrow": "Featured Provider",
    "popup.triage.eyebrow": "Popup triage",
    "popup.summary.visible": "Visible",
    "popup.summary.live_ready": "Live ready",
    "popup.summary.setup_blockers": "Setup blockers",
    "popup.summary.policy_only": "Policy only",
    "settings.topbar.title": "सेटिंग्स",
    "settings.topbar.subtitle": "Quick Setup, appearance और advanced Provider controls",
    "settings.overview.eyebrow": "सेटिंग्स अवलोकन",
    "settings.overview.title": "Control surface summary",
    "settings.overview.detail": "Visibility, permissions, credentials और hybrid source controls को संभालने के लिए इस स्क्रीन का उपयोग करें। पूरी page पढ़ने के बजाय सीधे जरूरी section पर जाएं।",
    "settings.overview.aria": "सेटिंग्स अवलोकन",
    "settings.sections.aria": "सेटिंग्स sections",
    "settings.sections.preferences": "Preferences",
    "settings.sections.visibility": "Visibility",
    "settings.sections.credentials": "Credentials",
    "settings.sections.sources": "Sources",
    "settings.sections.permissions": "Permissions",
    "settings.actions.back_to_top": "ऊपर जाएं",
    "settings.actions.back_to_top_short": "ऊपर",
    "settings.summary.visible": "Visible",
    "settings.summary.stored_secrets": "Stored secrets",
    "settings.summary.bound_pages": "Bound pages",
    "settings.summary.needs_access": "Access चाहिए",
    "settings.preferences.eyebrow": "Appearance और sync",
    "settings.preferences.sync_interval_label": "Default sync interval",
    "settings.preferences.warning_threshold_label": "Warning threshold",
    "settings.preferences.locale_label": "App language",
    "settings.preferences.theme_mode_label": "Theme mode",
    "settings.preferences.accent_preset_label": "Accent preset",
    "settings.preferences.popup_progress_style_label": "Popup quota style",
    "settings.preferences.sidebar_progress_style_label": "Sidebar quota style",
    "settings.preferences.full_page_progress_style_label": "Tab quota style",
    "settings.preferences.progress_style.line": "Line",
    "settings.preferences.progress_style.circle": "Circle",
    "settings.preferences.popup_size_label": "Popup size",
    "settings.preferences.popup_size.compact": "Compact",
    "settings.preferences.popup_size.balanced": "Balanced",
    "settings.preferences.popup_size.wide": "Wide",
    "settings.preferences.popup_corner_label": "Popup corners",
    "settings.preferences.popup_corner.square": "Square",
    "settings.preferences.popup_corner.soft": "Soft",
    "settings.preferences.popup_corner.rounded": "Rounded",
    "settings.preferences.popup_shadow_label": "Popup shadow",
    "settings.preferences.popup_shadow.none": "None",
    "settings.preferences.popup_shadow.soft": "Soft",
    "settings.preferences.popup_shadow.elevated": "Elevated",
    "settings.preferences.action_badge_label": "Toolbar badge",
    "settings.preferences.minutes": "मिनट",
    "settings.preferences.locale.system": "सिस्टम का अनुसरण करें",
    "settings.preferences.locale.en": "अंग्रेजी",
    "settings.preferences.locale.zh_cn": "सरलीकृत चीनी",
    "settings.preferences.theme_mode.system": "सिस्टम का अनुसरण करें",
    "settings.preferences.theme_mode.light": "लाइट",
    "settings.preferences.theme_mode.dark": "डार्क",
    "settings.preferences.theme_preset.default": "Default blue",
    "settings.preferences.theme_preset.meadow": "Meadow",
    "settings.preferences.theme_preset.sunset": "Sunset",
    "settings.preferences.theme_preset.custom": "Custom seed",
    "settings.toast.preferences_saved_title": "Preferences सहेजी गईं",
    "settings.toast.preferences_saved_detail": "मौजूदा preview settings local dashboard state में सहेज दी गई हैं।",
  },
  id: {
    "app.loading.eyebrow": "Memuat",
    "app.loading.title": "Menyiapkan status dasbor",
    "app.loading.detail": "Menginisialisasi penyimpanan dasbor dan message bus.",
    "app.error.eyebrow": "Status tidak tersedia",
    "app.error.title": "Inisialisasi belum selesai",
    "app.error.detail_fallback": "Tidak dapat memuat status aplikasi dari extension storage atau local preview storage.",
    "common.actions.retry": "Coba lagi",
    "common.actions.settings": "Pengaturan",
    "common.actions.refresh": "Segarkan",
    "common.actions.refresh_all": "Segarkan semua",
    "common.actions.back": "Kembali",
    "common.actions.open_dashboard": "Buka dasbor",
    "common.actions.open_settings": "Buka pengaturan",
    "common.actions.open_dashboard_tab": "Buka tab dasbor",
    "common.actions.open_settings_tab": "Buka tab pengaturan",
    "common.actions.tab": "Tab",
    "common.actions.save": "Simpan",
    "common.theme.toggle_to_dark_label": "Gelap",
    "common.theme.toggle_to_dark_title": "Beralih ke mode gelap",
    "common.theme.toggle_to_light_label": "Terang",
    "common.theme.toggle_to_light_title": "Beralih ke mode terang",
    "dashboard.topbar.title": "Dasbor Penggunaan AI",
    "dashboard.topbar.subtitle": "Penggunaan, kredit, dan kesehatan sinkronisasi",
    "dashboard.hero.eyebrow": "Ringkasan",
    "dashboard.hero.title": "Satu dasbor untuk kuota AI coding",
    "dashboard.hero.detail": "Official APIs, documented quota policies, dan guarded page parsing paths digabungkan menjadi satu dashboard release-ready untuk refresh, settings, dan detail Provider.",
    "dashboard.hero.release_chip": "Material 3 · release candidate",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Kartu Provider",
    "dashboard.providers.detail": "Kartu diurutkan menurut severity lalu current access gaps, sehingga provider berisiko tinggi tetap berada di atas sambil menjaga current product contract tetap terlihat.",
    "dashboard.providers.aria": "Kartu Provider",
    "dashboard.empty.eyebrow": "Tidak ada Provider terlihat",
    "dashboard.empty.detail": "Mulai dari Quick Setup untuk mengaktifkan Provider pertama, lalu selesaikan langkah akses dan usage page sebelum kembali ke dasbor.",
    "dashboard.empty.action": "Buka Quick Setup",
    "dashboard.summary.aria": "Ringkasan dasbor",
    "dashboard.summary.visible": "Terlihat",
    "dashboard.summary.healthy": "Sehat",
    "dashboard.summary.needs_access": "Perlu akses",
    "dashboard.summary.needs_attention": "Perlu perhatian",
    "popup.loading.eyebrow": "Toolbar Popup",
    "popup.loading.title": "Memuat cached dashboard state",
    "popup.loading.detail": "Menyiapkan shared quota snapshot untuk browser profile ini.",
    "popup.error.eyebrow": "Toolbar Popup",
    "popup.error.title": "Popup gagal dimuat",
    "popup.header.eyebrow": "Toolbar Popup",
    "popup.header.title": "Ringkasan cepat",
    "popup.summary.aria": "Ringkasan atas Popup",
    "popup.guidance.eyebrow": "Panduan Popup",
    "popup.snapshot_status.eyebrow": "Status snapshot",
    "popup.actions.eyebrow": "Jalur lain",
    "popup.actions.refresh": "Segarkan",
    "popup.actions.refreshing": "Menyegarkan",
    "popup.featured.eyebrow": "Provider unggulan",
    "popup.featured.single_eyebrow": "Provider unggulan",
    "popup.triage.eyebrow": "Triage Popup",
    "popup.summary.visible": "Terlihat",
    "popup.summary.live_ready": "Live ready",
    "popup.summary.setup_blockers": "Setup blockers",
    "popup.summary.policy_only": "Policy only",
    "settings.topbar.title": "Pengaturan",
    "settings.topbar.subtitle": "Quick Setup, appearance, dan advanced Provider controls",
    "settings.overview.eyebrow": "Ringkasan pengaturan",
    "settings.overview.title": "Ringkasan control surface",
    "settings.overview.detail": "Gunakan layar ini untuk mengelola visibility, permissions, credentials, dan hybrid source controls. Lompat langsung ke section yang dibutuhkan tanpa membaca seluruh halaman.",
    "settings.overview.aria": "Ringkasan pengaturan",
    "settings.sections.aria": "Section pengaturan",
    "settings.sections.preferences": "Preferensi",
    "settings.sections.visibility": "Visibility",
    "settings.sections.credentials": "Credentials",
    "settings.sections.sources": "Sources",
    "settings.sections.permissions": "Permissions",
    "settings.actions.back_to_top": "Kembali ke atas",
    "settings.actions.back_to_top_short": "Atas",
    "settings.summary.visible": "Terlihat",
    "settings.summary.stored_secrets": "Stored secrets",
    "settings.summary.bound_pages": "Bound pages",
    "settings.summary.needs_access": "Perlu akses",
    "settings.preferences.eyebrow": "Appearance dan sync",
    "settings.preferences.sync_interval_label": "Default sync interval",
    "settings.preferences.warning_threshold_label": "Warning threshold",
    "settings.preferences.locale_label": "Bahasa aplikasi",
    "settings.preferences.theme_mode_label": "Theme mode",
    "settings.preferences.accent_preset_label": "Accent preset",
    "settings.preferences.popup_progress_style_label": "Gaya kuota Popup",
    "settings.preferences.sidebar_progress_style_label": "Gaya kuota sidebar",
    "settings.preferences.full_page_progress_style_label": "Gaya kuota tab",
    "settings.preferences.progress_style.line": "Line",
    "settings.preferences.progress_style.circle": "Circle",
    "settings.preferences.popup_size_label": "Ukuran Popup",
    "settings.preferences.popup_size.compact": "Compact",
    "settings.preferences.popup_size.balanced": "Balanced",
    "settings.preferences.popup_size.wide": "Wide",
    "settings.preferences.popup_corner_label": "Sudut Popup",
    "settings.preferences.popup_corner.square": "Square",
    "settings.preferences.popup_corner.soft": "Soft",
    "settings.preferences.popup_corner.rounded": "Rounded",
    "settings.preferences.popup_shadow_label": "Bayangan Popup",
    "settings.preferences.popup_shadow.none": "None",
    "settings.preferences.popup_shadow.soft": "Soft",
    "settings.preferences.popup_shadow.elevated": "Elevated",
    "settings.preferences.action_badge_label": "Toolbar badge",
    "settings.preferences.minutes": "menit",
    "settings.preferences.locale.system": "Ikuti sistem",
    "settings.preferences.locale.en": "Inggris",
    "settings.preferences.locale.zh_cn": "Tionghoa Sederhana",
    "settings.preferences.theme_mode.system": "Ikuti sistem",
    "settings.preferences.theme_mode.light": "Terang",
    "settings.preferences.theme_mode.dark": "Gelap",
    "settings.preferences.theme_preset.default": "Biru default",
    "settings.preferences.theme_preset.meadow": "Padang rumput",
    "settings.preferences.theme_preset.sunset": "Senja",
    "settings.preferences.theme_preset.custom": "Custom seed",
    "settings.toast.preferences_saved_title": "Preferensi disimpan",
    "settings.toast.preferences_saved_detail": "Pengaturan preview saat ini disimpan ke local dashboard state.",
  },
} satisfies Partial<Record<ResolvedAppLocale, Partial<RuntimeMessages>>>;
