import type { ResolvedAppLocale, RuntimeMessages } from "../i18n";

export const LATIN_RUNTIME_MESSAGE_OVERRIDES = {
  "es-419": {
    "app.loading.eyebrow": "Cargando",
    "app.loading.title": "Preparando el estado del panel",
    "app.loading.detail": "Inicializando el almacenamiento del panel y el bus de mensajes.",
    "app.error.eyebrow": "Estado no disponible",
    "app.error.title": "La inicialización no se completó",
    "app.error.detail_fallback": "No se pudo cargar el estado de la app desde el almacenamiento de la extensión o el almacenamiento local de vista previa.",
    "common.actions.retry": "Reintentar",
    "common.actions.settings": "Configuración",
    "common.actions.refresh": "Actualizar",
    "common.actions.refresh_all": "Actualizar todo",
    "common.actions.back": "Volver",
    "common.actions.open_dashboard": "Abrir panel",
    "common.actions.open_settings": "Abrir configuración",
    "common.actions.open_dashboard_tab": "Abrir pestaña del panel",
    "common.actions.open_settings_tab": "Abrir pestaña de configuración",
    "common.actions.tab": "Pestaña",
    "common.actions.save": "Guardar",
    "common.theme.toggle_to_dark_label": "Oscuro",
    "common.theme.toggle_to_dark_title": "Cambiar a modo oscuro",
    "common.theme.toggle_to_light_label": "Claro",
    "common.theme.toggle_to_light_title": "Cambiar a modo claro",
    "dashboard.topbar.title": "Panel de uso de IA",
    "dashboard.topbar.subtitle": "Uso, créditos y estado de sincronización",
    "dashboard.hero.eyebrow": "Resumen",
    "dashboard.hero.title": "Un panel para las cuotas de codificación con IA",
    "dashboard.hero.detail": "APIs oficiales, políticas de cuota documentadas y fuentes protegidas de análisis de páginas se reúnen en un panel listo para lanzamiento con actualizaciones, configuración y detalles de Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidato de lanzamiento",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Tarjetas de Provider",
    "dashboard.providers.detail": "Las tarjetas se ordenan primero por gravedad y luego por brechas de acceso actuales, para que los provider de mayor riesgo se mantengan arriba sin perder de vista el contrato de producto actual.",
    "dashboard.providers.aria": "Tarjetas de Provider",
    "dashboard.empty.eyebrow": "No hay Provider visibles",
    "dashboard.empty.detail": "Empieza en Quick Setup para activar tu primer Provider, completa los pasos de acceso y página de uso, y luego vuelve al panel.",
    "dashboard.empty.action": "Abrir Quick Setup",
    "dashboard.summary.aria": "Resumen del panel",
    "dashboard.summary.visible": "Visibles",
    "dashboard.summary.healthy": "Correctos",
    "dashboard.summary.needs_access": "Requiere acceso",
    "dashboard.summary.needs_attention": "Requiere atención",
    "popup.loading.eyebrow": "Popup de barra de herramientas",
    "popup.loading.title": "Cargando el estado del panel en caché",
    "popup.loading.detail": "Preparando la instantánea compartida de cuotas para este perfil del navegador.",
    "popup.error.eyebrow": "Popup de barra de herramientas",
    "popup.error.title": "No se pudo cargar el popup",
    "popup.header.eyebrow": "Popup de barra de herramientas",
    "popup.header.title": "Vista rápida",
    "popup.summary.aria": "Resumen superior del popup",
    "popup.guidance.eyebrow": "Guía del popup",
    "popup.snapshot_status.eyebrow": "Estado de instantánea",
    "popup.actions.eyebrow": "Otra ruta",
    "popup.actions.refresh": "Actualizar",
    "popup.actions.refreshing": "Actualizando",
    "popup.featured.eyebrow": "Providers destacados",
    "popup.featured.single_eyebrow": "Provider destacado",
    "popup.triage.eyebrow": "Priorización del popup",
    "popup.summary.visible": "Visibles",
    "popup.summary.live_ready": "Listo para datos en vivo",
    "popup.summary.setup_blockers": "Bloqueos de configuración",
    "popup.summary.policy_only": "Solo política",
    "settings.topbar.title": "Configuración",
    "settings.topbar.subtitle": "Quick Setup, apariencia y controles avanzados de Provider",
    "settings.overview.eyebrow": "Resumen de configuración",
    "settings.overview.title": "Resumen de superficie de control",
    "settings.overview.detail": "Usa esta pantalla para administrar visibilidad, permisos, credenciales y controles de source híbridos. Salta directamente a la sección que necesitas en vez de revisar toda la página.",
    "settings.overview.aria": "Resumen de configuración",
    "settings.sections.aria": "Secciones de configuración",
    "settings.sections.preferences": "Preferencias",
    "settings.sections.visibility": "Visibilidad",
    "settings.sections.credentials": "Credenciales",
    "settings.sections.sources": "Fuentes",
    "settings.sections.permissions": "Permisos",
    "settings.actions.back_to_top": "Volver arriba",
    "settings.actions.back_to_top_short": "Arriba",
    "settings.summary.visible": "Visibles",
    "settings.summary.stored_secrets": "Secretos guardados",
    "settings.summary.bound_pages": "Páginas vinculadas",
    "settings.summary.needs_access": "Requiere acceso",
    "settings.preferences.eyebrow": "Apariencia y sincronización",
    "settings.preferences.sync_interval_label": "Intervalo de sincronización predeterminado",
    "settings.preferences.warning_threshold_label": "Umbral de advertencia",
    "settings.preferences.locale_label": "Idioma de la app",
    "settings.preferences.theme_mode_label": "Modo de tema",
    "settings.preferences.accent_preset_label": "Preajuste de acento",
    "settings.preferences.popup_progress_style_label": "Estilo de cuota del Popup",
    "settings.preferences.sidebar_progress_style_label": "Estilo de cuota de la barra lateral",
    "settings.preferences.full_page_progress_style_label": "Estilo de cuota de la pestaña",
    "settings.preferences.progress_style.line": "Línea",
    "settings.preferences.progress_style.circle": "Círculo",
    "settings.preferences.progress_style.circle_soft": "Círculo suave",
    "settings.preferences.progress_style.circle_gauge": "Indicador circular",
    "settings.preferences.popup_size_label": "Tamaño del Popup",
    "settings.preferences.popup_size.compact": "Compacto",
    "settings.preferences.popup_size.balanced": "Equilibrado",
    "settings.preferences.popup_size.wide": "Ancho",
    "settings.preferences.popup_corner_label": "Esquinas del Popup",
    "settings.preferences.popup_corner.square": "Cuadradas",
    "settings.preferences.popup_corner.soft": "Suaves",
    "settings.preferences.popup_corner.rounded": "Redondeadas",
    "settings.preferences.popup_shadow_label": "Sombra del Popup",
    "settings.preferences.popup_shadow.none": "Ninguna",
    "settings.preferences.popup_shadow.soft": "Suave",
    "settings.preferences.popup_shadow.elevated": "Elevada",
    "settings.preferences.action_badge_label": "Insignia de barra de herramientas",
    "settings.preferences.minutes": "minutos",
    "settings.preferences.locale.system": "Seguir sistema",
    "settings.preferences.locale.en": "Inglés",
    "settings.preferences.locale.zh_cn": "Chino simplificado",
    "settings.preferences.theme_mode.system": "Seguir sistema",
    "settings.preferences.theme_mode.light": "Claro",
    "settings.preferences.theme_mode.dark": "Oscuro",
    "settings.preferences.theme_preset.default": "Azul predeterminado",
    "settings.preferences.theme_preset.meadow": "Prado",
    "settings.preferences.theme_preset.sunset": "Atardecer",
    "settings.preferences.theme_preset.custom": "Semilla personalizada",
    "settings.toast.preferences_saved_title": "Preferencias guardadas",
    "settings.toast.preferences_saved_detail": "La configuración actual de vista previa se guardó en el estado local del panel.",
  },
  "pt-BR": {
    "app.loading.eyebrow": "Carregando",
    "app.loading.title": "Preparando o estado do painel",
    "app.loading.detail": "Inicializando o armazenamento do painel e o barramento de mensagens.",
    "app.error.eyebrow": "Estado indisponível",
    "app.error.title": "A inicialização não foi concluída",
    "app.error.detail_fallback": "Não foi possível carregar o estado do app do armazenamento da extensão ou do armazenamento local de prévia.",
    "common.actions.retry": "Tentar novamente",
    "common.actions.settings": "Configurações",
    "common.actions.refresh": "Atualizar",
    "common.actions.refresh_all": "Atualizar tudo",
    "common.actions.back": "Voltar",
    "common.actions.open_dashboard": "Abrir painel",
    "common.actions.open_settings": "Abrir configurações",
    "common.actions.open_dashboard_tab": "Abrir aba do painel",
    "common.actions.open_settings_tab": "Abrir aba de configurações",
    "common.actions.tab": "Aba",
    "common.actions.save": "Salvar",
    "common.theme.toggle_to_dark_label": "Escuro",
    "common.theme.toggle_to_dark_title": "Alternar para modo escuro",
    "common.theme.toggle_to_light_label": "Claro",
    "common.theme.toggle_to_light_title": "Alternar para modo claro",
    "dashboard.topbar.title": "Painel de uso de IA",
    "dashboard.topbar.subtitle": "Uso, créditos e integridade da sincronização",
    "dashboard.hero.eyebrow": "Visão geral",
    "dashboard.hero.title": "Um painel para cotas de codificação com IA",
    "dashboard.hero.detail": "APIs oficiais, políticas de cota documentadas e fontes protegidas de análise de página são reunidas em um painel pronto para lançamento com atualizações, configurações e detalhes de Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidato a lançamento",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Cartões de Provider",
    "dashboard.providers.detail": "Os cartões são ordenados primeiro por gravidade e depois pelas lacunas de acesso atuais, mantendo os provider de maior risco no topo do painel sem perder o contrato de produto atual de vista.",
    "dashboard.providers.aria": "Cartões de Provider",
    "dashboard.empty.eyebrow": "Nenhum Provider visível",
    "dashboard.empty.detail": "Comece no Quick Setup para ativar seu primeiro Provider, conclua as etapas de acesso e página de uso e depois volte ao painel.",
    "dashboard.empty.action": "Abrir Quick Setup",
    "dashboard.summary.aria": "Resumo do painel",
    "dashboard.summary.visible": "Visíveis",
    "dashboard.summary.healthy": "Saudáveis",
    "dashboard.summary.needs_access": "Precisa de acesso",
    "dashboard.summary.needs_attention": "Precisa de atenção",
    "popup.loading.eyebrow": "Popup da barra de ferramentas",
    "popup.loading.title": "Carregando o estado em cache do painel",
    "popup.loading.detail": "Preparando o instantâneo compartilhado de cotas para este perfil do navegador.",
    "popup.error.eyebrow": "Popup da barra de ferramentas",
    "popup.error.title": "Falha ao carregar o popup",
    "popup.header.eyebrow": "Popup da barra de ferramentas",
    "popup.header.title": "Vista rápida",
    "popup.summary.aria": "Resumo superior do popup",
    "popup.guidance.eyebrow": "Orientação do popup",
    "popup.snapshot_status.eyebrow": "Estado do instantâneo",
    "popup.actions.eyebrow": "Outra rota",
    "popup.actions.refresh": "Atualizar",
    "popup.actions.refreshing": "Atualizando",
    "popup.featured.eyebrow": "Providers em destaque",
    "popup.featured.single_eyebrow": "Provider em destaque",
    "popup.triage.eyebrow": "Triagem do popup",
    "popup.summary.visible": "Visíveis",
    "popup.summary.live_ready": "Pronto para dados ao vivo",
    "popup.summary.setup_blockers": "Bloqueios de configuração",
    "popup.summary.policy_only": "Somente política",
    "settings.topbar.title": "Configurações",
    "settings.topbar.subtitle": "Quick Setup, aparência e controles avançados de Provider",
    "settings.overview.eyebrow": "Visão geral das configurações",
    "settings.overview.title": "Resumo da superfície de controle",
    "settings.overview.detail": "Use esta tela para gerenciar visibilidade, permissões, credenciais e controles de source híbridos. Vá direto para a seção necessária em vez de percorrer a página inteira.",
    "settings.overview.aria": "Visão geral das configurações",
    "settings.sections.aria": "Seções de configurações",
    "settings.sections.preferences": "Preferências",
    "settings.sections.visibility": "Visibilidade",
    "settings.sections.credentials": "Credenciais",
    "settings.sections.sources": "Fontes",
    "settings.sections.permissions": "Permissões",
    "settings.actions.back_to_top": "Voltar ao topo",
    "settings.actions.back_to_top_short": "Topo",
    "settings.summary.visible": "Visíveis",
    "settings.summary.stored_secrets": "Segredos armazenados",
    "settings.summary.bound_pages": "Páginas vinculadas",
    "settings.summary.needs_access": "Precisa de acesso",
    "settings.preferences.eyebrow": "Aparência e sincronização",
    "settings.preferences.sync_interval_label": "Intervalo padrão de sincronização",
    "settings.preferences.warning_threshold_label": "Limite de aviso",
    "settings.preferences.locale_label": "Idioma do app",
    "settings.preferences.theme_mode_label": "Modo de tema",
    "settings.preferences.accent_preset_label": "Predefinição de destaque",
    "settings.preferences.popup_progress_style_label": "Estilo de cota do Popup",
    "settings.preferences.sidebar_progress_style_label": "Estilo de cota da barra lateral",
    "settings.preferences.full_page_progress_style_label": "Estilo de cota da aba",
    "settings.preferences.progress_style.line": "Linha",
    "settings.preferences.progress_style.circle": "Círculo",
    "settings.preferences.progress_style.circle_soft": "Círculo suave",
    "settings.preferences.progress_style.circle_gauge": "Medidor circular",
    "settings.preferences.popup_size_label": "Tamanho do Popup",
    "settings.preferences.popup_size.compact": "Compacto",
    "settings.preferences.popup_size.balanced": "Equilibrado",
    "settings.preferences.popup_size.wide": "Amplo",
    "settings.preferences.popup_corner_label": "Cantos do Popup",
    "settings.preferences.popup_corner.square": "Quadrados",
    "settings.preferences.popup_corner.soft": "Suaves",
    "settings.preferences.popup_corner.rounded": "Arredondados",
    "settings.preferences.popup_shadow_label": "Sombra do Popup",
    "settings.preferences.popup_shadow.none": "Nenhuma",
    "settings.preferences.popup_shadow.soft": "Suave",
    "settings.preferences.popup_shadow.elevated": "Elevada",
    "settings.preferences.action_badge_label": "Selo da barra de ferramentas",
    "settings.preferences.minutes": "minutos",
    "settings.preferences.locale.system": "Seguir sistema",
    "settings.preferences.locale.en": "Inglês",
    "settings.preferences.locale.zh_cn": "Chinês simplificado",
    "settings.preferences.theme_mode.system": "Seguir sistema",
    "settings.preferences.theme_mode.light": "Claro",
    "settings.preferences.theme_mode.dark": "Escuro",
    "settings.preferences.theme_preset.default": "Azul padrão",
    "settings.preferences.theme_preset.meadow": "Prado",
    "settings.preferences.theme_preset.sunset": "Pôr do sol",
    "settings.preferences.theme_preset.custom": "Semente personalizada",
    "settings.toast.preferences_saved_title": "Preferências salvas",
    "settings.toast.preferences_saved_detail": "As configurações atuais da prévia foram salvas no estado local do painel.",
  },
  fr: {
    "app.loading.eyebrow": "Chargement",
    "app.loading.title": "Préparation de l'état du tableau de bord",
    "app.loading.detail": "Initialisation du stockage du tableau de bord et du bus de messages.",
    "app.error.eyebrow": "État indisponible",
    "app.error.title": "L'initialisation n'a pas été terminée",
    "app.error.detail_fallback": "Impossible de charger l'état de l'app depuis le stockage de l'extension ou le stockage local d'aperçu.",
    "common.actions.retry": "Réessayer",
    "common.actions.settings": "Paramètres",
    "common.actions.refresh": "Actualiser",
    "common.actions.refresh_all": "Tout actualiser",
    "common.actions.back": "Retour",
    "common.actions.open_dashboard": "Ouvrir le tableau de bord",
    "common.actions.open_settings": "Ouvrir les paramètres",
    "common.actions.open_dashboard_tab": "Ouvrir l'onglet du tableau de bord",
    "common.actions.open_settings_tab": "Ouvrir l'onglet des paramètres",
    "common.actions.tab": "Onglet",
    "common.actions.save": "Enregistrer",
    "common.theme.toggle_to_dark_label": "Sombre",
    "common.theme.toggle_to_dark_title": "Passer au mode sombre",
    "common.theme.toggle_to_light_label": "Clair",
    "common.theme.toggle_to_light_title": "Passer au mode clair",
    "dashboard.topbar.title": "Tableau de bord d'utilisation de l'IA",
    "dashboard.topbar.subtitle": "Utilisation, crédits et état de synchronisation",
    "dashboard.hero.eyebrow": "Vue d'ensemble",
    "dashboard.hero.title": "Un tableau de bord pour les quotas de codage IA",
    "dashboard.hero.detail": "Les API officielles, les politiques de quota documentées et les sources protégées d'analyse de page sont réunies dans un tableau de bord prêt pour publication, avec actualisation, paramètres et détails Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidat de publication",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Cartes Provider",
    "dashboard.providers.detail": "Les cartes sont triées d'abord par gravité, puis par lacunes d'accès actuelles, afin de garder les provider les plus risqués en haut du tableau de bord tout en exposant le contrat produit actuel.",
    "dashboard.providers.aria": "Cartes Provider",
    "dashboard.empty.eyebrow": "Aucun Provider visible",
    "dashboard.empty.detail": "Commencez dans Quick Setup pour activer votre premier Provider, terminez les étapes d'accès et de page d'utilisation, puis revenez au tableau de bord.",
    "dashboard.empty.action": "Ouvrir Quick Setup",
    "dashboard.summary.aria": "Résumé du tableau de bord",
    "dashboard.summary.visible": "Visibles",
    "dashboard.summary.healthy": "Sains",
    "dashboard.summary.needs_access": "Accès requis",
    "dashboard.summary.needs_attention": "Attention requise",
    "popup.loading.eyebrow": "Popup de la barre d'outils",
    "popup.loading.title": "Chargement de l'état mis en cache du tableau de bord",
    "popup.loading.detail": "Préparation de l'instantané partagé des quotas pour ce profil de navigateur.",
    "popup.error.eyebrow": "Popup de la barre d'outils",
    "popup.error.title": "Échec du chargement du popup",
    "popup.header.eyebrow": "Popup de la barre d'outils",
    "popup.header.title": "Coup d'oeil rapide",
    "popup.summary.aria": "Résumé supérieur du popup",
    "popup.guidance.eyebrow": "Guide du popup",
    "popup.snapshot_status.eyebrow": "État de l'instantané",
    "popup.actions.eyebrow": "Autre route",
    "popup.actions.refresh": "Actualiser",
    "popup.actions.refreshing": "Actualisation",
    "popup.featured.eyebrow": "Providers mis en avant",
    "popup.featured.single_eyebrow": "Provider mis en avant",
    "popup.triage.eyebrow": "Triage du popup",
    "popup.summary.visible": "Visibles",
    "popup.summary.live_ready": "Prêt pour les données en direct",
    "popup.summary.setup_blockers": "Blocages de configuration",
    "popup.summary.policy_only": "Politique uniquement",
    "settings.topbar.title": "Paramètres",
    "settings.topbar.subtitle": "Quick Setup, apparence et contrôles Provider avancés",
    "settings.overview.eyebrow": "Vue d'ensemble des paramètres",
    "settings.overview.title": "Résumé de la surface de contrôle",
    "settings.overview.detail": "Utilisez cet écran pour gérer la visibilité, les autorisations, les identifiants et les contrôles source hybrides. Accédez directement à la section nécessaire au lieu de parcourir toute la page.",
    "settings.overview.aria": "Vue d'ensemble des paramètres",
    "settings.sections.aria": "Sections de paramètres",
    "settings.sections.preferences": "Préférences",
    "settings.sections.visibility": "Visibilité",
    "settings.sections.credentials": "Identifiants",
    "settings.sections.sources": "Sources",
    "settings.sections.permissions": "Autorisations",
    "settings.actions.back_to_top": "Retour en haut",
    "settings.actions.back_to_top_short": "Haut",
    "settings.summary.visible": "Visibles",
    "settings.summary.stored_secrets": "Secrets enregistrés",
    "settings.summary.bound_pages": "Pages liées",
    "settings.summary.needs_access": "Accès requis",
    "settings.preferences.eyebrow": "Apparence et synchronisation",
    "settings.preferences.sync_interval_label": "Intervalle de synchronisation par défaut",
    "settings.preferences.warning_threshold_label": "Seuil d'avertissement",
    "settings.preferences.locale_label": "Langue de l'app",
    "settings.preferences.theme_mode_label": "Mode de thème",
    "settings.preferences.accent_preset_label": "Préréglage d'accent",
    "settings.preferences.popup_progress_style_label": "Style de quota du Popup",
    "settings.preferences.sidebar_progress_style_label": "Style de quota de la barre latérale",
    "settings.preferences.full_page_progress_style_label": "Style de quota de l'onglet",
    "settings.preferences.progress_style.line": "Ligne",
    "settings.preferences.progress_style.circle": "Cercle",
    "settings.preferences.progress_style.circle_soft": "Cercle doux",
    "settings.preferences.progress_style.circle_gauge": "Jauge circulaire",
    "settings.preferences.popup_size_label": "Taille du Popup",
    "settings.preferences.popup_size.compact": "Compact",
    "settings.preferences.popup_size.balanced": "Équilibré",
    "settings.preferences.popup_size.wide": "Large",
    "settings.preferences.popup_corner_label": "Coins du Popup",
    "settings.preferences.popup_corner.square": "Carrés",
    "settings.preferences.popup_corner.soft": "Souples",
    "settings.preferences.popup_corner.rounded": "Arrondis",
    "settings.preferences.popup_shadow_label": "Ombre du Popup",
    "settings.preferences.popup_shadow.none": "Aucune",
    "settings.preferences.popup_shadow.soft": "Souple",
    "settings.preferences.popup_shadow.elevated": "Élevée",
    "settings.preferences.action_badge_label": "Badge de la barre d'outils",
    "settings.preferences.minutes": "minutes",
    "settings.preferences.locale.system": "Suivre le système",
    "settings.preferences.locale.en": "Anglais",
    "settings.preferences.locale.zh_cn": "Chinois simplifié",
    "settings.preferences.theme_mode.system": "Suivre le système",
    "settings.preferences.theme_mode.light": "Clair",
    "settings.preferences.theme_mode.dark": "Sombre",
    "settings.preferences.theme_preset.default": "Bleu par défaut",
    "settings.preferences.theme_preset.meadow": "Prairie",
    "settings.preferences.theme_preset.sunset": "Coucher de soleil",
    "settings.preferences.theme_preset.custom": "Graine personnalisée",
    "settings.toast.preferences_saved_title": "Préférences enregistrées",
    "settings.toast.preferences_saved_detail": "Les paramètres actuels de l'aperçu ont été enregistrés dans l'état local du tableau de bord.",
  },
  de: {
    "app.loading.eyebrow": "Laden",
    "app.loading.title": "Dashboard-Status wird vorbereitet",
    "app.loading.detail": "Dashboard-Speicher und Nachrichtenbus werden initialisiert.",
    "app.error.eyebrow": "Status nicht verfügbar",
    "app.error.title": "Initialisierung wurde nicht abgeschlossen",
    "app.error.detail_fallback": "Der App-Status konnte weder aus dem Erweiterungsspeicher noch aus dem lokalen Vorschauspeicher geladen werden.",
    "common.actions.retry": "Erneut versuchen",
    "common.actions.settings": "Einstellungen",
    "common.actions.refresh": "Aktualisieren",
    "common.actions.refresh_all": "Alle aktualisieren",
    "common.actions.back": "Zurück",
    "common.actions.open_dashboard": "Dashboard öffnen",
    "common.actions.open_settings": "Einstellungen öffnen",
    "common.actions.open_dashboard_tab": "Dashboard-Tab öffnen",
    "common.actions.open_settings_tab": "Einstellungen-Tab öffnen",
    "common.actions.tab": "Tab",
    "common.actions.save": "Speichern",
    "common.theme.toggle_to_dark_label": "Dunkel",
    "common.theme.toggle_to_dark_title": "In den Dunkelmodus wechseln",
    "common.theme.toggle_to_light_label": "Hell",
    "common.theme.toggle_to_light_title": "In den Hellmodus wechseln",
    "dashboard.topbar.title": "KI-Nutzungsdashboard",
    "dashboard.topbar.subtitle": "Nutzung, Credits und Synchronisierungsstatus",
    "dashboard.hero.eyebrow": "Übersicht",
    "dashboard.hero.title": "Ein Dashboard für KI-Coding-Kontingente",
    "dashboard.hero.detail": "Offizielle APIs, dokumentierte Kontingentrichtlinien und geschützte Seitenanalysequellen werden in einem veröffentlichungsreifen Dashboard für Aktualisierungen, Einstellungen und Provider-Details gebündelt.",
    "dashboard.hero.release_chip": "Material 3 · Release-Kandidat",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider-Karten",
    "dashboard.providers.detail": "Karten werden zuerst nach Schweregrad und dann nach aktuellen Zugriffslücken sortiert, damit riskante provider oben bleiben und der aktuelle Produktvertrag trotzdem sichtbar bleibt.",
    "dashboard.providers.aria": "Provider-Karten",
    "dashboard.empty.eyebrow": "Keine sichtbaren Provider",
    "dashboard.empty.detail": "Beginne in Quick Setup, aktiviere deinen ersten Provider, schließe die Zugriffs- und Nutzungsseiten-Schritte ab und kehre dann zum Dashboard zurück.",
    "dashboard.empty.action": "Quick Setup öffnen",
    "dashboard.summary.aria": "Dashboard-Zusammenfassung",
    "dashboard.summary.visible": "Sichtbar",
    "dashboard.summary.healthy": "OK",
    "dashboard.summary.needs_access": "Zugriff nötig",
    "dashboard.summary.needs_attention": "Aufmerksamkeit nötig",
    "popup.loading.eyebrow": "Toolbar-Popup",
    "popup.loading.title": "Zwischengespeicherter Dashboard-Status wird geladen",
    "popup.loading.detail": "Gemeinsame Kontingent-Momentaufnahme für dieses Browserprofil wird vorbereitet.",
    "popup.error.eyebrow": "Toolbar-Popup",
    "popup.error.title": "Popup konnte nicht geladen werden",
    "popup.header.eyebrow": "Toolbar-Popup",
    "popup.header.title": "Schnellüberblick",
    "popup.summary.aria": "Obere Popup-Zusammenfassung",
    "popup.guidance.eyebrow": "Popup-Hinweise",
    "popup.snapshot_status.eyebrow": "Momentaufnahme-Status",
    "popup.actions.eyebrow": "Andere Route",
    "popup.actions.refresh": "Aktualisieren",
    "popup.actions.refreshing": "Aktualisierung",
    "popup.featured.eyebrow": "Hervorgehobene Provider",
    "popup.featured.single_eyebrow": "Hervorgehobener Provider",
    "popup.triage.eyebrow": "Popup-Triage",
    "popup.summary.visible": "Sichtbar",
    "popup.summary.live_ready": "Live bereit",
    "popup.summary.setup_blockers": "Setup-Blocker",
    "popup.summary.policy_only": "Nur Richtlinie",
    "settings.topbar.title": "Einstellungen",
    "settings.topbar.subtitle": "Quick Setup, Darstellung und erweiterte Provider-Steuerung",
    "settings.overview.eyebrow": "Einstellungsübersicht",
    "settings.overview.title": "Zusammenfassung der Steueroberfläche",
    "settings.overview.detail": "Verwalte hier Sichtbarkeit, Berechtigungen, Zugangsdaten und hybride source-Steuerung. Springe direkt zum benötigten Abschnitt, statt die ganze Seite zu durchsuchen.",
    "settings.overview.aria": "Einstellungsübersicht",
    "settings.sections.aria": "Einstellungsabschnitte",
    "settings.sections.preferences": "Voreinstellungen",
    "settings.sections.visibility": "Sichtbarkeit",
    "settings.sections.credentials": "Zugangsdaten",
    "settings.sections.sources": "Quellen",
    "settings.sections.permissions": "Berechtigungen",
    "settings.actions.back_to_top": "Nach oben",
    "settings.actions.back_to_top_short": "Oben",
    "settings.summary.visible": "Sichtbar",
    "settings.summary.stored_secrets": "Gespeicherte Secrets",
    "settings.summary.bound_pages": "Gebundene Seiten",
    "settings.summary.needs_access": "Zugriff nötig",
    "settings.preferences.eyebrow": "Darstellung & Synchronisierung",
    "settings.preferences.sync_interval_label": "Standard-Synchronisierungsintervall",
    "settings.preferences.warning_threshold_label": "Warnschwelle",
    "settings.preferences.locale_label": "App-Sprache",
    "settings.preferences.theme_mode_label": "Designmodus",
    "settings.preferences.accent_preset_label": "Akzent-Voreinstellung",
    "settings.preferences.popup_progress_style_label": "Popup-Kontingentstil",
    "settings.preferences.sidebar_progress_style_label": "Seitenleisten-Kontingentstil",
    "settings.preferences.full_page_progress_style_label": "Tab-Kontingentstil",
    "settings.preferences.progress_style.line": "Linie",
    "settings.preferences.progress_style.circle": "Kreis",
    "settings.preferences.progress_style.circle_soft": "Weicher Kreis",
    "settings.preferences.progress_style.circle_gauge": "Kreis-Anzeige",
    "settings.preferences.popup_size_label": "Popup-Größe",
    "settings.preferences.popup_size.compact": "Kompakt",
    "settings.preferences.popup_size.balanced": "Ausgewogen",
    "settings.preferences.popup_size.wide": "Breit",
    "settings.preferences.popup_corner_label": "Popup-Ecken",
    "settings.preferences.popup_corner.square": "Eckig",
    "settings.preferences.popup_corner.soft": "Weich",
    "settings.preferences.popup_corner.rounded": "Gerundet",
    "settings.preferences.popup_shadow_label": "Popup-Schatten",
    "settings.preferences.popup_shadow.none": "Keiner",
    "settings.preferences.popup_shadow.soft": "Weich",
    "settings.preferences.popup_shadow.elevated": "Erhöht",
    "settings.preferences.action_badge_label": "Toolbar-Badge",
    "settings.preferences.minutes": "Minuten",
    "settings.preferences.locale.system": "System folgen",
    "settings.preferences.locale.en": "Englisch",
    "settings.preferences.locale.zh_cn": "Vereinfachtes Chinesisch",
    "settings.preferences.theme_mode.system": "System folgen",
    "settings.preferences.theme_mode.light": "Hell",
    "settings.preferences.theme_mode.dark": "Dunkel",
    "settings.preferences.theme_preset.default": "Standardblau",
    "settings.preferences.theme_preset.meadow": "Wiese",
    "settings.preferences.theme_preset.sunset": "Sonnenuntergang",
    "settings.preferences.theme_preset.custom": "Benutzerdefinierter Seed",
    "settings.toast.preferences_saved_title": "Voreinstellungen gespeichert",
    "settings.toast.preferences_saved_detail": "Die aktuellen Vorschau-Einstellungen wurden im lokalen Dashboard-Status gespeichert.",
  },
  it: {
    "app.loading.eyebrow": "Caricamento",
    "app.loading.title": "Preparazione dello stato della dashboard",
    "app.loading.detail": "Inizializzazione dello storage della dashboard e del bus dei messaggi.",
    "app.error.eyebrow": "Stato non disponibile",
    "app.error.title": "Inizializzazione non completata",
    "app.error.detail_fallback": "Impossibile caricare lo stato dell'app dallo storage dell'estensione o dallo storage locale di anteprima.",
    "common.actions.retry": "Riprova",
    "common.actions.settings": "Impostazioni",
    "common.actions.refresh": "Aggiorna",
    "common.actions.refresh_all": "Aggiorna tutto",
    "common.actions.back": "Indietro",
    "common.actions.open_dashboard": "Apri dashboard",
    "common.actions.open_settings": "Apri impostazioni",
    "common.actions.open_dashboard_tab": "Apri scheda dashboard",
    "common.actions.open_settings_tab": "Apri scheda impostazioni",
    "common.actions.tab": "Scheda",
    "common.actions.save": "Salva",
    "common.theme.toggle_to_dark_label": "Scuro",
    "common.theme.toggle_to_dark_title": "Passa alla modalità scura",
    "common.theme.toggle_to_light_label": "Chiaro",
    "common.theme.toggle_to_light_title": "Passa alla modalità chiara",
    "dashboard.topbar.title": "Dashboard utilizzo IA",
    "dashboard.topbar.subtitle": "Utilizzo, crediti e stato della sincronizzazione",
    "dashboard.hero.eyebrow": "Panoramica",
    "dashboard.hero.title": "Una dashboard per le quote di coding IA",
    "dashboard.hero.detail": "API ufficiali, policy di quota documentate e fonti protette di analisi pagina sono raccolte in una dashboard pronta per il rilascio con aggiornamenti, impostazioni e dettagli Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidato al rilascio",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Schede Provider",
    "dashboard.providers.detail": "Le schede sono ordinate prima per gravità e poi per lacune di accesso correnti, così i provider più rischiosi restano in alto mantenendo visibile il contratto di prodotto attuale.",
    "dashboard.providers.aria": "Schede Provider",
    "dashboard.empty.eyebrow": "Nessun Provider visibile",
    "dashboard.empty.detail": "Inizia da Quick Setup per abilitare il primo Provider, completa i passaggi di accesso e pagina di utilizzo, poi torna alla dashboard.",
    "dashboard.empty.action": "Apri Quick Setup",
    "dashboard.summary.aria": "Riepilogo dashboard",
    "dashboard.summary.visible": "Visibili",
    "dashboard.summary.healthy": "In ordine",
    "dashboard.summary.needs_access": "Accesso richiesto",
    "dashboard.summary.needs_attention": "Attenzione richiesta",
    "popup.loading.eyebrow": "Popup barra strumenti",
    "popup.loading.title": "Caricamento dello stato dashboard in cache",
    "popup.loading.detail": "Preparazione dello snapshot quote condiviso per questo profilo browser.",
    "popup.error.eyebrow": "Popup barra strumenti",
    "popup.error.title": "Caricamento popup non riuscito",
    "popup.header.eyebrow": "Popup barra strumenti",
    "popup.header.title": "Vista rapida",
    "popup.summary.aria": "Riepilogo superiore popup",
    "popup.guidance.eyebrow": "Guida popup",
    "popup.snapshot_status.eyebrow": "Stato snapshot",
    "popup.actions.eyebrow": "Altra route",
    "popup.actions.refresh": "Aggiorna",
    "popup.actions.refreshing": "Aggiornamento",
    "popup.featured.eyebrow": "Provider in evidenza",
    "popup.featured.single_eyebrow": "Provider in evidenza",
    "popup.triage.eyebrow": "Triage popup",
    "popup.summary.visible": "Visibili",
    "popup.summary.live_ready": "Pronto per dati live",
    "popup.summary.setup_blockers": "Blocchi configurazione",
    "popup.summary.policy_only": "Solo policy",
    "settings.topbar.title": "Impostazioni",
    "settings.topbar.subtitle": "Quick Setup, aspetto e controlli Provider avanzati",
    "settings.overview.eyebrow": "Panoramica impostazioni",
    "settings.overview.title": "Riepilogo superficie di controllo",
    "settings.overview.detail": "Usa questa schermata per gestire visibilità, autorizzazioni, credenziali e controlli source ibridi. Vai direttamente alla sezione necessaria invece di scorrere tutta la pagina.",
    "settings.overview.aria": "Panoramica impostazioni",
    "settings.sections.aria": "Sezioni impostazioni",
    "settings.sections.preferences": "Preferenze",
    "settings.sections.visibility": "Visibilità",
    "settings.sections.credentials": "Credenziali",
    "settings.sections.sources": "Fonti",
    "settings.sections.permissions": "Autorizzazioni",
    "settings.actions.back_to_top": "Torna su",
    "settings.actions.back_to_top_short": "Su",
    "settings.summary.visible": "Visibili",
    "settings.summary.stored_secrets": "Segreti salvati",
    "settings.summary.bound_pages": "Pagine collegate",
    "settings.summary.needs_access": "Accesso richiesto",
    "settings.preferences.eyebrow": "Aspetto e sincronizzazione",
    "settings.preferences.sync_interval_label": "Intervallo sincronizzazione predefinito",
    "settings.preferences.warning_threshold_label": "Soglia di avviso",
    "settings.preferences.locale_label": "Lingua app",
    "settings.preferences.theme_mode_label": "Modalità tema",
    "settings.preferences.accent_preset_label": "Preset accento",
    "settings.preferences.popup_progress_style_label": "Stile quota Popup",
    "settings.preferences.sidebar_progress_style_label": "Stile quota barra laterale",
    "settings.preferences.full_page_progress_style_label": "Stile quota scheda",
    "settings.preferences.progress_style.line": "Linea",
    "settings.preferences.progress_style.circle": "Cerchio",
    "settings.preferences.progress_style.circle_soft": "Cerchio morbido",
    "settings.preferences.progress_style.circle_gauge": "Indicatore circolare",
    "settings.preferences.popup_size_label": "Dimensione Popup",
    "settings.preferences.popup_size.compact": "Compatta",
    "settings.preferences.popup_size.balanced": "Bilanciata",
    "settings.preferences.popup_size.wide": "Ampia",
    "settings.preferences.popup_corner_label": "Angoli Popup",
    "settings.preferences.popup_corner.square": "Squadrati",
    "settings.preferences.popup_corner.soft": "Morbidi",
    "settings.preferences.popup_corner.rounded": "Arrotondati",
    "settings.preferences.popup_shadow_label": "Ombra Popup",
    "settings.preferences.popup_shadow.none": "Nessuna",
    "settings.preferences.popup_shadow.soft": "Morbida",
    "settings.preferences.popup_shadow.elevated": "Elevata",
    "settings.preferences.action_badge_label": "Badge barra strumenti",
    "settings.preferences.minutes": "minuti",
    "settings.preferences.locale.system": "Segui sistema",
    "settings.preferences.locale.en": "Inglese",
    "settings.preferences.locale.zh_cn": "Cinese semplificato",
    "settings.preferences.theme_mode.system": "Segui sistema",
    "settings.preferences.theme_mode.light": "Chiaro",
    "settings.preferences.theme_mode.dark": "Scuro",
    "settings.preferences.theme_preset.default": "Blu predefinito",
    "settings.preferences.theme_preset.meadow": "Prato",
    "settings.preferences.theme_preset.sunset": "Tramonto",
    "settings.preferences.theme_preset.custom": "Seed personalizzato",
    "settings.toast.preferences_saved_title": "Preferenze salvate",
    "settings.toast.preferences_saved_detail": "Le impostazioni di anteprima correnti sono state salvate nello stato locale della dashboard.",
  },
} satisfies Partial<Record<ResolvedAppLocale, Partial<RuntimeMessages>>>;
