import type { ResolvedAppLocale, RuntimeMessages } from "../i18n";

export const CJK_RUNTIME_MESSAGE_OVERRIDES = {
  "zh-CN": {
    "app.loading.eyebrow": "加载中",
    "app.loading.title": "正在准备仪表板状态",
    "app.loading.detail": "正在初始化仪表板存储和消息总线。",
    "app.error.eyebrow": "状态不可用",
    "app.error.title": "初始化未完成",
    "app.error.detail_fallback": "无法从扩展存储或本地预览存储加载应用状态。",
    "common.actions.retry": "重试",
    "common.actions.settings": "设置",
    "common.actions.refresh": "刷新",
    "common.actions.refresh_all": "全部刷新",
    "common.actions.back": "返回",
    "common.actions.open_dashboard": "打开仪表板",
    "common.actions.open_settings": "打开设置",
    "common.actions.open_dashboard_tab": "打开仪表板标签页",
    "common.actions.open_settings_tab": "打开设置标签页",
    "common.actions.tab": "标签页",
    "common.actions.sidebar": "侧栏",
    "common.actions.open_sidebar": "打开侧栏",
    "common.actions.save": "保存",
    "provider.account.selector_label": "Provider 账号",
    "provider.account.settings_title": "活动 Provider 账号",
    "common.theme.toggle_to_dark_label": "夜间",
    "common.theme.toggle_to_dark_title": "切换到夜间模式",
    "common.theme.toggle_to_light_label": "白天",
    "common.theme.toggle_to_light_title": "切换到白天模式",
    "common.theme.toggle_to_system_label": "系统",
    "common.theme.toggle_to_system_title": "切换到跟随系统",
    "common.theme.toggle_to_time_label": "按时间",
    "common.theme.toggle_to_time_title": "切换到根据当地时间自动调整",
    "dashboard.topbar.title": "AI 用量仪表板",
    "dashboard.topbar.subtitle": "用量、额度与同步健康",
    "dashboard.hero.eyebrow": "概览",
    "dashboard.hero.title": "AI 编码额度概览",
    "dashboard.hero.detail": "官方 API、文档化配额策略与受控页面解析路径，被收敛到一个可发布的仪表板里，用于刷新、设置和 Provider 深入查看。",
    "dashboard.hero.release_chip": "Material 3 · 发布候选",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 卡片",
    "dashboard.providers.detail": "卡片先按严重程度排序，再按当前访问缺口排序，让高风险 provider 保持在顶部，同时保留当前产品合同的一眼可见性。",
    "dashboard.providers.aria": "Provider 卡片",
    "dashboard.empty.eyebrow": "没有可见 Provider",
    "dashboard.empty.detail": "请先进入 Quick Setup 启用第一个 Provider，再按提示完成授权和用量页面步骤，然后回到仪表板。",
    "dashboard.empty.action": "打开 Quick Setup",
    "dashboard.summary.aria": "仪表板摘要",
    "dashboard.summary.visible": "可见",
    "dashboard.summary.healthy": "健康",
    "dashboard.summary.needs_access": "需授权",
    "dashboard.summary.needs_attention": "需关注",
    "popup.loading.eyebrow": "工具栏弹窗",
    "popup.loading.title": "正在加载缓存的仪表板状态",
    "popup.loading.detail": "正在为此浏览器配置文件准备共享配额快照。",
    "popup.error.eyebrow": "工具栏弹窗",
    "popup.error.title": "弹窗加载失败",
    "popup.header.eyebrow": "工具栏弹窗",
    "popup.header.title": "快速概览",
    "popup.summary.aria": "弹窗顶部摘要",
    "popup.guidance.eyebrow": "弹窗引导",
    "popup.snapshot_status.eyebrow": "快照状态",
    "popup.actions.eyebrow": "其他入口",
    "popup.actions.refresh": "刷新",
    "popup.actions.refreshing": "刷新中",
    "popup.actions.refresh_title": "立即刷新",
    "popup.actions.refresh_drift_note": "自动同步时间是近似值；Chrome 休眠或 service worker 空闲时，alarms 可能会漂移。",
    "popup.actions.hide_header_actions": "隐藏顶部操作",
    "popup.actions.show_header_actions": "显示顶部操作",
    "popup.actions.hide_footer_info": "隐藏底部信息",
    "popup.actions.show_footer_info": "显示底部信息",
    "popup.providers.collapse_card": "收起 Provider 卡片",
    "popup.providers.expand_card": "展开 Provider 卡片",
    "popup.providers.previous": "上一个 Provider",
    "popup.providers.next": "下一个 Provider",
    "popup.featured.eyebrow": "重点 Provider",
    "popup.featured.single_eyebrow": "重点 Provider",
    "popup.triage.eyebrow": "弹窗分诊",
    "popup.summary.visible": "可见",
    "popup.summary.live_ready": "可实时同步",
    "popup.summary.setup_blockers": "配置阻塞",
    "popup.summary.policy_only": "仅策略",
    "settings.topbar.title": "设置",
    "settings.topbar.subtitle": "快速设置、外观与高级 Provider 控制",
    "settings.overview.eyebrow": "设置概览",
    "settings.overview.title": "控制面摘要",
    "settings.overview.detail": "用这个页面管理可见性、权限、凭据和混合 source 控制。直接跳到你需要的部分，而不是从上到下通读整页。",
    "settings.overview.aria": "设置概览",
    "settings.sections.aria": "设置分区",
    "settings.sections.preferences": "偏好",
    "settings.sections.visibility": "可见性",
    "settings.sections.credentials": "凭据",
    "settings.sections.sources": "来源",
    "settings.sections.permissions": "权限",
    "settings.actions.back_to_top": "返回顶部",
    "settings.actions.back_to_top_short": "顶部",
    "settings.summary.visible": "可见",
    "settings.summary.stored_secrets": "已存密钥",
    "settings.summary.bound_pages": "已绑定页面",
    "settings.summary.needs_access": "需授权",
    "settings.preferences.eyebrow": "外观与同步",
    "settings.preferences.sync_interval_label": "默认同步间隔",
    "settings.preferences.warning_threshold_label": "告警阈值",
    "settings.preferences.locale_label": "应用语言",
    "settings.preferences.theme_mode_label": "主题模式",
    "settings.preferences.motion_mode_label": "动画效果",
    "settings.preferences.accent_preset_label": "强调色预设",
    "settings.preferences.popup_progress_style_label": "Popup 额度样式",
    "settings.preferences.popup_circular_row_count_label": "圆环每行数量",
    "settings.preferences.popup_circular_row_count_helper": "只影响 Popup 的圆圈、柔和圆环和仪表圆环；直线进度保持每行一项。",
    "settings.preferences.popup_circular_row_count.one": "每行 1 个",
    "settings.preferences.popup_circular_row_count.two": "每行 2 个",
    "settings.preferences.popup_circular_row_count.four": "每行 4 个",
    "settings.preferences.popup_circular_row_count.three": "每行 3 个",
    "settings.preferences.sidebar_progress_style_label": "侧栏额度样式",
    "settings.preferences.full_page_progress_style_label": "标签页额度样式",
    "settings.preferences.progress_style.line": "直线",
    "settings.preferences.progress_style.circle": "圆圈",
    "settings.preferences.progress_style.circle_soft": "柔和圆环",
    "settings.preferences.progress_style.circle_gauge": "仪表圆环",
    "settings.preferences.popup_size_label": "Popup 尺寸",
    "settings.preferences.popup_size.compact": "紧凑",
    "settings.preferences.popup_size.balanced": "均衡",
    "settings.preferences.popup_size.wide": "宽版",
    "settings.preferences.popup_provider_browsing_mode_label": "Popup Provider 浏览方式",
    "settings.preferences.popup_provider_browsing_mode.collapsible": "可折叠卡片",
    "settings.preferences.popup_provider_browsing_mode.single": "单卡片切换",
    "settings.preferences.popup_provider_browsing_mode.scroll": "连续滚动",
    "settings.preferences.popup_corner_label": "Popup 圆角",
    "settings.preferences.popup_corner.square": "直角",
    "settings.preferences.popup_corner.soft": "柔和",
    "settings.preferences.popup_corner.rounded": "圆润",
    "settings.preferences.popup_shadow_label": "Popup 阴影",
    "settings.preferences.popup_shadow.none": "无",
    "settings.preferences.popup_shadow.soft": "轻微",
    "settings.preferences.popup_shadow.elevated": "加强",
    "settings.preferences.action_badge_label": "工具栏图标标记",
    "settings.preferences.action_badge_mode_label": "标记选择模式",
    "settings.preferences.action_badge_mode_helper": "自动模式会在没有 Provider 额度标记时显示异常数量；有可显示的 Provider 额度标记后，会轮转这些标记。手动模式会保持你选择的标记来源。",
    "settings.preferences.action_badge_mode_auto": "自动",
    "settings.preferences.action_badge_mode_manual": "手动",
    "settings.preferences.action_badge_restore_auto": "恢复自动",
    "settings.preferences.action_badge_helper": "选择一个或多个工具栏标记来源。实际显示的标记会在已选来源之间轮转。",
    "settings.preferences.seconds": "秒",
    "settings.preferences.action_badge_rotation_label": "标记轮转间隔",
    "settings.preferences.action_badge_rotation_helper": "控制工具栏标记以及匹配标记的工具栏图标多久切换到下一个已选来源。",
    "settings.preferences.action_badge_rotation_menu_button": "展开标记轮转预设",
    "settings.preferences.toolbar_icon_label": "工具栏图标",
    "settings.preferences.toolbar_icon.default": "默认图标",
    "settings.preferences.toolbar_icon.match_badge": "匹配工具栏标记",
    "settings.preferences.toolbar_icon.provider": "Provider 图标",
    "settings.preferences.toolbar_icon.custom": "自定义图片",
    "settings.preferences.toolbar_icon_provider_label": "图标 Provider",
    "settings.preferences.toolbar_icon_custom_label": "自定义工具栏图标",
    "settings.preferences.toolbar_icon_custom_empty": "未选择自定义图片",
    "settings.preferences.toolbar_icon_custom_selected": "已选择自定义图片",
    "settings.preferences.toolbar_icon_custom_clear": "清除",
    "settings.preferences.ui_font_label": "界面字体",
    "settings.preferences.ui_font_helper": "使用本机安全字体栈，并在 popup、侧栏、完整标签页和 Provider 详情中统一生效；不会加载远程字体。",
    "settings.preferences.ui_font.default": "默认字体",
    "settings.preferences.ui_font.system": "系统界面",
    "settings.preferences.ui_font.serif": "衬线",
    "settings.preferences.ui_font.mono": "等宽",
    "settings.popup_appearance_preview.eyebrow": "工具栏弹窗预览",
    "settings.popup_appearance_preview.title": "工具栏弹窗预览",
    "settings.popup_appearance_preview.detail": "在重新打开工具栏弹窗前，先预览当前 popup 宽度、圆角、阴影和额度样式。",
    "settings.popup_appearance_preview.remaining_label": "预览剩余额度",
    "settings.popup_appearance_preview.remaining_error": "请输入 0 到 100 的数值。",
    "settings.popup_appearance_preview.open_test_popup": "打开工具栏弹窗预览",
    "settings.popup_appearance_preview.close_test_popup": "关闭工具栏弹窗预览",
    "settings.popup_appearance_preview.drag_test_popup": "拖拽工具栏弹窗预览",
    "settings.popup_appearance_preview.sample_refresh": "刷新",
    "settings.popup_appearance_preview.sample_tab": "标签页",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "每周使用窗口",
    "settings.preferences.minutes": "分钟",
    "settings.preferences.locale.system": "跟随系统",
    "settings.preferences.locale.en": "英语",
    "settings.preferences.locale.zh_cn": "简体中文",
    "settings.preferences.theme_mode.system": "跟随系统",
    "settings.preferences.theme_mode.light": "白天",
    "settings.preferences.theme_mode.dark": "夜间",
    "settings.preferences.theme_mode.time": "根据时间",
    "settings.preferences.theme_mode_helper": "根据设备当地时间自动切换：07:00–19:00 使用白天模式，其余时间使用夜间模式；不会读取地理位置。",
    "settings.preferences.motion_mode.system": "跟随系统",
    "settings.preferences.motion_mode.full": "开启",
    "settings.preferences.motion_mode.reduced": "减少",
    "settings.preferences.theme_preset.default": "默认蓝",
    "settings.preferences.theme_preset.meadow": "草地",
    "settings.preferences.theme_preset.sunset": "日落",
    "settings.preferences.theme_preset.custom": "自定义种子",
    "settings.theme_customization.eyebrow": "自定义种子",
    "settings.theme_customization.title": "已校验的强调色种子",
    "settings.theme_customization.detail": "使用一个经过校验的 #RRGGBB 种子，而不是直接编辑单个主题 token。生成出的强调色角色会在侧栏、popup 和 audit hub 中共享。",
    "settings.theme_customization.seed_label": "自定义种子颜色",
    "settings.theme_customization.apply": "应用自定义种子",
    "settings.theme_customization.reset": "恢复默认",
    "settings.theme_customization.preview.aria": "自定义种子预览",
    "settings.theme_customization.preview.primary": "主色",
    "settings.theme_customization.preview.secondary_container": "次级容器",
    "settings.theme_customization.preview.tertiary": "第三色",
    "settings.visibility.eyebrow": "Provider 可见性",
    "settings.visibility.displayEnabled_detail": "在仪表板中可见。",
    "settings.visibility.disabled_detail": "已从仪表板隐藏。",
    "settings.credentials.eyebrow": "凭据",
    "settings.credentials.title": "已存密钥与工作区配置",
    "settings.credentials.detail": "这些卡片管理扩展本地保存的 admin 和 enterprise 路径凭据。个人 session-page 路径仍然避免 cookie 导出，也不会要求手动粘贴 auth header。",
    "settings.credentials.codex_session_title": "Codex 临时会话 token",
    "settings.credentials.codex_session_state": "仅当前会话",
    "settings.credentials.codex_session_help": "仅用于高级恢复。只有本地自动发现 ChatGPT 会话失败时，才粘贴裸 access token。",
    "settings.credentials.codex_session_input": "临时 access token",
    "settings.credentials.codex_session_placeholder": "只粘贴 token 本身",
    "settings.credentials.codex_session_save": "用于当前浏览器会话",
    "settings.credentials.codex_session_clear": "清除临时 token",
    "settings.credentials.codex_session_footer": "token 仅保存在 chrome.storage.session，只会发送到 chatgpt.com，并会随浏览器会话或扩展生命周期结束而清除。不要粘贴 Cookie、JSON、refresh token 或 Authorization header。",
    "settings.sources.eyebrow": "来源连接",
    "settings.sources.title": "混合来源合同",
    "settings.sources.detail": "这些卡片说明每个 provider 当前是通过官方 API、已登录页面会话，还是文档化 quota policy 同步，同时明确每条路径当前是 shipped 还是 deferred 的产品合同。",
    "settings.permissions.eyebrow": "Host 访问",
    "settings.permissions.title": "权限控制",
    "settings.permissions.detail": "在扩展模式下，这些操作使用 chrome.permissions；在浏览器预览模式下，它们会回退到本地状态模拟。",
    "settings.toast.preferences_saved_title": "偏好已保存",
    "settings.toast.preferences_saved_detail": "当前预览的设置已经持久化到本地仪表板状态。",
  },
  "zh-TW": {
    "app.loading.eyebrow": "載入中",
    "app.loading.title": "正在準備儀表板狀態",
    "app.loading.detail": "正在初始化儀表板儲存與訊息匯流排。",
    "app.error.eyebrow": "狀態無法使用",
    "app.error.title": "初始化未完成",
    "app.error.detail_fallback": "無法從擴充功能儲存空間或本機預覽儲存空間載入應用程式狀態。",
    "common.actions.retry": "重試",
    "common.actions.settings": "設定",
    "common.actions.refresh": "重新整理",
    "common.actions.refresh_all": "全部重新整理",
    "common.actions.back": "返回",
    "common.actions.open_dashboard": "開啟儀表板",
    "common.actions.open_settings": "開啟設定",
    "common.actions.open_dashboard_tab": "開啟儀表板分頁",
    "common.actions.open_settings_tab": "開啟設定分頁",
    "common.actions.tab": "分頁",
    "common.actions.sidebar": "側欄",
    "common.actions.open_sidebar": "開啟側欄",
    "common.actions.save": "儲存",
    "provider.account.selector_label": "Provider 帳號",
    "provider.account.settings_title": "使用中的 Provider 帳號",
    "common.theme.toggle_to_dark_label": "夜間",
    "common.theme.toggle_to_dark_title": "切換到夜間模式",
    "common.theme.toggle_to_light_label": "白天",
    "common.theme.toggle_to_light_title": "切換到白天模式",
    "common.theme.toggle_to_system_label": "系統",
    "common.theme.toggle_to_system_title": "切換到跟隨系統",
    "common.theme.toggle_to_time_label": "按時間",
    "common.theme.toggle_to_time_title": "切換到依當地時間自動調整",
    "dashboard.topbar.title": "AI 用量儀表板",
    "dashboard.topbar.subtitle": "用量、額度與同步健康",
    "dashboard.hero.eyebrow": "概覽",
    "dashboard.hero.title": "AI 編碼額度概覽",
    "dashboard.hero.detail": "官方 API、文件化配額策略與受控頁面解析路徑，會收斂到一個可發布的儀表板中，用於重新整理、設定和 Provider 深入查看。",
    "dashboard.hero.release_chip": "Material 3 · 發布候選",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 卡片",
    "dashboard.providers.detail": "卡片先按嚴重程度排序，再按目前存取缺口排序，讓高風險 provider 保持在頂部，同時保留目前產品合約的一眼可見性。",
    "dashboard.providers.aria": "Provider 卡片",
    "dashboard.empty.eyebrow": "沒有可見 Provider",
    "dashboard.empty.detail": "請先進入 Quick Setup 啟用第一個 Provider，再依提示完成授權與用量頁面步驟，然後回到儀表板。",
    "dashboard.empty.action": "開啟 Quick Setup",
    "dashboard.summary.aria": "儀表板摘要",
    "dashboard.summary.visible": "可見",
    "dashboard.summary.healthy": "健康",
    "dashboard.summary.needs_access": "需授權",
    "dashboard.summary.needs_attention": "需關注",
    "popup.loading.eyebrow": "工具列彈窗",
    "popup.loading.title": "正在載入快取的儀表板狀態",
    "popup.loading.detail": "正在為此瀏覽器設定檔準備共享配額快照。",
    "popup.error.eyebrow": "工具列彈窗",
    "popup.error.title": "彈窗載入失敗",
    "popup.header.eyebrow": "工具列彈窗",
    "popup.header.title": "快速概覽",
    "popup.summary.aria": "彈窗頂部摘要",
    "popup.guidance.eyebrow": "彈窗引導",
    "popup.snapshot_status.eyebrow": "快照狀態",
    "popup.actions.eyebrow": "其他入口",
    "popup.actions.refresh": "重新整理",
    "popup.actions.refreshing": "重新整理中",
    "popup.actions.refresh_title": "立即重新整理",
    "popup.actions.refresh_drift_note": "自動同步時間是近似值；Chrome 休眠或 service worker 閒置時，alarms 可能會漂移。",
    "popup.actions.hide_header_actions": "隱藏頂部操作",
    "popup.actions.show_header_actions": "顯示頂部操作",
    "popup.actions.hide_footer_info": "隱藏底部資訊",
    "popup.actions.show_footer_info": "顯示底部資訊",
    "popup.providers.collapse_card": "收合 Provider 卡片",
    "popup.providers.expand_card": "展開 Provider 卡片",
    "popup.providers.previous": "上一個 Provider",
    "popup.providers.next": "下一個 Provider",
    "popup.featured.eyebrow": "重點 Provider",
    "popup.featured.single_eyebrow": "重點 Provider",
    "popup.triage.eyebrow": "彈窗分診",
    "popup.summary.visible": "可見",
    "popup.summary.live_ready": "可即時同步",
    "popup.summary.setup_blockers": "設定阻礙",
    "popup.summary.policy_only": "僅策略",
    "settings.topbar.title": "設定",
    "settings.topbar.subtitle": "快速設定、外觀與進階 Provider 控制",
    "settings.overview.eyebrow": "設定概覽",
    "settings.overview.title": "控制面摘要",
    "settings.overview.detail": "使用此頁面管理可見性、權限、憑據和混合 source 控制。直接跳到需要的區段，而不是從上到下通讀整頁。",
    "settings.overview.aria": "設定概覽",
    "settings.sections.aria": "設定區段",
    "settings.sections.preferences": "偏好",
    "settings.sections.visibility": "可見性",
    "settings.sections.credentials": "憑據",
    "settings.sections.sources": "來源",
    "settings.sections.permissions": "權限",
    "settings.actions.back_to_top": "返回頂部",
    "settings.actions.back_to_top_short": "頂部",
    "settings.summary.visible": "可見",
    "settings.summary.stored_secrets": "已存密鑰",
    "settings.summary.bound_pages": "已綁定頁面",
    "settings.summary.needs_access": "需授權",
    "settings.preferences.eyebrow": "外觀與同步",
    "settings.preferences.sync_interval_label": "預設同步間隔",
    "settings.preferences.warning_threshold_label": "警示閾值",
    "settings.preferences.locale_label": "應用程式語言",
    "settings.preferences.theme_mode_label": "主題模式",
    "settings.preferences.motion_mode_label": "動畫效果",
    "settings.preferences.accent_preset_label": "強調色預設",
    "settings.preferences.popup_progress_style_label": "Popup 額度樣式",
    "settings.preferences.popup_circular_row_count_label": "圓環每列數量",
    "settings.preferences.popup_circular_row_count_helper": "只影響 Popup 的圓圈、柔和圓環和儀表圓環；直線進度維持每列一項。",
    "settings.preferences.popup_circular_row_count.one": "每列 1 個",
    "settings.preferences.popup_circular_row_count.two": "每列 2 個",
    "settings.preferences.popup_circular_row_count.four": "每列 4 個",
    "settings.preferences.popup_circular_row_count.three": "每列 3 個",
    "settings.preferences.sidebar_progress_style_label": "側欄額度樣式",
    "settings.preferences.full_page_progress_style_label": "分頁額度樣式",
    "settings.preferences.progress_style.line": "直線",
    "settings.preferences.progress_style.circle": "圓圈",
    "settings.preferences.progress_style.circle_soft": "柔和圓環",
    "settings.preferences.progress_style.circle_gauge": "儀表圓環",
    "settings.preferences.popup_size_label": "Popup 尺寸",
    "settings.preferences.popup_size.compact": "緊湊",
    "settings.preferences.popup_size.balanced": "均衡",
    "settings.preferences.popup_size.wide": "寬版",
    "settings.preferences.popup_provider_browsing_mode_label": "Popup Provider 瀏覽方式",
    "settings.preferences.popup_provider_browsing_mode.collapsible": "可收合卡片",
    "settings.preferences.popup_provider_browsing_mode.single": "單一卡片切換",
    "settings.preferences.popup_provider_browsing_mode.scroll": "連續捲動",
    "settings.preferences.popup_corner_label": "Popup 圓角",
    "settings.preferences.popup_corner.square": "直角",
    "settings.preferences.popup_corner.soft": "柔和",
    "settings.preferences.popup_corner.rounded": "圓潤",
    "settings.preferences.popup_shadow_label": "Popup 陰影",
    "settings.preferences.popup_shadow.none": "無",
    "settings.preferences.popup_shadow.soft": "輕微",
    "settings.preferences.popup_shadow.elevated": "加強",
    "settings.preferences.action_badge_label": "工具列圖示標記",
    "settings.preferences.action_badge_mode_label": "標記選擇模式",
    "settings.preferences.action_badge_mode_helper": "自動模式會在沒有 Provider 額度標記時顯示異常數量；有可顯示的 Provider 額度標記後，會輪轉這些標記。手動模式會保留你選擇的標記來源。",
    "settings.preferences.action_badge_mode_auto": "自動",
    "settings.preferences.action_badge_mode_manual": "手動",
    "settings.preferences.action_badge_restore_auto": "恢復自動",
    "settings.preferences.toolbar_icon_label": "工具列圖示",
    "settings.preferences.toolbar_icon.default": "預設圖示",
    "settings.preferences.toolbar_icon.match_badge": "匹配工具列標記",
    "settings.preferences.toolbar_icon.provider": "Provider 圖示",
    "settings.preferences.toolbar_icon.custom": "自訂圖片",
    "settings.preferences.toolbar_icon_provider_label": "圖示 Provider",
    "settings.preferences.toolbar_icon_custom_label": "自訂工具列圖示",
    "settings.preferences.toolbar_icon_custom_empty": "未選擇自訂圖片",
    "settings.preferences.toolbar_icon_custom_selected": "已選擇自訂圖片",
    "settings.preferences.toolbar_icon_custom_clear": "清除",
    "settings.preferences.ui_font_label": "介面字體",
    "settings.preferences.ui_font_helper": "使用本機安全字體堆疊，並在 popup、側欄、完整分頁和 Provider 詳情中一致生效；不會載入遠端字體。",
    "settings.preferences.ui_font.default": "預設字體",
    "settings.preferences.ui_font.system": "系統介面",
    "settings.preferences.ui_font.serif": "襯線",
    "settings.preferences.ui_font.mono": "等寬",
    "settings.preferences.minutes": "分鐘",
    "settings.preferences.locale.system": "跟隨系統",
    "settings.preferences.locale.en": "英文",
    "settings.preferences.locale.zh_cn": "簡體中文",
    "settings.preferences.theme_mode.system": "跟隨系統",
    "settings.preferences.theme_mode.light": "白天",
    "settings.preferences.theme_mode.dark": "夜間",
    "settings.preferences.theme_mode.time": "依時間",
    "settings.preferences.theme_mode_helper": "依裝置當地時間自動切換：07:00–19:00 使用白天模式，其餘時間使用夜間模式；不會讀取地理位置。",
    "settings.preferences.motion_mode.system": "跟隨系統",
    "settings.preferences.motion_mode.full": "開啟",
    "settings.preferences.motion_mode.reduced": "減少",
    "settings.preferences.theme_preset.default": "預設藍",
    "settings.preferences.theme_preset.meadow": "草地",
    "settings.preferences.theme_preset.sunset": "日落",
    "settings.preferences.theme_preset.custom": "自訂種子",
    "settings.toast.preferences_saved_title": "偏好已儲存",
    "settings.toast.preferences_saved_detail": "目前預覽的設定已持久化到本機儀表板狀態。",
  },
  ja: {
    "app.loading.eyebrow": "読み込み中",
    "app.loading.title": "ダッシュボード状態を準備中",
    "app.loading.detail": "ダッシュボードストアとメッセージバスを初期化しています。",
    "app.error.eyebrow": "状態を利用できません",
    "app.error.title": "初期化が完了しませんでした",
    "app.error.detail_fallback": "拡張機能ストレージまたはローカルプレビューのストレージからアプリ状態を読み込めませんでした。",
    "common.actions.retry": "再試行",
    "common.actions.settings": "設定",
    "common.actions.refresh": "更新",
    "common.actions.refresh_all": "すべて更新",
    "common.actions.back": "戻る",
    "common.actions.open_dashboard": "ダッシュボードを開く",
    "common.actions.open_settings": "設定を開く",
    "common.actions.open_dashboard_tab": "ダッシュボードタブを開く",
    "common.actions.open_settings_tab": "設定タブを開く",
    "common.actions.tab": "タブ",
    "common.actions.sidebar": "サイドバー",
    "common.actions.open_sidebar": "サイドバーで開く",
    "common.actions.save": "保存",
    "provider.account.selector_label": "Provider アカウント",
    "provider.account.settings_title": "有効な Provider アカウント",
    "common.theme.toggle_to_dark_label": "ダーク",
    "common.theme.toggle_to_dark_title": "ダークモードに切り替える",
    "common.theme.toggle_to_light_label": "ライト",
    "common.theme.toggle_to_light_title": "ライトモードに切り替える",
    "common.theme.toggle_to_system_label": "システム",
    "common.theme.toggle_to_system_title": "システムテーマに切り替える",
    "common.theme.toggle_to_time_label": "時刻連動",
    "common.theme.toggle_to_time_title": "現地時刻に合わせる",
    "dashboard.topbar.title": "AI 使用状況ダッシュボード",
    "dashboard.topbar.subtitle": "使用状況、クレジット、同期状態",
    "dashboard.hero.eyebrow": "概要",
    "dashboard.hero.title": "AI コーディングクォータ概要",
    "dashboard.hero.detail": "公式 API、ドキュメント化されたクォータポリシー、保護されたページ解析ソースを、更新、設定、Provider 詳細確認のためのリリース対応ダッシュボードに集約します。",
    "dashboard.hero.release_chip": "Material 3 · リリース候補",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider カード",
    "dashboard.providers.detail": "カードは重要度を優先し、その次に現在のアクセス不足で並びます。リスクの高い provider をダッシュボード上部に保ちながら、現在のプロダクト契約を一目で確認できます。",
    "dashboard.providers.aria": "Provider カード",
    "dashboard.empty.eyebrow": "表示中の Provider なし",
    "dashboard.empty.detail": "Quick Setup で最初の Provider を有効にし、アクセスと使用状況ページの手順を完了してからダッシュボードに戻ってください。",
    "dashboard.empty.action": "Quick Setup を開く",
    "dashboard.summary.aria": "ダッシュボード概要",
    "dashboard.summary.visible": "表示中",
    "dashboard.summary.healthy": "正常",
    "dashboard.summary.needs_access": "アクセスが必要",
    "dashboard.summary.needs_attention": "要確認",
    "popup.loading.eyebrow": "ツールバーポップアップ",
    "popup.loading.title": "キャッシュ済みダッシュボード状態を読み込み中",
    "popup.loading.detail": "このブラウザプロファイル用の共有クォータスナップショットを準備しています。",
    "popup.error.eyebrow": "ツールバーポップアップ",
    "popup.error.title": "ポップアップの読み込みに失敗しました",
    "popup.header.eyebrow": "ツールバーポップアップ",
    "popup.header.title": "クイック確認",
    "popup.summary.aria": "ポップアップ上部の概要",
    "popup.guidance.eyebrow": "ポップアップガイダンス",
    "popup.snapshot_status.eyebrow": "スナップショット状態",
    "popup.actions.eyebrow": "その他の入口",
    "popup.actions.refresh": "更新",
    "popup.actions.refreshing": "更新中",
    "popup.actions.refresh_title": "今すぐ更新",
    "popup.actions.refresh_drift_note": "自動同期の時刻は概算です。Chrome がスリープ中、または service worker がアイドル状態のときは alarms がずれることがあります。",
    "popup.actions.hide_header_actions": "上部操作を隠す",
    "popup.actions.show_header_actions": "上部操作を表示",
    "popup.actions.hide_footer_info": "フッター情報を隠す",
    "popup.actions.show_footer_info": "フッター情報を表示",
    "popup.providers.collapse_card": "Provider カードを折りたたむ",
    "popup.providers.expand_card": "Provider カードを展開",
    "popup.providers.previous": "前の Provider",
    "popup.providers.next": "次の Provider",
    "popup.featured.eyebrow": "注目 Provider",
    "popup.featured.single_eyebrow": "注目 Provider",
    "popup.triage.eyebrow": "ポップアップ優先確認",
    "popup.summary.visible": "表示中",
    "popup.summary.live_ready": "ライブ準備済み",
    "popup.summary.setup_blockers": "設定ブロッカー",
    "popup.summary.policy_only": "ポリシーのみ",
    "settings.topbar.title": "設定",
    "settings.topbar.subtitle": "Quick Setup、外観、高度な Provider 管理",
    "settings.overview.eyebrow": "設定の概要",
    "settings.overview.title": "コントロール画面の概要",
    "settings.overview.detail": "この画面で表示、権限、認証情報、ハイブリッド source 管理を扱います。ページ全体を上から下まで探す代わりに、必要なセクションへ直接移動できます。",
    "settings.overview.aria": "設定の概要",
    "settings.sections.aria": "設定セクション",
    "settings.sections.preferences": "環境設定",
    "settings.sections.visibility": "表示",
    "settings.sections.credentials": "認証情報",
    "settings.sections.sources": "ソース",
    "settings.sections.permissions": "権限",
    "settings.actions.back_to_top": "トップに戻る",
    "settings.actions.back_to_top_short": "トップ",
    "settings.summary.visible": "表示中",
    "settings.summary.stored_secrets": "保存済みシークレット",
    "settings.summary.bound_pages": "バインド済みページ",
    "settings.summary.needs_access": "アクセスが必要",
    "settings.preferences.eyebrow": "外観と同期",
    "settings.preferences.sync_interval_label": "既定の同期間隔",
    "settings.preferences.warning_threshold_label": "警告しきい値",
    "settings.preferences.locale_label": "アプリの言語",
    "settings.preferences.theme_mode_label": "テーマモード",
    "settings.preferences.motion_mode_label": "アニメーション効果",
    "settings.preferences.accent_preset_label": "アクセントプリセット",
    "settings.preferences.popup_progress_style_label": "Popup クォータ表示",
    "settings.preferences.popup_circular_row_count_label": "円形項目の列数",
    "settings.preferences.popup_circular_row_count_helper": "Popup の円形、ソフト円形、ゲージ円形にのみ適用します。ライン表示は 1 行 1 項目のままです。",
    "settings.preferences.popup_circular_row_count.one": "1 項目/行",
    "settings.preferences.popup_circular_row_count.two": "2 項目/行",
    "settings.preferences.popup_circular_row_count.four": "4 項目/行",
    "settings.preferences.popup_circular_row_count.three": "3 項目/行",
    "settings.preferences.sidebar_progress_style_label": "サイドバーのクォータ表示",
    "settings.preferences.full_page_progress_style_label": "タブのクォータ表示",
    "settings.preferences.progress_style.line": "ライン",
    "settings.preferences.progress_style.circle": "円形",
    "settings.preferences.progress_style.circle_soft": "ソフト円形",
    "settings.preferences.progress_style.circle_gauge": "ゲージ円形",
    "settings.preferences.popup_size_label": "Popup サイズ",
    "settings.preferences.popup_size.compact": "コンパクト",
    "settings.preferences.popup_size.balanced": "バランス",
    "settings.preferences.popup_size.wide": "ワイド",
    "settings.preferences.popup_provider_browsing_mode_label": "Popup Provider 表示",
    "settings.preferences.popup_provider_browsing_mode.collapsible": "折りたたみカード",
    "settings.preferences.popup_provider_browsing_mode.single": "1枚ずつ切り替え",
    "settings.preferences.popup_provider_browsing_mode.scroll": "連続スクロール",
    "settings.preferences.popup_corner_label": "Popup の角",
    "settings.preferences.popup_corner.square": "四角",
    "settings.preferences.popup_corner.soft": "ソフト",
    "settings.preferences.popup_corner.rounded": "丸め",
    "settings.preferences.popup_shadow_label": "Popup の影",
    "settings.preferences.popup_shadow.none": "なし",
    "settings.preferences.popup_shadow.soft": "ソフト",
    "settings.preferences.popup_shadow.elevated": "強調",
    "settings.preferences.action_badge_label": "ツールバーバッジ",
    "settings.preferences.action_badge_mode_label": "バッジ選択モード",
    "settings.preferences.action_badge_mode_helper": "自動モードでは、Provider のクォータバッジが使えるまでは注意件数を表示し、使えるようになると表示中 Provider のクォータバッジをローテーションします。手動モードでは選んだバッジ元をそのまま保持します。",
    "settings.preferences.action_badge_mode_auto": "自動",
    "settings.preferences.action_badge_mode_manual": "手動",
    "settings.preferences.action_badge_restore_auto": "自動に戻す",
    "settings.preferences.toolbar_icon_label": "ツールバーアイコン",
    "settings.preferences.toolbar_icon.default": "デフォルトアイコン",
    "settings.preferences.toolbar_icon.match_badge": "ツールバーバッジに合わせる",
    "settings.preferences.toolbar_icon.provider": "Provider アイコン",
    "settings.preferences.toolbar_icon.custom": "カスタム画像",
    "settings.preferences.toolbar_icon_provider_label": "アイコン Provider",
    "settings.preferences.toolbar_icon_custom_label": "カスタムツールバーアイコン",
    "settings.preferences.toolbar_icon_custom_empty": "カスタム画像なし",
    "settings.preferences.toolbar_icon_custom_selected": "カスタム画像を選択済み",
    "settings.preferences.toolbar_icon_custom_clear": "クリア",
    "settings.preferences.ui_font_label": "UI フォント",
    "settings.preferences.ui_font_helper": "ローカルの安全なシステムフォントスタックを使い、popup、サイドバー、フルページタブ、Provider 詳細に一貫して適用します。リモートフォントは読み込みません。",
    "settings.preferences.ui_font.default": "デフォルト",
    "settings.preferences.ui_font.system": "システム UI",
    "settings.preferences.ui_font.serif": "セリフ",
    "settings.preferences.ui_font.mono": "等幅",
    "settings.preferences.minutes": "分",
    "settings.preferences.locale.system": "システムに従う",
    "settings.preferences.locale.en": "英語",
    "settings.preferences.locale.zh_cn": "簡体字中国語",
    "settings.preferences.theme_mode.system": "システムに従う",
    "settings.preferences.theme_mode.light": "ライト",
    "settings.preferences.theme_mode.dark": "ダーク",
    "settings.preferences.theme_mode.time": "現地時刻に合わせる",
    "settings.preferences.theme_mode_helper": "端末の現地時刻を使用し、07:00〜19:00はライト、それ以外はダークに切り替えます。位置情報は使用しません。",
    "settings.preferences.motion_mode.system": "システムに従う",
    "settings.preferences.motion_mode.full": "オン",
    "settings.preferences.motion_mode.reduced": "減らす",
    "settings.preferences.theme_preset.default": "デフォルトブルー",
    "settings.preferences.theme_preset.meadow": "メドウ",
    "settings.preferences.theme_preset.sunset": "サンセット",
    "settings.preferences.theme_preset.custom": "カスタムシード",
    "settings.toast.preferences_saved_title": "設定を保存しました",
    "settings.toast.preferences_saved_detail": "現在のプレビュー設定をローカルダッシュボード状態に保存しました。",
  },
  ko: {
    "app.loading.eyebrow": "로딩 중",
    "app.loading.title": "대시보드 상태 준비 중",
    "app.loading.detail": "대시보드 저장소와 메시지 버스를 초기화하는 중입니다.",
    "app.error.eyebrow": "상태를 사용할 수 없음",
    "app.error.title": "초기화가 완료되지 않았습니다",
    "app.error.detail_fallback": "확장 프로그램 저장소 또는 로컬 미리보기 저장소에서 앱 상태를 불러오지 못했습니다.",
    "common.actions.retry": "다시 시도",
    "common.actions.settings": "설정",
    "common.actions.refresh": "새로 고침",
    "common.actions.refresh_all": "모두 새로 고침",
    "common.actions.back": "뒤로",
    "common.actions.open_dashboard": "대시보드 열기",
    "common.actions.open_settings": "설정 열기",
    "common.actions.open_dashboard_tab": "대시보드 탭 열기",
    "common.actions.open_settings_tab": "설정 탭 열기",
    "common.actions.tab": "탭",
    "common.actions.sidebar": "사이드바",
    "common.actions.open_sidebar": "사이드바 열기",
    "common.actions.save": "저장",
    "provider.account.selector_label": "Provider 계정",
    "provider.account.settings_title": "활성 Provider 계정",
    "common.theme.toggle_to_dark_label": "다크",
    "common.theme.toggle_to_dark_title": "다크 모드로 전환",
    "common.theme.toggle_to_light_label": "라이트",
    "common.theme.toggle_to_light_title": "라이트 모드로 전환",
    "common.theme.toggle_to_system_label": "시스템",
    "common.theme.toggle_to_system_title": "시스템 테마로 전환",
    "common.theme.toggle_to_time_label": "시간 기준",
    "common.theme.toggle_to_time_title": "현지 시간 테마로 전환",
    "dashboard.topbar.title": "AI 사용량 대시보드",
    "dashboard.topbar.subtitle": "사용량, 크레딧, 동기화 상태",
    "dashboard.hero.eyebrow": "개요",
    "dashboard.hero.title": "AI 코딩 할당량 개요",
    "dashboard.hero.detail": "공식 API, 문서화된 할당량 정책, 보호된 페이지 파싱 소스를 새로 고침, 설정, Provider 상세 확인을 위한 릴리스 준비 대시보드에 모읍니다.",
    "dashboard.hero.release_chip": "Material 3 · 릴리스 후보",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 카드",
    "dashboard.providers.detail": "카드는 먼저 심각도, 그다음 현재 접근 공백 순서로 정렬됩니다. 위험이 큰 provider를 대시보드 상단에 유지하면서 현재 제품 계약도 한눈에 볼 수 있습니다.",
    "dashboard.providers.aria": "Provider 카드",
    "dashboard.empty.eyebrow": "표시 중인 Provider 없음",
    "dashboard.empty.detail": "Quick Setup에서 첫 Provider를 활성화한 뒤 접근 권한과 사용량 페이지 단계를 마치고 대시보드로 돌아오세요.",
    "dashboard.empty.action": "Quick Setup 열기",
    "dashboard.summary.aria": "대시보드 요약",
    "dashboard.summary.visible": "표시됨",
    "dashboard.summary.healthy": "정상",
    "dashboard.summary.needs_access": "접근 필요",
    "dashboard.summary.needs_attention": "확인 필요",
    "popup.loading.eyebrow": "도구 모음 팝업",
    "popup.loading.title": "캐시된 대시보드 상태를 불러오는 중",
    "popup.loading.detail": "이 브라우저 프로필의 공유 할당량 스냅샷을 준비하고 있습니다.",
    "popup.error.eyebrow": "도구 모음 팝업",
    "popup.error.title": "팝업을 불러오지 못했습니다",
    "popup.header.eyebrow": "도구 모음 팝업",
    "popup.header.title": "빠른 보기",
    "popup.summary.aria": "팝업 상단 요약",
    "popup.guidance.eyebrow": "팝업 가이드",
    "popup.snapshot_status.eyebrow": "스냅샷 상태",
    "popup.actions.eyebrow": "다른 경로",
    "popup.actions.refresh": "새로 고침",
    "popup.actions.refreshing": "새로 고치는 중",
    "popup.actions.refresh_title": "지금 새로 고침",
    "popup.actions.refresh_drift_note": "자동 동기화 시간은 근사값입니다. Chrome이 절전 상태이거나 service worker가 유휴 상태이면 alarms가 밀릴 수 있습니다.",
    "popup.actions.hide_header_actions": "상단 작업 숨기기",
    "popup.actions.show_header_actions": "상단 작업 표시",
    "popup.actions.hide_footer_info": "하단 정보 숨기기",
    "popup.actions.show_footer_info": "하단 정보 표시",
    "popup.providers.collapse_card": "Provider 카드 접기",
    "popup.providers.expand_card": "Provider 카드 펼치기",
    "popup.providers.previous": "이전 Provider",
    "popup.providers.next": "다음 Provider",
    "popup.featured.eyebrow": "주요 Provider",
    "popup.featured.single_eyebrow": "주요 Provider",
    "popup.triage.eyebrow": "팝업 우선 확인",
    "popup.summary.visible": "표시됨",
    "popup.summary.live_ready": "라이브 준비됨",
    "popup.summary.setup_blockers": "설정 차단 항목",
    "popup.summary.policy_only": "정책만",
    "settings.topbar.title": "설정",
    "settings.topbar.subtitle": "Quick Setup, 모양, 고급 Provider 관리",
    "settings.overview.eyebrow": "설정 개요",
    "settings.overview.title": "제어 화면 요약",
    "settings.overview.detail": "이 화면에서 표시 여부, 권한, 인증 정보, 하이브리드 source 제어를 관리합니다. 페이지 전체를 훑지 않고 필요한 섹션으로 바로 이동할 수 있습니다.",
    "settings.overview.aria": "설정 개요",
    "settings.sections.aria": "설정 섹션",
    "settings.sections.preferences": "환경설정",
    "settings.sections.visibility": "표시",
    "settings.sections.credentials": "인증 정보",
    "settings.sections.sources": "소스",
    "settings.sections.permissions": "권한",
    "settings.actions.back_to_top": "맨 위로",
    "settings.actions.back_to_top_short": "맨 위",
    "settings.summary.visible": "표시됨",
    "settings.summary.stored_secrets": "저장된 비밀 정보",
    "settings.summary.bound_pages": "연결된 페이지",
    "settings.summary.needs_access": "접근 필요",
    "settings.preferences.eyebrow": "모양 및 동기화",
    "settings.preferences.sync_interval_label": "기본 동기화 간격",
    "settings.preferences.warning_threshold_label": "경고 임계값",
    "settings.preferences.locale_label": "앱 언어",
    "settings.preferences.theme_mode_label": "테마 모드",
    "settings.preferences.motion_mode_label": "애니메이션 효과",
    "settings.preferences.accent_preset_label": "강조 색상 프리셋",
    "settings.preferences.popup_progress_style_label": "Popup 할당량 표시",
    "settings.preferences.popup_circular_row_count_label": "원형 항목 행당 개수",
    "settings.preferences.popup_circular_row_count_helper": "Popup의 원형, 부드러운 원형, 게이지 원형에만 적용됩니다. 선형 진행률은 행당 1개로 유지됩니다.",
    "settings.preferences.popup_circular_row_count.one": "행당 1개",
    "settings.preferences.popup_circular_row_count.two": "행당 2개",
    "settings.preferences.popup_circular_row_count.four": "행당 4개",
    "settings.preferences.popup_circular_row_count.three": "행당 3개",
    "settings.preferences.sidebar_progress_style_label": "사이드바 할당량 표시",
    "settings.preferences.full_page_progress_style_label": "탭 할당량 표시",
    "settings.preferences.progress_style.line": "선",
    "settings.preferences.progress_style.circle": "원형",
    "settings.preferences.progress_style.circle_soft": "부드러운 원형",
    "settings.preferences.progress_style.circle_gauge": "게이지 원형",
    "settings.preferences.popup_size_label": "Popup 크기",
    "settings.preferences.popup_size.compact": "컴팩트",
    "settings.preferences.popup_size.balanced": "균형",
    "settings.preferences.popup_size.wide": "넓게",
    "settings.preferences.popup_provider_browsing_mode_label": "Popup Provider 탐색",
    "settings.preferences.popup_provider_browsing_mode.collapsible": "접을 수 있는 카드",
    "settings.preferences.popup_provider_browsing_mode.single": "한 번에 한 카드",
    "settings.preferences.popup_provider_browsing_mode.scroll": "연속 스크롤",
    "settings.preferences.popup_corner_label": "Popup 모서리",
    "settings.preferences.popup_corner.square": "각진",
    "settings.preferences.popup_corner.soft": "부드럽게",
    "settings.preferences.popup_corner.rounded": "둥글게",
    "settings.preferences.popup_shadow_label": "Popup 그림자",
    "settings.preferences.popup_shadow.none": "없음",
    "settings.preferences.popup_shadow.soft": "부드럽게",
    "settings.preferences.popup_shadow.elevated": "강조",
    "settings.preferences.action_badge_label": "도구 모음 배지",
    "settings.preferences.action_badge_mode_label": "배지 선택 모드",
    "settings.preferences.action_badge_mode_helper": "자동 모드는 Provider quota 배지가 없을 때는 주의 항목 수를 보여주고, 표시 가능한 Provider quota 배지가 생기면 그 배지들을 순환합니다. 수동 모드는 선택한 배지 소스를 그대로 유지합니다.",
    "settings.preferences.action_badge_mode_auto": "자동",
    "settings.preferences.action_badge_mode_manual": "수동",
    "settings.preferences.action_badge_restore_auto": "자동으로 복원",
    "settings.preferences.toolbar_icon_label": "도구 모음 아이콘",
    "settings.preferences.toolbar_icon.default": "기본 아이콘",
    "settings.preferences.toolbar_icon.match_badge": "도구 모음 배지에 맞춤",
    "settings.preferences.toolbar_icon.provider": "Provider 아이콘",
    "settings.preferences.toolbar_icon.custom": "사용자 이미지",
    "settings.preferences.toolbar_icon_provider_label": "아이콘 Provider",
    "settings.preferences.toolbar_icon_custom_label": "사용자 도구 모음 아이콘",
    "settings.preferences.toolbar_icon_custom_empty": "사용자 이미지 없음",
    "settings.preferences.toolbar_icon_custom_selected": "사용자 이미지 선택됨",
    "settings.preferences.toolbar_icon_custom_clear": "지우기",
    "settings.preferences.ui_font_label": "UI 글꼴",
    "settings.preferences.ui_font_helper": "로컬의 안전한 시스템 글꼴 스택을 사용해 popup, 사이드바, 전체 페이지 탭, Provider 상세에 동일하게 적용합니다. 원격 글꼴은 로드하지 않습니다.",
    "settings.preferences.ui_font.default": "기본",
    "settings.preferences.ui_font.system": "시스템 UI",
    "settings.preferences.ui_font.serif": "세리프",
    "settings.preferences.ui_font.mono": "고정폭",
    "settings.preferences.minutes": "분",
    "settings.preferences.locale.system": "시스템 따름",
    "settings.preferences.locale.en": "영어",
    "settings.preferences.locale.zh_cn": "중국어 간체",
    "settings.preferences.theme_mode.system": "시스템 따름",
    "settings.preferences.theme_mode.light": "라이트",
    "settings.preferences.theme_mode.dark": "다크",
    "settings.preferences.theme_mode.time": "현지 시간 기준",
    "settings.preferences.theme_mode_helper": "기기의 현지 시간을 사용해 07:00~19:00에는 라이트, 그 외 시간에는 다크 모드로 전환합니다. 위치 정보는 사용하지 않습니다.",
    "settings.preferences.motion_mode.system": "시스템 따름",
    "settings.preferences.motion_mode.full": "켜기",
    "settings.preferences.motion_mode.reduced": "줄이기",
    "settings.preferences.theme_preset.default": "기본 파란색",
    "settings.preferences.theme_preset.meadow": "메도우",
    "settings.preferences.theme_preset.sunset": "선셋",
    "settings.preferences.theme_preset.custom": "사용자 지정 시드",
    "settings.toast.preferences_saved_title": "환경설정이 저장됨",
    "settings.toast.preferences_saved_detail": "현재 미리보기 설정이 로컬 대시보드 상태에 저장되었습니다.",
  },
} satisfies Partial<Record<ResolvedAppLocale, Partial<RuntimeMessages>>>;
