import type { ResolvedAppLocale } from "./i18n";

export type ApiGatewayMeteringLocalizedCopy = {
  overview: string;
  trend: string;
  models: string;
  limits: string;
  balance: string;
  quotaRemaining: string;
  dailyRemaining: string;
  weeklyRemaining: string;
  monthlyRemaining: string;
  noFixedLimit: string;
  unavailable: string;
  actualSpend: string;
  referenceCost: string;
  estimatedSavings: string;
  requests: string;
  tokens: string;
  averageLatency: string;
  inputTokens: string;
  outputTokens: string;
  cacheCreationTokens: string;
  cacheReadTokens: string;
  tokenBreakdown: string;
  openSourceDashboard: string;
  recorded: string;
  sevenDays: string;
  thirtyDays: string;
  apiKeyScope: string;
  accountScope: string;
  savedData: string;
  currentData: string;
  other: string;
  reset: string;
  remaining: string;
  expand: string;
  collapse: string;
  chartLegend: string;
};

const ENGLISH_COPY: ApiGatewayMeteringLocalizedCopy = {
  overview: "Usage summary",
  trend: "Usage trend",
  models: "Leading models",
  limits: "Limit windows",
  balance: "Available balance",
  quotaRemaining: "Quota remaining",
  dailyRemaining: "Daily allowance remaining",
  weeklyRemaining: "Weekly allowance remaining",
  monthlyRemaining: "Monthly allowance remaining",
  noFixedLimit: "No fixed limit returned",
  unavailable: "Not available",
  actualSpend: "Actual spend",
  referenceCost: "Reference cost",
  estimatedSavings: "Estimated savings",
  requests: "Requests",
  tokens: "Tokens",
  averageLatency: "Average latency",
  inputTokens: "Input",
  outputTokens: "Output",
  cacheCreationTokens: "Cache creation",
  cacheReadTokens: "Cache read",
  tokenBreakdown: "Token breakdown",
  openSourceDashboard: "Open source dashboard",
  recorded: "Recorded",
  sevenDays: "7 days",
  thirtyDays: "30 days",
  apiKeyScope: "API key scope",
  accountScope: "Account scope",
  savedData: "Saved data",
  currentData: "Current data",
  other: "Other",
  reset: "Resets",
  remaining: "remaining",
  expand: "Show metering details",
  collapse: "Hide metering details",
  chartLegend: "Usage legend",
};

const COPY_OVERRIDES: Record<
  Exclude<ResolvedAppLocale, "en">,
  ApiGatewayMeteringLocalizedCopy
> = {
  "zh-CN": {
    overview: "用量摘要",
    trend: "用量趋势",
    models: "主要模型",
    limits: "额度窗口",
    balance: "可用余额",
    quotaRemaining: "剩余额度",
    dailyRemaining: "每日剩余额度",
    weeklyRemaining: "每周剩余额度",
    monthlyRemaining: "每月剩余额度",
    noFixedLimit: "来源未返回固定限额",
    unavailable: "暂无数据",
    actualSpend: "实际支出",
    referenceCost: "参考成本",
    estimatedSavings: "估算节省",
    requests: "请求",
    tokens: "Token",
    averageLatency: "平均延迟",
    inputTokens: "输入",
    outputTokens: "输出",
    cacheCreationTokens: "缓存创建",
    cacheReadTokens: "缓存读取",
    tokenBreakdown: "Token 构成",
    openSourceDashboard: "打开来源仪表板",
    recorded: "已记录",
    sevenDays: "7 天",
    thirtyDays: "30 天",
    apiKeyScope: "API 密钥范围",
    accountScope: "账户范围",
    savedData: "已保存数据",
    currentData: "当前数据",
    other: "其他",
    reset: "重置于",
    remaining: "剩余",
    expand: "展开计量详情",
    collapse: "收起计量详情",
    chartLegend: "用量图例",
  },
  "zh-TW": {
    overview: "用量摘要",
    trend: "用量趨勢",
    models: "主要模型",
    limits: "額度視窗",
    balance: "可用餘額",
    quotaRemaining: "剩餘額度",
    dailyRemaining: "每日剩餘額度",
    weeklyRemaining: "每週剩餘額度",
    monthlyRemaining: "每月剩餘額度",
    noFixedLimit: "來源未回傳固定限額",
    unavailable: "暫無資料",
    actualSpend: "實際支出",
    referenceCost: "參考成本",
    estimatedSavings: "估算節省",
    requests: "請求",
    tokens: "Token",
    averageLatency: "平均延遲",
    inputTokens: "輸入",
    outputTokens: "輸出",
    cacheCreationTokens: "快取建立",
    cacheReadTokens: "快取讀取",
    tokenBreakdown: "Token 組成",
    openSourceDashboard: "開啟來源儀表板",
    recorded: "已記錄",
    sevenDays: "7 天",
    thirtyDays: "30 天",
    apiKeyScope: "API 金鑰範圍",
    accountScope: "帳戶範圍",
    savedData: "已儲存資料",
    currentData: "目前資料",
    other: "其他",
    reset: "重設於",
    remaining: "剩餘",
    expand: "展開計量詳情",
    collapse: "收合計量詳情",
    chartLegend: "用量圖例",
  },
  ja: {
    overview: "使用概要",
    trend: "使用推移",
    models: "主なモデル",
    limits: "上限ウィンドウ",
    balance: "利用可能残高",
    quotaRemaining: "残りクォータ",
    dailyRemaining: "1 日あたりの残り",
    weeklyRemaining: "1 週間あたりの残り",
    monthlyRemaining: "1 か月あたりの残り",
    noFixedLimit: "固定上限は返されませんでした",
    unavailable: "データなし",
    actualSpend: "実際の支出",
    referenceCost: "参考コスト",
    estimatedSavings: "推定節約額",
    requests: "リクエスト",
    tokens: "Token",
    averageLatency: "平均レイテンシ",
    inputTokens: "入力",
    outputTokens: "出力",
    cacheCreationTokens: "キャッシュ作成",
    cacheReadTokens: "キャッシュ読み取り",
    tokenBreakdown: "Token 内訳",
    openSourceDashboard: "元のダッシュボードを開く",
    recorded: "記録済み",
    sevenDays: "7 日",
    thirtyDays: "30 日",
    apiKeyScope: "API key 範囲",
    accountScope: "アカウント範囲",
    savedData: "保存済みデータ",
    currentData: "現在のデータ",
    other: "その他",
    reset: "リセット",
    remaining: "残り",
    expand: "計量詳細を表示",
    collapse: "計量詳細を非表示",
    chartLegend: "使用量の凡例",
  },
  ko: {
    overview: "사용량 요약",
    trend: "사용량 추이",
    models: "주요 모델",
    limits: "한도 구간",
    balance: "사용 가능 잔액",
    quotaRemaining: "남은 할당량",
    dailyRemaining: "일일 남은 할당량",
    weeklyRemaining: "주간 남은 할당량",
    monthlyRemaining: "월간 남은 할당량",
    noFixedLimit: "고정 한도가 반환되지 않음",
    unavailable: "데이터 없음",
    actualSpend: "실제 지출",
    referenceCost: "기준 비용",
    estimatedSavings: "예상 절감액",
    requests: "요청",
    tokens: "Token",
    averageLatency: "평균 지연 시간",
    inputTokens: "입력",
    outputTokens: "출력",
    cacheCreationTokens: "캐시 생성",
    cacheReadTokens: "캐시 읽기",
    tokenBreakdown: "Token 구성",
    openSourceDashboard: "원본 대시보드 열기",
    recorded: "기록됨",
    sevenDays: "7일",
    thirtyDays: "30일",
    apiKeyScope: "API key 범위",
    accountScope: "계정 범위",
    savedData: "저장된 데이터",
    currentData: "현재 데이터",
    other: "기타",
    reset: "재설정",
    remaining: "남음",
    expand: "계량 세부정보 표시",
    collapse: "계량 세부정보 숨기기",
    chartLegend: "사용량 범례",
  },
  "es-419": {
    overview: "Resumen de uso",
    trend: "Tendencia de uso",
    models: "Modelos principales",
    limits: "Ventanas de límite",
    balance: "Saldo disponible",
    quotaRemaining: "Cuota restante",
    dailyRemaining: "Asignación diaria restante",
    weeklyRemaining: "Asignación semanal restante",
    monthlyRemaining: "Asignación mensual restante",
    noFixedLimit: "La fuente no informó un límite fijo",
    unavailable: "No disponible",
    actualSpend: "Gasto real",
    referenceCost: "Costo de referencia",
    estimatedSavings: "Ahorro estimado",
    requests: "Solicitudes",
    tokens: "Tokens",
    averageLatency: "Latencia promedio",
    inputTokens: "Entrada",
    outputTokens: "Salida",
    cacheCreationTokens: "Creación de caché",
    cacheReadTokens: "Lectura de caché",
    tokenBreakdown: "Desglose de tokens",
    openSourceDashboard: "Abrir panel de origen",
    recorded: "Registrado",
    sevenDays: "7 días",
    thirtyDays: "30 días",
    apiKeyScope: "Alcance de API key",
    accountScope: "Alcance de cuenta",
    savedData: "Datos guardados",
    currentData: "Datos actuales",
    other: "Otros",
    reset: "Se restablece",
    remaining: "restante",
    expand: "Mostrar detalles de medición",
    collapse: "Ocultar detalles de medición",
    chartLegend: "Leyenda de uso",
  },
  "pt-BR": {
    overview: "Resumo de uso",
    trend: "Tendência de uso",
    models: "Principais modelos",
    limits: "Janelas de limite",
    balance: "Saldo disponível",
    quotaRemaining: "Cota restante",
    dailyRemaining: "Limite diário restante",
    weeklyRemaining: "Limite semanal restante",
    monthlyRemaining: "Limite mensal restante",
    noFixedLimit: "A origem não informou limite fixo",
    unavailable: "Indisponível",
    actualSpend: "Gasto real",
    referenceCost: "Custo de referência",
    estimatedSavings: "Economia estimada",
    requests: "Solicitações",
    tokens: "Tokens",
    averageLatency: "Latência média",
    inputTokens: "Entrada",
    outputTokens: "Saída",
    cacheCreationTokens: "Criação de cache",
    cacheReadTokens: "Leitura de cache",
    tokenBreakdown: "Detalhamento de tokens",
    openSourceDashboard: "Abrir painel de origem",
    recorded: "Registrado",
    sevenDays: "7 dias",
    thirtyDays: "30 dias",
    apiKeyScope: "Escopo da API key",
    accountScope: "Escopo da conta",
    savedData: "Dados salvos",
    currentData: "Dados atuais",
    other: "Outros",
    reset: "Redefine em",
    remaining: "restante",
    expand: "Mostrar detalhes de medição",
    collapse: "Ocultar detalhes de medição",
    chartLegend: "Legenda de uso",
  },
  fr: {
    overview: "Résumé d’utilisation",
    trend: "Tendance d’utilisation",
    models: "Modèles principaux",
    limits: "Fenêtres de limite",
    balance: "Solde disponible",
    quotaRemaining: "Quota restant",
    dailyRemaining: "Allocation quotidienne restante",
    weeklyRemaining: "Allocation hebdomadaire restante",
    monthlyRemaining: "Allocation mensuelle restante",
    noFixedLimit: "Aucune limite fixe renvoyée",
    unavailable: "Indisponible",
    actualSpend: "Dépense réelle",
    referenceCost: "Coût de référence",
    estimatedSavings: "Économies estimées",
    requests: "Requêtes",
    tokens: "Tokens",
    averageLatency: "Latence moyenne",
    inputTokens: "Entrée",
    outputTokens: "Sortie",
    cacheCreationTokens: "Création du cache",
    cacheReadTokens: "Lecture du cache",
    tokenBreakdown: "Répartition des tokens",
    openSourceDashboard: "Ouvrir le tableau de bord source",
    recorded: "Enregistré",
    sevenDays: "7 jours",
    thirtyDays: "30 jours",
    apiKeyScope: "Portée de la clé API",
    accountScope: "Portée du compte",
    savedData: "Données enregistrées",
    currentData: "Données actuelles",
    other: "Autres",
    reset: "Réinitialisation",
    remaining: "restant",
    expand: "Afficher les détails de mesure",
    collapse: "Masquer les détails de mesure",
    chartLegend: "Légende d’utilisation",
  },
  de: {
    overview: "Nutzungsübersicht",
    trend: "Nutzungsverlauf",
    models: "Führende Modelle",
    limits: "Limitfenster",
    balance: "Verfügbares Guthaben",
    quotaRemaining: "Verbleibendes Kontingent",
    dailyRemaining: "Verbleibendes Tageskontingent",
    weeklyRemaining: "Verbleibendes Wochenkontingent",
    monthlyRemaining: "Verbleibendes Monatskontingent",
    noFixedLimit: "Quelle meldet kein festes Limit",
    unavailable: "Nicht verfügbar",
    actualSpend: "Tatsächliche Ausgaben",
    referenceCost: "Referenzkosten",
    estimatedSavings: "Geschätzte Ersparnis",
    requests: "Anfragen",
    tokens: "Tokens",
    averageLatency: "Durchschnittliche Latenz",
    inputTokens: "Eingabe",
    outputTokens: "Ausgabe",
    cacheCreationTokens: "Cache-Erstellung",
    cacheReadTokens: "Cache-Lesezugriff",
    tokenBreakdown: "Token-Aufteilung",
    openSourceDashboard: "Quell-Dashboard öffnen",
    recorded: "Erfasst",
    sevenDays: "7 Tage",
    thirtyDays: "30 Tage",
    apiKeyScope: "API-Key-Bereich",
    accountScope: "Kontobereich",
    savedData: "Gespeicherte Daten",
    currentData: "Aktuelle Daten",
    other: "Sonstige",
    reset: "Zurücksetzung",
    remaining: "verbleibend",
    expand: "Messdetails anzeigen",
    collapse: "Messdetails ausblenden",
    chartLegend: "Nutzungslegende",
  },
  it: {
    overview: "Riepilogo utilizzo",
    trend: "Andamento utilizzo",
    models: "Modelli principali",
    limits: "Finestre dei limiti",
    balance: "Saldo disponibile",
    quotaRemaining: "Quota rimanente",
    dailyRemaining: "Limite giornaliero rimanente",
    weeklyRemaining: "Limite settimanale rimanente",
    monthlyRemaining: "Limite mensile rimanente",
    noFixedLimit: "La fonte non ha restituito un limite fisso",
    unavailable: "Non disponibile",
    actualSpend: "Spesa effettiva",
    referenceCost: "Costo di riferimento",
    estimatedSavings: "Risparmio stimato",
    requests: "Richieste",
    tokens: "Token",
    averageLatency: "Latenza media",
    inputTokens: "Input",
    outputTokens: "Output",
    cacheCreationTokens: "Creazione cache",
    cacheReadTokens: "Lettura cache",
    tokenBreakdown: "Dettaglio token",
    openSourceDashboard: "Apri dashboard di origine",
    recorded: "Registrato",
    sevenDays: "7 giorni",
    thirtyDays: "30 giorni",
    apiKeyScope: "Ambito API key",
    accountScope: "Ambito account",
    savedData: "Dati salvati",
    currentData: "Dati correnti",
    other: "Altro",
    reset: "Reimposta",
    remaining: "rimanente",
    expand: "Mostra dettagli di misurazione",
    collapse: "Nascondi dettagli di misurazione",
    chartLegend: "Legenda utilizzo",
  },
  ru: {
    overview: "Сводка использования",
    trend: "Динамика использования",
    models: "Основные модели",
    limits: "Окна лимитов",
    balance: "Доступный баланс",
    quotaRemaining: "Остаток квоты",
    dailyRemaining: "Остаток дневного лимита",
    weeklyRemaining: "Остаток недельного лимита",
    monthlyRemaining: "Остаток месячного лимита",
    noFixedLimit: "Источник не вернул фиксированный лимит",
    unavailable: "Недоступно",
    actualSpend: "Фактические расходы",
    referenceCost: "Расчётная стоимость",
    estimatedSavings: "Оценка экономии",
    requests: "Запросы",
    tokens: "Токены",
    averageLatency: "Средняя задержка",
    inputTokens: "Входные",
    outputTokens: "Выходные",
    cacheCreationTokens: "Создание кэша",
    cacheReadTokens: "Чтение кэша",
    tokenBreakdown: "Распределение токенов",
    openSourceDashboard: "Открыть исходную панель",
    recorded: "Записано",
    sevenDays: "7 дней",
    thirtyDays: "30 дней",
    apiKeyScope: "Область API-ключа",
    accountScope: "Область аккаунта",
    savedData: "Сохранённые данные",
    currentData: "Текущие данные",
    other: "Другое",
    reset: "Сброс",
    remaining: "осталось",
    expand: "Показать сведения об учёте",
    collapse: "Скрыть сведения об учёте",
    chartLegend: "Легенда использования",
  },
  ar: {
    overview: "ملخص الاستخدام",
    trend: "اتجاه الاستخدام",
    models: "النماذج الرئيسية",
    limits: "نوافذ الحدود",
    balance: "الرصيد المتاح",
    quotaRemaining: "الحصة المتبقية",
    dailyRemaining: "المتبقي من الحد اليومي",
    weeklyRemaining: "المتبقي من الحد الأسبوعي",
    monthlyRemaining: "المتبقي من الحد الشهري",
    noFixedLimit: "لم يُرجع المصدر حدًا ثابتًا",
    unavailable: "غير متاح",
    actualSpend: "الإنفاق الفعلي",
    referenceCost: "التكلفة المرجعية",
    estimatedSavings: "التوفير التقديري",
    requests: "الطلبات",
    tokens: "الرموز",
    averageLatency: "متوسط زمن الاستجابة",
    inputTokens: "الإدخال",
    outputTokens: "الإخراج",
    cacheCreationTokens: "إنشاء الذاكرة المؤقتة",
    cacheReadTokens: "قراءة الذاكرة المؤقتة",
    tokenBreakdown: "تفصيل الرموز",
    openSourceDashboard: "فتح لوحة المصدر",
    recorded: "مسجل",
    sevenDays: "7 أيام",
    thirtyDays: "30 يومًا",
    apiKeyScope: "نطاق مفتاح API",
    accountScope: "نطاق الحساب",
    savedData: "بيانات محفوظة",
    currentData: "بيانات حالية",
    other: "أخرى",
    reset: "إعادة الضبط",
    remaining: "متبقٍ",
    expand: "إظهار تفاصيل القياس",
    collapse: "إخفاء تفاصيل القياس",
    chartLegend: "وسيلة إيضاح الاستخدام",
  },
  hi: {
    overview: "उपयोग सारांश",
    trend: "उपयोग रुझान",
    models: "मुख्य मॉडल",
    limits: "सीमा विंडो",
    balance: "उपलब्ध शेष",
    quotaRemaining: "शेष कोटा",
    dailyRemaining: "शेष दैनिक सीमा",
    weeklyRemaining: "शेष साप्ताहिक सीमा",
    monthlyRemaining: "शेष मासिक सीमा",
    noFixedLimit: "स्रोत ने निश्चित सीमा नहीं दी",
    unavailable: "उपलब्ध नहीं",
    actualSpend: "वास्तविक खर्च",
    referenceCost: "संदर्भ लागत",
    estimatedSavings: "अनुमानित बचत",
    requests: "अनुरोध",
    tokens: "टोकन",
    averageLatency: "औसत विलंब",
    inputTokens: "इनपुट",
    outputTokens: "आउटपुट",
    cacheCreationTokens: "कैश निर्माण",
    cacheReadTokens: "कैश पठन",
    tokenBreakdown: "टोकन विवरण",
    openSourceDashboard: "स्रोत डैशबोर्ड खोलें",
    recorded: "रिकॉर्ड किया गया",
    sevenDays: "7 दिन",
    thirtyDays: "30 दिन",
    apiKeyScope: "API key दायरा",
    accountScope: "खाता दायरा",
    savedData: "सहेजा हुआ डेटा",
    currentData: "वर्तमान डेटा",
    other: "अन्य",
    reset: "रीसेट",
    remaining: "शेष",
    expand: "मीटरिंग विवरण दिखाएँ",
    collapse: "मीटरिंग विवरण छिपाएँ",
    chartLegend: "उपयोग संकेत",
  },
  id: {
    overview: "Ringkasan penggunaan",
    trend: "Tren penggunaan",
    models: "Model utama",
    limits: "Jendela batas",
    balance: "Saldo tersedia",
    quotaRemaining: "Kuota tersisa",
    dailyRemaining: "Sisa batas harian",
    weeklyRemaining: "Sisa batas mingguan",
    monthlyRemaining: "Sisa batas bulanan",
    noFixedLimit: "Sumber tidak mengembalikan batas tetap",
    unavailable: "Tidak tersedia",
    actualSpend: "Pengeluaran aktual",
    referenceCost: "Biaya referensi",
    estimatedSavings: "Perkiraan penghematan",
    requests: "Permintaan",
    tokens: "Token",
    averageLatency: "Latensi rata-rata",
    inputTokens: "Input",
    outputTokens: "Output",
    cacheCreationTokens: "Pembuatan cache",
    cacheReadTokens: "Pembacaan cache",
    tokenBreakdown: "Rincian token",
    openSourceDashboard: "Buka dasbor sumber",
    recorded: "Tercatat",
    sevenDays: "7 hari",
    thirtyDays: "30 hari",
    apiKeyScope: "Cakupan API key",
    accountScope: "Cakupan akun",
    savedData: "Data tersimpan",
    currentData: "Data saat ini",
    other: "Lainnya",
    reset: "Direset",
    remaining: "tersisa",
    expand: "Tampilkan detail pengukuran",
    collapse: "Sembunyikan detail pengukuran",
    chartLegend: "Legenda penggunaan",
  },
};

export function buildApiGatewayMeteringLocalizedCopy(
  locale: ResolvedAppLocale,
): ApiGatewayMeteringLocalizedCopy {
  return locale === "en" ? ENGLISH_COPY : COPY_OVERRIDES[locale];
}
