import type { ResolvedAppLocale } from "./i18n";

export type CursorUsageLocalizedCopy = {
  billingSummary: string;
  recentUsage: string;
  billingCycle: string;
  planUsage: string;
  firstPartyPool: string;
  apiPool: string;
  onDemand: string;
  includedValue: string;
  bonusValue: string;
  actualCharge: string;
  enabled: string;
  disabled: string;
  unavailable: string;
  stale: string;
  updated: string;
  sevenDays: string;
  thirtyDays: string;
  models: string;
  usageTypes: string;
  noHistory: string;
  expand: string;
  collapse: string;
  settingsDetail: string;
  sourceLinksLabel: string;
  usagePage: string;
  spendingPage: string;
  csvAvailable: string;
};

const CURSOR_USAGE_COPY: Record<ResolvedAppLocale, CursorUsageLocalizedCopy> = {
  en: {
    billingSummary: "Usage & billing",
    recentUsage: "Recent usage",
    billingCycle: "Billing cycle",
    planUsage: "Plan usage value",
    firstPartyPool: "Included model pool",
    apiPool: "Third-party API pool",
    onDemand: "On-Demand",
    includedValue: "Included",
    bonusValue: "Free / bonus",
    actualCharge: "Actual charge",
    enabled: "Enabled",
    disabled: "Off",
    unavailable: "Not available",
    stale: "Saved data",
    updated: "Updated",
    sevenDays: "7 days",
    thirtyDays: "30 days",
    models: "Models",
    usageTypes: "Usage types",
    noHistory: "No aggregate usage history yet",
    expand: "Show Cursor usage details",
    collapse: "Hide Cursor usage details",
    settingsDetail:
      "Show, hide, and reorder billing and aggregate usage independently on each surface.",
    sourceLinksLabel: "Cursor usage source links",
    usagePage: "Usage page",
    spendingPage: "Spending page",
    csvAvailable: "CSV export is available from the Cursor Usage page.",
  },
  "zh-CN": {
    billingSummary: "用量与计费",
    recentUsage: "近期用量",
    billingCycle: "计费周期",
    planUsage: "套餐内用量价值",
    firstPartyPool: "第一方模型池",
    apiPool: "第三方 API 池",
    onDemand: "按量付费",
    includedValue: "套餐内",
    bonusValue: "免费 / 赠送",
    actualCharge: "实际支出",
    enabled: "已启用",
    disabled: "未启用",
    unavailable: "暂无数据",
    stale: "已保存数据",
    updated: "更新于",
    sevenDays: "7 天",
    thirtyDays: "30 天",
    models: "主要模型",
    usageTypes: "用量类型",
    noHistory: "暂无聚合用量历史",
    expand: "展开 Cursor 用量详情",
    collapse: "收起 Cursor 用量详情",
    settingsDetail: "可按界面分别显示、隐藏和调整计费摘要与聚合用量的顺序。",
    sourceLinksLabel: "Cursor 用量来源链接",
    usagePage: "用量页面",
    spendingPage: "支出页面",
    csvAvailable: "可在 Cursor 用量页面导出 CSV。",
  },
  "zh-TW": {
    billingSummary: "用量與計費",
    recentUsage: "近期用量",
    billingCycle: "計費週期",
    planUsage: "方案內用量價值",
    firstPartyPool: "第一方模型集區",
    apiPool: "第三方 API 集區",
    onDemand: "隨用隨付",
    includedValue: "方案內",
    bonusValue: "免費 / 贈送",
    actualCharge: "實際支出",
    enabled: "已啟用",
    disabled: "未啟用",
    unavailable: "暫無資料",
    stale: "已儲存資料",
    updated: "更新於",
    sevenDays: "7 天",
    thirtyDays: "30 天",
    models: "主要模型",
    usageTypes: "用量類型",
    noHistory: "尚無彙總用量記錄",
    expand: "展開 Cursor 用量詳情",
    collapse: "收合 Cursor 用量詳情",
    settingsDetail: "可依介面分別顯示、隱藏及調整計費摘要與彙總用量順序。",
    sourceLinksLabel: "Cursor 用量來源連結",
    usagePage: "用量頁面",
    spendingPage: "支出頁面",
    csvAvailable: "可從 Cursor 用量頁面匯出 CSV。",
  },
  ja: {
    billingSummary: "使用量と請求",
    recentUsage: "最近の使用量",
    billingCycle: "請求期間",
    planUsage: "プラン内使用価値",
    firstPartyPool: "対象モデル枠",
    apiPool: "外部 API 枠",
    onDemand: "従量課金",
    includedValue: "プラン内",
    bonusValue: "無料 / ボーナス",
    actualCharge: "実際の請求額",
    enabled: "有効",
    disabled: "オフ",
    unavailable: "データなし",
    stale: "保存済みデータ",
    updated: "更新",
    sevenDays: "7 日",
    thirtyDays: "30 日",
    models: "モデル",
    usageTypes: "使用区分",
    noHistory: "集計された使用履歴はまだありません",
    expand: "Cursor の使用詳細を表示",
    collapse: "Cursor の使用詳細を非表示",
    settingsDetail: "画面ごとに請求概要と集計使用量の表示・順序を設定します。",
    sourceLinksLabel: "Cursor 使用量の参照リンク",
    usagePage: "使用量ページ",
    spendingPage: "支出ページ",
    csvAvailable: "Cursor の使用量ページから CSV を出力できます。",
  },
  ko: {
    billingSummary: "사용량 및 결제",
    recentUsage: "최근 사용량",
    billingCycle: "결제 주기",
    planUsage: "플랜 내 사용 가치",
    firstPartyPool: "포함 모델 풀",
    apiPool: "타사 API 풀",
    onDemand: "종량제",
    includedValue: "플랜 포함",
    bonusValue: "무료 / 보너스",
    actualCharge: "실제 청구액",
    enabled: "사용",
    disabled: "꺼짐",
    unavailable: "데이터 없음",
    stale: "저장된 데이터",
    updated: "업데이트",
    sevenDays: "7일",
    thirtyDays: "30일",
    models: "모델",
    usageTypes: "사용 유형",
    noHistory: "집계 사용 기록이 아직 없습니다",
    expand: "Cursor 사용량 세부정보 표시",
    collapse: "Cursor 사용량 세부정보 숨기기",
    settingsDetail: "화면별로 결제 요약과 집계 사용량의 표시 및 순서를 설정합니다.",
    sourceLinksLabel: "Cursor 사용량 원본 링크",
    usagePage: "사용량 페이지",
    spendingPage: "지출 페이지",
    csvAvailable: "Cursor 사용량 페이지에서 CSV를 내보낼 수 있습니다.",
  },
  "es-419": {
    billingSummary: "Uso y facturación",
    recentUsage: "Uso reciente",
    billingCycle: "Ciclo de facturación",
    planUsage: "Valor de uso del plan",
    firstPartyPool: "Grupo de modelos incluidos",
    apiPool: "Grupo de API de terceros",
    onDemand: "Bajo demanda",
    includedValue: "Incluido",
    bonusValue: "Gratis / bonificación",
    actualCharge: "Cargo real",
    enabled: "Activado",
    disabled: "Desactivado",
    unavailable: "No disponible",
    stale: "Datos guardados",
    updated: "Actualizado",
    sevenDays: "7 días",
    thirtyDays: "30 días",
    models: "Modelos",
    usageTypes: "Tipos de uso",
    noHistory: "Aún no hay historial de uso agregado",
    expand: "Mostrar detalles de uso de Cursor",
    collapse: "Ocultar detalles de uso de Cursor",
    settingsDetail: "Muestra, oculta y ordena la facturación y el uso agregado por pantalla.",
    sourceLinksLabel: "Enlaces de origen del uso de Cursor",
    usagePage: "Página de uso",
    spendingPage: "Página de gastos",
    csvAvailable: "La página de uso de Cursor permite exportar un CSV.",
  },
  "pt-BR": {
    billingSummary: "Uso e faturamento",
    recentUsage: "Uso recente",
    billingCycle: "Ciclo de faturamento",
    planUsage: "Valor de uso do plano",
    firstPartyPool: "Grupo de modelos incluídos",
    apiPool: "Grupo de APIs de terceiros",
    onDemand: "Sob demanda",
    includedValue: "Incluído",
    bonusValue: "Grátis / bônus",
    actualCharge: "Cobrança real",
    enabled: "Ativado",
    disabled: "Desativado",
    unavailable: "Indisponível",
    stale: "Dados salvos",
    updated: "Atualizado",
    sevenDays: "7 dias",
    thirtyDays: "30 dias",
    models: "Modelos",
    usageTypes: "Tipos de uso",
    noHistory: "Ainda não há histórico de uso agregado",
    expand: "Mostrar detalhes de uso do Cursor",
    collapse: "Ocultar detalhes de uso do Cursor",
    settingsDetail: "Mostre, oculte e reordene faturamento e uso agregado por tela.",
    sourceLinksLabel: "Links de origem do uso do Cursor",
    usagePage: "Página de uso",
    spendingPage: "Página de gastos",
    csvAvailable: "A página de uso do Cursor permite exportar CSV.",
  },
  fr: {
    billingSummary: "Utilisation et facturation",
    recentUsage: "Utilisation récente",
    billingCycle: "Période de facturation",
    planUsage: "Valeur d’utilisation du forfait",
    firstPartyPool: "Réserve de modèles incluse",
    apiPool: "Réserve d’API tierces",
    onDemand: "À la demande",
    includedValue: "Inclus",
    bonusValue: "Gratuit / bonus",
    actualCharge: "Montant facturé",
    enabled: "Activé",
    disabled: "Désactivé",
    unavailable: "Indisponible",
    stale: "Données enregistrées",
    updated: "Mis à jour",
    sevenDays: "7 jours",
    thirtyDays: "30 jours",
    models: "Modèles",
    usageTypes: "Types d’utilisation",
    noHistory: "Aucun historique d’utilisation agrégé pour le moment",
    expand: "Afficher les détails d’utilisation de Cursor",
    collapse: "Masquer les détails d’utilisation de Cursor",
    settingsDetail: "Affichez, masquez et réordonnez la facturation et l’usage agrégé par écran.",
    sourceLinksLabel: "Liens sources de l’utilisation Cursor",
    usagePage: "Page d’utilisation",
    spendingPage: "Page des dépenses",
    csvAvailable: "Un export CSV est disponible sur la page d’utilisation Cursor.",
  },
  de: {
    billingSummary: "Nutzung und Abrechnung",
    recentUsage: "Letzte Nutzung",
    billingCycle: "Abrechnungszeitraum",
    planUsage: "Nutzungswert im Tarif",
    firstPartyPool: "Enthaltener Modellpool",
    apiPool: "Drittanbieter-API-Pool",
    onDemand: "Bedarfsabhängig",
    includedValue: "Enthalten",
    bonusValue: "Kostenlos / Bonus",
    actualCharge: "Tatsächliche Kosten",
    enabled: "Aktiviert",
    disabled: "Aus",
    unavailable: "Nicht verfügbar",
    stale: "Gespeicherte Daten",
    updated: "Aktualisiert",
    sevenDays: "7 Tage",
    thirtyDays: "30 Tage",
    models: "Modelle",
    usageTypes: "Nutzungsarten",
    noHistory: "Noch kein aggregierter Nutzungsverlauf verfügbar",
    expand: "Cursor-Nutzungsdetails anzeigen",
    collapse: "Cursor-Nutzungsdetails ausblenden",
    settingsDetail: "Abrechnung und aggregierte Nutzung je Ansicht einblenden und sortieren.",
    sourceLinksLabel: "Quelllinks zur Cursor-Nutzung",
    usagePage: "Nutzungsseite",
    spendingPage: "Ausgabenseite",
    csvAvailable: "Auf der Cursor-Nutzungsseite ist ein CSV-Export verfügbar.",
  },
  it: {
    billingSummary: "Utilizzo e fatturazione",
    recentUsage: "Utilizzo recente",
    billingCycle: "Periodo di fatturazione",
    planUsage: "Valore di utilizzo del piano",
    firstPartyPool: "Pool di modelli incluso",
    apiPool: "Pool API di terze parti",
    onDemand: "A consumo",
    includedValue: "Incluso",
    bonusValue: "Gratis / bonus",
    actualCharge: "Addebito effettivo",
    enabled: "Attivo",
    disabled: "Disattivato",
    unavailable: "Non disponibile",
    stale: "Dati salvati",
    updated: "Aggiornato",
    sevenDays: "7 giorni",
    thirtyDays: "30 giorni",
    models: "Modelli",
    usageTypes: "Tipi di utilizzo",
    noHistory: "Nessuna cronologia aggregata disponibile",
    expand: "Mostra i dettagli di utilizzo di Cursor",
    collapse: "Nascondi i dettagli di utilizzo di Cursor",
    settingsDetail: "Mostra, nascondi e riordina fatturazione e uso aggregato per schermata.",
    sourceLinksLabel: "Link alle fonti di utilizzo Cursor",
    usagePage: "Pagina utilizzo",
    spendingPage: "Pagina spese",
    csvAvailable: "La pagina di utilizzo Cursor consente di esportare un CSV.",
  },
  ru: {
    billingSummary: "Использование и оплата",
    recentUsage: "Недавнее использование",
    billingCycle: "Расчётный период",
    planUsage: "Стоимость использования в тарифе",
    firstPartyPool: "Пул включённых моделей",
    apiPool: "Пул сторонних API",
    onDemand: "По потреблению",
    includedValue: "Включено",
    bonusValue: "Бесплатно / бонус",
    actualCharge: "Фактические расходы",
    enabled: "Включено",
    disabled: "Выключено",
    unavailable: "Недоступно",
    stale: "Сохранённые данные",
    updated: "Обновлено",
    sevenDays: "7 дней",
    thirtyDays: "30 дней",
    models: "Модели",
    usageTypes: "Типы использования",
    noHistory: "Сводной истории использования пока нет",
    expand: "Показать сведения об использовании Cursor",
    collapse: "Скрыть сведения об использовании Cursor",
    settingsDetail: "Настройте видимость и порядок оплаты и сводного использования для каждого экрана.",
    sourceLinksLabel: "Ссылки на источники использования Cursor",
    usagePage: "Страница использования",
    spendingPage: "Страница расходов",
    csvAvailable: "На странице использования Cursor доступен экспорт CSV.",
  },
  ar: {
    billingSummary: "الاستخدام والفوترة",
    recentUsage: "الاستخدام الأخير",
    billingCycle: "دورة الفوترة",
    planUsage: "قيمة الاستخدام ضمن الخطة",
    firstPartyPool: "مجموعة النماذج المشمولة",
    apiPool: "مجموعة واجهات الطرف الثالث",
    onDemand: "حسب الاستخدام",
    includedValue: "مشمول",
    bonusValue: "مجاني / مكافأة",
    actualCharge: "التكلفة الفعلية",
    enabled: "مفعّل",
    disabled: "متوقف",
    unavailable: "غير متاح",
    stale: "بيانات محفوظة",
    updated: "آخر تحديث",
    sevenDays: "7 أيام",
    thirtyDays: "30 يومًا",
    models: "النماذج",
    usageTypes: "أنواع الاستخدام",
    noHistory: "لا يوجد سجل استخدام مجمّع بعد",
    expand: "إظهار تفاصيل استخدام Cursor",
    collapse: "إخفاء تفاصيل استخدام Cursor",
    settingsDetail: "اعرض أو أخفِ ورتّب ملخص الفوترة والاستخدام المجمّع لكل واجهة.",
    sourceLinksLabel: "روابط مصدر استخدام Cursor",
    usagePage: "صفحة الاستخدام",
    spendingPage: "صفحة الإنفاق",
    csvAvailable: "يمكن تصدير CSV من صفحة استخدام Cursor.",
  },
  hi: {
    billingSummary: "उपयोग और बिलिंग",
    recentUsage: "हाल का उपयोग",
    billingCycle: "बिलिंग अवधि",
    planUsage: "प्लान में उपयोग का मूल्य",
    firstPartyPool: "शामिल मॉडल पूल",
    apiPool: "तृतीय-पक्ष API पूल",
    onDemand: "मांग पर",
    includedValue: "शामिल",
    bonusValue: "मुफ़्त / बोनस",
    actualCharge: "वास्तविक शुल्क",
    enabled: "चालू",
    disabled: "बंद",
    unavailable: "उपलब्ध नहीं",
    stale: "सहेजा गया डेटा",
    updated: "अपडेट किया गया",
    sevenDays: "7 दिन",
    thirtyDays: "30 दिन",
    models: "मॉडल",
    usageTypes: "उपयोग के प्रकार",
    noHistory: "अभी कोई समेकित उपयोग इतिहास नहीं है",
    expand: "Cursor उपयोग विवरण दिखाएँ",
    collapse: "Cursor उपयोग विवरण छिपाएँ",
    settingsDetail: "हर स्क्रीन पर बिलिंग और समेकित उपयोग को अलग से दिखाएँ और क्रम बदलें।",
    sourceLinksLabel: "Cursor उपयोग स्रोत लिंक",
    usagePage: "उपयोग पेज",
    spendingPage: "खर्च पेज",
    csvAvailable: "Cursor उपयोग पेज से CSV निर्यात उपलब्ध है।",
  },
  id: {
    billingSummary: "Penggunaan dan penagihan",
    recentUsage: "Penggunaan terbaru",
    billingCycle: "Siklus penagihan",
    planUsage: "Nilai penggunaan paket",
    firstPartyPool: "Kumpulan model tercakup",
    apiPool: "Kumpulan API pihak ketiga",
    onDemand: "Sesuai pemakaian",
    includedValue: "Tercakup",
    bonusValue: "Gratis / bonus",
    actualCharge: "Tagihan aktual",
    enabled: "Aktif",
    disabled: "Nonaktif",
    unavailable: "Tidak tersedia",
    stale: "Data tersimpan",
    updated: "Diperbarui",
    sevenDays: "7 hari",
    thirtyDays: "30 hari",
    models: "Model",
    usageTypes: "Jenis penggunaan",
    noHistory: "Belum ada riwayat penggunaan agregat",
    expand: "Tampilkan detail penggunaan Cursor",
    collapse: "Sembunyikan detail penggunaan Cursor",
    settingsDetail: "Tampilkan, sembunyikan, dan urutkan ringkasan tagihan serta penggunaan per layar.",
    sourceLinksLabel: "Tautan sumber penggunaan Cursor",
    usagePage: "Halaman penggunaan",
    spendingPage: "Halaman pengeluaran",
    csvAvailable: "Ekspor CSV tersedia dari halaman penggunaan Cursor.",
  },
};

export function buildCursorUsageLocalizedCopy(
  locale: string,
): CursorUsageLocalizedCopy {
  return CURSOR_USAGE_COPY[locale as ResolvedAppLocale] ?? CURSOR_USAGE_COPY.en;
}
