import type { ResolvedAppLocale } from "./i18n";

export type CustomSourceCardCopy = {
  custom: string;
  openSettings: string;
  refresh: string;
  noSnapshot: string;
  sourceContract: string;
  endpoint: string;
  syncEvery: string;
  minutes: string;
  stale: string;
  summaryAriaSuffix: string;
  contextAria: string;
  remaining: string;
  used: string;
  tracked: string;
};

export const CUSTOM_SOURCE_CARD_COPY: Record<
  ResolvedAppLocale,
  CustomSourceCardCopy
> = {
  en: {
    custom: "Custom",
    openSettings: "Settings",
    refresh: "Refresh",
    noSnapshot: "No synced data yet.",
    sourceContract: "Custom JSON endpoint",
    endpoint: "Endpoint",
    syncEvery: "Sync interval",
    minutes: "min",
    stale: "Stale",
    summaryAriaSuffix: "custom source summary",
    contextAria: "Custom source context",
    remaining: "remaining",
    used: "used",
    tracked: "tracked",
  },
  "zh-CN": {
    custom: "自定义",
    openSettings: "设置",
    refresh: "刷新",
    noSnapshot: "尚未同步到可显示的数据。",
    sourceContract: "自定义 JSON 端点",
    endpoint: "端点",
    syncEvery: "同步间隔",
    minutes: "分钟",
    stale: "已过期",
    summaryAriaSuffix: "自定义来源摘要",
    contextAria: "自定义来源上下文",
    remaining: "剩余",
    used: "已用",
    tracked: "已跟踪",
  },
  "zh-TW": {
    custom: "自訂",
    openSettings: "設定",
    refresh: "重新整理",
    noSnapshot: "尚未同步到可顯示的資料。",
    sourceContract: "自訂 JSON 端點",
    endpoint: "端點",
    syncEvery: "同步間隔",
    minutes: "分鐘",
    stale: "已過期",
    summaryAriaSuffix: "自訂來源摘要",
    contextAria: "自訂來源上下文",
    remaining: "剩餘",
    used: "已用",
    tracked: "已追蹤",
  },
  ja: {
    custom: "カスタム",
    openSettings: "設定",
    refresh: "更新",
    noSnapshot: "同期済みデータはまだありません。",
    sourceContract: "カスタム JSON エンドポイント",
    endpoint: "エンドポイント",
    syncEvery: "同期間隔",
    minutes: "分",
    stale: "古い",
    summaryAriaSuffix: "カスタムソース概要",
    contextAria: "カスタムソースのコンテキスト",
    remaining: "残り",
    used: "使用済み",
    tracked: "追跡済み",
  },
  ko: {
    custom: "사용자 지정",
    openSettings: "설정",
    refresh: "새로고침",
    noSnapshot: "아직 동기화된 데이터가 없습니다.",
    sourceContract: "사용자 JSON 엔드포인트",
    endpoint: "엔드포인트",
    syncEvery: "동기화 간격",
    minutes: "분",
    stale: "오래됨",
    summaryAriaSuffix: "사용자 소스 요약",
    contextAria: "사용자 소스 컨텍스트",
    remaining: "남음",
    used: "사용됨",
    tracked: "추적됨",
  },
  "es-419": {
    custom: "Personalizado",
    openSettings: "Configuración",
    refresh: "Actualizar",
    noSnapshot: "Aún no hay datos sincronizados.",
    sourceContract: "Endpoint JSON personalizado",
    endpoint: "Endpoint",
    syncEvery: "Intervalo de sincronización",
    minutes: "min",
    stale: "Desactualizado",
    summaryAriaSuffix: "resumen de fuente personalizada",
    contextAria: "Contexto de fuente personalizada",
    remaining: "restantes",
    used: "usados",
    tracked: "registrados",
  },
  "pt-BR": {
    custom: "Personalizado",
    openSettings: "Configurações",
    refresh: "Atualizar",
    noSnapshot: "Ainda não há dados sincronizados.",
    sourceContract: "Endpoint JSON personalizado",
    endpoint: "Endpoint",
    syncEvery: "Intervalo de sincronização",
    minutes: "min",
    stale: "Desatualizado",
    summaryAriaSuffix: "resumo da fonte personalizada",
    contextAria: "Contexto da fonte personalizada",
    remaining: "restantes",
    used: "usados",
    tracked: "monitorados",
  },
  fr: {
    custom: "Personnalisé",
    openSettings: "Paramètres",
    refresh: "Actualiser",
    noSnapshot: "Aucune donnée synchronisée pour l'instant.",
    sourceContract: "Endpoint JSON personnalisé",
    endpoint: "Endpoint",
    syncEvery: "Intervalle de synchro",
    minutes: "min",
    stale: "Obsolète",
    summaryAriaSuffix: "résumé de source personnalisée",
    contextAria: "Contexte de source personnalisée",
    remaining: "restants",
    used: "utilisés",
    tracked: "suivis",
  },
  de: {
    custom: "Eigene Quelle",
    openSettings: "Einstellungen",
    refresh: "Aktualisieren",
    noSnapshot: "Noch keine synchronisierten Daten.",
    sourceContract: "Eigener JSON-Endpunkt",
    endpoint: "Endpunkt",
    syncEvery: "Sync-Intervall",
    minutes: "Min.",
    stale: "Veraltet",
    summaryAriaSuffix: "Zusammenfassung eigener Quelle",
    contextAria: "Kontext der eigenen Quelle",
    remaining: "übrig",
    used: "verwendet",
    tracked: "erfasst",
  },
  it: {
    custom: "Personalizzato",
    openSettings: "Impostazioni",
    refresh: "Aggiorna",
    noSnapshot: "Nessun dato sincronizzato.",
    sourceContract: "Endpoint JSON personalizzato",
    endpoint: "Endpoint",
    syncEvery: "Intervallo sync",
    minutes: "min",
    stale: "Obsoleto",
    summaryAriaSuffix: "riepilogo fonte personalizzata",
    contextAria: "Contesto fonte personalizzata",
    remaining: "rimanenti",
    used: "usati",
    tracked: "tracciati",
  },
  ru: {
    custom: "Своя",
    openSettings: "Настройки",
    refresh: "Обновить",
    noSnapshot: "Синхронизированных данных пока нет.",
    sourceContract: "Свой JSON-endpoint",
    endpoint: "Endpoint",
    syncEvery: "Интервал синхронизации",
    minutes: "мин",
    stale: "Устарело",
    summaryAriaSuffix: "сводка пользовательского источника",
    contextAria: "Контекст пользовательского источника",
    remaining: "осталось",
    used: "использовано",
    tracked: "отслеживается",
  },
  ar: {
    custom: "مخصص",
    openSettings: "الإعدادات",
    refresh: "تحديث",
    noSnapshot: "لا توجد بيانات متزامنة بعد.",
    sourceContract: "نقطة JSON مخصصة",
    endpoint: "Endpoint",
    syncEvery: "فاصل المزامنة",
    minutes: "د",
    stale: "قديم",
    summaryAriaSuffix: "ملخص مصدر مخصص",
    contextAria: "سياق المصدر المخصص",
    remaining: "متبقية",
    used: "مستخدمة",
    tracked: "متتبعة",
  },
  hi: {
    custom: "कस्टम",
    openSettings: "सेटिंग्स",
    refresh: "रीफ़्रेश",
    noSnapshot: "अभी कोई synced data नहीं है।",
    sourceContract: "कस्टम JSON एंडपॉइंट",
    endpoint: "एंडपॉइंट",
    syncEvery: "सिंक अंतराल",
    minutes: "मिनट",
    stale: "पुराना",
    summaryAriaSuffix: "कस्टम स्रोत सारांश",
    contextAria: "कस्टम स्रोत संदर्भ",
    remaining: "शेष",
    used: "उपयोग",
    tracked: "ट्रैक किया गया",
  },
  id: {
    custom: "Kustom",
    openSettings: "Pengaturan",
    refresh: "Segarkan",
    noSnapshot: "Belum ada data yang disinkronkan.",
    sourceContract: "Endpoint JSON kustom",
    endpoint: "Endpoint",
    syncEvery: "Interval sinkronisasi",
    minutes: "mnt",
    stale: "Kedaluwarsa",
    summaryAriaSuffix: "ringkasan sumber kustom",
    contextAria: "Konteks sumber kustom",
    remaining: "tersisa",
    used: "terpakai",
    tracked: "terpantau",
  },
};

export function getCustomSourceCardCopy(
  locale: ResolvedAppLocale,
): CustomSourceCardCopy {
  return CUSTOM_SOURCE_CARD_COPY[locale];
}
