// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 David-Lzy (https://github.com/David-Lzy). All rights reserved.
// Source: https://github.com/David-Lzy/AI_Usage_Dashboard

// Synthetic snapshots for tests and explicitly requested screenshot presets only.
import type { AppState } from "../providers/types";
import {
  createCredentialDiagnostic,
  createPageSessionDiagnostic,
  createPolicyOnlyDiagnostic,
  createSourceSelectionDiagnostic,
  createUsageThresholdDiagnostic,
} from "../providers/diagnostics";
import { createDefaultAppState, createEmptyProviderSecrets } from "./production-state";

export const SAMPLE_PROVIDER_SECRETS = createEmptyProviderSecrets();
const defaults = createDefaultAppState();
export const SAMPLE_APP_STATE: AppState = {
  ...defaults,
  providers: [
    {
      providerId: "cursor-personal-page",
      providerLabel: "Cursor Personal",
      planName: "Cursor Personal Dashboard",
      quotaUnit: "requests",
      quotaWindow: "monthly",
      used: null,
      remaining: null,
      total: null,
      resetAt: "Mar 23 - Apr 21",
      resetLabel: "Your usage per day across this billing period",
      syncedAt: "2026-04-20 10:42",
      syncSource: "page_parse",
      syncStatus: "ok",
      warningReason: "On-demand usage is off.",
      warningDiagnostic: createUsageThresholdDiagnostic({
        providerId: "cursor-personal-page",
        usageThresholdKind: "on_demand_off",
        rawMessage: "On-demand usage is off.",
        unitLabel: "requests",
      }),
      lastSyncLabel: "Synced 2m ago",
      sourceSelectionReason: "Session page selected.",
      sourceSelectionDiagnostic: createSourceSelectionDiagnostic({
        providerId: "cursor-personal-page",
        sourcePreference: "session_page",
        selectedKind: "session_page",
        hadFallback: false,
        rawMessage: "Session page selected.",
      }),
      sourceFallbackReason: null,
      usageFacts: [
        {
          label: "Billing period",
          value: "Mar 23 - Apr 21",
          detail: "Your usage per day across this billing period",
        },
        {
          label: "Total spend",
          value: "$0",
          detail: "Current selected period",
        },
        {
          label: "Included",
          value: "$0",
          detail: "Plan-included spend shown by Cursor",
        },
        {
          label: "On-demand",
          value: "$0",
          detail: "Usage-based spend shown by Cursor",
        },
      ],
      tone: "neutral",
    },
    {
      providerId: "cursor-team-api",
      providerLabel: "Cursor Team API",
      planName: "Cursor Team Admin API",
      quotaUnit: "requests",
      quotaWindow: "monthly",
      used: null,
      remaining: null,
      total: null,
      resetAt: "Admin API key required",
      resetLabel: "Add a Cursor Admin API key to sync team analytics.",
      syncedAt: "2026-04-20 10:42",
      syncSource: "official",
      syncStatus: "warning",
      warningReason: "Cursor Admin API key is missing.",
      warningDiagnostic: createCredentialDiagnostic({
        providerId: "cursor-team-api",
        credentialKind: "admin_api_key",
        rawMessage: "Cursor Admin API key is missing.",
      }),
      lastSyncLabel: "Credentials needed",
      sourceSelectionReason: "Official API selected.",
      sourceSelectionDiagnostic: createSourceSelectionDiagnostic({
        providerId: "cursor-team-api",
        sourcePreference: "official_api",
        selectedKind: "official_api",
        hadFallback: false,
        rawMessage: "Official API selected.",
      }),
      sourceFallbackReason: null,
      usageFacts: [
        {
          label: "Credential",
          value: "Missing",
          detail: "Store a Cursor Admin API key before team analytics can sync.",
          tone: "warning",
        },
      ],
      tone: "warning",
    },
    {
      providerId: "jetbrains-org-page",
      providerLabel: "JetBrains AI",
      planName: "Deferred organization source",
      quotaUnit: "credits",
      quotaWindow: "monthly",
      used: null,
      remaining: null,
      total: null,
      resetAt: "Unavailable while deferred",
      resetLabel: "No live quota is claimed by this deferred source",
      syncedAt: "2026-04-20 10:40",
      syncSource: "page_parse",
      syncStatus: "warning",
      warningReason:
        "JetBrains organization usage remains deferred until a real organization-visible Users and licensing session is reverified.",
      warningDiagnostic: null,
      lastSyncLabel: "JetBrains integration remains deferred",
      sourceSelectionReason:
        "JetBrains session-page parsing is retained for future verification, but no live source is active in this release.",
      sourceFallbackReason: null,
      tone: "warning",
    },
    {
      providerId: "claude-code-team-page",
      providerLabel: "Claude Personal",
      planName: "Claude personal usage page",
      quotaUnit: "percent",
      quotaWindow: "daily",
      used: null,
      remaining: null,
      total: null,
      resetAt: "Visible personal usage windows",
      resetLabel: "Open the logged-in Claude usage page to refresh visible windows.",
      syncedAt: "2026-04-20 10:08",
      syncSource: "page_parse",
      syncStatus: "warning",
      warningReason: "Claude personal usage page has not been attached in this profile.",
      warningDiagnostic: createPageSessionDiagnostic({
        providerId: "claude-code-team-page",
        pageSessionKind: "open_page_required",
        rawMessage: "Claude personal usage page has not been attached in this profile.",
      }),
      lastSyncLabel: "Usage page needed",
      sourceSelectionReason: "Session page selected.",
      sourceSelectionDiagnostic: createSourceSelectionDiagnostic({
        providerId: "claude-code-team-page",
        sourcePreference: "session_page",
        selectedKind: "session_page",
        hadFallback: false,
        rawMessage: "Session page selected.",
      }),
      sourceFallbackReason: null,
      tone: "warning",
    },
    {
      providerId: "claude-code-admin-api",
      providerLabel: "Claude Admin API",
      planName: "Analytics Admin API",
      quotaUnit: "sessions",
      quotaWindow: "daily",
      used: 5,
      remaining: null,
      total: null,
      resetAt: "2026-04-21 00:00 UTC",
      resetLabel: "Daily analytics snapshot; exact remaining quota unavailable",
      syncedAt: "2026-04-20 10:08",
      syncSource: "official",
      syncStatus: "warning",
      warningReason:
        "Analytics source does not expose exact remaining Claude Code quota",
      lastSyncLabel: "Analytics snapshot 34m ago",
      sourceSelectionReason:
        "Official API is the only shipped live source for Claude Code.",
      sourceFallbackReason: null,
      tone: "warning",
    },
    {
      providerId: "gemini-policy",
      providerLabel: "Gemini Code Assist",
      planName: "Gemini Code Assist Enterprise (documented policy)",
      quotaUnit: "requests",
      quotaWindow: "daily",
      used: null,
      remaining: null,
      total: 2000,
      resetAt: "Daily per-user quota window",
      resetLabel:
        "Documented quota only; check Google Cloud Quotas for live project usage",
      syncedAt: "2026-04-20 10:12",
      syncSource: "official",
      syncStatus: "warning",
      warningReason:
        "120/min and 2000/day per user for Gemini CLI and agent mode. No stable official per-user live usage source is documented.",
      warningDiagnostic: createPolicyOnlyDiagnostic({
        providerId: "gemini-policy",
        policyOnlyKind: "documented_limit_only",
        rawMessage:
          "120/min and 2000/day per user for Gemini CLI and agent mode. No stable official per-user live usage source is documented.",
      }),
      lastSyncLabel: "Documented quota snapshot 30m ago",
      sourceSelectionReason:
        "Policy only is the only shipped source for Gemini Code Assist.",
      sourceFallbackReason: null,
      tone: "warning",
    },
    {
      providerId: "codex-personal-page",
      providerLabel: "Codex Personal",
      planName: "Codex personal usage pages",
      quotaUnit: "percent",
      quotaWindow: "rolling",
      used: 25,
      remaining: 75,
      total: 100,
      resetAt: "2026-04-20 15:55",
      resetLabel: "5-hour usage window resets at 15:55",
      syncedAt: "2026-04-20 10:18",
      syncSource: "page_parse",
      syncStatus: "ok",
      warningReason: null,
      lastSyncLabel: "Usage page snapshot 24m ago",
      sourceSelectionReason: "Session page selected.",
      sourceSelectionDiagnostic: createSourceSelectionDiagnostic({
        providerId: "codex-personal-page",
        sourcePreference: "session_page",
        selectedKind: "session_page",
        hadFallback: false,
        rawMessage: "Session page selected.",
      }),
      sourceFallbackReason: null,
      usageWindows: [
        {
          label: "5-hour usage window",
          normalizedLabel: "5-hour usage window",
          kind: "rolling_5h",
          modelLabel: null,
          quotaUnit: "percent",
          used: 25,
          remaining: 75,
          total: 100,
          resetAt: "2026-04-20 15:55",
          resetLabel: "Resets at 15:55",
        },
        {
          label: "Weekly usage window",
          normalizedLabel: "Weekly usage window",
          kind: "weekly",
          modelLabel: null,
          quotaUnit: "percent",
          used: 59,
          remaining: 41,
          total: 100,
          resetAt: "2026-04-21 09:15",
          resetLabel: "Resets Apr 21 09:15",
        },
      ],
      tone: "neutral",
    },
    {
      providerId: "codex-enterprise-api",
      providerLabel: "Codex Enterprise API",
      planName: "Codex Analytics API (Enterprise workspace)",
      quotaUnit: "credits",
      quotaWindow: "daily",
      used: null,
      remaining: null,
      total: null,
      resetAt: "Previous UTC day analytics window",
      resetLabel:
        "Daily analytics snapshot; remaining workspace credits are checked in Settings > Billing",
      syncedAt: "2026-04-20 10:18",
      syncSource: "official",
      syncStatus: "warning",
      warningReason:
        "Enterprise analytics API selected. Exact remaining workspace credits are not exposed by the analytics endpoint.",
      lastSyncLabel: "Analytics snapshot 24m ago",
      sourceSelectionReason: "Official API selected.",
      sourceSelectionDiagnostic: createSourceSelectionDiagnostic({
        providerId: "codex-enterprise-api",
        sourcePreference: "official_api",
        selectedKind: "official_api",
        hadFallback: false,
        rawMessage: "Official API selected.",
      }),
      sourceFallbackReason: null,
      tone: "warning",
    },
    {
      providerId: "sub2api-api-key",
      providerLabel: "Sub2API",
      planName: "Sub2API API-key usage",
      quotaUnit: "credits",
      quotaWindow: "daily",
      used: null,
      remaining: null,
      total: null,
      resetAt: "Not configured",
      resetLabel: "Connect a deployment and API key in Settings",
      syncedAt: "Not synced",
      syncSource: "official",
      syncStatus: "warning",
      warningReason: "Sub2API deployment and API key are not configured.",
      warningDiagnostic: createCredentialDiagnostic({
        providerId: "sub2api-api-key",
        credentialKind: "admin_api_key",
        rawMessage: "Sub2API deployment and API key are not configured.",
      }),
      lastSyncLabel: "Not connected",
      sourceSelectionReason: "Official API selected.",
      sourceFallbackReason: null,
      tone: "warning",
    },
  ],
  providerSettings: defaults.providerSettings.map((setting) => ({
    ...setting,
    status: setting.id === "jetbrains-org-page" || setting.id === "sub2api-api-key"
      ? "missing" : "granted",
  })),
};
