import type { ResolvedAppLocale } from "./i18n";
import type {
  LocalCompanionSettingsFailure,
  LocalCompanionSettingsStatus,
} from "./local-companion-settings";
import type { SyncStatus } from "../providers/types";

export type LocalCompanionLocalizedCopy = {
  eyebrow: string;
  title: string;
  detail: string;
  baseUrl: string;
  pairingCode: string;
  pair: string;
  refreshIndex: string;
  refreshSource: string;
  removeSource: string;
  disconnect: string;
  source: string;
  noSources: string;
  managedState: string;
  captured: string;
  stale: string;
  unavailable: string;
  working: string;
  statuses: Record<LocalCompanionSettingsStatus, string>;
  managedStatuses: Record<SyncStatus, string>;
  failures: Record<LocalCompanionSettingsFailure, string>;
};

type LocalCompanionLocalizedCopyBase = Omit<
  LocalCompanionLocalizedCopy,
  "managedStatuses"
>;

const COPY: Record<ResolvedAppLocale, LocalCompanionLocalizedCopyBase> = {
  en: {
    eyebrow: "Local developer bridge",
    title: "Local Companion",
    detail:
      "Pair with a loopback companion to manage sanitized local source rows.",
    baseUrl: "Loopback URL",
    pairingCode: "Pairing code",
    pair: "Pair",
    refreshIndex: "Refresh index",
    refreshSource: "Refresh source",
    removeSource: "Remove saved source",
    disconnect: "Disconnect",
    source: "Source",
    noSources: "No companion sources are available.",
    managedState: "Managed state",
    captured: "Captured",
    stale: "Stale",
    unavailable: "Unavailable",
    working: "Working...",
    statuses: {
      disconnected: "Disconnected",
      connected: "Connected",
      expired: "Expired",
      unavailable: "Unavailable",
    },
    failures: {
      invalid_base_url: "Use a valid loopback URL.",
      invalid_pairing_code: "Use a valid pairing code.",
      invalid_token: "Pairing was not accepted.",
      unavailable: "The local companion is unavailable.",
      timeout: "The local companion timed out.",
      unauthorized: "Pairing is no longer authorized.",
      rate_limited: "Try again later.",
      http_error: "The local companion could not complete the request.",
      response_too_large: "The local companion response was rejected.",
      invalid_response: "The local companion response was invalid.",
      permission_required: "Loopback access permission is required.",
      developer_required: "Developer access is required.",
      source_missing: "That source is no longer available.",
      conflict: "The local companion state changed. Refresh the index.",
      superseded: "This request was superseded.",
    },
  },
  "zh-CN": {
    eyebrow: "本地开发者桥接",
    title: "本地伴侣",
    detail: "与 loopback 本地伴侣配对以管理经过清理的本地来源行。",
    baseUrl: "Loopback URL",
    pairingCode: "配对代码",
    pair: "配对",
    refreshIndex: "刷新索引",
    refreshSource: "刷新来源",
    removeSource: "移除已保存的来源",
    disconnect: "断开连接",
    source: "来源",
    noSources: "没有可用的伴侣来源。",
    managedState: "受管状态",
    captured: "采集时间",
    stale: "已过期",
    unavailable: "不可用",
    working: "处理中...",
    statuses: {
      disconnected: "未连接",
      connected: "已连接",
      expired: "已过期",
      unavailable: "不可用",
    },
    failures: {
      invalid_base_url: "请使用有效的 loopback URL。",
      invalid_pairing_code: "请使用有效的配对代码。",
      invalid_token: "配对未被接受。",
      unavailable: "本地伴侣不可用。",
      timeout: "本地伴侣超时。",
      unauthorized: "配对不再获得授权。",
      rate_limited: "请稍后重试。",
      http_error: "本地伴侣无法完成请求。",
      response_too_large: "本地伴侣响应被拒绝。",
      invalid_response: "本地伴侣响应无效。",
      permission_required: "需要 loopback 访问权限。",
      developer_required: "需要开发者访问权限。",
      source_missing: "该来源已不可用。",
      conflict: "本地伴侣状态已更改，请刷新索引。",
      superseded: "该请求已被替代。",
    },
  },
  "zh-TW": {
    eyebrow: "本機開發者橋接",
    title: "本機伴侶",
    detail: "與 loopback 本機伴侶配對以管理已清理的本機來源列。",
    baseUrl: "Loopback URL",
    pairingCode: "配對代碼",
    pair: "配對",
    refreshIndex: "重新整理索引",
    refreshSource: "重新整理來源",
    removeSource: "移除已儲存的來源",
    disconnect: "中斷連線",
    source: "來源",
    noSources: "沒有可用的伴侶來源。",
    managedState: "受管狀態",
    captured: "擷取時間",
    stale: "已過期",
    unavailable: "無法使用",
    working: "處理中...",
    statuses: {
      disconnected: "未連線",
      connected: "已連線",
      expired: "已過期",
      unavailable: "無法使用",
    },
    failures: {
      invalid_base_url: "請使用有效的 loopback URL。",
      invalid_pairing_code: "請使用有效的配對代碼。",
      invalid_token: "配對未被接受。",
      unavailable: "本機伴侶無法使用。",
      timeout: "本機伴侶逾時。",
      unauthorized: "配對不再獲得授權。",
      rate_limited: "請稍後再試。",
      http_error: "本機伴侶無法完成要求。",
      response_too_large: "本機伴侶回應被拒絕。",
      invalid_response: "本機伴侶回應無效。",
      permission_required: "需要 loopback 存取權。",
      developer_required: "需要開發者存取權。",
      source_missing: "該來源已不可用。",
      conflict: "本機伴侶狀態已變更，請重新整理索引。",
      superseded: "此要求已被取代。",
    },
  },
  ja: {
    eyebrow: "ローカル開発者ブリッジ",
    title: "ローカルコンパニオン",
    detail:
      "ループバックのローカルコンパニオンとペアリングして、サニタイズ済みローカルソース行を管理します。",
    baseUrl: "ループバック URL",
    pairingCode: "ペアリングコード",
    pair: "ペアリング",
    refreshIndex: "インデックスを更新",
    refreshSource: "ソースを更新",
    removeSource: "保存済みのソースを削除",
    disconnect: "切断",
    source: "ソース",
    noSources: "利用可能なコンパニオンソースはありません。",
    managedState: "管理状態",
    captured: "取得日時",
    stale: "古い",
    unavailable: "利用不可",
    working: "処理中...",
    statuses: {
      disconnected: "未接続",
      connected: "接続済み",
      expired: "期限切れ",
      unavailable: "利用不可",
    },
    failures: {
      invalid_base_url: "有効なループバック URL を使用してください。",
      invalid_pairing_code: "有効なペアリングコードを使用してください。",
      invalid_token: "ペアリングは承認されませんでした。",
      unavailable: "ローカルコンパニオンは利用できません。",
      timeout: "ローカルコンパニオンがタイムアウトしました。",
      unauthorized: "ペアリングの認証が失効しました。",
      rate_limited: "後でもう一度お試しください。",
      http_error: "ローカルコンパニオンは要求を完了できません。",
      response_too_large: "ローカルコンパニオンの応答は拒否されました。",
      invalid_response: "ローカルコンパニオンの応答が無効です。",
      permission_required: "ループバックアクセス権が必要です。",
      developer_required: "開発者アクセスが必要です。",
      source_missing: "そのソースは利用できなくなりました。",
      conflict:
        "ローカルコンパニオンの状態が変わりました。インデックスを更新してください。",
      superseded: "この要求は置き換えられました。",
    },
  },
  ko: {
    eyebrow: "로컬 개발자 브리지",
    title: "로컬 컴패니언",
    detail:
      "루프백 로컬 컴패니언과 페어링하여 정리된 로컬 소스 행을 관리합니다.",
    baseUrl: "루프백 URL",
    pairingCode: "페어링 코드",
    pair: "페어링",
    refreshIndex: "색인 새로 고침",
    refreshSource: "소스 새로 고침",
    removeSource: "저장된 소스 제거",
    disconnect: "연결 해제",
    source: "소스",
    noSources: "사용 가능한 컴패니언 소스가 없습니다.",
    managedState: "관리 상태",
    captured: "캡처됨",
    stale: "오래됨",
    unavailable: "사용할 수 없음",
    working: "처리 중...",
    statuses: {
      disconnected: "연결 안 됨",
      connected: "연결됨",
      expired: "만료됨",
      unavailable: "사용할 수 없음",
    },
    failures: {
      invalid_base_url: "유효한 루프백 URL을 사용하세요.",
      invalid_pairing_code: "유효한 페어링 코드를 사용하세요.",
      invalid_token: "페어링이 승인되지 않았습니다.",
      unavailable: "로컬 컴패니언을 사용할 수 없습니다.",
      timeout: "로컬 컴패니언 시간이 초과되었습니다.",
      unauthorized: "페어링 인증이 만료되었습니다.",
      rate_limited: "나중에 다시 시도하세요.",
      http_error: "로컬 컴패니언이 요청을 완료하지 못했습니다.",
      response_too_large: "로컬 컴패니언 응답이 거부되었습니다.",
      invalid_response: "로컬 컴패니언 응답이 올바르지 않습니다.",
      permission_required: "루프백 액세스 권한이 필요합니다.",
      developer_required: "개발자 액세스가 필요합니다.",
      source_missing: "해당 소스를 더 이상 사용할 수 없습니다.",
      conflict: "로컬 컴패니언 상태가 변경되었습니다. 색인을 새로 고치세요.",
      superseded: "이 요청은 대체되었습니다.",
    },
  },
  "es-419": {
    eyebrow: "Puente local para desarrolladores",
    title: "Compañero local",
    detail:
      "Empareja un compañero local de loopback para administrar filas de origen locales saneadas.",
    baseUrl: "URL de loopback",
    pairingCode: "Código de emparejamiento",
    pair: "Emparejar",
    refreshIndex: "Actualizar índice",
    refreshSource: "Actualizar origen",
    removeSource: "Quitar origen guardado",
    disconnect: "Desconectar",
    source: "Origen",
    noSources: "No hay orígenes de compañero disponibles.",
    managedState: "Estado administrado",
    captured: "Capturado",
    stale: "Desactualizado",
    unavailable: "No disponible",
    working: "Procesando...",
    statuses: {
      disconnected: "Desconectado",
      connected: "Conectado",
      expired: "Vencido",
      unavailable: "No disponible",
    },
    failures: {
      invalid_base_url: "Usa una URL de loopback válida.",
      invalid_pairing_code: "Usa un código de emparejamiento válido.",
      invalid_token: "No se aceptó el emparejamiento.",
      unavailable: "El compañero local no está disponible.",
      timeout: "El compañero local agotó el tiempo.",
      unauthorized: "El emparejamiento ya no está autorizado.",
      rate_limited: "Inténtalo más tarde.",
      http_error: "El compañero local no pudo completar la solicitud.",
      response_too_large: "Se rechazó la respuesta del compañero local.",
      invalid_response: "La respuesta del compañero local no es válida.",
      permission_required: "Se requiere permiso de loopback.",
      developer_required: "Se requiere acceso de desarrollador.",
      source_missing: "Ese origen ya no está disponible.",
      conflict: "El estado del compañero local cambió. Actualiza el índice.",
      superseded: "Esta solicitud fue reemplazada.",
    },
  },
  "pt-BR": {
    eyebrow: "Ponte local para desenvolvedores",
    title: "Companheiro local",
    detail:
      "Emparelhe um companheiro local de loopback para gerenciar linhas de origem locais saneadas.",
    baseUrl: "URL de loopback",
    pairingCode: "Código de pareamento",
    pair: "Parear",
    refreshIndex: "Atualizar índice",
    refreshSource: "Atualizar origem",
    removeSource: "Remover origem salva",
    disconnect: "Desconectar",
    source: "Origem",
    noSources: "Não há origens de companheiro disponíveis.",
    managedState: "Estado gerenciado",
    captured: "Capturado",
    stale: "Desatualizado",
    unavailable: "Indisponível",
    working: "Processando...",
    statuses: {
      disconnected: "Desconectado",
      connected: "Conectado",
      expired: "Expirado",
      unavailable: "Indisponível",
    },
    failures: {
      invalid_base_url: "Use uma URL de loopback válida.",
      invalid_pairing_code: "Use um código de pareamento válido.",
      invalid_token: "O pareamento não foi aceito.",
      unavailable: "O companheiro local está indisponível.",
      timeout: "O companheiro local expirou.",
      unauthorized: "O pareamento não está mais autorizado.",
      rate_limited: "Tente novamente mais tarde.",
      http_error: "O companheiro local não concluiu a solicitação.",
      response_too_large: "A resposta do companheiro local foi rejeitada.",
      invalid_response: "A resposta do companheiro local é inválida.",
      permission_required: "É necessária permissão de loopback.",
      developer_required: "É necessário acesso de desenvolvedor.",
      source_missing: "Essa origem não está mais disponível.",
      conflict: "O estado do companheiro local mudou. Atualize o índice.",
      superseded: "Esta solicitação foi substituída.",
    },
  },
  fr: {
    eyebrow: "Pont local développeur",
    title: "Compagnon local",
    detail:
      "Associez un compagnon local de bouclage pour gérer les lignes de source locale nettoyées.",
    baseUrl: "URL de bouclage",
    pairingCode: "Code d'association",
    pair: "Associer",
    refreshIndex: "Actualiser l'index",
    refreshSource: "Actualiser la source",
    removeSource: "Supprimer la source enregistrée",
    disconnect: "Déconnecter",
    source: "Source",
    noSources: "Aucune source compagnon n'est disponible.",
    managedState: "État géré",
    captured: "Capturé",
    stale: "Obsolète",
    unavailable: "Indisponible",
    working: "Traitement...",
    statuses: {
      disconnected: "Déconnecté",
      connected: "Connecté",
      expired: "Expiré",
      unavailable: "Indisponible",
    },
    failures: {
      invalid_base_url: "Utilisez une URL de bouclage valide.",
      invalid_pairing_code: "Utilisez un code d'association valide.",
      invalid_token: "L'association n'a pas été acceptée.",
      unavailable: "Le compagnon local est indisponible.",
      timeout: "Le compagnon local a expiré.",
      unauthorized: "L'association n'est plus autorisée.",
      rate_limited: "Réessayez plus tard.",
      http_error: "Le compagnon local n'a pas pu terminer la demande.",
      response_too_large: "La réponse du compagnon local a été refusée.",
      invalid_response: "La réponse du compagnon local n'est pas valide.",
      permission_required: "L'accès au bouclage est requis.",
      developer_required: "L'accès développeur est requis.",
      source_missing: "Cette source n'est plus disponible.",
      conflict: "L'état du compagnon local a changé. Actualisez l'index.",
      superseded: "Cette demande a été remplacée.",
    },
  },
  de: {
    eyebrow: "Lokale Entwicklerbrücke",
    title: "Lokaler Begleiter",
    detail:
      "Koppeln Sie einen lokalen Loopback-Begleiter, um bereinigte lokale Quellzeilen zu verwalten.",
    baseUrl: "Loopback-URL",
    pairingCode: "Kopplungscode",
    pair: "Koppeln",
    refreshIndex: "Index aktualisieren",
    refreshSource: "Quelle aktualisieren",
    removeSource: "Gespeicherte Quelle entfernen",
    disconnect: "Trennen",
    source: "Quelle",
    noSources: "Keine Begleiterquellen verfügbar.",
    managedState: "Verwalteter Status",
    captured: "Erfasst",
    stale: "Veraltet",
    unavailable: "Nicht verfügbar",
    working: "Wird verarbeitet...",
    statuses: {
      disconnected: "Getrennt",
      connected: "Verbunden",
      expired: "Abgelaufen",
      unavailable: "Nicht verfügbar",
    },
    failures: {
      invalid_base_url: "Verwenden Sie eine gültige Loopback-URL.",
      invalid_pairing_code: "Verwenden Sie einen gültigen Kopplungscode.",
      invalid_token: "Die Kopplung wurde nicht akzeptiert.",
      unavailable: "Der lokale Begleiter ist nicht verfügbar.",
      timeout: "Zeitüberschreitung beim lokalen Begleiter.",
      unauthorized: "Die Kopplung ist nicht mehr autorisiert.",
      rate_limited: "Versuchen Sie es später erneut.",
      http_error: "Der lokale Begleiter konnte die Anfrage nicht abschließen.",
      response_too_large: "Die Antwort des lokalen Begleiters wurde abgelehnt.",
      invalid_response: "Die Antwort des lokalen Begleiters ist ungültig.",
      permission_required: "Loopback-Zugriff ist erforderlich.",
      developer_required: "Entwicklerzugriff ist erforderlich.",
      source_missing: "Diese Quelle ist nicht mehr verfügbar.",
      conflict:
        "Der Zustand des lokalen Begleiters hat sich geändert. Aktualisieren Sie den Index.",
      superseded: "Diese Anfrage wurde ersetzt.",
    },
  },
  it: {
    eyebrow: "Bridge locale per sviluppatori",
    title: "Compagno locale",
    detail:
      "Associa un compagno locale di loopback per gestire righe di origine locale sanificate.",
    baseUrl: "URL di loopback",
    pairingCode: "Codice di associazione",
    pair: "Associa",
    refreshIndex: "Aggiorna indice",
    refreshSource: "Aggiorna origine",
    removeSource: "Rimuovi origine salvata",
    disconnect: "Disconnetti",
    source: "Origine",
    noSources: "Non sono disponibili origini del compagno.",
    managedState: "Stato gestito",
    captured: "Acquisito",
    stale: "Non aggiornato",
    unavailable: "Non disponibile",
    working: "Elaborazione...",
    statuses: {
      disconnected: "Disconnesso",
      connected: "Connesso",
      expired: "Scaduto",
      unavailable: "Non disponibile",
    },
    failures: {
      invalid_base_url: "Usa un URL di loopback valido.",
      invalid_pairing_code: "Usa un codice di associazione valido.",
      invalid_token: "L'associazione non è stata accettata.",
      unavailable: "Il compagno locale non è disponibile.",
      timeout: "Il compagno locale ha superato il tempo limite.",
      unauthorized: "L'associazione non è più autorizzata.",
      rate_limited: "Riprova più tardi.",
      http_error: "Il compagno locale non ha completato la richiesta.",
      response_too_large: "La risposta del compagno locale è stata rifiutata.",
      invalid_response: "La risposta del compagno locale non è valida.",
      permission_required: "È richiesta l'autorizzazione loopback.",
      developer_required: "È richiesto l'accesso sviluppatore.",
      source_missing: "Questa origine non è più disponibile.",
      conflict: "Lo stato del compagno locale è cambiato. Aggiorna l'indice.",
      superseded: "Questa richiesta è stata sostituita.",
    },
  },
  ru: {
    eyebrow: "Локальный мост разработчика",
    title: "Локальный помощник",
    detail:
      "Подключите локальный loopback-помощник для управления очищенными строками локальных источников.",
    baseUrl: "URL loopback",
    pairingCode: "Код подключения",
    pair: "Подключить",
    refreshIndex: "Обновить индекс",
    refreshSource: "Обновить источник",
    removeSource: "Удалить сохраненный источник",
    disconnect: "Отключить",
    source: "Источник",
    noSources: "Нет доступных источников помощника.",
    managedState: "Управляемое состояние",
    captured: "Получено",
    stale: "Устарело",
    unavailable: "Недоступно",
    working: "Обработка...",
    statuses: {
      disconnected: "Отключено",
      connected: "Подключено",
      expired: "Истекло",
      unavailable: "Недоступно",
    },
    failures: {
      invalid_base_url: "Используйте допустимый URL loopback.",
      invalid_pairing_code: "Используйте допустимый код подключения.",
      invalid_token: "Подключение не принято.",
      unavailable: "Локальный помощник недоступен.",
      timeout: "Истекло время ожидания локального помощника.",
      unauthorized: "Подключение больше не авторизовано.",
      rate_limited: "Повторите попытку позже.",
      http_error: "Локальный помощник не завершил запрос.",
      response_too_large: "Ответ локального помощника отклонен.",
      invalid_response: "Ответ локального помощника недействителен.",
      permission_required: "Требуется доступ loopback.",
      developer_required: "Требуется доступ разработчика.",
      source_missing: "Этот источник больше недоступен.",
      conflict: "Состояние локального помощника изменилось. Обновите индекс.",
      superseded: "Этот запрос заменен.",
    },
  },
  ar: {
    eyebrow: "جسر المطور المحلي",
    title: "المرافق المحلي",
    detail: "اقرن مرافق loopback محليًا لإدارة صفوف المصدر المحلية المنقحة.",
    baseUrl: "عنوان URL للـ loopback",
    pairingCode: "رمز الاقتران",
    pair: "اقتران",
    refreshIndex: "تحديث الفهرس",
    refreshSource: "تحديث المصدر",
    removeSource: "إزالة المصدر المحفوظ",
    disconnect: "قطع الاتصال",
    source: "المصدر",
    noSources: "لا توجد مصادر مرافق متاحة.",
    managedState: "الحالة المدارة",
    captured: "وقت الالتقاط",
    stale: "قديم",
    unavailable: "غير متاح",
    working: "جارٍ العمل...",
    statuses: {
      disconnected: "غير متصل",
      connected: "متصل",
      expired: "منتهي",
      unavailable: "غير متاح",
    },
    failures: {
      invalid_base_url: "استخدم عنوان URL صالحًا للـ loopback.",
      invalid_pairing_code: "استخدم رمز اقتران صالحًا.",
      invalid_token: "لم يُقبل الاقتران.",
      unavailable: "المرافق المحلي غير متاح.",
      timeout: "انتهت مهلة المرافق المحلي.",
      unauthorized: "لم يعد الاقتران مخولًا.",
      rate_limited: "حاول مرة أخرى لاحقًا.",
      http_error: "لم يتمكن المرافق المحلي من إكمال الطلب.",
      response_too_large: "رُفض رد المرافق المحلي.",
      invalid_response: "رد المرافق المحلي غير صالح.",
      permission_required: "يلزم إذن loopback.",
      developer_required: "يلزم وصول المطور.",
      source_missing: "لم يعد هذا المصدر متاحًا.",
      conflict: "تغيرت حالة المرافق المحلي. حدّث الفهرس.",
      superseded: "تم استبدال هذا الطلب.",
    },
  },
  hi: {
    eyebrow: "स्थानीय डेवलपर ब्रिज",
    title: "स्थानीय साथी",
    detail:
      "साफ की गई स्थानीय स्रोत पंक्तियों को प्रबंधित करने के लिए loopback स्थानीय साथी को पेयर करें।",
    baseUrl: "Loopback URL",
    pairingCode: "पेयरिंग कोड",
    pair: "पेयर करें",
    refreshIndex: "सूचकांक रीफ़्रेश करें",
    refreshSource: "स्रोत रीफ़्रेश करें",
    removeSource: "सहेजा गया स्रोत हटाएं",
    disconnect: "डिस्कनेक्ट करें",
    source: "स्रोत",
    noSources: "कोई साथी स्रोत उपलब्ध नहीं है।",
    managedState: "प्रबंधित स्थिति",
    captured: "कैप्चर किया गया",
    stale: "पुराना",
    unavailable: "अनुपलब्ध",
    working: "प्रक्रिया जारी है...",
    statuses: {
      disconnected: "डिस्कनेक्ट",
      connected: "कनेक्टेड",
      expired: "समाप्त",
      unavailable: "अनुपलब्ध",
    },
    failures: {
      invalid_base_url: "मान्य loopback URL का उपयोग करें।",
      invalid_pairing_code: "मान्य पेयरिंग कोड का उपयोग करें।",
      invalid_token: "पेयरिंग स्वीकार नहीं हुई।",
      unavailable: "स्थानीय साथी उपलब्ध नहीं है।",
      timeout: "स्थानीय साथी का समय समाप्त हो गया।",
      unauthorized: "पेयरिंग अब अधिकृत नहीं है।",
      rate_limited: "बाद में फिर से प्रयास करें।",
      http_error: "स्थानीय साथी अनुरोध पूरा नहीं कर सका।",
      response_too_large: "स्थानीय साथी प्रतिक्रिया अस्वीकृत हुई।",
      invalid_response: "स्थानीय साथी प्रतिक्रिया अमान्य है।",
      permission_required: "Loopback अनुमति आवश्यक है।",
      developer_required: "डेवलपर पहुंच आवश्यक है।",
      source_missing: "वह स्रोत अब उपलब्ध नहीं है।",
      conflict: "स्थानीय साथी स्थिति बदल गई। सूचकांक रीफ़्रेश करें।",
      superseded: "यह अनुरोध बदला गया था।",
    },
  },
  id: {
    eyebrow: "Jembatan pengembang lokal",
    title: "Pendamping lokal",
    detail:
      "Pasangkan pendamping loopback lokal untuk mengelola baris sumber lokal yang telah dibersihkan.",
    baseUrl: "URL loopback",
    pairingCode: "Kode pemasangan",
    pair: "Pasangkan",
    refreshIndex: "Segarkan indeks",
    refreshSource: "Segarkan sumber",
    removeSource: "Hapus sumber tersimpan",
    disconnect: "Putuskan",
    source: "Sumber",
    noSources: "Tidak ada sumber pendamping yang tersedia.",
    managedState: "Status terkelola",
    captured: "Diambil",
    stale: "Kedaluwarsa",
    unavailable: "Tidak tersedia",
    working: "Memproses...",
    statuses: {
      disconnected: "Terputus",
      connected: "Terhubung",
      expired: "Kedaluwarsa",
      unavailable: "Tidak tersedia",
    },
    failures: {
      invalid_base_url: "Gunakan URL loopback yang valid.",
      invalid_pairing_code: "Gunakan kode pemasangan yang valid.",
      invalid_token: "Pemasangan tidak diterima.",
      unavailable: "Pendamping lokal tidak tersedia.",
      timeout: "Waktu pendamping lokal habis.",
      unauthorized: "Pemasangan tidak lagi diizinkan.",
      rate_limited: "Coba lagi nanti.",
      http_error: "Pendamping lokal tidak dapat menyelesaikan permintaan.",
      response_too_large: "Respons pendamping lokal ditolak.",
      invalid_response: "Respons pendamping lokal tidak valid.",
      permission_required: "Izin loopback diperlukan.",
      developer_required: "Akses pengembang diperlukan.",
      source_missing: "Sumber tersebut tidak lagi tersedia.",
      conflict: "Status pendamping lokal berubah. Segarkan indeks.",
      superseded: "Permintaan ini digantikan.",
    },
  },
};

const MANAGED_STATUS_COPY: Record<
  ResolvedAppLocale,
  Record<SyncStatus, string>
> = {
  en: { ok: "Current", warning: "Warning", error: "Error" },
  "zh-CN": { ok: "当前", warning: "警告", error: "错误" },
  "zh-TW": { ok: "目前", warning: "警告", error: "錯誤" },
  ja: { ok: "正常", warning: "警告", error: "エラー" },
  ko: { ok: "정상", warning: "경고", error: "오류" },
  "es-419": { ok: "Actual", warning: "Advertencia", error: "Error" },
  "pt-BR": { ok: "Atual", warning: "Aviso", error: "Erro" },
  fr: { ok: "À jour", warning: "Avertissement", error: "Erreur" },
  de: { ok: "Aktuell", warning: "Warnung", error: "Fehler" },
  it: { ok: "Aggiornato", warning: "Avviso", error: "Errore" },
  ru: { ok: "Актуально", warning: "Предупреждение", error: "Ошибка" },
  ar: { ok: "حالي", warning: "تحذير", error: "خطأ" },
  hi: { ok: "वर्तमान", warning: "चेतावनी", error: "त्रुटि" },
  id: { ok: "Terkini", warning: "Peringatan", error: "Kesalahan" },
};

export function buildLocalCompanionLocalizedCopy(
  locale: ResolvedAppLocale,
): LocalCompanionLocalizedCopy {
  return { ...COPY[locale], managedStatuses: MANAGED_STATUS_COPY[locale] };
}
