import type { ResolvedAppLocale } from "./i18n";

type ProviderDetailExtendedLocale = Exclude<ResolvedAppLocale, "en" | "zh-CN">;

export type ProviderDetailExtendedCopyText = {
  topbarSubtitle: string;
  openDetailTabTitle: (providerLabel: string) => string;
  sections: {
    syncStatus: string;
    providerDetail: string;
    usage: string;
  };
  badges: {
    needsAccess: string;
    healthy: string;
    warning: string;
    syncIssue: string;
  };
  fieldLabels: {
    plan: string;
    status: string;
    quotaModel: string;
    used: string;
    remaining: string;
    resetTime: string;
    sourcePreference: string;
    syncSource: string;
    productContract: string;
    sessionPageContract: string;
    graduationGate: string;
    sessionPageGate: string;
    sourceFidelity: string;
    sourceState: string;
    usedValueFidelity: string;
    remainingValueFidelity: string;
    resetValueFidelity: string;
    availabilitySummary: string;
    accessModel: string;
    credentialPersistence: string;
    cookieStorage: string;
    manualCookieImport: string;
    hostAccessRequirement: string;
    pageBinding: string;
    bindingMode: string;
    bindingDetail: string;
    selectionReason: string;
    selectionDiagnostic: string;
    selectionDiagnosticSummary: string;
    fallbackReason: string;
    fallbackDiagnostic: string;
    fallbackDiagnosticSummary: string;
    sourceNote: string;
    lastSync: string;
    hostAccess: string;
    hosts: string;
    fallbackPath: string;
  };
  notes: {
    accessStatus: string;
    accessStatusDetail: string;
    sourceState: string;
    sourceFidelity: string;
    productContract: string;
    graduationGatePrefix: string;
    sessionPageTrackPrefix: string;
    sessionPageGatePrefix: string;
    trustBoundary: string;
    pageBinding: string;
    usageWindows: string;
    sourcePageRecovery: string;
    sourcePageRecoveryDetail: string;
    openSourcePageAction: string;
    diagnosticSummary: string;
    warningReason: string;
  };
  values: {
    granted: string;
    missing: string;
    unknown: string;
    notAvailableFromSource: string;
    unknownUsageWindowPercentage: string;
    usedAndRemaining: (used: string, remaining: string) => string;
    usedOnly: (used: string) => string;
    remainingOnly: (remaining: string) => string;
    tracked: (used: string, quotaUnit: string) => string;
    unknownOfTotal: (total: string, quotaUnit: string) => string;
    unknownQuotaUnit: (quotaUnit: string) => string;
  };
  heroDetail: string;
  progressLabel: (providerLabel: string) => string;
};

export const PROVIDER_DETAIL_EXTENDED_COPY: Record<
  ProviderDetailExtendedLocale,
  ProviderDetailExtendedCopyText
> = {
  "zh-TW": {
    topbarSubtitle: "目前 provider source 快照",
    openDetailTabTitle: (provider) => `打開 ${provider} 詳情分頁`,
    sections: {
      syncStatus: "同步狀態",
      providerDetail: "Provider 詳情",
      usage: "用量",
    },
    badges: {
      needsAccess: "需要授權",
      healthy: "健康",
      warning: "警告",
      syncIssue: "同步問題",
    },
    fieldLabels: {
      plan: "方案",
      status: "狀態",
      quotaModel: "Quota model",
      used: "已用",
      remaining: "剩餘",
      resetTime: "重置時間",
      sourcePreference: "來源偏好",
      syncSource: "同步來源",
      productContract: "產品合約",
      sessionPageContract: "Session-page 合約",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "來源保真度",
      sourceState: "來源狀態",
      usedValueFidelity: "已用值保真度",
      remainingValueFidelity: "剩餘值保真度",
      resetValueFidelity: "重置值保真度",
      availabilitySummary: "可用性摘要",
      accessModel: "存取模型",
      credentialPersistence: "Credential 保存",
      cookieStorage: "Cookie 儲存",
      manualCookieImport: "手動 Cookie 匯入",
      hostAccessRequirement: "Host access 要求",
      pageBinding: "頁面綁定",
      bindingMode: "綁定模式",
      bindingDetail: "綁定詳情",
      selectionReason: "選擇原因",
      selectionDiagnostic: "選擇診斷",
      selectionDiagnosticSummary: "選擇摘要",
      fallbackReason: "Fallback 原因",
      fallbackDiagnostic: "Fallback 診斷",
      fallbackDiagnosticSummary: "Fallback 摘要",
      sourceNote: "來源說明",
      lastSync: "上次同步",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Fallback 路徑",
    },
    notes: {
      accessStatus: "存取狀態",
      accessStatusDetail:
        "這個 provider 目前缺少 host access。授予所需 host permission 前，後續 live sync 可能會失敗。",
      sourceState: "來源狀態",
      sourceFidelity: "來源保真度",
      productContract: "產品合約",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "信任邊界",
      pageBinding: "頁面綁定",
      usageWindows: "可見用量上下文",
      sourcePageRecovery: "來源頁面恢復",
      sourcePageRecoveryDetail:
        "打開或切回這個 provider 已發布的 session-page source，並保存匹配的頁面綁定。",
      openSourcePageAction: "打開來源頁面",
      diagnosticSummary: "診斷摘要",
      warningReason: "警告原因",
    },
    values: {
      granted: "已授權",
      missing: "缺失",
      unknown: "未知",
      notAvailableFromSource: "此來源不可用",
      unknownUsageWindowPercentage: "未知 usage-window 百分比",
      usedAndRemaining: (used, remaining) => `已用 ${used} · 剩餘 ${remaining}`,
      usedOnly: (used) => `已用 ${used}`,
      remainingOnly: (remaining) => `剩餘 ${remaining}`,
      tracked: (used, quotaUnit) => `已追蹤 ${used} ${quotaUnit}`,
      unknownOfTotal: (total, quotaUnit) => `未知 / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `未知 ${quotaUnit}`,
    },
    heroDetail:
      "這個詳情頁反映 dashboard 和 refresh flow 目前使用的標準化 provider 快照，包括 side panel 顯示的 source fidelity 和 product-contract 語義。",
    progressLabel: (provider) => `${provider} usage ratio`,
  },
  ja: {
    topbarSubtitle: "現在の provider source スナップショット",
    openDetailTabTitle: (provider) => `${provider} 詳細タブを開く`,
    sections: {
      syncStatus: "同期状態",
      providerDetail: "Provider 詳細",
      usage: "使用量",
    },
    badges: {
      needsAccess: "アクセスが必要",
      healthy: "正常",
      warning: "警告",
      syncIssue: "同期問題",
    },
    fieldLabels: {
      plan: "プラン",
      status: "状態",
      quotaModel: "Quota model",
      used: "使用済み",
      remaining: "残り",
      resetTime: "リセット時刻",
      sourcePreference: "ソース設定",
      syncSource: "同期ソース",
      productContract: "Product contract",
      sessionPageContract: "Session-page contract",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "ソース忠実度",
      sourceState: "ソース状態",
      usedValueFidelity: "使用済み値の忠実度",
      remainingValueFidelity: "残り値の忠実度",
      resetValueFidelity: "リセット値の忠実度",
      availabilitySummary: "可用性サマリー",
      accessModel: "アクセスモデル",
      credentialPersistence: "Credential 保存",
      cookieStorage: "Cookie 保存",
      manualCookieImport: "手動 Cookie import",
      hostAccessRequirement: "Host access 要件",
      pageBinding: "ページバインド",
      bindingMode: "バインドモード",
      bindingDetail: "バインド詳細",
      selectionReason: "選択理由",
      selectionDiagnostic: "選択診断",
      selectionDiagnosticSummary: "選択サマリー",
      fallbackReason: "Fallback 理由",
      fallbackDiagnostic: "Fallback 診断",
      fallbackDiagnosticSummary: "Fallback サマリー",
      sourceNote: "ソースメモ",
      lastSync: "最終同期",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Fallback path",
    },
    notes: {
      accessStatus: "アクセス状態",
      accessStatusDetail:
        "この provider は host access が不足しています。必要な host permission を許可するまで、以後の live sync は失敗する可能性があります。",
      sourceState: "ソース状態",
      sourceFidelity: "ソース忠実度",
      productContract: "Product contract",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "信頼境界",
      pageBinding: "ページバインド",
      usageWindows: "表示された使用量コンテキスト",
      sourcePageRecovery: "ソースページ復旧",
      sourcePageRecoveryDetail:
        "この provider の出荷済み session-page source を開くか前面にして、対応するページバインドを保存します。",
      openSourcePageAction: "ソースページを開く",
      diagnosticSummary: "診断サマリー",
      warningReason: "警告理由",
    },
    values: {
      granted: "許可済み",
      missing: "不足",
      unknown: "不明",
      notAvailableFromSource: "このソースでは利用不可",
      unknownUsageWindowPercentage: "不明な usage-window 割合",
      usedAndRemaining: (used, remaining) => `${used} 使用済み · ${remaining} 残り`,
      usedOnly: (used) => `${used} 使用済み`,
      remainingOnly: (remaining) => `${remaining} 残り`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} 追跡済み`,
      unknownOfTotal: (total, quotaUnit) => `不明 / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `不明 ${quotaUnit}`,
    },
    heroDetail:
      "この詳細ビューは、dashboard と refresh flow が現在使っている標準化 provider スナップショットを示します。side panel に表示される source fidelity と product-contract の意味も含みます。",
    progressLabel: (provider) => `${provider} usage ratio`,
  },
  ko: {
    topbarSubtitle: "현재 provider source 스냅샷",
    openDetailTabTitle: (provider) => `${provider} 상세 탭 열기`,
    sections: {
      syncStatus: "동기화 상태",
      providerDetail: "Provider 상세",
      usage: "사용량",
    },
    badges: {
      needsAccess: "접근 필요",
      healthy: "정상",
      warning: "경고",
      syncIssue: "동기화 문제",
    },
    fieldLabels: {
      plan: "플랜",
      status: "상태",
      quotaModel: "Quota model",
      used: "사용됨",
      remaining: "남음",
      resetTime: "reset 시간",
      sourcePreference: "소스 선호",
      syncSource: "동기화 소스",
      productContract: "Product contract",
      sessionPageContract: "Session-page contract",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "소스 정확도",
      sourceState: "소스 상태",
      usedValueFidelity: "사용 값 정확도",
      remainingValueFidelity: "남은 값 정확도",
      resetValueFidelity: "reset 값 정확도",
      availabilitySummary: "가용성 요약",
      accessModel: "액세스 모델",
      credentialPersistence: "Credential 저장",
      cookieStorage: "Cookie 저장",
      manualCookieImport: "수동 Cookie import",
      hostAccessRequirement: "Host access 요구 사항",
      pageBinding: "페이지 바인딩",
      bindingMode: "바인딩 모드",
      bindingDetail: "바인딩 상세",
      selectionReason: "선택 이유",
      selectionDiagnostic: "선택 진단",
      selectionDiagnosticSummary: "선택 요약",
      fallbackReason: "Fallback 이유",
      fallbackDiagnostic: "Fallback 진단",
      fallbackDiagnosticSummary: "Fallback 요약",
      sourceNote: "소스 메모",
      lastSync: "마지막 동기화",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Fallback path",
    },
    notes: {
      accessStatus: "액세스 상태",
      accessStatusDetail:
        "이 provider에는 host access가 없습니다. 필요한 host permission을 허용하기 전까지 이후 live sync가 실패할 수 있습니다.",
      sourceState: "소스 상태",
      sourceFidelity: "소스 정확도",
      productContract: "Product contract",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "신뢰 경계",
      pageBinding: "페이지 바인딩",
      usageWindows: "표시된 사용량 컨텍스트",
      sourcePageRecovery: "소스 페이지 복구",
      sourcePageRecoveryDetail:
        "이 provider의 shipped session-page source를 열거나 포커스하고 일치하는 page binding을 저장합니다.",
      openSourcePageAction: "소스 페이지 열기",
      diagnosticSummary: "진단 요약",
      warningReason: "경고 이유",
    },
    values: {
      granted: "허용됨",
      missing: "없음",
      unknown: "알 수 없음",
      notAvailableFromSource: "이 소스에서 사용할 수 없음",
      unknownUsageWindowPercentage: "알 수 없는 usage-window 비율",
      usedAndRemaining: (used, remaining) => `${used} 사용 · ${remaining} 남음`,
      usedOnly: (used) => `${used} 사용`,
      remainingOnly: (remaining) => `${remaining} 남음`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} 추적됨`,
      unknownOfTotal: (total, quotaUnit) => `알 수 없음 / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `알 수 없는 ${quotaUnit}`,
    },
    heroDetail:
      "이 상세 화면은 dashboard와 refresh flow가 현재 사용하는 표준화 provider 스냅샷을 보여주며, side panel의 source fidelity 및 product-contract 의미를 포함합니다.",
    progressLabel: (provider) => `${provider} usage ratio`,
  },
  "es-419": {
    topbarSubtitle: "Snapshot actual del provider source",
    openDetailTabTitle: (provider) => `Abrir pestaña de detalle de ${provider}`,
    sections: {
      syncStatus: "Estado de sincronización",
      providerDetail: "Detalle del provider",
      usage: "Uso",
    },
    badges: {
      needsAccess: "Requiere acceso",
      healthy: "Correcto",
      warning: "Advertencia",
      syncIssue: "Problema de sync",
    },
    fieldLabels: {
      plan: "Plan",
      status: "Estado",
      quotaModel: "Modelo de cuota",
      used: "Usado",
      remaining: "Restante",
      resetTime: "Hora de reset",
      sourcePreference: "Preferencia de fuente",
      syncSource: "Fuente de sync",
      productContract: "Contrato de producto",
      sessionPageContract: "Contrato session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Fidelidad de fuente",
      sourceState: "Estado de fuente",
      usedValueFidelity: "Fidelidad del valor usado",
      remainingValueFidelity: "Fidelidad del valor restante",
      resetValueFidelity: "Fidelidad del valor reset",
      availabilitySummary: "Resumen de disponibilidad",
      accessModel: "Modelo de acceso",
      credentialPersistence: "Persistencia de credential",
      cookieStorage: "Almacenamiento de cookies",
      manualCookieImport: "Import manual de cookies",
      hostAccessRequirement: "Requisito de host access",
      pageBinding: "Vínculo de página",
      bindingMode: "Modo de vínculo",
      bindingDetail: "Detalle de vínculo",
      selectionReason: "Motivo de selección",
      selectionDiagnostic: "Diagnóstico de selección",
      selectionDiagnosticSummary: "Resumen de selección",
      fallbackReason: "Motivo de fallback",
      fallbackDiagnostic: "Diagnóstico de fallback",
      fallbackDiagnosticSummary: "Resumen de fallback",
      sourceNote: "Nota de fuente",
      lastSync: "Última sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Ruta fallback",
    },
    notes: {
      accessStatus: "Estado de acceso",
      accessStatusDetail:
        "Falta host access para este provider. Las futuras live syncs pueden fallar hasta que se concedan los host permissions requeridos.",
      sourceState: "Estado de fuente",
      sourceFidelity: "Fidelidad de fuente",
      productContract: "Contrato de producto",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Límite de confianza",
      pageBinding: "Vínculo de página",
      usageWindows: "Contexto de uso visible",
      sourcePageRecovery: "Recuperación de source page",
      sourcePageRecoveryDetail:
        "Abre o enfoca el session-page source publicado de este provider y guarda el vínculo de página coincidente.",
      openSourcePageAction: "Abrir source page",
      diagnosticSummary: "Resumen diagnóstico",
      warningReason: "Motivo de advertencia",
    },
    values: {
      granted: "Concedido",
      missing: "Falta",
      unknown: "Desconocido",
      notAvailableFromSource: "No disponible desde esta fuente",
      unknownUsageWindowPercentage: "Porcentaje de usage-window desconocido",
      usedAndRemaining: (used, remaining) => `${used} usado · ${remaining} restante`,
      usedOnly: (used) => `${used} usado`,
      remainingOnly: (remaining) => `${remaining} restante`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} rastreado`,
      unknownOfTotal: (total, quotaUnit) => `Desconocido / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `${quotaUnit} desconocido`,
    },
    heroDetail:
      "Esta vista refleja el snapshot normalizado del provider que usan el dashboard y el refresh flow, incluyendo la semántica de source fidelity y product-contract mostrada en el side panel.",
    progressLabel: (provider) => `Ratio de uso de ${provider}`,
  },
  "pt-BR": {
    topbarSubtitle: "Snapshot atual do provider source",
    openDetailTabTitle: (provider) => `Abrir aba de detalhes de ${provider}`,
    sections: {
      syncStatus: "Status de sync",
      providerDetail: "Detalhe do provider",
      usage: "Uso",
    },
    badges: {
      needsAccess: "Requer acesso",
      healthy: "Saudável",
      warning: "Aviso",
      syncIssue: "Problema de sync",
    },
    fieldLabels: {
      plan: "Plano",
      status: "Status",
      quotaModel: "Modelo de cota",
      used: "Usado",
      remaining: "Restante",
      resetTime: "Hora de reset",
      sourcePreference: "Preferência de fonte",
      syncSource: "Fonte de sync",
      productContract: "Contrato de produto",
      sessionPageContract: "Contrato session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Fidelidade da fonte",
      sourceState: "Estado da fonte",
      usedValueFidelity: "Fidelidade do valor usado",
      remainingValueFidelity: "Fidelidade do valor restante",
      resetValueFidelity: "Fidelidade do valor reset",
      availabilitySummary: "Resumo de disponibilidade",
      accessModel: "Modelo de acesso",
      credentialPersistence: "Persistência de credential",
      cookieStorage: "Armazenamento de cookies",
      manualCookieImport: "Import manual de cookies",
      hostAccessRequirement: "Requisito de host access",
      pageBinding: "Vínculo de página",
      bindingMode: "Modo de vínculo",
      bindingDetail: "Detalhe do vínculo",
      selectionReason: "Motivo da seleção",
      selectionDiagnostic: "Diagnóstico de seleção",
      selectionDiagnosticSummary: "Resumo da seleção",
      fallbackReason: "Motivo do fallback",
      fallbackDiagnostic: "Diagnóstico de fallback",
      fallbackDiagnosticSummary: "Resumo do fallback",
      sourceNote: "Nota da fonte",
      lastSync: "Última sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Caminho fallback",
    },
    notes: {
      accessStatus: "Status de acesso",
      accessStatusDetail:
        "Falta host access para este provider. Live syncs futuras podem falhar até que os host permissions necessários sejam concedidos.",
      sourceState: "Estado da fonte",
      sourceFidelity: "Fidelidade da fonte",
      productContract: "Contrato de produto",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Limite de confiança",
      pageBinding: "Vínculo de página",
      usageWindows: "Contexto de uso visível",
      sourcePageRecovery: "Recuperação da source page",
      sourcePageRecoveryDetail:
        "Abra ou foque o session-page source publicado deste provider e salve o vínculo de página correspondente.",
      openSourcePageAction: "Abrir source page",
      diagnosticSummary: "Resumo diagnóstico",
      warningReason: "Motivo do aviso",
    },
    values: {
      granted: "Concedido",
      missing: "Ausente",
      unknown: "Desconhecido",
      notAvailableFromSource: "Não disponível nesta fonte",
      unknownUsageWindowPercentage: "Porcentagem de usage-window desconhecida",
      usedAndRemaining: (used, remaining) => `${used} usado · ${remaining} restante`,
      usedOnly: (used) => `${used} usado`,
      remainingOnly: (remaining) => `${remaining} restante`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} rastreado`,
      unknownOfTotal: (total, quotaUnit) => `Desconhecido / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `${quotaUnit} desconhecido`,
    },
    heroDetail:
      "Esta visão reflete o snapshot normalizado do provider usado pelo dashboard e pelo refresh flow, incluindo a semântica de source fidelity e product-contract mostrada no side panel.",
    progressLabel: (provider) => `Razão de uso de ${provider}`,
  },
  fr: {
    topbarSubtitle: "Snapshot provider source actuel",
    openDetailTabTitle: (provider) => `Ouvrir l'onglet de détail ${provider}`,
    sections: {
      syncStatus: "État de synchronisation",
      providerDetail: "Détail du provider",
      usage: "Utilisation",
    },
    badges: {
      needsAccess: "Accès requis",
      healthy: "Sain",
      warning: "Avertissement",
      syncIssue: "Problème de sync",
    },
    fieldLabels: {
      plan: "Plan",
      status: "État",
      quotaModel: "Modèle de quota",
      used: "Utilisé",
      remaining: "Restant",
      resetTime: "Heure de reset",
      sourcePreference: "Préférence de source",
      syncSource: "Source de sync",
      productContract: "Contrat produit",
      sessionPageContract: "Contrat session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Fidélité de source",
      sourceState: "État de source",
      usedValueFidelity: "Fidélité de la valeur utilisée",
      remainingValueFidelity: "Fidélité de la valeur restante",
      resetValueFidelity: "Fidélité de la valeur reset",
      availabilitySummary: "Résumé de disponibilité",
      accessModel: "Modèle d'accès",
      credentialPersistence: "Persistance de credential",
      cookieStorage: "Stockage des cookies",
      manualCookieImport: "Import manuel de cookies",
      hostAccessRequirement: "Exigence host access",
      pageBinding: "Lien de page",
      bindingMode: "Mode de lien",
      bindingDetail: "Détail du lien",
      selectionReason: "Raison de sélection",
      selectionDiagnostic: "Diagnostic de sélection",
      selectionDiagnosticSummary: "Résumé de sélection",
      fallbackReason: "Raison de fallback",
      fallbackDiagnostic: "Diagnostic de fallback",
      fallbackDiagnosticSummary: "Résumé de fallback",
      sourceNote: "Note de source",
      lastSync: "Dernière sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Chemin fallback",
    },
    notes: {
      accessStatus: "État d'accès",
      accessStatusDetail:
        "Host access est manquant pour ce provider. Les futures live syncs peuvent échouer jusqu'à ce que les host permissions requis soient accordés.",
      sourceState: "État de source",
      sourceFidelity: "Fidélité de source",
      productContract: "Contrat produit",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Limite de confiance",
      pageBinding: "Lien de page",
      usageWindows: "Contexte d'utilisation visible",
      sourcePageRecovery: "Récupération source page",
      sourcePageRecoveryDetail:
        "Ouvrez ou ciblez le session-page source livré de ce provider et enregistrez le lien de page correspondant.",
      openSourcePageAction: "Ouvrir la source page",
      diagnosticSummary: "Résumé diagnostic",
      warningReason: "Raison de l'avertissement",
    },
    values: {
      granted: "Accordé",
      missing: "Manquant",
      unknown: "Inconnu",
      notAvailableFromSource: "Non disponible depuis cette source",
      unknownUsageWindowPercentage: "Pourcentage usage-window inconnu",
      usedAndRemaining: (used, remaining) => `${used} utilisé · ${remaining} restant`,
      usedOnly: (used) => `${used} utilisé`,
      remainingOnly: (remaining) => `${remaining} restant`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} suivi`,
      unknownOfTotal: (total, quotaUnit) => `Inconnu / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `${quotaUnit} inconnu`,
    },
    heroDetail:
      "Cette vue reflète le snapshot provider normalisé actuellement utilisé par le dashboard et le refresh flow, y compris la sémantique source fidelity et product-contract affichée dans le side panel.",
    progressLabel: (provider) => `Ratio d'utilisation ${provider}`,
  },
  de: {
    topbarSubtitle: "Aktueller provider source Snapshot",
    openDetailTabTitle: (provider) => `${provider}-Detailtab öffnen`,
    sections: {
      syncStatus: "Sync-Status",
      providerDetail: "Provider-Detail",
      usage: "Nutzung",
    },
    badges: {
      needsAccess: "Zugriff nötig",
      healthy: "Gesund",
      warning: "Warnung",
      syncIssue: "Sync-Problem",
    },
    fieldLabels: {
      plan: "Plan",
      status: "Status",
      quotaModel: "Kontingentmodell",
      used: "Verwendet",
      remaining: "Verbleibend",
      resetTime: "Reset-Zeit",
      sourcePreference: "Quellenpräferenz",
      syncSource: "Sync-Quelle",
      productContract: "Produktvertrag",
      sessionPageContract: "Session-page Vertrag",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Quellenfidelity",
      sourceState: "Quellenstatus",
      usedValueFidelity: "Fidelity des verwendeten Werts",
      remainingValueFidelity: "Fidelity des Restwerts",
      resetValueFidelity: "Fidelity des Reset-Werts",
      availabilitySummary: "Verfügbarkeitsübersicht",
      accessModel: "Zugriffsmodell",
      credentialPersistence: "Credential-Persistenz",
      cookieStorage: "Cookie-Speicher",
      manualCookieImport: "Manueller Cookie-Import",
      hostAccessRequirement: "Host-access-Anforderung",
      pageBinding: "Seitenbindung",
      bindingMode: "Bindungsmodus",
      bindingDetail: "Bindungsdetail",
      selectionReason: "Auswahlgrund",
      selectionDiagnostic: "Auswahldiagnose",
      selectionDiagnosticSummary: "Auswahlübersicht",
      fallbackReason: "Fallback-Grund",
      fallbackDiagnostic: "Fallback-Diagnose",
      fallbackDiagnosticSummary: "Fallback-Übersicht",
      sourceNote: "Quellennotiz",
      lastSync: "Letzte Sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Fallback-Pfad",
    },
    notes: {
      accessStatus: "Zugriffsstatus",
      accessStatusDetail:
        "Host access fehlt für diesen provider. Künftige live syncs können fehlschlagen, bis die erforderlichen host permissions erteilt sind.",
      sourceState: "Quellenstatus",
      sourceFidelity: "Quellenfidelity",
      productContract: "Produktvertrag",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Vertrauensgrenze",
      pageBinding: "Seitenbindung",
      usageWindows: "Sichtbarer Nutzungskontext",
      sourcePageRecovery: "Source-page-Wiederherstellung",
      sourcePageRecoveryDetail:
        "Öffnen oder fokussieren Sie die ausgelieferte session-page source dieses providers und speichern Sie die passende Seitenbindung.",
      openSourcePageAction: "Source page öffnen",
      diagnosticSummary: "Diagnoseübersicht",
      warningReason: "Warnungsgrund",
    },
    values: {
      granted: "Gewährt",
      missing: "Fehlt",
      unknown: "Unbekannt",
      notAvailableFromSource: "Aus dieser Quelle nicht verfügbar",
      unknownUsageWindowPercentage: "Unbekannter usage-window Prozentsatz",
      usedAndRemaining: (used, remaining) => `${used} verwendet · ${remaining} verbleibend`,
      usedOnly: (used) => `${used} verwendet`,
      remainingOnly: (remaining) => `${remaining} verbleibend`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} verfolgt`,
      unknownOfTotal: (total, quotaUnit) => `Unbekannt / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `Unbekannt ${quotaUnit}`,
    },
    heroDetail:
      "Diese Detailansicht zeigt den normalisierten provider snapshot, den dashboard und refresh flow aktuell verwenden, einschließlich source fidelity und product-contract Semantik im side panel.",
    progressLabel: (provider) => `${provider} Nutzungsverhältnis`,
  },
  it: {
    topbarSubtitle: "Snapshot provider source attuale",
    openDetailTabTitle: (provider) => `Apri scheda dettagli ${provider}`,
    sections: {
      syncStatus: "Stato sync",
      providerDetail: "Dettaglio provider",
      usage: "Uso",
    },
    badges: {
      needsAccess: "Accesso richiesto",
      healthy: "Sano",
      warning: "Avviso",
      syncIssue: "Problema di sync",
    },
    fieldLabels: {
      plan: "Piano",
      status: "Stato",
      quotaModel: "Modello quota",
      used: "Usato",
      remaining: "Restante",
      resetTime: "Ora reset",
      sourcePreference: "Preferenza fonte",
      syncSource: "Fonte sync",
      productContract: "Contratto prodotto",
      sessionPageContract: "Contratto session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Fedeltà fonte",
      sourceState: "Stato fonte",
      usedValueFidelity: "Fedeltà valore usato",
      remainingValueFidelity: "Fedeltà valore restante",
      resetValueFidelity: "Fedeltà valore reset",
      availabilitySummary: "Riepilogo disponibilità",
      accessModel: "Modello di accesso",
      credentialPersistence: "Persistenza credential",
      cookieStorage: "Archiviazione cookie",
      manualCookieImport: "Import manuale cookie",
      hostAccessRequirement: "Requisito host access",
      pageBinding: "Binding pagina",
      bindingMode: "Modalità binding",
      bindingDetail: "Dettaglio binding",
      selectionReason: "Motivo selezione",
      selectionDiagnostic: "Diagnostica selezione",
      selectionDiagnosticSummary: "Riepilogo selezione",
      fallbackReason: "Motivo fallback",
      fallbackDiagnostic: "Diagnostica fallback",
      fallbackDiagnosticSummary: "Riepilogo fallback",
      sourceNote: "Nota fonte",
      lastSync: "Ultima sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Percorso fallback",
    },
    notes: {
      accessStatus: "Stato accesso",
      accessStatusDetail:
        "Host access manca per questo provider. Le live sync future potrebbero fallire finché non vengono concessi gli host permissions richiesti.",
      sourceState: "Stato fonte",
      sourceFidelity: "Fedeltà fonte",
      productContract: "Contratto prodotto",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Confine di fiducia",
      pageBinding: "Binding pagina",
      usageWindows: "Contesto uso visibile",
      sourcePageRecovery: "Recupero source page",
      sourcePageRecoveryDetail:
        "Apri o metti a fuoco il session-page source rilasciato di questo provider e salva il binding pagina corrispondente.",
      openSourcePageAction: "Apri source page",
      diagnosticSummary: "Riepilogo diagnostica",
      warningReason: "Motivo avviso",
    },
    values: {
      granted: "Concesso",
      missing: "Mancante",
      unknown: "Sconosciuto",
      notAvailableFromSource: "Non disponibile da questa fonte",
      unknownUsageWindowPercentage: "Percentuale usage-window sconosciuta",
      usedAndRemaining: (used, remaining) => `${used} usato · ${remaining} restante`,
      usedOnly: (used) => `${used} usato`,
      remainingOnly: (remaining) => `${remaining} restante`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} tracciato`,
      unknownOfTotal: (total, quotaUnit) => `Sconosciuto / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `${quotaUnit} sconosciuto`,
    },
    heroDetail:
      "Questa vista mostra lo snapshot provider normalizzato usato dal dashboard e dal refresh flow, inclusa la semantica source fidelity e product-contract mostrata nel side panel.",
    progressLabel: (provider) => `Rapporto uso ${provider}`,
  },
  ru: {
    topbarSubtitle: "Текущий снимок provider source",
    openDetailTabTitle: (provider) => `Открыть вкладку деталей ${provider}`,
    sections: {
      syncStatus: "Статус синхронизации",
      providerDetail: "Детали provider",
      usage: "Использование",
    },
    badges: {
      needsAccess: "Нужен доступ",
      healthy: "Норма",
      warning: "Предупреждение",
      syncIssue: "Проблема синхронизации",
    },
    fieldLabels: {
      plan: "План",
      status: "Статус",
      quotaModel: "Модель квоты",
      used: "Использовано",
      remaining: "Осталось",
      resetTime: "Время reset",
      sourcePreference: "Предпочтение источника",
      syncSource: "Источник синхронизации",
      productContract: "Контракт продукта",
      sessionPageContract: "Контракт session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Точность источника",
      sourceState: "Состояние источника",
      usedValueFidelity: "Точность использованного значения",
      remainingValueFidelity: "Точность остатка",
      resetValueFidelity: "Точность reset значения",
      availabilitySummary: "Сводка доступности",
      accessModel: "Модель доступа",
      credentialPersistence: "Хранение credential",
      cookieStorage: "Хранение cookie",
      manualCookieImport: "Ручной импорт cookie",
      hostAccessRequirement: "Требование host access",
      pageBinding: "Привязка страницы",
      bindingMode: "Режим привязки",
      bindingDetail: "Детали привязки",
      selectionReason: "Причина выбора",
      selectionDiagnostic: "Диагностика выбора",
      selectionDiagnosticSummary: "Сводка выбора",
      fallbackReason: "Причина fallback",
      fallbackDiagnostic: "Диагностика fallback",
      fallbackDiagnosticSummary: "Сводка fallback",
      sourceNote: "Примечание источника",
      lastSync: "Последняя синхронизация",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Путь fallback",
    },
    notes: {
      accessStatus: "Статус доступа",
      accessStatusDetail:
        "Для этого provider отсутствует host access. Будущие live sync могут завершаться ошибкой, пока не будут выданы нужные host permissions.",
      sourceState: "Состояние источника",
      sourceFidelity: "Точность источника",
      productContract: "Контракт продукта",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Граница доверия",
      pageBinding: "Привязка страницы",
      usageWindows: "Видимый контекст использования",
      sourcePageRecovery: "Восстановление source page",
      sourcePageRecoveryDetail:
        "Откройте или сфокусируйте shipped session-page source этого provider и сохраните соответствующую привязку страницы.",
      openSourcePageAction: "Открыть source page",
      diagnosticSummary: "Сводка диагностики",
      warningReason: "Причина предупреждения",
    },
    values: {
      granted: "Разрешено",
      missing: "Отсутствует",
      unknown: "Неизвестно",
      notAvailableFromSource: "Недоступно из этого источника",
      unknownUsageWindowPercentage: "Неизвестный процент usage-window",
      usedAndRemaining: (used, remaining) => `${used} использовано · ${remaining} осталось`,
      usedOnly: (used) => `${used} использовано`,
      remainingOnly: (remaining) => `${remaining} осталось`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} отслеживается`,
      unknownOfTotal: (total, quotaUnit) => `Неизвестно / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `Неизвестно ${quotaUnit}`,
    },
    heroDetail:
      "Этот экран показывает нормализованный снимок provider, который сейчас используют dashboard и refresh flow, включая семантику source fidelity и product-contract в side panel.",
    progressLabel: (provider) => `Доля использования ${provider}`,
  },
  ar: {
    topbarSubtitle: "لقطة provider source الحالية",
    openDetailTabTitle: (provider) => `فتح تبويب تفاصيل ${provider}`,
    sections: {
      syncStatus: "حالة المزامنة",
      providerDetail: "تفاصيل provider",
      usage: "الاستخدام",
    },
    badges: {
      needsAccess: "يتطلب وصولا",
      healthy: "سليم",
      warning: "تحذير",
      syncIssue: "مشكلة مزامنة",
    },
    fieldLabels: {
      plan: "الخطة",
      status: "الحالة",
      quotaModel: "نموذج الحصة",
      used: "المستخدم",
      remaining: "المتبقي",
      resetTime: "وقت reset",
      sourcePreference: "تفضيل المصدر",
      syncSource: "مصدر sync",
      productContract: "عقد المنتج",
      sessionPageContract: "عقد session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "دقة المصدر",
      sourceState: "حالة المصدر",
      usedValueFidelity: "دقة قيمة المستخدم",
      remainingValueFidelity: "دقة قيمة المتبقي",
      resetValueFidelity: "دقة قيمة reset",
      availabilitySummary: "ملخص التوفر",
      accessModel: "نموذج الوصول",
      credentialPersistence: "حفظ credential",
      cookieStorage: "تخزين cookie",
      manualCookieImport: "استيراد cookie يدوي",
      hostAccessRequirement: "متطلب host access",
      pageBinding: "ربط الصفحة",
      bindingMode: "وضع الربط",
      bindingDetail: "تفاصيل الربط",
      selectionReason: "سبب الاختيار",
      selectionDiagnostic: "تشخيص الاختيار",
      selectionDiagnosticSummary: "ملخص الاختيار",
      fallbackReason: "سبب fallback",
      fallbackDiagnostic: "تشخيص fallback",
      fallbackDiagnosticSummary: "ملخص fallback",
      sourceNote: "ملاحظة المصدر",
      lastSync: "آخر sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "مسار fallback",
    },
    notes: {
      accessStatus: "حالة الوصول",
      accessStatusDetail:
        "host access مفقود لهذا provider. قد تفشل live syncs اللاحقة حتى يتم منح host permissions المطلوبة.",
      sourceState: "حالة المصدر",
      sourceFidelity: "دقة المصدر",
      productContract: "عقد المنتج",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "حد الثقة",
      pageBinding: "ربط الصفحة",
      usageWindows: "سياق الاستخدام المرئي",
      sourcePageRecovery: "استعادة source page",
      sourcePageRecoveryDetail:
        "افتح أو ركز على session-page source المنشور لهذا provider واحفظ ربط الصفحة المطابق.",
      openSourcePageAction: "فتح source page",
      diagnosticSummary: "ملخص التشخيص",
      warningReason: "سبب التحذير",
    },
    values: {
      granted: "ممنوح",
      missing: "مفقود",
      unknown: "غير معروف",
      notAvailableFromSource: "غير متاح من هذا المصدر",
      unknownUsageWindowPercentage: "نسبة usage-window غير معروفة",
      usedAndRemaining: (used, remaining) => `${used} مستخدم · ${remaining} متبق`,
      usedOnly: (used) => `${used} مستخدم`,
      remainingOnly: (remaining) => `${remaining} متبق`,
      tracked: (used, quotaUnit) => `تم تتبع ${used} ${quotaUnit}`,
      unknownOfTotal: (total, quotaUnit) => `غير معروف / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `${quotaUnit} غير معروف`,
    },
    heroDetail:
      "تعرض هذه الصفحة لقطة provider الموحدة التي يستخدمها dashboard و refresh flow حاليا، بما في ذلك دلالات source fidelity و product-contract المعروضة في side panel.",
    progressLabel: (provider) => `نسبة استخدام ${provider}`,
  },
  hi: {
    topbarSubtitle: "वर्तमान provider source snapshot",
    openDetailTabTitle: (provider) => `${provider} detail tab खोलें`,
    sections: {
      syncStatus: "Sync स्थिति",
      providerDetail: "Provider विवरण",
      usage: "उपयोग",
    },
    badges: {
      needsAccess: "Access चाहिए",
      healthy: "Healthy",
      warning: "Warning",
      syncIssue: "Sync issue",
    },
    fieldLabels: {
      plan: "Plan",
      status: "Status",
      quotaModel: "Quota model",
      used: "Used",
      remaining: "Remaining",
      resetTime: "Reset time",
      sourcePreference: "Source preference",
      syncSource: "Sync source",
      productContract: "Product contract",
      sessionPageContract: "Session-page contract",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Source fidelity",
      sourceState: "Source state",
      usedValueFidelity: "Used value fidelity",
      remainingValueFidelity: "Remaining value fidelity",
      resetValueFidelity: "Reset value fidelity",
      availabilitySummary: "Availability summary",
      accessModel: "Access model",
      credentialPersistence: "Credential persistence",
      cookieStorage: "Cookie storage",
      manualCookieImport: "Manual cookie import",
      hostAccessRequirement: "Host access requirement",
      pageBinding: "Page binding",
      bindingMode: "Binding mode",
      bindingDetail: "Binding detail",
      selectionReason: "Selection reason",
      selectionDiagnostic: "Selection diagnostic",
      selectionDiagnosticSummary: "Selection summary",
      fallbackReason: "Fallback reason",
      fallbackDiagnostic: "Fallback diagnostic",
      fallbackDiagnosticSummary: "Fallback summary",
      sourceNote: "Source note",
      lastSync: "Last sync",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Fallback path",
    },
    notes: {
      accessStatus: "Access status",
      accessStatusDetail:
        "इस provider के लिए host access missing है। required host permissions मिलने तक future live syncs fail हो सकती हैं।",
      sourceState: "Source state",
      sourceFidelity: "Source fidelity",
      productContract: "Product contract",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Trust boundary",
      pageBinding: "Page binding",
      usageWindows: "Visible usage context",
      sourcePageRecovery: "Source-page recovery",
      sourcePageRecoveryDetail:
        "इस provider के shipped session-page source को खोलें या focus करें और matching page binding save करें।",
      openSourcePageAction: "Source page खोलें",
      diagnosticSummary: "Diagnostic summary",
      warningReason: "Warning reason",
    },
    values: {
      granted: "मिला हुआ",
      missing: "Missing",
      unknown: "अज्ञात",
      notAvailableFromSource: "इस source से available नहीं",
      unknownUsageWindowPercentage: "उपयोग अवधि का प्रतिशत उपलब्ध नहीं है",
      usedAndRemaining: (used, remaining) => `${used} उपयोग · ${remaining} शेष`,
      usedOnly: (used) => `${used} उपयोग`,
      remainingOnly: (remaining) => `${remaining} शेष`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} ट्रैक किया गया`,
      unknownOfTotal: (total, quotaUnit) => `अज्ञात / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `अज्ञात ${quotaUnit}`,
    },
    heroDetail:
      "यह detail view dashboard और refresh flow द्वारा use किए जा रहे normalized provider snapshot को दिखाता है, जिसमें side panel की source fidelity और product-contract semantics शामिल हैं।",
    progressLabel: (provider) => `${provider} usage ratio`,
  },
  id: {
    topbarSubtitle: "Snapshot provider source saat ini",
    openDetailTabTitle: (provider) => `Buka tab detail ${provider}`,
    sections: {
      syncStatus: "Status sync",
      providerDetail: "Detail provider",
      usage: "Penggunaan",
    },
    badges: {
      needsAccess: "Perlu akses",
      healthy: "Sehat",
      warning: "Peringatan",
      syncIssue: "Masalah sync",
    },
    fieldLabels: {
      plan: "Paket",
      status: "Status",
      quotaModel: "Model kuota",
      used: "Terpakai",
      remaining: "Tersisa",
      resetTime: "Waktu reset",
      sourcePreference: "Preferensi sumber",
      syncSource: "Sumber sync",
      productContract: "Kontrak produk",
      sessionPageContract: "Kontrak session-page",
      graduationGate: "Graduation gate",
      sessionPageGate: "Session-page gate",
      sourceFidelity: "Fidelitas sumber",
      sourceState: "Status sumber",
      usedValueFidelity: "Fidelitas nilai terpakai",
      remainingValueFidelity: "Fidelitas nilai tersisa",
      resetValueFidelity: "Fidelitas nilai reset",
      availabilitySummary: "Ringkasan ketersediaan",
      accessModel: "Model akses",
      credentialPersistence: "Persistensi credential",
      cookieStorage: "Penyimpanan cookie",
      manualCookieImport: "Import cookie manual",
      hostAccessRequirement: "Kebutuhan host access",
      pageBinding: "Binding halaman",
      bindingMode: "Mode binding",
      bindingDetail: "Detail binding",
      selectionReason: "Alasan pemilihan",
      selectionDiagnostic: "Diagnostik pemilihan",
      selectionDiagnosticSummary: "Ringkasan pemilihan",
      fallbackReason: "Alasan fallback",
      fallbackDiagnostic: "Diagnostik fallback",
      fallbackDiagnosticSummary: "Ringkasan fallback",
      sourceNote: "Catatan sumber",
      lastSync: "Sync terakhir",
      hostAccess: "Host access",
      hosts: "Hosts",
      fallbackPath: "Jalur fallback",
    },
    notes: {
      accessStatus: "Status akses",
      accessStatusDetail:
        "Host access belum ada untuk provider ini. Live sync berikutnya dapat gagal sampai host permissions yang diperlukan diberikan.",
      sourceState: "Status sumber",
      sourceFidelity: "Fidelitas sumber",
      productContract: "Kontrak produk",
      graduationGatePrefix: "Graduation gate: ",
      sessionPageTrackPrefix: "Session-page track: ",
      sessionPageGatePrefix: "Session-page gate: ",
      trustBoundary: "Batas kepercayaan",
      pageBinding: "Binding halaman",
      usageWindows: "Konteks penggunaan terlihat",
      sourcePageRecovery: "Pemulihan source page",
      sourcePageRecoveryDetail:
        "Buka atau fokuskan session-page source yang dikirim untuk provider ini dan simpan binding halaman yang cocok.",
      openSourcePageAction: "Buka source page",
      diagnosticSummary: "Ringkasan diagnostik",
      warningReason: "Alasan peringatan",
    },
    values: {
      granted: "Diberikan",
      missing: "Belum ada",
      unknown: "Tidak diketahui",
      notAvailableFromSource: "Tidak tersedia dari sumber ini",
      unknownUsageWindowPercentage: "Persentase usage-window tidak diketahui",
      usedAndRemaining: (used, remaining) => `${used} terpakai · ${remaining} tersisa`,
      usedOnly: (used) => `${used} terpakai`,
      remainingOnly: (remaining) => `${remaining} tersisa`,
      tracked: (used, quotaUnit) => `${used} ${quotaUnit} dilacak`,
      unknownOfTotal: (total, quotaUnit) => `Tidak diketahui / ${total} ${quotaUnit}`,
      unknownQuotaUnit: (quotaUnit) => `${quotaUnit} tidak diketahui`,
    },
    heroDetail:
      "Tampilan detail ini mencerminkan snapshot provider ternormalisasi yang sedang digunakan dashboard dan refresh flow, termasuk semantik source fidelity dan product-contract yang tampil di side panel.",
    progressLabel: (provider) => `Rasio penggunaan ${provider}`,
  },
};

export function getProviderDetailExtendedCopy(
  locale: ResolvedAppLocale,
): ProviderDetailExtendedCopyText | null {
  if (locale === "en" || locale === "zh-CN") {
    return null;
  }

  return PROVIDER_DETAIL_EXTENDED_COPY[locale];
}
