import type {
  ProviderServiceStatusFailureReason,
  ProviderServiceStatusLevel,
  ProviderServiceStatusVendorId,
} from "../providers/types";
import type { ResolvedAppLocale } from "./i18n";

export type ProviderServiceStatusLocalizedCopy = {
  eyebrow: string;
  settingsTitle: string;
  settingsDetail: string;
  officialSource: string;
  openStatusPage: string;
  incident: string;
  stale: string;
  notChecked: string;
  accessDenied: string;
  levels: Record<ProviderServiceStatusLevel, string>;
  failures: Record<Exclude<ProviderServiceStatusFailureReason, null>, string>;
  vendors: Record<ProviderServiceStatusVendorId, string>;
};

const ENGLISH_COPY: ProviderServiceStatusLocalizedCopy = {
  eyebrow: "Service status",
  settingsTitle: "Official service status",
  settingsDetail:
    "Optionally show each vendor's official public status. Hidden modules do not request status data.",
  officialSource: "Official status",
  openStatusPage: "Open official status page",
  incident: "Active incident",
  stale: "Status unavailable",
  notChecked: "Not checked yet",
  accessDenied: "Status access was not granted. The module remains off.",
  levels: {
    operational: "Operational",
    degraded: "Degraded",
    outage: "Outage",
    maintenance: "Maintenance",
    unknown: "Unknown",
  },
  failures: {
    permission_missing: "Status-page access is not granted",
    offline: "Status page could not be reached",
    timeout: "Status request timed out",
    rate_limited: "Status page temporarily limited requests",
    http_error: "Status page returned an error",
    invalid_response: "Status response could not be verified",
  },
  vendors: {
    openai: "OpenAI",
    anthropic: "Anthropic",
    cursor: "Cursor",
  },
};

const LOCALIZED_OVERRIDES: Partial<
  Record<ResolvedAppLocale, Partial<ProviderServiceStatusLocalizedCopy>>
> = {
  "zh-CN": {
    eyebrow: "服务状态",
    settingsTitle: "官方服务状态",
    settingsDetail:
      "可选择在各界面显示厂商官方公开状态；隐藏的模块不会请求状态数据。",
    officialSource: "官方状态",
    openStatusPage: "打开官方状态页",
    incident: "进行中的事故",
    stale: "状态暂不可用",
    notChecked: "尚未检查",
    accessDenied: "未授予状态页访问权限，模块仍保持关闭。",
    levels: {
      operational: "运行正常",
      degraded: "性能下降",
      outage: "服务中断",
      maintenance: "维护中",
      unknown: "状态未知",
    },
    failures: {
      permission_missing: "尚未授予状态页访问权限",
      offline: "无法连接状态页",
      timeout: "状态请求超时",
      rate_limited: "状态页暂时限制请求",
      http_error: "状态页返回错误",
      invalid_response: "无法验证状态响应",
    },
  },
  "zh-TW": {
    eyebrow: "服務狀態",
    settingsTitle: "官方服務狀態",
    settingsDetail: "可選擇在各介面顯示官方公開狀態；隱藏的模組不會發出請求。",
    officialSource: "官方狀態",
    openStatusPage: "開啟官方狀態頁",
    incident: "進行中的事件",
    stale: "狀態暫不可用",
    notChecked: "尚未檢查",
    accessDenied: "未授予狀態頁存取權，模組仍保持關閉。",
    levels: {
      operational: "運作正常",
      degraded: "效能下降",
      outage: "服務中斷",
      maintenance: "維護中",
      unknown: "狀態未知",
    },
    failures: {
      permission_missing: "尚未授予狀態頁存取權",
      offline: "無法連線至狀態頁",
      timeout: "狀態請求逾時",
      rate_limited: "狀態頁暫時限制請求",
      http_error: "狀態頁傳回錯誤",
      invalid_response: "無法驗證狀態回應",
    },
  },
  ja: {
    eyebrow: "サービス状況",
    settingsTitle: "公式サービス状況",
    settingsDetail: "各画面に公式の公開状況を表示します。非表示時は取得しません。",
    officialSource: "公式ステータス",
    openStatusPage: "公式ステータスページを開く",
    incident: "発生中の障害",
    stale: "状況を取得できません",
    notChecked: "未確認",
    accessDenied: "アクセスが許可されなかったため、表示はオフのままです。",
    levels: {
      operational: "正常稼働",
      degraded: "性能低下",
      outage: "障害発生中",
      maintenance: "メンテナンス中",
      unknown: "状況不明",
    },
    failures: {
      permission_missing: "ステータスページへのアクセスが未許可です",
      offline: "ステータスページに接続できません",
      timeout: "ステータス要求がタイムアウトしました",
      rate_limited: "ステータスページが要求を一時制限しています",
      http_error: "ステータスページがエラーを返しました",
      invalid_response: "ステータス応答を検証できません",
    },
  },
  ko: {
    eyebrow: "서비스 상태",
    settingsTitle: "공식 서비스 상태",
    settingsDetail: "각 화면에 공식 공개 상태를 표시합니다. 숨기면 요청하지 않습니다.",
    officialSource: "공식 상태",
    openStatusPage: "공식 상태 페이지 열기",
    incident: "진행 중인 장애",
    stale: "상태를 확인할 수 없음",
    notChecked: "확인 전",
    accessDenied: "상태 페이지 접근이 허용되지 않아 모듈이 꺼진 상태로 유지됩니다.",
    levels: {
      operational: "정상 운영",
      degraded: "성능 저하",
      outage: "서비스 중단",
      maintenance: "점검 중",
      unknown: "상태 알 수 없음",
    },
    failures: {
      permission_missing: "상태 페이지 접근 권한이 없습니다",
      offline: "상태 페이지에 연결할 수 없습니다",
      timeout: "상태 요청 시간이 초과되었습니다",
      rate_limited: "상태 페이지가 요청을 일시 제한했습니다",
      http_error: "상태 페이지가 오류를 반환했습니다",
      invalid_response: "상태 응답을 확인할 수 없습니다",
    },
  },
  "es-419": {
    eyebrow: "Estado del servicio",
    settingsTitle: "Estado oficial del servicio",
    settingsDetail: "Muestra el estado público oficial por superficie. Lo oculto no hace solicitudes.",
    officialSource: "Estado oficial",
    openStatusPage: "Abrir página oficial de estado",
    incident: "Incidente activo",
    stale: "Estado no disponible",
    notChecked: "Aún no verificado",
    accessDenied: "No se otorgó acceso; el módulo sigue desactivado.",
    levels: {
      operational: "Operativo",
      degraded: "Rendimiento degradado",
      outage: "Interrupción",
      maintenance: "Mantenimiento",
      unknown: "Desconocido",
    },
    failures: {
      permission_missing: "No se otorgó acceso a la página de estado",
      offline: "No se pudo contactar la página de estado",
      timeout: "La solicitud de estado agotó el tiempo",
      rate_limited: "La página de estado limitó temporalmente las solicitudes",
      http_error: "La página de estado devolvió un error",
      invalid_response: "No se pudo verificar la respuesta de estado",
    },
  },
  "pt-BR": {
    eyebrow: "Status do serviço",
    settingsTitle: "Status oficial do serviço",
    settingsDetail: "Mostra o status público oficial em cada tela. Módulos ocultos não consultam dados.",
    officialSource: "Status oficial",
    openStatusPage: "Abrir página oficial de status",
    incident: "Incidente ativo",
    stale: "Status indisponível",
    notChecked: "Ainda não verificado",
    accessDenied: "O acesso não foi concedido; o módulo continua desativado.",
    levels: {
      operational: "Operacional",
      degraded: "Desempenho degradado",
      outage: "Indisponível",
      maintenance: "Em manutenção",
      unknown: "Desconhecido",
    },
    failures: {
      permission_missing: "O acesso à página de status não foi concedido",
      offline: "Não foi possível acessar a página de status",
      timeout: "A solicitação de status expirou",
      rate_limited: "A página de status limitou temporariamente as solicitações",
      http_error: "A página de status retornou um erro",
      invalid_response: "Não foi possível verificar a resposta de status",
    },
  },
  fr: {
    eyebrow: "État du service",
    settingsTitle: "État officiel du service",
    settingsDetail: "Affiche l’état public officiel par interface. Un module masqué n’effectue aucune requête.",
    officialSource: "État officiel",
    openStatusPage: "Ouvrir la page d’état officielle",
    incident: "Incident en cours",
    stale: "État indisponible",
    notChecked: "Pas encore vérifié",
    accessDenied: "L’accès n’a pas été accordé ; le module reste désactivé.",
    levels: {
      operational: "Opérationnel",
      degraded: "Performances dégradées",
      outage: "Interruption",
      maintenance: "Maintenance",
      unknown: "Inconnu",
    },
    failures: {
      permission_missing: "L’accès à la page d’état n’est pas accordé",
      offline: "La page d’état est inaccessible",
      timeout: "La demande d’état a expiré",
      rate_limited: "La page d’état limite temporairement les demandes",
      http_error: "La page d’état a renvoyé une erreur",
      invalid_response: "La réponse d’état n’a pas pu être vérifiée",
    },
  },
  de: {
    eyebrow: "Dienststatus",
    settingsTitle: "Offizieller Dienststatus",
    settingsDetail: "Zeigt den offiziellen öffentlichen Status je Oberfläche. Ausgeblendete Module rufen nichts ab.",
    officialSource: "Offizieller Status",
    openStatusPage: "Offizielle Statusseite öffnen",
    incident: "Aktiver Vorfall",
    stale: "Status nicht verfügbar",
    notChecked: "Noch nicht geprüft",
    accessDenied: "Der Zugriff wurde nicht erteilt; das Modul bleibt deaktiviert.",
    levels: {
      operational: "Betriebsbereit",
      degraded: "Beeinträchtigt",
      outage: "Ausfall",
      maintenance: "Wartung",
      unknown: "Unbekannt",
    },
    failures: {
      permission_missing: "Der Zugriff auf die Statusseite fehlt",
      offline: "Die Statusseite ist nicht erreichbar",
      timeout: "Die Statusanfrage hat das Zeitlimit überschritten",
      rate_limited: "Die Statusseite begrenzt Anfragen vorübergehend",
      http_error: "Die Statusseite hat einen Fehler zurückgegeben",
      invalid_response: "Die Statusantwort konnte nicht geprüft werden",
    },
  },
  it: {
    eyebrow: "Stato del servizio",
    settingsTitle: "Stato ufficiale del servizio",
    settingsDetail: "Mostra lo stato pubblico ufficiale per schermata. I moduli nascosti non inviano richieste.",
    officialSource: "Stato ufficiale",
    openStatusPage: "Apri la pagina di stato ufficiale",
    incident: "Problema attivo",
    stale: "Stato non disponibile",
    notChecked: "Non ancora verificato",
    accessDenied: "Accesso non concesso; il modulo resta disattivato.",
    levels: {
      operational: "Operativo",
      degraded: "Prestazioni ridotte",
      outage: "Interruzione",
      maintenance: "Manutenzione",
      unknown: "Sconosciuto",
    },
    failures: {
      permission_missing: "Accesso alla pagina di stato non concesso",
      offline: "Impossibile raggiungere la pagina di stato",
      timeout: "La richiesta di stato è scaduta",
      rate_limited: "La pagina di stato limita temporaneamente le richieste",
      http_error: "La pagina di stato ha restituito un errore",
      invalid_response: "Impossibile verificare la risposta di stato",
    },
  },
  ru: {
    eyebrow: "Статус сервиса",
    settingsTitle: "Официальный статус сервиса",
    settingsDetail: "Показывает официальный публичный статус. Скрытые модули не выполняют запросы.",
    officialSource: "Официальный статус",
    openStatusPage: "Открыть официальную страницу статуса",
    incident: "Активный инцидент",
    stale: "Статус недоступен",
    notChecked: "Ещё не проверено",
    accessDenied: "Доступ не предоставлен; модуль остался выключенным.",
    levels: {
      operational: "Работает",
      degraded: "Сниженная производительность",
      outage: "Сбой",
      maintenance: "Обслуживание",
      unknown: "Неизвестно",
    },
    failures: {
      permission_missing: "Нет доступа к странице статуса",
      offline: "Не удалось открыть страницу статуса",
      timeout: "Время ожидания запроса статуса истекло",
      rate_limited: "Страница статуса временно ограничила запросы",
      http_error: "Страница статуса вернула ошибку",
      invalid_response: "Не удалось проверить ответ статуса",
    },
  },
  ar: {
    eyebrow: "حالة الخدمة",
    settingsTitle: "حالة الخدمة الرسمية",
    settingsDetail: "يعرض الحالة العامة الرسمية لكل واجهة. الوحدات المخفية لا ترسل طلبات.",
    officialSource: "الحالة الرسمية",
    openStatusPage: "فتح صفحة الحالة الرسمية",
    incident: "حادث نشط",
    stale: "الحالة غير متاحة",
    notChecked: "لم يتم الفحص بعد",
    accessDenied: "لم يُمنح الوصول؛ ستبقى الوحدة متوقفة.",
    levels: {
      operational: "تعمل بصورة طبيعية",
      degraded: "أداء متراجع",
      outage: "انقطاع",
      maintenance: "صيانة",
      unknown: "غير معروف",
    },
    failures: {
      permission_missing: "لم يُمنح الوصول إلى صفحة الحالة",
      offline: "تعذر الوصول إلى صفحة الحالة",
      timeout: "انتهت مهلة طلب الحالة",
      rate_limited: "حدّت صفحة الحالة الطلبات مؤقتًا",
      http_error: "أعادت صفحة الحالة خطأ",
      invalid_response: "تعذر التحقق من استجابة الحالة",
    },
  },
  hi: {
    eyebrow: "सेवा स्थिति",
    settingsTitle: "आधिकारिक सेवा स्थिति",
    settingsDetail: "हर सतह पर आधिकारिक सार्वजनिक स्थिति दिखाएँ। छिपे मॉड्यूल अनुरोध नहीं करते।",
    officialSource: "आधिकारिक स्थिति",
    openStatusPage: "आधिकारिक स्थिति पृष्ठ खोलें",
    incident: "सक्रिय घटना",
    stale: "स्थिति उपलब्ध नहीं",
    notChecked: "अभी जाँच नहीं हुई",
    accessDenied: "पहुँच नहीं मिली; मॉड्यूल बंद रहेगा।",
    levels: {
      operational: "सामान्य",
      degraded: "प्रदर्शन कम",
      outage: "सेवा बाधित",
      maintenance: "रखरखाव",
      unknown: "अज्ञात",
    },
    failures: {
      permission_missing: "स्थिति पृष्ठ की अनुमति नहीं मिली",
      offline: "स्थिति पृष्ठ तक नहीं पहुँचा जा सका",
      timeout: "स्थिति अनुरोध का समय समाप्त हुआ",
      rate_limited: "स्थिति पृष्ठ ने अनुरोध अस्थायी रूप से सीमित किए",
      http_error: "स्थिति पृष्ठ ने त्रुटि लौटाई",
      invalid_response: "स्थिति प्रतिक्रिया सत्यापित नहीं हो सकी",
    },
  },
  id: {
    eyebrow: "Status layanan",
    settingsTitle: "Status layanan resmi",
    settingsDetail: "Tampilkan status publik resmi per tampilan. Modul tersembunyi tidak meminta data.",
    officialSource: "Status resmi",
    openStatusPage: "Buka halaman status resmi",
    incident: "Insiden aktif",
    stale: "Status tidak tersedia",
    notChecked: "Belum diperiksa",
    accessDenied: "Akses tidak diberikan; modul tetap nonaktif.",
    levels: {
      operational: "Beroperasi",
      degraded: "Kinerja menurun",
      outage: "Gangguan",
      maintenance: "Pemeliharaan",
      unknown: "Tidak diketahui",
    },
    failures: {
      permission_missing: "Akses ke halaman status belum diberikan",
      offline: "Halaman status tidak dapat dijangkau",
      timeout: "Permintaan status kehabisan waktu",
      rate_limited: "Halaman status membatasi permintaan sementara",
      http_error: "Halaman status mengembalikan kesalahan",
      invalid_response: "Respons status tidak dapat diverifikasi",
    },
  },
};

export function buildProviderServiceStatusLocalizedCopy(
  locale: ResolvedAppLocale,
): ProviderServiceStatusLocalizedCopy {
  const override = LOCALIZED_OVERRIDES[locale];
  return {
    ...ENGLISH_COPY,
    ...override,
    levels: {
      ...ENGLISH_COPY.levels,
      ...override?.levels,
    },
    failures: {
      ...ENGLISH_COPY.failures,
      ...override?.failures,
    },
    vendors: {
      ...ENGLISH_COPY.vendors,
      ...override?.vendors,
    },
  };
}
