import type { ResolvedAppLocale } from "./i18n";

export type QuotaNotificationLocalizedCopy = {
  eyebrow: string;
  title: string;
  enabled: string;
  paused: string;
  threshold: string;
  percent: string;
  accounts: string;
  windows: string;
  windowKindLabels: Record<
    "rolling_5h" | "weekly" | "model_rolling_5h" | "model_weekly",
    string
  >;
  noAccounts: string;
  noSupportedWindows: string;
  loading: string;
  permissionNotGranted: string;
  permissionUnsupported: string;
  pausedStatus: string;
  readyStatus: string;
  unavailable: string;
  saveFailed: string;
  test: string;
  testSent: string;
  testFailed: string;
  notifyLowTitle: string;
  notifyLowBody: string;
  notifyResetTitle: string;
  notifyResetBody: string;
  notifyTestTitle: string;
  notifyTestBody: string;
};

const COPY: Record<ResolvedAppLocale, QuotaNotificationLocalizedCopy> = {
  en: {
    eyebrow: "Notifications",
    title: "Quota notifications",
    enabled: "Enable notifications",
    paused: "Pause notifications",
    threshold: "Notification trigger threshold",
    percent: "%",
    accounts: "Accounts",
    windows: "Usage windows",
    windowKindLabels: {
      rolling_5h: "5-hour usage",
      weekly: "Weekly usage",
      model_rolling_5h: "5-hour model usage",
      model_weekly: "Weekly model usage",
    },
    noAccounts: "No accounts are available for notifications.",
    noSupportedWindows: "No supported usage windows are available for notifications.",
    loading: "Loading notification settings",
    permissionNotGranted: "Notification permission is not granted.",
    permissionUnsupported: "Notifications are not supported in this browser.",
    pausedStatus: "Notifications are paused.",
    readyStatus: "Notifications are ready.",
    unavailable: "Notification settings are unavailable.",
    saveFailed: "Notification settings could not be updated.",
    test: "Send test notification",
    testSent: "Test notification sent.",
    testFailed: "Test notification could not be sent.",
    notifyLowTitle: "{provider} quota is low",
    notifyLowBody: "{provider}: {remaining}% remaining",
    notifyResetTitle: "{provider} quota reset",
    notifyResetBody: "{provider} quota is available again.",
    notifyTestTitle: "Quota notifications are on",
    notifyTestBody: "This is a test notification from AI Usage Dashboard.",
  },
  "zh-CN": {
    eyebrow: "通知",
    title: "用量通知",
    enabled: "启用通知",
    paused: "暂停通知",
    threshold: "通知触发阈值",
    percent: "%",
    accounts: "账户",
    windows: "用量窗口",
    windowKindLabels: {
      rolling_5h: "5 小时用量",
      weekly: "每周用量",
      model_rolling_5h: "模型 5 小时用量",
      model_weekly: "模型每周用量",
    },
    noAccounts: "没有可用于通知的账户。",
    noSupportedWindows: "没有可用于通知的受支持用量窗口。",
    loading: "正在加载通知设置",
    permissionNotGranted: "尚未授予通知权限。",
    permissionUnsupported: "此浏览器不支持通知。",
    pausedStatus: "通知已暂停。",
    readyStatus: "通知已准备就绪。",
    unavailable: "通知设置不可用。",
    saveFailed: "无法更新通知设置。",
    test: "发送测试通知",
    testSent: "已发送测试通知。",
    testFailed: "无法发送测试通知。",
    notifyLowTitle: "{provider} 配额较低",
    notifyLowBody: "{provider} 剩余 {remaining}%",
    notifyResetTitle: "{provider} 配额已重置",
    notifyResetBody: "{provider} 配额现已恢复可用。",
    notifyTestTitle: "配额通知已开启",
    notifyTestBody: "这是来自 AI Usage Dashboard 的测试通知。",
  },
  "zh-TW": {
    eyebrow: "通知",
    title: "用量通知",
    enabled: "啟用通知",
    paused: "暫停通知",
    threshold: "通知觸發閾值",
    percent: "%",
    accounts: "帳戶",
    windows: "用量視窗",
    windowKindLabels: {
      rolling_5h: "5 小時用量",
      weekly: "每週用量",
      model_rolling_5h: "模型 5 小時用量",
      model_weekly: "模型每週用量",
    },
    noAccounts: "沒有可用於通知的帳戶。",
    noSupportedWindows: "沒有可用於通知的支援用量視窗。",
    loading: "正在載入通知設定",
    permissionNotGranted: "尚未授予通知權限。",
    permissionUnsupported: "此瀏覽器不支援通知。",
    pausedStatus: "通知已暫停。",
    readyStatus: "通知已準備就緒。",
    unavailable: "通知設定無法使用。",
    saveFailed: "無法更新通知設定。",
    test: "傳送測試通知",
    testSent: "已傳送測試通知。",
    testFailed: "無法傳送測試通知。",
    notifyLowTitle: "{provider} 配額偏低",
    notifyLowBody: "{provider} 剩餘 {remaining}%",
    notifyResetTitle: "{provider} 配額已重置",
    notifyResetBody: "{provider} 配額現在可再次使用。",
    notifyTestTitle: "配額通知已開啟",
    notifyTestBody: "這是來自 AI Usage Dashboard 的測試通知。",
  },
  ja: {
    eyebrow: "通知",
    title: "使用量の通知",
    enabled: "通知を有効にする",
    paused: "通知を一時停止する",
    threshold: "通知のトリガーしきい値",
    percent: "%",
    accounts: "アカウント",
    windows: "使用量ウィンドウ",
    windowKindLabels: {
      rolling_5h: "5 時間の使用量",
      weekly: "週間使用量",
      model_rolling_5h: "モデルの 5 時間使用量",
      model_weekly: "モデルの週間使用量",
    },
    noAccounts: "通知に使用できるアカウントはありません。",
    noSupportedWindows: "通知に対応した使用量ウィンドウはありません。",
    loading: "通知設定を読み込み中",
    permissionNotGranted: "通知の権限が許可されていません。",
    permissionUnsupported: "このブラウザは通知に対応していません。",
    pausedStatus: "通知は一時停止中です。",
    readyStatus: "通知の準備ができました。",
    unavailable: "通知設定を利用できません。",
    saveFailed: "通知設定を更新できませんでした。",
    test: "テスト通知を送信",
    testSent: "テスト通知を送信しました。",
    testFailed: "テスト通知を送信できませんでした。",
    notifyLowTitle: "{provider} の割り当てが少なくなっています",
    notifyLowBody: "{provider}: 残り {remaining}%",
    notifyResetTitle: "{provider} の割り当てがリセットされました",
    notifyResetBody: "{provider} の割り当てを再び利用できます。",
    notifyTestTitle: "割り当て通知はオンです",
    notifyTestBody: "AI Usage Dashboard からのテスト通知です。",
  },
  ko: {
    eyebrow: "알림",
    title: "할당량 알림",
    enabled: "알림 사용",
    paused: "알림 일시중지",
    threshold: "알림 트리거 임계값",
    percent: "%",
    accounts: "계정",
    windows: "사용량 기간",
    windowKindLabels: {
      rolling_5h: "5시간 사용량",
      weekly: "주간 사용량",
      model_rolling_5h: "모델 5시간 사용량",
      model_weekly: "모델 주간 사용량",
    },
    noAccounts: "알림에 사용할 수 있는 계정이 없습니다.",
    noSupportedWindows: "알림에 지원되는 사용량 기간이 없습니다.",
    loading: "알림 설정을 불러오는 중",
    permissionNotGranted: "알림 권한이 허용되지 않았습니다.",
    permissionUnsupported: "이 브라우저에서는 알림을 지원하지 않습니다.",
    pausedStatus: "알림이 일시중지되었습니다.",
    readyStatus: "알림이 준비되었습니다.",
    unavailable: "알림 설정을 사용할 수 없습니다.",
    saveFailed: "알림 설정을 업데이트할 수 없습니다.",
    test: "테스트 알림 보내기",
    testSent: "테스트 알림을 보냈습니다.",
    testFailed: "테스트 알림을 보낼 수 없습니다.",
    notifyLowTitle: "{provider} 할당량이 부족합니다",
    notifyLowBody: "{provider}: {remaining}% 남음",
    notifyResetTitle: "{provider} 할당량이 초기화되었습니다",
    notifyResetBody: "{provider} 할당량을 다시 사용할 수 있습니다.",
    notifyTestTitle: "할당량 알림이 켜져 있습니다",
    notifyTestBody: "AI Usage Dashboard의 테스트 알림입니다.",
  },
  "es-419": {
    eyebrow: "Notificaciones",
    title: "Notificaciones de cuota",
    enabled: "Activar notificaciones",
    paused: "Pausar notificaciones",
    threshold: "Umbral de activación de notificaciones",
    percent: "%",
    accounts: "Cuentas",
    windows: "Periodos de uso",
    windowKindLabels: {
      rolling_5h: "Uso de 5 horas",
      weekly: "Uso semanal",
      model_rolling_5h: "Uso de modelo de 5 horas",
      model_weekly: "Uso semanal de modelo",
    },
    noAccounts: "No hay cuentas disponibles para notificaciones.",
    noSupportedWindows: "No hay periodos de uso compatibles para notificaciones.",
    loading: "Cargando la configuración de notificaciones",
    permissionNotGranted: "El permiso de notificaciones no esta concedido.",
    permissionUnsupported: "Este navegador no admite notificaciones.",
    pausedStatus: "Las notificaciones están pausadas.",
    readyStatus: "Las notificaciones están listas.",
    unavailable: "La configuración de notificaciones no está disponible.",
    saveFailed: "No se pudo actualizar la configuración de notificaciones.",
    test: "Enviar notificación de prueba",
    testSent: "Notificación de prueba enviada.",
    testFailed: "No se pudo enviar la notificación de prueba.",
    notifyLowTitle: "La cuota de {provider} es baja",
    notifyLowBody: "{provider}: queda {remaining}%",
    notifyResetTitle: "La cuota de {provider} se restableció",
    notifyResetBody: "La cuota de {provider} está disponible nuevamente.",
    notifyTestTitle: "Las notificaciones de cuota están activas",
    notifyTestBody: "Esta es una notificación de prueba de AI Usage Dashboard.",
  },
  "pt-BR": {
    eyebrow: "Notificações",
    title: "Notificações de cota",
    enabled: "Ativar notificações",
    paused: "Pausar notificações",
    threshold: "Limite para notificações",
    percent: "%",
    accounts: "Contas",
    windows: "Janelas de uso",
    windowKindLabels: {
      rolling_5h: "Uso de 5 horas",
      weekly: "Uso semanal",
      model_rolling_5h: "Uso de modelo de 5 horas",
      model_weekly: "Uso semanal de modelo",
    },
    noAccounts: "Não há contas disponíveis para notificações.",
    noSupportedWindows: "Não há janelas de uso compatíveis para notificações.",
    loading: "Carregando configurações de notificação",
    permissionNotGranted: "A permissão de notificações não foi concedida.",
    permissionUnsupported: "Este navegador não oferece suporte a notificações.",
    pausedStatus: "As notificações estão pausadas.",
    readyStatus: "As notificações estão prontas.",
    unavailable: "As configurações de notificação não estão disponíveis.",
    saveFailed: "Não foi possível atualizar as configurações de notificação.",
    test: "Enviar notificação de teste",
    testSent: "Notificação de teste enviada.",
    testFailed: "Não foi possível enviar a notificação de teste.",
    notifyLowTitle: "A cota de {provider} está baixa",
    notifyLowBody: "{provider}: {remaining}% restante",
    notifyResetTitle: "A cota de {provider} foi redefinida",
    notifyResetBody: "A cota de {provider} está disponível novamente.",
    notifyTestTitle: "As notificações de cota estão ativadas",
    notifyTestBody: "Esta é uma notificação de teste do AI Usage Dashboard.",
  },
  fr: {
    eyebrow: "Notifications",
    title: "Notifications de quota",
    enabled: "Activer les notifications",
    paused: "Mettre les notifications en pause",
    threshold: "Seuil de déclenchement des notifications",
    percent: "%",
    accounts: "Comptes",
    windows: "Fenêtres d'utilisation",
    windowKindLabels: {
      rolling_5h: "Utilisation sur 5 heures",
      weekly: "Utilisation hebdomadaire",
      model_rolling_5h: "Utilisation de modèle sur 5 heures",
      model_weekly: "Utilisation hebdomadaire de modèle",
    },
    noAccounts: "Aucun compte n'est disponible pour les notifications.",
    noSupportedWindows: "Aucune fenêtre d'utilisation compatible n'est disponible pour les notifications.",
    loading: "Chargement des paramètres de notification",
    permissionNotGranted: "L'autorisation des notifications n'est pas accordée.",
    permissionUnsupported: "Les notifications ne sont pas prises en charge par ce navigateur.",
    pausedStatus: "Les notifications sont en pause.",
    readyStatus: "Les notifications sont prêtes.",
    unavailable: "Les paramètres de notification ne sont pas disponibles.",
    saveFailed: "Les paramètres de notification n'ont pas pu être mis à jour.",
    test: "Envoyer une notification de test",
    testSent: "Notification de test envoyée.",
    testFailed: "La notification de test n'a pas pu être envoyée.",
    notifyLowTitle: "Le quota de {provider} est faible",
    notifyLowBody: "{provider}: {remaining}% restant",
    notifyResetTitle: "Le quota de {provider} a été réinitialisé",
    notifyResetBody: "Le quota de {provider} est à nouveau disponible.",
    notifyTestTitle: "Les notifications de quota sont activées",
    notifyTestBody: "Ceci est une notification de test de AI Usage Dashboard.",
  },
  de: {
    eyebrow: "Benachrichtigungen",
    title: "Kontingentbenachrichtigungen",
    enabled: "Benachrichtigungen aktivieren",
    paused: "Benachrichtigungen pausieren",
    threshold: "Schwelle für Benachrichtigungen",
    percent: "%",
    accounts: "Konten",
    windows: "Nutzungsfenster",
    windowKindLabels: {
      rolling_5h: "5-Stunden-Nutzung",
      weekly: "Wöchentliche Nutzung",
      model_rolling_5h: "5-Stunden-Modellnutzung",
      model_weekly: "Wöchentliche Modellnutzung",
    },
    noAccounts: "Keine Konten für Benachrichtigungen verfügbar.",
    noSupportedWindows: "Keine unterstützten Nutzungsfenster für Benachrichtigungen verfügbar.",
    loading: "Benachrichtigungseinstellungen werden geladen",
    permissionNotGranted: "Die Benachrichtigungsberechtigung ist nicht erteilt.",
    permissionUnsupported: "Dieser Browser unterstützt keine Benachrichtigungen.",
    pausedStatus: "Benachrichtigungen sind pausiert.",
    readyStatus: "Benachrichtigungen sind bereit.",
    unavailable: "Benachrichtigungseinstellungen sind nicht verfügbar.",
    saveFailed: "Benachrichtigungseinstellungen konnten nicht aktualisiert werden.",
    test: "Testbenachrichtigung senden",
    testSent: "Testbenachrichtigung gesendet.",
    testFailed: "Testbenachrichtigung konnte nicht gesendet werden.",
    notifyLowTitle: "{provider}-Kontingent ist niedrig",
    notifyLowBody: "{provider}: {remaining}% verbleibend",
    notifyResetTitle: "{provider}-Kontingent wurde zurückgesetzt",
    notifyResetBody: "{provider}-Kontingent ist wieder verfügbar.",
    notifyTestTitle: "Kontingentbenachrichtigungen sind aktiviert",
    notifyTestBody: "Dies ist eine Testbenachrichtigung von AI Usage Dashboard.",
  },
  it: {
    eyebrow: "Notifiche",
    title: "Notifiche quota",
    enabled: "Abilita notifiche",
    paused: "Sospendi notifiche",
    threshold: "Soglia per le notifiche",
    percent: "%",
    accounts: "Account",
    windows: "Finestre di utilizzo",
    windowKindLabels: {
      rolling_5h: "Utilizzo di 5 ore",
      weekly: "Utilizzo settimanale",
      model_rolling_5h: "Utilizzo modello di 5 ore",
      model_weekly: "Utilizzo modello settimanale",
    },
    noAccounts: "Non sono disponibili account per le notifiche.",
    noSupportedWindows: "Non sono disponibili finestre di utilizzo supportate per le notifiche.",
    loading: "Caricamento impostazioni notifiche",
    permissionNotGranted: "L'autorizzazione alle notifiche non e concessa.",
    permissionUnsupported: "Questo browser non supporta le notifiche.",
    pausedStatus: "Le notifiche sono sospese.",
    readyStatus: "Le notifiche sono pronte.",
    unavailable: "Le impostazioni delle notifiche non sono disponibili.",
    saveFailed: "Non e stato possibile aggiornare le impostazioni delle notifiche.",
    test: "Invia notifica di prova",
    testSent: "Notifica di prova inviata.",
    testFailed: "Non e stato possibile inviare la notifica di prova.",
    notifyLowTitle: "La quota di {provider} e bassa",
    notifyLowBody: "{provider}: {remaining}% rimanente",
    notifyResetTitle: "La quota di {provider} e stata reimpostata",
    notifyResetBody: "La quota di {provider} e di nuovo disponibile.",
    notifyTestTitle: "Le notifiche quota sono attive",
    notifyTestBody: "Questa e una notifica di prova di AI Usage Dashboard.",
  },
  ru: {
    eyebrow: "Уведомления",
    title: "Уведомления о квоте",
    enabled: "Включить уведомления",
    paused: "Приостановить уведомления",
    threshold: "Порог для уведомлений",
    percent: "%",
    accounts: "Учетные записи",
    windows: "Окна использования",
    windowKindLabels: {
      rolling_5h: "Использование за 5 часов",
      weekly: "Еженедельное использование",
      model_rolling_5h: "Использование модели за 5 часов",
      model_weekly: "Еженедельное использование модели",
    },
    noAccounts: "Нет учетных записей для уведомлений.",
    noSupportedWindows: "Нет поддерживаемых окон использования для уведомлений.",
    loading: "Загрузка настроек уведомлений",
    permissionNotGranted: "Разрешение на уведомления не предоставлено.",
    permissionUnsupported: "Этот браузер не поддерживает уведомления.",
    pausedStatus: "Уведомления приостановлены.",
    readyStatus: "Уведомления готовы.",
    unavailable: "Настройки уведомлений недоступны.",
    saveFailed: "Не удалось обновить настройки уведомлений.",
    test: "Отправить тестовое уведомление",
    testSent: "Тестовое уведомление отправлено.",
    testFailed: "Не удалось отправить тестовое уведомление.",
    notifyLowTitle: "Квота {provider} заканчивается",
    notifyLowBody: "{provider}: осталось {remaining}%",
    notifyResetTitle: "Квота {provider} сброшена",
    notifyResetBody: "Квота {provider} снова доступна.",
    notifyTestTitle: "Уведомления о квоте включены",
    notifyTestBody: "Это тестовое уведомление от AI Usage Dashboard.",
  },
  ar: {
    eyebrow: "الإشعارات",
    title: "إشعارات الحصة",
    enabled: "تفعيل الإشعارات",
    paused: "إيقاف الإشعارات مؤقتا",
    threshold: "عتبة تشغيل الإشعارات",
    percent: "%",
    accounts: "الحسابات",
    windows: "نوافذ الاستخدام",
    windowKindLabels: {
      rolling_5h: "استخدام 5 ساعات",
      weekly: "استخدام أسبوعي",
      model_rolling_5h: "استخدام نموذج 5 ساعات",
      model_weekly: "استخدام نموذج أسبوعي",
    },
    noAccounts: "لا توجد حسابات متاحة للإشعارات.",
    noSupportedWindows: "لا توجد نوافذ استخدام مدعومة للإشعارات.",
    loading: "جار تحميل إعدادات الإشعارات",
    permissionNotGranted: "لم يتم منح إذن الإشعارات.",
    permissionUnsupported: "هذا المتصفح لا يدعم الإشعارات.",
    pausedStatus: "الإشعارات متوقفة مؤقتا.",
    readyStatus: "الإشعارات جاهزة.",
    unavailable: "إعدادات الإشعارات غير متاحة.",
    saveFailed: "تعذر تحديث إعدادات الإشعارات.",
    test: "إرسال إشعار اختباري",
    testSent: "تم إرسال الإشعار الاختباري.",
    testFailed: "تعذر إرسال الإشعار الاختباري.",
    notifyLowTitle: "حصة {provider} منخفضة",
    notifyLowBody: "{provider}: المتبقي {remaining}%",
    notifyResetTitle: "تمت إعادة تعيين حصة {provider}",
    notifyResetBody: "حصة {provider} متاحة مرة أخرى.",
    notifyTestTitle: "إشعارات الحصة مفعلة",
    notifyTestBody: "هذا إشعار اختباري من AI Usage Dashboard.",
  },
  hi: {
    eyebrow: "सूचनाएं",
    title: "कोटा सूचनाएं",
    enabled: "सूचनाएं चालू करें",
    paused: "सूचनाएं रोकें",
    threshold: "सूचना ट्रिगर सीमा",
    percent: "%",
    accounts: "खाते",
    windows: "उपयोग विंडो",
    windowKindLabels: {
      rolling_5h: "5 घंटे का उपयोग",
      weekly: "साप्ताहिक उपयोग",
      model_rolling_5h: "मॉडल का 5 घंटे का उपयोग",
      model_weekly: "मॉडल का साप्ताहिक उपयोग",
    },
    noAccounts: "सूचनाओं के लिए कोई खाता उपलब्ध नहीं है।",
    noSupportedWindows: "सूचनाओं के लिए कोई समर्थित उपयोग विंडो उपलब्ध नहीं है।",
    loading: "सूचना सेटिंग लोड हो रही हैं",
    permissionNotGranted: "सूचना अनुमति प्रदान नहीं की गई है।",
    permissionUnsupported: "यह ब्राउज़र सूचनाओं का समर्थन नहीं करता।",
    pausedStatus: "सूचनाएं रोकी गई हैं।",
    readyStatus: "सूचनाएं तैयार हैं।",
    unavailable: "सूचना सेटिंग उपलब्ध नहीं हैं।",
    saveFailed: "सूचना सेटिंग अपडेट नहीं की जा सकीं।",
    test: "परीक्षण सूचना भेजें",
    testSent: "परीक्षण सूचना भेजी गई।",
    testFailed: "परीक्षण सूचना नहीं भेजी जा सकी।",
    notifyLowTitle: "{provider} कोटा कम है",
    notifyLowBody: "{provider}: {remaining}% शेष",
    notifyResetTitle: "{provider} कोटा रीसेट हुआ",
    notifyResetBody: "{provider} कोटा फिर से उपलब्ध है।",
    notifyTestTitle: "कोटा सूचनाएं चालू हैं",
    notifyTestBody: "यह AI Usage Dashboard से एक परीक्षण सूचना है।",
  },
  id: {
    eyebrow: "Notifikasi",
    title: "Notifikasi kuota",
    enabled: "Aktifkan notifikasi",
    paused: "Jeda notifikasi",
    threshold: "Ambang pemicu notifikasi",
    percent: "%",
    accounts: "Akun",
    windows: "Jendela penggunaan",
    windowKindLabels: {
      rolling_5h: "Penggunaan 5 jam",
      weekly: "Penggunaan mingguan",
      model_rolling_5h: "Penggunaan model 5 jam",
      model_weekly: "Penggunaan model mingguan",
    },
    noAccounts: "Tidak ada akun yang tersedia untuk notifikasi.",
    noSupportedWindows: "Tidak ada jendela penggunaan yang didukung untuk notifikasi.",
    loading: "Memuat pengaturan notifikasi",
    permissionNotGranted: "Izin notifikasi belum diberikan.",
    permissionUnsupported: "Browser ini tidak mendukung notifikasi.",
    pausedStatus: "Notifikasi dijeda.",
    readyStatus: "Notifikasi siap.",
    unavailable: "Pengaturan notifikasi tidak tersedia.",
    saveFailed: "Pengaturan notifikasi tidak dapat diperbarui.",
    test: "Kirim notifikasi percobaan",
    testSent: "Notifikasi percobaan terkirim.",
    testFailed: "Notifikasi percobaan tidak dapat dikirim.",
    notifyLowTitle: "Kuota {provider} rendah",
    notifyLowBody: "{provider}: {remaining}% tersisa",
    notifyResetTitle: "Kuota {provider} direset",
    notifyResetBody: "Kuota {provider} tersedia lagi.",
    notifyTestTitle: "Notifikasi kuota aktif",
    notifyTestBody: "Ini adalah notifikasi percobaan dari AI Usage Dashboard.",
  },
};

export function buildQuotaNotificationLocalizedCopy(
  locale: ResolvedAppLocale,
): QuotaNotificationLocalizedCopy {
  return COPY[locale];
}
