import type { ResolvedAppLocale, RuntimeMessages } from "./i18n";

const EN_RUNTIME_MESSAGES = {
    "app.loading.eyebrow": "Loading",
    "app.loading.title": "Preparing dashboard state",
    "app.loading.detail": "Initializing the dashboard store and message bus.",
    "app.error.eyebrow": "State Unavailable",
    "app.error.title": "Initialization did not complete",
    "app.error.detail_fallback": "The app state could not be loaded from extension storage or local preview storage.",
    "common.actions.retry": "Retry",
    "common.actions.settings": "Settings",
    "common.actions.refresh": "Refresh",
    "common.actions.refresh_all": "Refresh All",
    "common.actions.back": "Back",
    "common.actions.open_dashboard": "Open dashboard",
    "common.actions.open_settings": "Open settings",
    "common.actions.open_dashboard_tab": "Open dashboard tab",
    "common.actions.open_settings_tab": "Open settings tab",
    "common.actions.tab": "Tab",
    "common.actions.save": "Save",
    "common.theme.toggle_to_dark_label": "Dark",
    "common.theme.toggle_to_dark_title": "Switch to dark mode",
    "common.theme.toggle_to_light_label": "Light",
    "common.theme.toggle_to_light_title": "Switch to light mode",
    "dashboard.topbar.title": "AI Usage Dashboard",
    "dashboard.topbar.subtitle": "Usage, credits, and sync health",
    "dashboard.hero.eyebrow": "Overview",
    "dashboard.hero.title": "One panel for AI coding quotas",
    "dashboard.hero.detail": "Official APIs, documented quota policies, and guarded page-parse sources are collected into one release-ready dashboard for refreshes, settings, and provider drill-downs.",
    "dashboard.hero.release_chip": "Material 3 · Release Candidate",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Provider cards",
    "dashboard.providers.detail": "Cards are ordered by severity first, then current access gaps, so the highest-risk providers stay at the top of the dashboard while still exposing the current product contract at a glance.",
    "dashboard.providers.aria": "Provider cards",
    "dashboard.empty.eyebrow": "No Visible Providers",
    "dashboard.empty.detail": "Start in Quick Setup to enable your first provider, then follow the access and usage-page steps before returning to the dashboard.",
    "dashboard.empty.action": "Open Quick Setup",
    "dashboard.summary.aria": "Dashboard summary",
    "dashboard.summary.visible": "Visible",
    "dashboard.summary.healthy": "Healthy",
    "dashboard.summary.needs_access": "Needs Access",
    "dashboard.summary.needs_attention": "Needs Attention",
    "popup.loading.eyebrow": "Toolbar Popup",
    "popup.loading.title": "Loading cached dashboard state",
    "popup.loading.detail": "Preparing the shared quota snapshot for this browser profile.",
    "popup.error.eyebrow": "Toolbar Popup",
    "popup.error.title": "Popup load failed",
    "popup.header.eyebrow": "Toolbar Popup",
    "popup.header.title": "Quick glance",
    "popup.summary.aria": "Popup top summary",
    "popup.guidance.eyebrow": "Popup Guidance",
    "popup.snapshot_status.eyebrow": "Snapshot Status",
    "popup.actions.eyebrow": "Other route",
    "popup.actions.refresh": "Refresh",
    "popup.actions.refreshing": "Refreshing",
    "popup.featured.eyebrow": "Featured providers",
    "popup.featured.single_eyebrow": "Featured provider",
    "popup.triage.eyebrow": "Popup Triage",
    "popup.summary.visible": "Visible",
    "popup.summary.live_ready": "Live ready",
    "popup.summary.setup_blockers": "Setup blockers",
    "popup.summary.policy_only": "Policy-only",
    "settings.topbar.title": "Settings",
    "settings.topbar.subtitle": "Quick setup, appearance, and advanced provider controls",
    "settings.overview.eyebrow": "Settings Overview",
    "settings.overview.title": "Control surface summary",
    "settings.overview.detail": "Use this screen to manage visibility, permissions, credentials, and hybrid source controls. Jump directly to the section you need instead of scanning the full page top to bottom.",
    "settings.overview.aria": "Settings overview",
    "settings.sections.aria": "Settings sections",
    "settings.sections.preferences": "Preferences",
    "settings.sections.visibility": "Visibility",
    "settings.sections.credentials": "Credentials",
    "settings.sections.sources": "Sources",
    "settings.sections.permissions": "Permissions",
    "settings.actions.back_to_top": "Back to top",
    "settings.actions.back_to_top_short": "Top",
    "settings.summary.visible": "Visible",
    "settings.summary.stored_secrets": "Stored Secrets",
    "settings.summary.bound_pages": "Bound Pages",
    "settings.summary.needs_access": "Needs Access",
    "settings.preferences.eyebrow": "Appearance & Sync",
    "settings.preferences.sync_interval_label": "Default sync interval",
    "settings.preferences.warning_threshold_label": "Warning threshold",
    "settings.preferences.locale_label": "App language",
    "settings.preferences.theme_mode_label": "Theme mode",
    "settings.preferences.accent_preset_label": "Accent preset",
    "settings.preferences.popup_progress_style_label": "Popup quota style",
    "settings.preferences.sidebar_progress_style_label": "Sidebar quota style",
    "settings.preferences.full_page_progress_style_label": "Tab quota style",
    "settings.preferences.progress_style.line": "Line",
    "settings.preferences.progress_style.circle": "Circle",
    "settings.preferences.popup_size_label": "Popup size",
    "settings.preferences.popup_size.compact": "Compact",
    "settings.preferences.popup_size.balanced": "Balanced",
    "settings.preferences.popup_size.wide": "Wide",
    "settings.preferences.popup_corner_label": "Popup corners",
    "settings.preferences.popup_corner.square": "Square",
    "settings.preferences.popup_corner.soft": "Soft",
    "settings.preferences.popup_corner.rounded": "Rounded",
    "settings.preferences.popup_shadow_label": "Popup shadow",
    "settings.preferences.popup_shadow.none": "None",
    "settings.preferences.popup_shadow.soft": "Soft",
    "settings.preferences.popup_shadow.elevated": "Elevated",
    "settings.preferences.action_badge_label": "Toolbar badge",
    "settings.popup_appearance_preview.eyebrow": "Popup Preview",
    "settings.popup_appearance_preview.title": "Toolbar bubble shape",
    "settings.popup_appearance_preview.detail": "Preview the selected popup width, corner, and shadow treatment before reopening the Chrome action.",
    "settings.popup_appearance_preview.sample_refresh": "Refresh",
    "settings.popup_appearance_preview.sample_tab": "Tab",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "Weekly usage window",
    "settings.preferences.minutes": "minutes",
    "settings.preferences.locale.system": "System",
    "settings.preferences.locale.en": "English",
    "settings.preferences.locale.zh_cn": "Simplified Chinese",
    "settings.preferences.theme_mode.system": "System",
    "settings.preferences.theme_mode.light": "Light",
    "settings.preferences.theme_mode.dark": "Dark",
    "settings.preferences.theme_preset.default": "Default Blue",
    "settings.preferences.theme_preset.meadow": "Meadow",
    "settings.preferences.theme_preset.sunset": "Sunset",
    "settings.preferences.theme_preset.custom": "Custom Seed",
    "settings.theme_customization.eyebrow": "Custom Seed",
    "settings.theme_customization.title": "Validated accent seed",
    "settings.theme_customization.detail": "Use one validated #RRGGBB seed instead of editing individual theme tokens. The generated accent roles stay shared across the side panel, popup, and audit hub.",
    "settings.theme_customization.seed_label": "Custom seed color",
    "settings.theme_customization.apply": "Apply custom seed",
    "settings.theme_customization.reset": "Reset to default",
    "settings.theme_customization.preview.aria": "Custom seed preview",
    "settings.theme_customization.preview.primary": "Primary",
    "settings.theme_customization.preview.secondary_container": "Secondary container",
    "settings.theme_customization.preview.tertiary": "Tertiary",
    "settings.visibility.eyebrow": "Provider Visibility",
    "settings.visibility.enabled_detail": "Visible in the dashboard.",
    "settings.visibility.disabled_detail": "Hidden from the dashboard.",
    "settings.credentials.eyebrow": "Credentials",
    "settings.credentials.title": "Stored secrets and workspace config",
    "settings.credentials.detail": "These cards manage extension-local secrets for supported admin and enterprise paths. Personal session-page routes still avoid cookie export and do not ask for manual auth-header paste.",
    "settings.sources.eyebrow": "Source Connections",
    "settings.sources.title": "Hybrid source contracts",
    "settings.sources.detail": "These cards explain whether each provider currently syncs from an official API, a logged-in page session, or documented quota policy, plus the explicit shipped or deferred product contract for each path.",
    "settings.permissions.eyebrow": "Host Access",
    "settings.permissions.title": "Permission controls",
    "settings.permissions.detail": "In extension mode these actions use chrome.permissions. In browser preview mode they fall back to local state simulation.",
    "settings.toast.preferences_saved_title": "Preferences saved",
    "settings.toast.preferences_saved_detail": "Settings are now persisted in local dashboard state for the preview.",
} satisfies RuntimeMessages;

const RUNTIME_MESSAGE_OVERRIDES: Partial<
  Record<ResolvedAppLocale, Partial<RuntimeMessages>>
> = {
  "zh-CN": {
    "app.loading.eyebrow": "加载中",
    "app.loading.title": "正在准备仪表板状态",
    "app.loading.detail": "正在初始化仪表板存储和消息总线。",
    "app.error.eyebrow": "状态不可用",
    "app.error.title": "初始化未完成",
    "app.error.detail_fallback": "无法从扩展存储或本地预览存储加载应用状态。",
    "common.actions.retry": "重试",
    "common.actions.settings": "设置",
    "common.actions.refresh": "刷新",
    "common.actions.refresh_all": "全部刷新",
    "common.actions.back": "返回",
    "common.actions.open_dashboard": "打开仪表板",
    "common.actions.open_settings": "打开设置",
    "common.actions.open_dashboard_tab": "打开仪表板标签页",
    "common.actions.open_settings_tab": "打开设置标签页",
    "common.actions.tab": "标签页",
    "common.actions.save": "保存",
    "common.theme.toggle_to_dark_label": "夜间",
    "common.theme.toggle_to_dark_title": "切换到夜间模式",
    "common.theme.toggle_to_light_label": "白天",
    "common.theme.toggle_to_light_title": "切换到白天模式",
    "dashboard.topbar.title": "AI 用量仪表板",
    "dashboard.topbar.subtitle": "用量、额度与同步健康",
    "dashboard.hero.eyebrow": "概览",
    "dashboard.hero.title": "一个面板掌握 AI 编码配额",
    "dashboard.hero.detail": "官方 API、文档化配额策略与受控页面解析路径，被收敛到一个可发布的仪表板里，用于刷新、设置和 Provider 深入查看。",
    "dashboard.hero.release_chip": "Material 3 · 发布候选",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 卡片",
    "dashboard.providers.detail": "卡片先按严重程度排序，再按当前访问缺口排序，让高风险 provider 保持在顶部，同时保留当前产品合同的一眼可见性。",
    "dashboard.providers.aria": "Provider 卡片",
    "dashboard.empty.eyebrow": "没有可见 Provider",
    "dashboard.empty.detail": "请先进入 Quick Setup 启用第一个 Provider，再按提示完成授权和用量页面步骤，然后回到仪表板。",
    "dashboard.empty.action": "打开 Quick Setup",
    "dashboard.summary.aria": "仪表板摘要",
    "dashboard.summary.visible": "可见",
    "dashboard.summary.healthy": "健康",
    "dashboard.summary.needs_access": "需授权",
    "dashboard.summary.needs_attention": "需关注",
    "popup.loading.eyebrow": "工具栏弹窗",
    "popup.loading.title": "正在加载缓存的仪表板状态",
    "popup.loading.detail": "正在为此浏览器配置文件准备共享配额快照。",
    "popup.error.eyebrow": "工具栏弹窗",
    "popup.error.title": "弹窗加载失败",
    "popup.header.eyebrow": "工具栏弹窗",
    "popup.header.title": "快速概览",
    "popup.summary.aria": "弹窗顶部摘要",
    "popup.guidance.eyebrow": "弹窗引导",
    "popup.snapshot_status.eyebrow": "快照状态",
    "popup.actions.eyebrow": "其他入口",
    "popup.actions.refresh": "刷新",
    "popup.actions.refreshing": "刷新中",
    "popup.featured.eyebrow": "重点 Provider",
    "popup.featured.single_eyebrow": "重点 Provider",
    "popup.triage.eyebrow": "弹窗分诊",
    "popup.summary.visible": "可见",
    "popup.summary.live_ready": "可实时同步",
    "popup.summary.setup_blockers": "配置阻塞",
    "popup.summary.policy_only": "仅策略",
    "settings.topbar.title": "设置",
    "settings.topbar.subtitle": "快速设置、外观与高级 Provider 控制",
    "settings.overview.eyebrow": "设置概览",
    "settings.overview.title": "控制面摘要",
    "settings.overview.detail": "用这个页面管理可见性、权限、凭据和混合 source 控制。直接跳到你需要的部分，而不是从上到下通读整页。",
    "settings.overview.aria": "设置概览",
    "settings.sections.aria": "设置分区",
    "settings.sections.preferences": "偏好",
    "settings.sections.visibility": "可见性",
    "settings.sections.credentials": "凭据",
    "settings.sections.sources": "来源",
    "settings.sections.permissions": "权限",
    "settings.actions.back_to_top": "返回顶部",
    "settings.actions.back_to_top_short": "顶部",
    "settings.summary.visible": "可见",
    "settings.summary.stored_secrets": "已存密钥",
    "settings.summary.bound_pages": "已绑定页面",
    "settings.summary.needs_access": "需授权",
    "settings.preferences.eyebrow": "外观与同步",
    "settings.preferences.sync_interval_label": "默认同步间隔",
    "settings.preferences.warning_threshold_label": "告警阈值",
    "settings.preferences.locale_label": "应用语言",
    "settings.preferences.theme_mode_label": "主题模式",
    "settings.preferences.accent_preset_label": "强调色预设",
    "settings.preferences.popup_progress_style_label": "Popup 额度样式",
    "settings.preferences.sidebar_progress_style_label": "侧栏额度样式",
    "settings.preferences.full_page_progress_style_label": "标签页额度样式",
    "settings.preferences.progress_style.line": "直线",
    "settings.preferences.progress_style.circle": "圆圈",
    "settings.preferences.popup_size_label": "Popup 尺寸",
    "settings.preferences.popup_size.compact": "紧凑",
    "settings.preferences.popup_size.balanced": "均衡",
    "settings.preferences.popup_size.wide": "宽版",
    "settings.preferences.popup_corner_label": "Popup 圆角",
    "settings.preferences.popup_corner.square": "直角",
    "settings.preferences.popup_corner.soft": "柔和",
    "settings.preferences.popup_corner.rounded": "圆润",
    "settings.preferences.popup_shadow_label": "Popup 阴影",
    "settings.preferences.popup_shadow.none": "无",
    "settings.preferences.popup_shadow.soft": "轻微",
    "settings.preferences.popup_shadow.elevated": "加强",
    "settings.preferences.action_badge_label": "工具栏图标标记",
    "settings.popup_appearance_preview.eyebrow": "Popup 预览",
    "settings.popup_appearance_preview.title": "工具栏弹窗形态",
    "settings.popup_appearance_preview.detail": "在重新打开 Chrome action 前，先预览当前 popup 宽度、圆角和阴影组合。",
    "settings.popup_appearance_preview.sample_refresh": "刷新",
    "settings.popup_appearance_preview.sample_tab": "标签页",
    "settings.popup_appearance_preview.sample_provider": "Codex",
    "settings.popup_appearance_preview.sample_quota": "每周使用窗口",
    "settings.preferences.minutes": "分钟",
    "settings.preferences.locale.system": "跟随系统",
    "settings.preferences.locale.en": "英语",
    "settings.preferences.locale.zh_cn": "简体中文",
    "settings.preferences.theme_mode.system": "跟随系统",
    "settings.preferences.theme_mode.light": "白天",
    "settings.preferences.theme_mode.dark": "夜间",
    "settings.preferences.theme_preset.default": "默认蓝",
    "settings.preferences.theme_preset.meadow": "草地",
    "settings.preferences.theme_preset.sunset": "日落",
    "settings.preferences.theme_preset.custom": "自定义种子",
    "settings.theme_customization.eyebrow": "自定义种子",
    "settings.theme_customization.title": "已校验的强调色种子",
    "settings.theme_customization.detail": "使用一个经过校验的 #RRGGBB 种子，而不是直接编辑单个主题 token。生成出的强调色角色会在侧栏、popup 和 audit hub 中共享。",
    "settings.theme_customization.seed_label": "自定义种子颜色",
    "settings.theme_customization.apply": "应用自定义种子",
    "settings.theme_customization.reset": "恢复默认",
    "settings.theme_customization.preview.aria": "自定义种子预览",
    "settings.theme_customization.preview.primary": "主色",
    "settings.theme_customization.preview.secondary_container": "次级容器",
    "settings.theme_customization.preview.tertiary": "第三色",
    "settings.visibility.eyebrow": "Provider 可见性",
    "settings.visibility.enabled_detail": "在仪表板中可见。",
    "settings.visibility.disabled_detail": "已从仪表板隐藏。",
    "settings.credentials.eyebrow": "凭据",
    "settings.credentials.title": "已存密钥与工作区配置",
    "settings.credentials.detail": "这些卡片管理扩展本地保存的 admin 和 enterprise 路径凭据。个人 session-page 路径仍然避免 cookie 导出，也不会要求手动粘贴 auth header。",
    "settings.sources.eyebrow": "来源连接",
    "settings.sources.title": "混合来源合同",
    "settings.sources.detail": "这些卡片说明每个 provider 当前是通过官方 API、已登录页面会话，还是文档化 quota policy 同步，同时明确每条路径当前是 shipped 还是 deferred 的产品合同。",
    "settings.permissions.eyebrow": "Host 访问",
    "settings.permissions.title": "权限控制",
    "settings.permissions.detail": "在扩展模式下，这些操作使用 chrome.permissions；在浏览器预览模式下，它们会回退到本地状态模拟。",
    "settings.toast.preferences_saved_title": "偏好已保存",
    "settings.toast.preferences_saved_detail": "当前预览的设置已经持久化到本地仪表板状态。",
  },
  "zh-TW": {
    "app.loading.eyebrow": "載入中",
    "app.loading.title": "正在準備儀表板狀態",
    "app.loading.detail": "正在初始化儀表板儲存與訊息匯流排。",
    "app.error.eyebrow": "狀態無法使用",
    "app.error.title": "初始化未完成",
    "app.error.detail_fallback": "無法從擴充功能儲存空間或本機預覽儲存空間載入應用程式狀態。",
    "common.actions.retry": "重試",
    "common.actions.settings": "設定",
    "common.actions.refresh": "重新整理",
    "common.actions.refresh_all": "全部重新整理",
    "common.actions.back": "返回",
    "common.actions.open_dashboard": "開啟儀表板",
    "common.actions.open_settings": "開啟設定",
    "common.actions.open_dashboard_tab": "開啟儀表板分頁",
    "common.actions.open_settings_tab": "開啟設定分頁",
    "common.actions.tab": "分頁",
    "common.actions.save": "儲存",
    "common.theme.toggle_to_dark_label": "夜間",
    "common.theme.toggle_to_dark_title": "切換到夜間模式",
    "common.theme.toggle_to_light_label": "白天",
    "common.theme.toggle_to_light_title": "切換到白天模式",
    "dashboard.topbar.title": "AI 用量儀表板",
    "dashboard.topbar.subtitle": "用量、額度與同步健康",
    "dashboard.hero.eyebrow": "概覽",
    "dashboard.hero.title": "一個面板掌握 AI 編碼配額",
    "dashboard.hero.detail": "官方 API、文件化配額策略與受控頁面解析路徑，會收斂到一個可發布的儀表板中，用於重新整理、設定和 Provider 深入查看。",
    "dashboard.hero.release_chip": "Material 3 · 發布候選",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 卡片",
    "dashboard.providers.detail": "卡片先按嚴重程度排序，再按目前存取缺口排序，讓高風險 provider 保持在頂部，同時保留目前產品合約的一眼可見性。",
    "dashboard.providers.aria": "Provider 卡片",
    "dashboard.empty.eyebrow": "沒有可見 Provider",
    "dashboard.empty.detail": "請先進入 Quick Setup 啟用第一個 Provider，再依提示完成授權與用量頁面步驟，然後回到儀表板。",
    "dashboard.empty.action": "開啟 Quick Setup",
    "dashboard.summary.aria": "儀表板摘要",
    "dashboard.summary.visible": "可見",
    "dashboard.summary.healthy": "健康",
    "dashboard.summary.needs_access": "需授權",
    "dashboard.summary.needs_attention": "需關注",
    "popup.loading.eyebrow": "工具列彈窗",
    "popup.loading.title": "正在載入快取的儀表板狀態",
    "popup.loading.detail": "正在為此瀏覽器設定檔準備共享配額快照。",
    "popup.error.eyebrow": "工具列彈窗",
    "popup.error.title": "彈窗載入失敗",
    "popup.header.eyebrow": "工具列彈窗",
    "popup.header.title": "快速概覽",
    "popup.summary.aria": "彈窗頂部摘要",
    "popup.guidance.eyebrow": "彈窗引導",
    "popup.snapshot_status.eyebrow": "快照狀態",
    "popup.actions.eyebrow": "其他入口",
    "popup.actions.refresh": "重新整理",
    "popup.actions.refreshing": "重新整理中",
    "popup.featured.eyebrow": "重點 Provider",
    "popup.featured.single_eyebrow": "重點 Provider",
    "popup.triage.eyebrow": "彈窗分診",
    "popup.summary.visible": "可見",
    "popup.summary.live_ready": "可即時同步",
    "popup.summary.setup_blockers": "設定阻礙",
    "popup.summary.policy_only": "僅策略",
    "settings.topbar.title": "設定",
    "settings.topbar.subtitle": "快速設定、外觀與進階 Provider 控制",
    "settings.overview.eyebrow": "設定概覽",
    "settings.overview.title": "控制面摘要",
    "settings.overview.detail": "使用此頁面管理可見性、權限、憑據和混合 source 控制。直接跳到需要的區段，而不是從上到下通讀整頁。",
    "settings.overview.aria": "設定概覽",
    "settings.sections.aria": "設定區段",
    "settings.sections.preferences": "偏好",
    "settings.sections.visibility": "可見性",
    "settings.sections.credentials": "憑據",
    "settings.sections.sources": "來源",
    "settings.sections.permissions": "權限",
    "settings.actions.back_to_top": "返回頂部",
    "settings.actions.back_to_top_short": "頂部",
    "settings.summary.visible": "可見",
    "settings.summary.stored_secrets": "已存密鑰",
    "settings.summary.bound_pages": "已綁定頁面",
    "settings.summary.needs_access": "需授權",
    "settings.preferences.eyebrow": "外觀與同步",
    "settings.preferences.sync_interval_label": "預設同步間隔",
    "settings.preferences.warning_threshold_label": "警示閾值",
    "settings.preferences.locale_label": "應用程式語言",
    "settings.preferences.theme_mode_label": "主題模式",
    "settings.preferences.accent_preset_label": "強調色預設",
    "settings.preferences.popup_progress_style_label": "Popup 額度樣式",
    "settings.preferences.sidebar_progress_style_label": "側欄額度樣式",
    "settings.preferences.full_page_progress_style_label": "分頁額度樣式",
    "settings.preferences.progress_style.line": "直線",
    "settings.preferences.progress_style.circle": "圓圈",
    "settings.preferences.popup_size_label": "Popup 尺寸",
    "settings.preferences.popup_size.compact": "緊湊",
    "settings.preferences.popup_size.balanced": "均衡",
    "settings.preferences.popup_size.wide": "寬版",
    "settings.preferences.popup_corner_label": "Popup 圓角",
    "settings.preferences.popup_corner.square": "直角",
    "settings.preferences.popup_corner.soft": "柔和",
    "settings.preferences.popup_corner.rounded": "圓潤",
    "settings.preferences.popup_shadow_label": "Popup 陰影",
    "settings.preferences.popup_shadow.none": "無",
    "settings.preferences.popup_shadow.soft": "輕微",
    "settings.preferences.popup_shadow.elevated": "加強",
    "settings.preferences.action_badge_label": "工具列圖示標記",
    "settings.preferences.minutes": "分鐘",
    "settings.preferences.locale.system": "跟隨系統",
    "settings.preferences.locale.en": "英文",
    "settings.preferences.locale.zh_cn": "簡體中文",
    "settings.preferences.theme_mode.system": "跟隨系統",
    "settings.preferences.theme_mode.light": "白天",
    "settings.preferences.theme_mode.dark": "夜間",
    "settings.preferences.theme_preset.default": "預設藍",
    "settings.preferences.theme_preset.meadow": "草地",
    "settings.preferences.theme_preset.sunset": "日落",
    "settings.preferences.theme_preset.custom": "自訂種子",
    "settings.toast.preferences_saved_title": "偏好已儲存",
    "settings.toast.preferences_saved_detail": "目前預覽的設定已持久化到本機儀表板狀態。",
  },
  ja: {
    "app.loading.eyebrow": "読み込み中",
    "app.loading.title": "ダッシュボード状態を準備中",
    "app.loading.detail": "ダッシュボードストアとメッセージバスを初期化しています。",
    "app.error.eyebrow": "状態を利用できません",
    "app.error.title": "初期化が完了しませんでした",
    "app.error.detail_fallback": "拡張機能ストレージまたはローカルプレビューのストレージからアプリ状態を読み込めませんでした。",
    "common.actions.retry": "再試行",
    "common.actions.settings": "設定",
    "common.actions.refresh": "更新",
    "common.actions.refresh_all": "すべて更新",
    "common.actions.back": "戻る",
    "common.actions.open_dashboard": "ダッシュボードを開く",
    "common.actions.open_settings": "設定を開く",
    "common.actions.open_dashboard_tab": "ダッシュボードタブを開く",
    "common.actions.open_settings_tab": "設定タブを開く",
    "common.actions.tab": "タブ",
    "common.actions.save": "保存",
    "common.theme.toggle_to_dark_label": "ダーク",
    "common.theme.toggle_to_dark_title": "ダークモードに切り替える",
    "common.theme.toggle_to_light_label": "ライト",
    "common.theme.toggle_to_light_title": "ライトモードに切り替える",
    "dashboard.topbar.title": "AI 使用状況ダッシュボード",
    "dashboard.topbar.subtitle": "使用状況、クレジット、同期状態",
    "dashboard.hero.eyebrow": "概要",
    "dashboard.hero.title": "AI コーディングクォータを一画面で把握",
    "dashboard.hero.detail": "公式 API、ドキュメント化されたクォータポリシー、保護されたページ解析ソースを、更新、設定、Provider 詳細確認のためのリリース対応ダッシュボードに集約します。",
    "dashboard.hero.release_chip": "Material 3 · リリース候補",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider カード",
    "dashboard.providers.detail": "カードは重要度を優先し、その次に現在のアクセス不足で並びます。リスクの高い provider をダッシュボード上部に保ちながら、現在のプロダクト契約を一目で確認できます。",
    "dashboard.providers.aria": "Provider カード",
    "dashboard.empty.eyebrow": "表示中の Provider なし",
    "dashboard.empty.detail": "Quick Setup で最初の Provider を有効にし、アクセスと使用状況ページの手順を完了してからダッシュボードに戻ってください。",
    "dashboard.empty.action": "Quick Setup を開く",
    "dashboard.summary.aria": "ダッシュボード概要",
    "dashboard.summary.visible": "表示中",
    "dashboard.summary.healthy": "正常",
    "dashboard.summary.needs_access": "アクセスが必要",
    "dashboard.summary.needs_attention": "要確認",
    "popup.loading.eyebrow": "ツールバーポップアップ",
    "popup.loading.title": "キャッシュ済みダッシュボード状態を読み込み中",
    "popup.loading.detail": "このブラウザプロファイル用の共有クォータスナップショットを準備しています。",
    "popup.error.eyebrow": "ツールバーポップアップ",
    "popup.error.title": "ポップアップの読み込みに失敗しました",
    "popup.header.eyebrow": "ツールバーポップアップ",
    "popup.header.title": "クイック確認",
    "popup.summary.aria": "ポップアップ上部の概要",
    "popup.guidance.eyebrow": "ポップアップガイダンス",
    "popup.snapshot_status.eyebrow": "スナップショット状態",
    "popup.actions.eyebrow": "その他の入口",
    "popup.actions.refresh": "更新",
    "popup.actions.refreshing": "更新中",
    "popup.featured.eyebrow": "注目 Provider",
    "popup.featured.single_eyebrow": "注目 Provider",
    "popup.triage.eyebrow": "ポップアップ優先確認",
    "popup.summary.visible": "表示中",
    "popup.summary.live_ready": "ライブ準備済み",
    "popup.summary.setup_blockers": "設定ブロッカー",
    "popup.summary.policy_only": "ポリシーのみ",
    "settings.topbar.title": "設定",
    "settings.topbar.subtitle": "Quick Setup、外観、高度な Provider 管理",
    "settings.overview.eyebrow": "設定の概要",
    "settings.overview.title": "コントロール画面の概要",
    "settings.overview.detail": "この画面で表示、権限、認証情報、ハイブリッド source 管理を扱います。ページ全体を上から下まで探す代わりに、必要なセクションへ直接移動できます。",
    "settings.overview.aria": "設定の概要",
    "settings.sections.aria": "設定セクション",
    "settings.sections.preferences": "環境設定",
    "settings.sections.visibility": "表示",
    "settings.sections.credentials": "認証情報",
    "settings.sections.sources": "ソース",
    "settings.sections.permissions": "権限",
    "settings.actions.back_to_top": "トップに戻る",
    "settings.actions.back_to_top_short": "トップ",
    "settings.summary.visible": "表示中",
    "settings.summary.stored_secrets": "保存済みシークレット",
    "settings.summary.bound_pages": "バインド済みページ",
    "settings.summary.needs_access": "アクセスが必要",
    "settings.preferences.eyebrow": "外観と同期",
    "settings.preferences.sync_interval_label": "既定の同期間隔",
    "settings.preferences.warning_threshold_label": "警告しきい値",
    "settings.preferences.locale_label": "アプリの言語",
    "settings.preferences.theme_mode_label": "テーマモード",
    "settings.preferences.accent_preset_label": "アクセントプリセット",
    "settings.preferences.popup_progress_style_label": "Popup クォータ表示",
    "settings.preferences.sidebar_progress_style_label": "サイドバーのクォータ表示",
    "settings.preferences.full_page_progress_style_label": "タブのクォータ表示",
    "settings.preferences.progress_style.line": "ライン",
    "settings.preferences.progress_style.circle": "円形",
    "settings.preferences.popup_size_label": "Popup サイズ",
    "settings.preferences.popup_size.compact": "コンパクト",
    "settings.preferences.popup_size.balanced": "バランス",
    "settings.preferences.popup_size.wide": "ワイド",
    "settings.preferences.popup_corner_label": "Popup の角",
    "settings.preferences.popup_corner.square": "四角",
    "settings.preferences.popup_corner.soft": "ソフト",
    "settings.preferences.popup_corner.rounded": "丸め",
    "settings.preferences.popup_shadow_label": "Popup の影",
    "settings.preferences.popup_shadow.none": "なし",
    "settings.preferences.popup_shadow.soft": "ソフト",
    "settings.preferences.popup_shadow.elevated": "強調",
    "settings.preferences.action_badge_label": "ツールバーバッジ",
    "settings.preferences.minutes": "分",
    "settings.preferences.locale.system": "システムに従う",
    "settings.preferences.locale.en": "英語",
    "settings.preferences.locale.zh_cn": "簡体字中国語",
    "settings.preferences.theme_mode.system": "システムに従う",
    "settings.preferences.theme_mode.light": "ライト",
    "settings.preferences.theme_mode.dark": "ダーク",
    "settings.preferences.theme_preset.default": "デフォルトブルー",
    "settings.preferences.theme_preset.meadow": "メドウ",
    "settings.preferences.theme_preset.sunset": "サンセット",
    "settings.preferences.theme_preset.custom": "カスタムシード",
    "settings.toast.preferences_saved_title": "設定を保存しました",
    "settings.toast.preferences_saved_detail": "現在のプレビュー設定をローカルダッシュボード状態に保存しました。",
  },
  ko: {
    "app.loading.eyebrow": "로딩 중",
    "app.loading.title": "대시보드 상태 준비 중",
    "app.loading.detail": "대시보드 저장소와 메시지 버스를 초기화하는 중입니다.",
    "app.error.eyebrow": "상태를 사용할 수 없음",
    "app.error.title": "초기화가 완료되지 않았습니다",
    "app.error.detail_fallback": "확장 프로그램 저장소 또는 로컬 미리보기 저장소에서 앱 상태를 불러오지 못했습니다.",
    "common.actions.retry": "다시 시도",
    "common.actions.settings": "설정",
    "common.actions.refresh": "새로 고침",
    "common.actions.refresh_all": "모두 새로 고침",
    "common.actions.back": "뒤로",
    "common.actions.open_dashboard": "대시보드 열기",
    "common.actions.open_settings": "설정 열기",
    "common.actions.open_dashboard_tab": "대시보드 탭 열기",
    "common.actions.open_settings_tab": "설정 탭 열기",
    "common.actions.tab": "탭",
    "common.actions.save": "저장",
    "common.theme.toggle_to_dark_label": "다크",
    "common.theme.toggle_to_dark_title": "다크 모드로 전환",
    "common.theme.toggle_to_light_label": "라이트",
    "common.theme.toggle_to_light_title": "라이트 모드로 전환",
    "dashboard.topbar.title": "AI 사용량 대시보드",
    "dashboard.topbar.subtitle": "사용량, 크레딧, 동기화 상태",
    "dashboard.hero.eyebrow": "개요",
    "dashboard.hero.title": "AI 코딩 할당량을 한 화면에서 확인",
    "dashboard.hero.detail": "공식 API, 문서화된 할당량 정책, 보호된 페이지 파싱 소스를 새로 고침, 설정, Provider 상세 확인을 위한 릴리스 준비 대시보드에 모읍니다.",
    "dashboard.hero.release_chip": "Material 3 · 릴리스 후보",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider 카드",
    "dashboard.providers.detail": "카드는 먼저 심각도, 그다음 현재 접근 공백 순서로 정렬됩니다. 위험이 큰 provider를 대시보드 상단에 유지하면서 현재 제품 계약도 한눈에 볼 수 있습니다.",
    "dashboard.providers.aria": "Provider 카드",
    "dashboard.empty.eyebrow": "표시 중인 Provider 없음",
    "dashboard.empty.detail": "Quick Setup에서 첫 Provider를 활성화한 뒤 접근 권한과 사용량 페이지 단계를 마치고 대시보드로 돌아오세요.",
    "dashboard.empty.action": "Quick Setup 열기",
    "dashboard.summary.aria": "대시보드 요약",
    "dashboard.summary.visible": "표시됨",
    "dashboard.summary.healthy": "정상",
    "dashboard.summary.needs_access": "접근 필요",
    "dashboard.summary.needs_attention": "확인 필요",
    "popup.loading.eyebrow": "도구 모음 팝업",
    "popup.loading.title": "캐시된 대시보드 상태를 불러오는 중",
    "popup.loading.detail": "이 브라우저 프로필의 공유 할당량 스냅샷을 준비하고 있습니다.",
    "popup.error.eyebrow": "도구 모음 팝업",
    "popup.error.title": "팝업을 불러오지 못했습니다",
    "popup.header.eyebrow": "도구 모음 팝업",
    "popup.header.title": "빠른 보기",
    "popup.summary.aria": "팝업 상단 요약",
    "popup.guidance.eyebrow": "팝업 가이드",
    "popup.snapshot_status.eyebrow": "스냅샷 상태",
    "popup.actions.eyebrow": "다른 경로",
    "popup.actions.refresh": "새로 고침",
    "popup.actions.refreshing": "새로 고치는 중",
    "popup.featured.eyebrow": "주요 Provider",
    "popup.featured.single_eyebrow": "주요 Provider",
    "popup.triage.eyebrow": "팝업 우선 확인",
    "popup.summary.visible": "표시됨",
    "popup.summary.live_ready": "라이브 준비됨",
    "popup.summary.setup_blockers": "설정 차단 항목",
    "popup.summary.policy_only": "정책만",
    "settings.topbar.title": "설정",
    "settings.topbar.subtitle": "Quick Setup, 모양, 고급 Provider 관리",
    "settings.overview.eyebrow": "설정 개요",
    "settings.overview.title": "제어 화면 요약",
    "settings.overview.detail": "이 화면에서 표시 여부, 권한, 인증 정보, 하이브리드 source 제어를 관리합니다. 페이지 전체를 훑지 않고 필요한 섹션으로 바로 이동할 수 있습니다.",
    "settings.overview.aria": "설정 개요",
    "settings.sections.aria": "설정 섹션",
    "settings.sections.preferences": "환경설정",
    "settings.sections.visibility": "표시",
    "settings.sections.credentials": "인증 정보",
    "settings.sections.sources": "소스",
    "settings.sections.permissions": "권한",
    "settings.actions.back_to_top": "맨 위로",
    "settings.actions.back_to_top_short": "맨 위",
    "settings.summary.visible": "표시됨",
    "settings.summary.stored_secrets": "저장된 비밀 정보",
    "settings.summary.bound_pages": "연결된 페이지",
    "settings.summary.needs_access": "접근 필요",
    "settings.preferences.eyebrow": "모양 및 동기화",
    "settings.preferences.sync_interval_label": "기본 동기화 간격",
    "settings.preferences.warning_threshold_label": "경고 임계값",
    "settings.preferences.locale_label": "앱 언어",
    "settings.preferences.theme_mode_label": "테마 모드",
    "settings.preferences.accent_preset_label": "강조 색상 프리셋",
    "settings.preferences.popup_progress_style_label": "Popup 할당량 표시",
    "settings.preferences.sidebar_progress_style_label": "사이드바 할당량 표시",
    "settings.preferences.full_page_progress_style_label": "탭 할당량 표시",
    "settings.preferences.progress_style.line": "선",
    "settings.preferences.progress_style.circle": "원형",
    "settings.preferences.popup_size_label": "Popup 크기",
    "settings.preferences.popup_size.compact": "컴팩트",
    "settings.preferences.popup_size.balanced": "균형",
    "settings.preferences.popup_size.wide": "넓게",
    "settings.preferences.popup_corner_label": "Popup 모서리",
    "settings.preferences.popup_corner.square": "각진",
    "settings.preferences.popup_corner.soft": "부드럽게",
    "settings.preferences.popup_corner.rounded": "둥글게",
    "settings.preferences.popup_shadow_label": "Popup 그림자",
    "settings.preferences.popup_shadow.none": "없음",
    "settings.preferences.popup_shadow.soft": "부드럽게",
    "settings.preferences.popup_shadow.elevated": "강조",
    "settings.preferences.action_badge_label": "도구 모음 배지",
    "settings.preferences.minutes": "분",
    "settings.preferences.locale.system": "시스템 따름",
    "settings.preferences.locale.en": "영어",
    "settings.preferences.locale.zh_cn": "중국어 간체",
    "settings.preferences.theme_mode.system": "시스템 따름",
    "settings.preferences.theme_mode.light": "라이트",
    "settings.preferences.theme_mode.dark": "다크",
    "settings.preferences.theme_preset.default": "기본 파란색",
    "settings.preferences.theme_preset.meadow": "메도우",
    "settings.preferences.theme_preset.sunset": "선셋",
    "settings.preferences.theme_preset.custom": "사용자 지정 시드",
    "settings.toast.preferences_saved_title": "환경설정이 저장됨",
    "settings.toast.preferences_saved_detail": "현재 미리보기 설정이 로컬 대시보드 상태에 저장되었습니다.",
  },
  "es-419": {
    "app.loading.eyebrow": "Cargando",
    "app.loading.title": "Preparando el estado del panel",
    "app.loading.detail": "Inicializando el almacenamiento del panel y el bus de mensajes.",
    "app.error.eyebrow": "Estado no disponible",
    "app.error.title": "La inicialización no se completó",
    "app.error.detail_fallback": "No se pudo cargar el estado de la app desde el almacenamiento de la extensión o el almacenamiento local de vista previa.",
    "common.actions.retry": "Reintentar",
    "common.actions.settings": "Configuración",
    "common.actions.refresh": "Actualizar",
    "common.actions.refresh_all": "Actualizar todo",
    "common.actions.back": "Volver",
    "common.actions.open_dashboard": "Abrir panel",
    "common.actions.open_settings": "Abrir configuración",
    "common.actions.open_dashboard_tab": "Abrir pestaña del panel",
    "common.actions.open_settings_tab": "Abrir pestaña de configuración",
    "common.actions.tab": "Pestaña",
    "common.actions.save": "Guardar",
    "common.theme.toggle_to_dark_label": "Oscuro",
    "common.theme.toggle_to_dark_title": "Cambiar a modo oscuro",
    "common.theme.toggle_to_light_label": "Claro",
    "common.theme.toggle_to_light_title": "Cambiar a modo claro",
    "dashboard.topbar.title": "Panel de uso de IA",
    "dashboard.topbar.subtitle": "Uso, créditos y estado de sincronización",
    "dashboard.hero.eyebrow": "Resumen",
    "dashboard.hero.title": "Un panel para las cuotas de codificación con IA",
    "dashboard.hero.detail": "APIs oficiales, políticas de cuota documentadas y fuentes protegidas de análisis de páginas se reúnen en un panel listo para lanzamiento con actualizaciones, configuración y detalles de Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidato de lanzamiento",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Tarjetas de Provider",
    "dashboard.providers.detail": "Las tarjetas se ordenan primero por gravedad y luego por brechas de acceso actuales, para que los provider de mayor riesgo se mantengan arriba sin perder de vista el contrato de producto actual.",
    "dashboard.providers.aria": "Tarjetas de Provider",
    "dashboard.empty.eyebrow": "No hay Provider visibles",
    "dashboard.empty.detail": "Empieza en Quick Setup para activar tu primer Provider, completa los pasos de acceso y página de uso, y luego vuelve al panel.",
    "dashboard.empty.action": "Abrir Quick Setup",
    "dashboard.summary.aria": "Resumen del panel",
    "dashboard.summary.visible": "Visibles",
    "dashboard.summary.healthy": "Correctos",
    "dashboard.summary.needs_access": "Requiere acceso",
    "dashboard.summary.needs_attention": "Requiere atención",
    "popup.loading.eyebrow": "Popup de barra de herramientas",
    "popup.loading.title": "Cargando el estado del panel en caché",
    "popup.loading.detail": "Preparando la instantánea compartida de cuotas para este perfil del navegador.",
    "popup.error.eyebrow": "Popup de barra de herramientas",
    "popup.error.title": "No se pudo cargar el popup",
    "popup.header.eyebrow": "Popup de barra de herramientas",
    "popup.header.title": "Vista rápida",
    "popup.summary.aria": "Resumen superior del popup",
    "popup.guidance.eyebrow": "Guía del popup",
    "popup.snapshot_status.eyebrow": "Estado de instantánea",
    "popup.actions.eyebrow": "Otra ruta",
    "popup.actions.refresh": "Actualizar",
    "popup.actions.refreshing": "Actualizando",
    "popup.featured.eyebrow": "Providers destacados",
    "popup.featured.single_eyebrow": "Provider destacado",
    "popup.triage.eyebrow": "Priorización del popup",
    "popup.summary.visible": "Visibles",
    "popup.summary.live_ready": "Listo para datos en vivo",
    "popup.summary.setup_blockers": "Bloqueos de configuración",
    "popup.summary.policy_only": "Solo política",
    "settings.topbar.title": "Configuración",
    "settings.topbar.subtitle": "Quick Setup, apariencia y controles avanzados de Provider",
    "settings.overview.eyebrow": "Resumen de configuración",
    "settings.overview.title": "Resumen de superficie de control",
    "settings.overview.detail": "Usa esta pantalla para administrar visibilidad, permisos, credenciales y controles de source híbridos. Salta directamente a la sección que necesitas en vez de revisar toda la página.",
    "settings.overview.aria": "Resumen de configuración",
    "settings.sections.aria": "Secciones de configuración",
    "settings.sections.preferences": "Preferencias",
    "settings.sections.visibility": "Visibilidad",
    "settings.sections.credentials": "Credenciales",
    "settings.sections.sources": "Fuentes",
    "settings.sections.permissions": "Permisos",
    "settings.actions.back_to_top": "Volver arriba",
    "settings.actions.back_to_top_short": "Arriba",
    "settings.summary.visible": "Visibles",
    "settings.summary.stored_secrets": "Secretos guardados",
    "settings.summary.bound_pages": "Páginas vinculadas",
    "settings.summary.needs_access": "Requiere acceso",
    "settings.preferences.eyebrow": "Apariencia y sincronización",
    "settings.preferences.sync_interval_label": "Intervalo de sincronización predeterminado",
    "settings.preferences.warning_threshold_label": "Umbral de advertencia",
    "settings.preferences.locale_label": "Idioma de la app",
    "settings.preferences.theme_mode_label": "Modo de tema",
    "settings.preferences.accent_preset_label": "Preajuste de acento",
    "settings.preferences.popup_progress_style_label": "Estilo de cuota del Popup",
    "settings.preferences.sidebar_progress_style_label": "Estilo de cuota de la barra lateral",
    "settings.preferences.full_page_progress_style_label": "Estilo de cuota de la pestaña",
    "settings.preferences.progress_style.line": "Línea",
    "settings.preferences.progress_style.circle": "Círculo",
    "settings.preferences.popup_size_label": "Tamaño del Popup",
    "settings.preferences.popup_size.compact": "Compacto",
    "settings.preferences.popup_size.balanced": "Equilibrado",
    "settings.preferences.popup_size.wide": "Ancho",
    "settings.preferences.popup_corner_label": "Esquinas del Popup",
    "settings.preferences.popup_corner.square": "Cuadradas",
    "settings.preferences.popup_corner.soft": "Suaves",
    "settings.preferences.popup_corner.rounded": "Redondeadas",
    "settings.preferences.popup_shadow_label": "Sombra del Popup",
    "settings.preferences.popup_shadow.none": "Ninguna",
    "settings.preferences.popup_shadow.soft": "Suave",
    "settings.preferences.popup_shadow.elevated": "Elevada",
    "settings.preferences.action_badge_label": "Insignia de barra de herramientas",
    "settings.preferences.minutes": "minutos",
    "settings.preferences.locale.system": "Seguir sistema",
    "settings.preferences.locale.en": "Inglés",
    "settings.preferences.locale.zh_cn": "Chino simplificado",
    "settings.preferences.theme_mode.system": "Seguir sistema",
    "settings.preferences.theme_mode.light": "Claro",
    "settings.preferences.theme_mode.dark": "Oscuro",
    "settings.preferences.theme_preset.default": "Azul predeterminado",
    "settings.preferences.theme_preset.meadow": "Prado",
    "settings.preferences.theme_preset.sunset": "Atardecer",
    "settings.preferences.theme_preset.custom": "Semilla personalizada",
    "settings.toast.preferences_saved_title": "Preferencias guardadas",
    "settings.toast.preferences_saved_detail": "La configuración actual de vista previa se guardó en el estado local del panel.",
  },
  "pt-BR": {
    "app.loading.eyebrow": "Carregando",
    "app.loading.title": "Preparando o estado do painel",
    "app.loading.detail": "Inicializando o armazenamento do painel e o barramento de mensagens.",
    "app.error.eyebrow": "Estado indisponível",
    "app.error.title": "A inicialização não foi concluída",
    "app.error.detail_fallback": "Não foi possível carregar o estado do app do armazenamento da extensão ou do armazenamento local de prévia.",
    "common.actions.retry": "Tentar novamente",
    "common.actions.settings": "Configurações",
    "common.actions.refresh": "Atualizar",
    "common.actions.refresh_all": "Atualizar tudo",
    "common.actions.back": "Voltar",
    "common.actions.open_dashboard": "Abrir painel",
    "common.actions.open_settings": "Abrir configurações",
    "common.actions.open_dashboard_tab": "Abrir aba do painel",
    "common.actions.open_settings_tab": "Abrir aba de configurações",
    "common.actions.tab": "Aba",
    "common.actions.save": "Salvar",
    "common.theme.toggle_to_dark_label": "Escuro",
    "common.theme.toggle_to_dark_title": "Alternar para modo escuro",
    "common.theme.toggle_to_light_label": "Claro",
    "common.theme.toggle_to_light_title": "Alternar para modo claro",
    "dashboard.topbar.title": "Painel de uso de IA",
    "dashboard.topbar.subtitle": "Uso, créditos e integridade da sincronização",
    "dashboard.hero.eyebrow": "Visão geral",
    "dashboard.hero.title": "Um painel para cotas de codificação com IA",
    "dashboard.hero.detail": "APIs oficiais, políticas de cota documentadas e fontes protegidas de análise de página são reunidas em um painel pronto para lançamento com atualizações, configurações e detalhes de Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidato a lançamento",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Cartões de Provider",
    "dashboard.providers.detail": "Os cartões são ordenados primeiro por gravidade e depois pelas lacunas de acesso atuais, mantendo os provider de maior risco no topo do painel sem perder o contrato de produto atual de vista.",
    "dashboard.providers.aria": "Cartões de Provider",
    "dashboard.empty.eyebrow": "Nenhum Provider visível",
    "dashboard.empty.detail": "Comece no Quick Setup para ativar seu primeiro Provider, conclua as etapas de acesso e página de uso e depois volte ao painel.",
    "dashboard.empty.action": "Abrir Quick Setup",
    "dashboard.summary.aria": "Resumo do painel",
    "dashboard.summary.visible": "Visíveis",
    "dashboard.summary.healthy": "Saudáveis",
    "dashboard.summary.needs_access": "Precisa de acesso",
    "dashboard.summary.needs_attention": "Precisa de atenção",
    "popup.loading.eyebrow": "Popup da barra de ferramentas",
    "popup.loading.title": "Carregando o estado em cache do painel",
    "popup.loading.detail": "Preparando o instantâneo compartilhado de cotas para este perfil do navegador.",
    "popup.error.eyebrow": "Popup da barra de ferramentas",
    "popup.error.title": "Falha ao carregar o popup",
    "popup.header.eyebrow": "Popup da barra de ferramentas",
    "popup.header.title": "Vista rápida",
    "popup.summary.aria": "Resumo superior do popup",
    "popup.guidance.eyebrow": "Orientação do popup",
    "popup.snapshot_status.eyebrow": "Estado do instantâneo",
    "popup.actions.eyebrow": "Outra rota",
    "popup.actions.refresh": "Atualizar",
    "popup.actions.refreshing": "Atualizando",
    "popup.featured.eyebrow": "Providers em destaque",
    "popup.featured.single_eyebrow": "Provider em destaque",
    "popup.triage.eyebrow": "Triagem do popup",
    "popup.summary.visible": "Visíveis",
    "popup.summary.live_ready": "Pronto para dados ao vivo",
    "popup.summary.setup_blockers": "Bloqueios de configuração",
    "popup.summary.policy_only": "Somente política",
    "settings.topbar.title": "Configurações",
    "settings.topbar.subtitle": "Quick Setup, aparência e controles avançados de Provider",
    "settings.overview.eyebrow": "Visão geral das configurações",
    "settings.overview.title": "Resumo da superfície de controle",
    "settings.overview.detail": "Use esta tela para gerenciar visibilidade, permissões, credenciais e controles de source híbridos. Vá direto para a seção necessária em vez de percorrer a página inteira.",
    "settings.overview.aria": "Visão geral das configurações",
    "settings.sections.aria": "Seções de configurações",
    "settings.sections.preferences": "Preferências",
    "settings.sections.visibility": "Visibilidade",
    "settings.sections.credentials": "Credenciais",
    "settings.sections.sources": "Fontes",
    "settings.sections.permissions": "Permissões",
    "settings.actions.back_to_top": "Voltar ao topo",
    "settings.actions.back_to_top_short": "Topo",
    "settings.summary.visible": "Visíveis",
    "settings.summary.stored_secrets": "Segredos armazenados",
    "settings.summary.bound_pages": "Páginas vinculadas",
    "settings.summary.needs_access": "Precisa de acesso",
    "settings.preferences.eyebrow": "Aparência e sincronização",
    "settings.preferences.sync_interval_label": "Intervalo padrão de sincronização",
    "settings.preferences.warning_threshold_label": "Limite de aviso",
    "settings.preferences.locale_label": "Idioma do app",
    "settings.preferences.theme_mode_label": "Modo de tema",
    "settings.preferences.accent_preset_label": "Predefinição de destaque",
    "settings.preferences.popup_progress_style_label": "Estilo de cota do Popup",
    "settings.preferences.sidebar_progress_style_label": "Estilo de cota da barra lateral",
    "settings.preferences.full_page_progress_style_label": "Estilo de cota da aba",
    "settings.preferences.progress_style.line": "Linha",
    "settings.preferences.progress_style.circle": "Círculo",
    "settings.preferences.popup_size_label": "Tamanho do Popup",
    "settings.preferences.popup_size.compact": "Compacto",
    "settings.preferences.popup_size.balanced": "Equilibrado",
    "settings.preferences.popup_size.wide": "Amplo",
    "settings.preferences.popup_corner_label": "Cantos do Popup",
    "settings.preferences.popup_corner.square": "Quadrados",
    "settings.preferences.popup_corner.soft": "Suaves",
    "settings.preferences.popup_corner.rounded": "Arredondados",
    "settings.preferences.popup_shadow_label": "Sombra do Popup",
    "settings.preferences.popup_shadow.none": "Nenhuma",
    "settings.preferences.popup_shadow.soft": "Suave",
    "settings.preferences.popup_shadow.elevated": "Elevada",
    "settings.preferences.action_badge_label": "Selo da barra de ferramentas",
    "settings.preferences.minutes": "minutos",
    "settings.preferences.locale.system": "Seguir sistema",
    "settings.preferences.locale.en": "Inglês",
    "settings.preferences.locale.zh_cn": "Chinês simplificado",
    "settings.preferences.theme_mode.system": "Seguir sistema",
    "settings.preferences.theme_mode.light": "Claro",
    "settings.preferences.theme_mode.dark": "Escuro",
    "settings.preferences.theme_preset.default": "Azul padrão",
    "settings.preferences.theme_preset.meadow": "Prado",
    "settings.preferences.theme_preset.sunset": "Pôr do sol",
    "settings.preferences.theme_preset.custom": "Semente personalizada",
    "settings.toast.preferences_saved_title": "Preferências salvas",
    "settings.toast.preferences_saved_detail": "As configurações atuais da prévia foram salvas no estado local do painel.",
  },
  fr: {
    "app.loading.eyebrow": "Chargement",
    "app.loading.title": "Préparation de l'état du tableau de bord",
    "app.loading.detail": "Initialisation du stockage du tableau de bord et du bus de messages.",
    "app.error.eyebrow": "État indisponible",
    "app.error.title": "L'initialisation n'a pas été terminée",
    "app.error.detail_fallback": "Impossible de charger l'état de l'app depuis le stockage de l'extension ou le stockage local d'aperçu.",
    "common.actions.retry": "Réessayer",
    "common.actions.settings": "Paramètres",
    "common.actions.refresh": "Actualiser",
    "common.actions.refresh_all": "Tout actualiser",
    "common.actions.back": "Retour",
    "common.actions.open_dashboard": "Ouvrir le tableau de bord",
    "common.actions.open_settings": "Ouvrir les paramètres",
    "common.actions.open_dashboard_tab": "Ouvrir l'onglet du tableau de bord",
    "common.actions.open_settings_tab": "Ouvrir l'onglet des paramètres",
    "common.actions.tab": "Onglet",
    "common.actions.save": "Enregistrer",
    "common.theme.toggle_to_dark_label": "Sombre",
    "common.theme.toggle_to_dark_title": "Passer au mode sombre",
    "common.theme.toggle_to_light_label": "Clair",
    "common.theme.toggle_to_light_title": "Passer au mode clair",
    "dashboard.topbar.title": "Tableau de bord d'utilisation de l'IA",
    "dashboard.topbar.subtitle": "Utilisation, crédits et état de synchronisation",
    "dashboard.hero.eyebrow": "Vue d'ensemble",
    "dashboard.hero.title": "Un tableau de bord pour les quotas de codage IA",
    "dashboard.hero.detail": "Les API officielles, les politiques de quota documentées et les sources protégées d'analyse de page sont réunies dans un tableau de bord prêt pour publication, avec actualisation, paramètres et détails Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidat de publication",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Cartes Provider",
    "dashboard.providers.detail": "Les cartes sont triées d'abord par gravité, puis par lacunes d'accès actuelles, afin de garder les provider les plus risqués en haut du tableau de bord tout en exposant le contrat produit actuel.",
    "dashboard.providers.aria": "Cartes Provider",
    "dashboard.empty.eyebrow": "Aucun Provider visible",
    "dashboard.empty.detail": "Commencez dans Quick Setup pour activer votre premier Provider, terminez les étapes d'accès et de page d'utilisation, puis revenez au tableau de bord.",
    "dashboard.empty.action": "Ouvrir Quick Setup",
    "dashboard.summary.aria": "Résumé du tableau de bord",
    "dashboard.summary.visible": "Visibles",
    "dashboard.summary.healthy": "Sains",
    "dashboard.summary.needs_access": "Accès requis",
    "dashboard.summary.needs_attention": "Attention requise",
    "popup.loading.eyebrow": "Popup de la barre d'outils",
    "popup.loading.title": "Chargement de l'état mis en cache du tableau de bord",
    "popup.loading.detail": "Préparation de l'instantané partagé des quotas pour ce profil de navigateur.",
    "popup.error.eyebrow": "Popup de la barre d'outils",
    "popup.error.title": "Échec du chargement du popup",
    "popup.header.eyebrow": "Popup de la barre d'outils",
    "popup.header.title": "Coup d'oeil rapide",
    "popup.summary.aria": "Résumé supérieur du popup",
    "popup.guidance.eyebrow": "Guide du popup",
    "popup.snapshot_status.eyebrow": "État de l'instantané",
    "popup.actions.eyebrow": "Autre route",
    "popup.actions.refresh": "Actualiser",
    "popup.actions.refreshing": "Actualisation",
    "popup.featured.eyebrow": "Providers mis en avant",
    "popup.featured.single_eyebrow": "Provider mis en avant",
    "popup.triage.eyebrow": "Triage du popup",
    "popup.summary.visible": "Visibles",
    "popup.summary.live_ready": "Prêt pour les données en direct",
    "popup.summary.setup_blockers": "Blocages de configuration",
    "popup.summary.policy_only": "Politique uniquement",
    "settings.topbar.title": "Paramètres",
    "settings.topbar.subtitle": "Quick Setup, apparence et contrôles Provider avancés",
    "settings.overview.eyebrow": "Vue d'ensemble des paramètres",
    "settings.overview.title": "Résumé de la surface de contrôle",
    "settings.overview.detail": "Utilisez cet écran pour gérer la visibilité, les autorisations, les identifiants et les contrôles source hybrides. Accédez directement à la section nécessaire au lieu de parcourir toute la page.",
    "settings.overview.aria": "Vue d'ensemble des paramètres",
    "settings.sections.aria": "Sections de paramètres",
    "settings.sections.preferences": "Préférences",
    "settings.sections.visibility": "Visibilité",
    "settings.sections.credentials": "Identifiants",
    "settings.sections.sources": "Sources",
    "settings.sections.permissions": "Autorisations",
    "settings.actions.back_to_top": "Retour en haut",
    "settings.actions.back_to_top_short": "Haut",
    "settings.summary.visible": "Visibles",
    "settings.summary.stored_secrets": "Secrets enregistrés",
    "settings.summary.bound_pages": "Pages liées",
    "settings.summary.needs_access": "Accès requis",
    "settings.preferences.eyebrow": "Apparence et synchronisation",
    "settings.preferences.sync_interval_label": "Intervalle de synchronisation par défaut",
    "settings.preferences.warning_threshold_label": "Seuil d'avertissement",
    "settings.preferences.locale_label": "Langue de l'app",
    "settings.preferences.theme_mode_label": "Mode de thème",
    "settings.preferences.accent_preset_label": "Préréglage d'accent",
    "settings.preferences.popup_progress_style_label": "Style de quota du Popup",
    "settings.preferences.sidebar_progress_style_label": "Style de quota de la barre latérale",
    "settings.preferences.full_page_progress_style_label": "Style de quota de l'onglet",
    "settings.preferences.progress_style.line": "Ligne",
    "settings.preferences.progress_style.circle": "Cercle",
    "settings.preferences.popup_size_label": "Taille du Popup",
    "settings.preferences.popup_size.compact": "Compact",
    "settings.preferences.popup_size.balanced": "Équilibré",
    "settings.preferences.popup_size.wide": "Large",
    "settings.preferences.popup_corner_label": "Coins du Popup",
    "settings.preferences.popup_corner.square": "Carrés",
    "settings.preferences.popup_corner.soft": "Souples",
    "settings.preferences.popup_corner.rounded": "Arrondis",
    "settings.preferences.popup_shadow_label": "Ombre du Popup",
    "settings.preferences.popup_shadow.none": "Aucune",
    "settings.preferences.popup_shadow.soft": "Souple",
    "settings.preferences.popup_shadow.elevated": "Élevée",
    "settings.preferences.action_badge_label": "Badge de la barre d'outils",
    "settings.preferences.minutes": "minutes",
    "settings.preferences.locale.system": "Suivre le système",
    "settings.preferences.locale.en": "Anglais",
    "settings.preferences.locale.zh_cn": "Chinois simplifié",
    "settings.preferences.theme_mode.system": "Suivre le système",
    "settings.preferences.theme_mode.light": "Clair",
    "settings.preferences.theme_mode.dark": "Sombre",
    "settings.preferences.theme_preset.default": "Bleu par défaut",
    "settings.preferences.theme_preset.meadow": "Prairie",
    "settings.preferences.theme_preset.sunset": "Coucher de soleil",
    "settings.preferences.theme_preset.custom": "Graine personnalisée",
    "settings.toast.preferences_saved_title": "Préférences enregistrées",
    "settings.toast.preferences_saved_detail": "Les paramètres actuels de l'aperçu ont été enregistrés dans l'état local du tableau de bord.",
  },
  de: {
    "app.loading.eyebrow": "Laden",
    "app.loading.title": "Dashboard-Status wird vorbereitet",
    "app.loading.detail": "Dashboard-Speicher und Nachrichtenbus werden initialisiert.",
    "app.error.eyebrow": "Status nicht verfügbar",
    "app.error.title": "Initialisierung wurde nicht abgeschlossen",
    "app.error.detail_fallback": "Der App-Status konnte weder aus dem Erweiterungsspeicher noch aus dem lokalen Vorschauspeicher geladen werden.",
    "common.actions.retry": "Erneut versuchen",
    "common.actions.settings": "Einstellungen",
    "common.actions.refresh": "Aktualisieren",
    "common.actions.refresh_all": "Alle aktualisieren",
    "common.actions.back": "Zurück",
    "common.actions.open_dashboard": "Dashboard öffnen",
    "common.actions.open_settings": "Einstellungen öffnen",
    "common.actions.open_dashboard_tab": "Dashboard-Tab öffnen",
    "common.actions.open_settings_tab": "Einstellungen-Tab öffnen",
    "common.actions.tab": "Tab",
    "common.actions.save": "Speichern",
    "common.theme.toggle_to_dark_label": "Dunkel",
    "common.theme.toggle_to_dark_title": "In den Dunkelmodus wechseln",
    "common.theme.toggle_to_light_label": "Hell",
    "common.theme.toggle_to_light_title": "In den Hellmodus wechseln",
    "dashboard.topbar.title": "KI-Nutzungsdashboard",
    "dashboard.topbar.subtitle": "Nutzung, Credits und Synchronisierungsstatus",
    "dashboard.hero.eyebrow": "Übersicht",
    "dashboard.hero.title": "Ein Dashboard für KI-Coding-Kontingente",
    "dashboard.hero.detail": "Offizielle APIs, dokumentierte Kontingentrichtlinien und geschützte Seitenanalysequellen werden in einem veröffentlichungsreifen Dashboard für Aktualisierungen, Einstellungen und Provider-Details gebündelt.",
    "dashboard.hero.release_chip": "Material 3 · Release-Kandidat",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Provider-Karten",
    "dashboard.providers.detail": "Karten werden zuerst nach Schweregrad und dann nach aktuellen Zugriffslücken sortiert, damit riskante provider oben bleiben und der aktuelle Produktvertrag trotzdem sichtbar bleibt.",
    "dashboard.providers.aria": "Provider-Karten",
    "dashboard.empty.eyebrow": "Keine sichtbaren Provider",
    "dashboard.empty.detail": "Beginne in Quick Setup, aktiviere deinen ersten Provider, schließe die Zugriffs- und Nutzungsseiten-Schritte ab und kehre dann zum Dashboard zurück.",
    "dashboard.empty.action": "Quick Setup öffnen",
    "dashboard.summary.aria": "Dashboard-Zusammenfassung",
    "dashboard.summary.visible": "Sichtbar",
    "dashboard.summary.healthy": "OK",
    "dashboard.summary.needs_access": "Zugriff nötig",
    "dashboard.summary.needs_attention": "Aufmerksamkeit nötig",
    "popup.loading.eyebrow": "Toolbar-Popup",
    "popup.loading.title": "Zwischengespeicherter Dashboard-Status wird geladen",
    "popup.loading.detail": "Gemeinsame Kontingent-Momentaufnahme für dieses Browserprofil wird vorbereitet.",
    "popup.error.eyebrow": "Toolbar-Popup",
    "popup.error.title": "Popup konnte nicht geladen werden",
    "popup.header.eyebrow": "Toolbar-Popup",
    "popup.header.title": "Schnellüberblick",
    "popup.summary.aria": "Obere Popup-Zusammenfassung",
    "popup.guidance.eyebrow": "Popup-Hinweise",
    "popup.snapshot_status.eyebrow": "Momentaufnahme-Status",
    "popup.actions.eyebrow": "Andere Route",
    "popup.actions.refresh": "Aktualisieren",
    "popup.actions.refreshing": "Aktualisierung",
    "popup.featured.eyebrow": "Hervorgehobene Provider",
    "popup.featured.single_eyebrow": "Hervorgehobener Provider",
    "popup.triage.eyebrow": "Popup-Triage",
    "popup.summary.visible": "Sichtbar",
    "popup.summary.live_ready": "Live bereit",
    "popup.summary.setup_blockers": "Setup-Blocker",
    "popup.summary.policy_only": "Nur Richtlinie",
    "settings.topbar.title": "Einstellungen",
    "settings.topbar.subtitle": "Quick Setup, Darstellung und erweiterte Provider-Steuerung",
    "settings.overview.eyebrow": "Einstellungsübersicht",
    "settings.overview.title": "Zusammenfassung der Steueroberfläche",
    "settings.overview.detail": "Verwalte hier Sichtbarkeit, Berechtigungen, Zugangsdaten und hybride source-Steuerung. Springe direkt zum benötigten Abschnitt, statt die ganze Seite zu durchsuchen.",
    "settings.overview.aria": "Einstellungsübersicht",
    "settings.sections.aria": "Einstellungsabschnitte",
    "settings.sections.preferences": "Voreinstellungen",
    "settings.sections.visibility": "Sichtbarkeit",
    "settings.sections.credentials": "Zugangsdaten",
    "settings.sections.sources": "Quellen",
    "settings.sections.permissions": "Berechtigungen",
    "settings.actions.back_to_top": "Nach oben",
    "settings.actions.back_to_top_short": "Oben",
    "settings.summary.visible": "Sichtbar",
    "settings.summary.stored_secrets": "Gespeicherte Secrets",
    "settings.summary.bound_pages": "Gebundene Seiten",
    "settings.summary.needs_access": "Zugriff nötig",
    "settings.preferences.eyebrow": "Darstellung & Synchronisierung",
    "settings.preferences.sync_interval_label": "Standard-Synchronisierungsintervall",
    "settings.preferences.warning_threshold_label": "Warnschwelle",
    "settings.preferences.locale_label": "App-Sprache",
    "settings.preferences.theme_mode_label": "Designmodus",
    "settings.preferences.accent_preset_label": "Akzent-Voreinstellung",
    "settings.preferences.popup_progress_style_label": "Popup-Kontingentstil",
    "settings.preferences.sidebar_progress_style_label": "Seitenleisten-Kontingentstil",
    "settings.preferences.full_page_progress_style_label": "Tab-Kontingentstil",
    "settings.preferences.progress_style.line": "Linie",
    "settings.preferences.progress_style.circle": "Kreis",
    "settings.preferences.popup_size_label": "Popup-Größe",
    "settings.preferences.popup_size.compact": "Kompakt",
    "settings.preferences.popup_size.balanced": "Ausgewogen",
    "settings.preferences.popup_size.wide": "Breit",
    "settings.preferences.popup_corner_label": "Popup-Ecken",
    "settings.preferences.popup_corner.square": "Eckig",
    "settings.preferences.popup_corner.soft": "Weich",
    "settings.preferences.popup_corner.rounded": "Gerundet",
    "settings.preferences.popup_shadow_label": "Popup-Schatten",
    "settings.preferences.popup_shadow.none": "Keiner",
    "settings.preferences.popup_shadow.soft": "Weich",
    "settings.preferences.popup_shadow.elevated": "Erhöht",
    "settings.preferences.action_badge_label": "Toolbar-Badge",
    "settings.preferences.minutes": "Minuten",
    "settings.preferences.locale.system": "System folgen",
    "settings.preferences.locale.en": "Englisch",
    "settings.preferences.locale.zh_cn": "Vereinfachtes Chinesisch",
    "settings.preferences.theme_mode.system": "System folgen",
    "settings.preferences.theme_mode.light": "Hell",
    "settings.preferences.theme_mode.dark": "Dunkel",
    "settings.preferences.theme_preset.default": "Standardblau",
    "settings.preferences.theme_preset.meadow": "Wiese",
    "settings.preferences.theme_preset.sunset": "Sonnenuntergang",
    "settings.preferences.theme_preset.custom": "Benutzerdefinierter Seed",
    "settings.toast.preferences_saved_title": "Voreinstellungen gespeichert",
    "settings.toast.preferences_saved_detail": "Die aktuellen Vorschau-Einstellungen wurden im lokalen Dashboard-Status gespeichert.",
  },
  it: {
    "app.loading.eyebrow": "Caricamento",
    "app.loading.title": "Preparazione dello stato della dashboard",
    "app.loading.detail": "Inizializzazione dello storage della dashboard e del bus dei messaggi.",
    "app.error.eyebrow": "Stato non disponibile",
    "app.error.title": "Inizializzazione non completata",
    "app.error.detail_fallback": "Impossibile caricare lo stato dell'app dallo storage dell'estensione o dallo storage locale di anteprima.",
    "common.actions.retry": "Riprova",
    "common.actions.settings": "Impostazioni",
    "common.actions.refresh": "Aggiorna",
    "common.actions.refresh_all": "Aggiorna tutto",
    "common.actions.back": "Indietro",
    "common.actions.open_dashboard": "Apri dashboard",
    "common.actions.open_settings": "Apri impostazioni",
    "common.actions.open_dashboard_tab": "Apri scheda dashboard",
    "common.actions.open_settings_tab": "Apri scheda impostazioni",
    "common.actions.tab": "Scheda",
    "common.actions.save": "Salva",
    "common.theme.toggle_to_dark_label": "Scuro",
    "common.theme.toggle_to_dark_title": "Passa alla modalità scura",
    "common.theme.toggle_to_light_label": "Chiaro",
    "common.theme.toggle_to_light_title": "Passa alla modalità chiara",
    "dashboard.topbar.title": "Dashboard utilizzo IA",
    "dashboard.topbar.subtitle": "Utilizzo, crediti e stato della sincronizzazione",
    "dashboard.hero.eyebrow": "Panoramica",
    "dashboard.hero.title": "Una dashboard per le quote di coding IA",
    "dashboard.hero.detail": "API ufficiali, policy di quota documentate e fonti protette di analisi pagina sono raccolte in una dashboard pronta per il rilascio con aggiornamenti, impostazioni e dettagli Provider.",
    "dashboard.hero.release_chip": "Material 3 · Candidato al rilascio",
    "dashboard.providers.eyebrow": "Provider",
    "dashboard.providers.title": "Schede Provider",
    "dashboard.providers.detail": "Le schede sono ordinate prima per gravità e poi per lacune di accesso correnti, così i provider più rischiosi restano in alto mantenendo visibile il contratto di prodotto attuale.",
    "dashboard.providers.aria": "Schede Provider",
    "dashboard.empty.eyebrow": "Nessun Provider visibile",
    "dashboard.empty.detail": "Inizia da Quick Setup per abilitare il primo Provider, completa i passaggi di accesso e pagina di utilizzo, poi torna alla dashboard.",
    "dashboard.empty.action": "Apri Quick Setup",
    "dashboard.summary.aria": "Riepilogo dashboard",
    "dashboard.summary.visible": "Visibili",
    "dashboard.summary.healthy": "In ordine",
    "dashboard.summary.needs_access": "Accesso richiesto",
    "dashboard.summary.needs_attention": "Attenzione richiesta",
    "popup.loading.eyebrow": "Popup barra strumenti",
    "popup.loading.title": "Caricamento dello stato dashboard in cache",
    "popup.loading.detail": "Preparazione dello snapshot quote condiviso per questo profilo browser.",
    "popup.error.eyebrow": "Popup barra strumenti",
    "popup.error.title": "Caricamento popup non riuscito",
    "popup.header.eyebrow": "Popup barra strumenti",
    "popup.header.title": "Vista rapida",
    "popup.summary.aria": "Riepilogo superiore popup",
    "popup.guidance.eyebrow": "Guida popup",
    "popup.snapshot_status.eyebrow": "Stato snapshot",
    "popup.actions.eyebrow": "Altra route",
    "popup.actions.refresh": "Aggiorna",
    "popup.actions.refreshing": "Aggiornamento",
    "popup.featured.eyebrow": "Provider in evidenza",
    "popup.featured.single_eyebrow": "Provider in evidenza",
    "popup.triage.eyebrow": "Triage popup",
    "popup.summary.visible": "Visibili",
    "popup.summary.live_ready": "Pronto per dati live",
    "popup.summary.setup_blockers": "Blocchi configurazione",
    "popup.summary.policy_only": "Solo policy",
    "settings.topbar.title": "Impostazioni",
    "settings.topbar.subtitle": "Quick Setup, aspetto e controlli Provider avanzati",
    "settings.overview.eyebrow": "Panoramica impostazioni",
    "settings.overview.title": "Riepilogo superficie di controllo",
    "settings.overview.detail": "Usa questa schermata per gestire visibilità, autorizzazioni, credenziali e controlli source ibridi. Vai direttamente alla sezione necessaria invece di scorrere tutta la pagina.",
    "settings.overview.aria": "Panoramica impostazioni",
    "settings.sections.aria": "Sezioni impostazioni",
    "settings.sections.preferences": "Preferenze",
    "settings.sections.visibility": "Visibilità",
    "settings.sections.credentials": "Credenziali",
    "settings.sections.sources": "Fonti",
    "settings.sections.permissions": "Autorizzazioni",
    "settings.actions.back_to_top": "Torna su",
    "settings.actions.back_to_top_short": "Su",
    "settings.summary.visible": "Visibili",
    "settings.summary.stored_secrets": "Segreti salvati",
    "settings.summary.bound_pages": "Pagine collegate",
    "settings.summary.needs_access": "Accesso richiesto",
    "settings.preferences.eyebrow": "Aspetto e sincronizzazione",
    "settings.preferences.sync_interval_label": "Intervallo sincronizzazione predefinito",
    "settings.preferences.warning_threshold_label": "Soglia di avviso",
    "settings.preferences.locale_label": "Lingua app",
    "settings.preferences.theme_mode_label": "Modalità tema",
    "settings.preferences.accent_preset_label": "Preset accento",
    "settings.preferences.popup_progress_style_label": "Stile quota Popup",
    "settings.preferences.sidebar_progress_style_label": "Stile quota barra laterale",
    "settings.preferences.full_page_progress_style_label": "Stile quota scheda",
    "settings.preferences.progress_style.line": "Linea",
    "settings.preferences.progress_style.circle": "Cerchio",
    "settings.preferences.popup_size_label": "Dimensione Popup",
    "settings.preferences.popup_size.compact": "Compatta",
    "settings.preferences.popup_size.balanced": "Bilanciata",
    "settings.preferences.popup_size.wide": "Ampia",
    "settings.preferences.popup_corner_label": "Angoli Popup",
    "settings.preferences.popup_corner.square": "Squadrati",
    "settings.preferences.popup_corner.soft": "Morbidi",
    "settings.preferences.popup_corner.rounded": "Arrotondati",
    "settings.preferences.popup_shadow_label": "Ombra Popup",
    "settings.preferences.popup_shadow.none": "Nessuna",
    "settings.preferences.popup_shadow.soft": "Morbida",
    "settings.preferences.popup_shadow.elevated": "Elevata",
    "settings.preferences.action_badge_label": "Badge barra strumenti",
    "settings.preferences.minutes": "minuti",
    "settings.preferences.locale.system": "Segui sistema",
    "settings.preferences.locale.en": "Inglese",
    "settings.preferences.locale.zh_cn": "Cinese semplificato",
    "settings.preferences.theme_mode.system": "Segui sistema",
    "settings.preferences.theme_mode.light": "Chiaro",
    "settings.preferences.theme_mode.dark": "Scuro",
    "settings.preferences.theme_preset.default": "Blu predefinito",
    "settings.preferences.theme_preset.meadow": "Prato",
    "settings.preferences.theme_preset.sunset": "Tramonto",
    "settings.preferences.theme_preset.custom": "Seed personalizzato",
    "settings.toast.preferences_saved_title": "Preferenze salvate",
    "settings.toast.preferences_saved_detail": "Le impostazioni di anteprima correnti sono state salvate nello stato locale della dashboard.",
  },
  ru: {
    "app.loading.eyebrow": "Загрузка",
    "app.loading.title": "Подготовка состояния панели",
    "app.loading.detail": "Инициализация хранилища панели и шины сообщений.",
    "app.error.eyebrow": "Состояние недоступно",
    "app.error.title": "Инициализация не завершена",
    "app.error.detail_fallback": "Не удалось загрузить состояние приложения из хранилища расширения или локального хранилища предпросмотра.",
    "common.actions.retry": "Повторить",
    "common.actions.settings": "Настройки",
    "common.actions.refresh": "Обновить",
    "common.actions.refresh_all": "Обновить все",
    "common.actions.back": "Назад",
    "common.actions.open_dashboard": "Открыть панель",
    "common.actions.open_settings": "Открыть настройки",
    "common.actions.open_dashboard_tab": "Открыть вкладку панели",
    "common.actions.open_settings_tab": "Открыть вкладку настроек",
    "common.actions.tab": "Вкладка",
    "common.actions.save": "Сохранить",
    "common.theme.toggle_to_dark_label": "Темная",
    "common.theme.toggle_to_dark_title": "Переключить на темный режим",
    "common.theme.toggle_to_light_label": "Светлая",
    "common.theme.toggle_to_light_title": "Переключить на светлый режим",
    "dashboard.topbar.title": "Панель использования ИИ",
    "dashboard.topbar.subtitle": "Использование, кредиты и состояние синхронизации",
    "dashboard.hero.eyebrow": "Обзор",
    "dashboard.hero.title": "Одна панель для квот AI coding",
    "dashboard.hero.detail": "Официальные API, документированные политики квот и защищенные источники анализа страниц собраны в готовую к выпуску панель для обновлений, настроек и деталей Provider.",
    "dashboard.hero.release_chip": "Material 3 · Кандидат релиза",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "Карточки Provider",
    "dashboard.providers.detail": "Карточки сортируются сначала по серьезности, затем по текущим пробелам доступа, чтобы provider с наибольшим риском оставались сверху, а текущий продуктовый контракт был виден сразу.",
    "dashboard.providers.aria": "Карточки Provider",
    "dashboard.empty.eyebrow": "Нет видимых Provider",
    "dashboard.empty.detail": "Начните с Quick Setup, включите первый Provider, выполните шаги доступа и страницы использования, затем вернитесь на панель.",
    "dashboard.empty.action": "Открыть Quick Setup",
    "dashboard.summary.aria": "Сводка панели",
    "dashboard.summary.visible": "Видимые",
    "dashboard.summary.healthy": "В порядке",
    "dashboard.summary.needs_access": "Нужен доступ",
    "dashboard.summary.needs_attention": "Требует внимания",
    "popup.loading.eyebrow": "Popup панели инструментов",
    "popup.loading.title": "Загрузка кэшированного состояния панели",
    "popup.loading.detail": "Подготовка общего снимка квот для этого профиля браузера.",
    "popup.error.eyebrow": "Popup панели инструментов",
    "popup.error.title": "Не удалось загрузить popup",
    "popup.header.eyebrow": "Popup панели инструментов",
    "popup.header.title": "Быстрый обзор",
    "popup.summary.aria": "Верхняя сводка popup",
    "popup.guidance.eyebrow": "Подсказки popup",
    "popup.snapshot_status.eyebrow": "Состояние снимка",
    "popup.actions.eyebrow": "Другой маршрут",
    "popup.actions.refresh": "Обновить",
    "popup.actions.refreshing": "Обновление",
    "popup.featured.eyebrow": "Выбранные Provider",
    "popup.featured.single_eyebrow": "Выбранный Provider",
    "popup.triage.eyebrow": "Разбор popup",
    "popup.summary.visible": "Видимые",
    "popup.summary.live_ready": "Готово к live-данным",
    "popup.summary.setup_blockers": "Блокеры настройки",
    "popup.summary.policy_only": "Только политика",
    "settings.topbar.title": "Настройки",
    "settings.topbar.subtitle": "Quick Setup, внешний вид и расширенное управление Provider",
    "settings.overview.eyebrow": "Обзор настроек",
    "settings.overview.title": "Сводка поверхности управления",
    "settings.overview.detail": "Используйте этот экран для управления видимостью, разрешениями, учетными данными и гибридными source-контролями. Переходите сразу к нужному разделу вместо просмотра всей страницы.",
    "settings.overview.aria": "Обзор настроек",
    "settings.sections.aria": "Разделы настроек",
    "settings.sections.preferences": "Предпочтения",
    "settings.sections.visibility": "Видимость",
    "settings.sections.credentials": "Учетные данные",
    "settings.sections.sources": "Источники",
    "settings.sections.permissions": "Разрешения",
    "settings.actions.back_to_top": "Наверх",
    "settings.actions.back_to_top_short": "Вверх",
    "settings.summary.visible": "Видимые",
    "settings.summary.stored_secrets": "Сохраненные секреты",
    "settings.summary.bound_pages": "Связанные страницы",
    "settings.summary.needs_access": "Нужен доступ",
    "settings.preferences.eyebrow": "Внешний вид и синхронизация",
    "settings.preferences.sync_interval_label": "Интервал синхронизации по умолчанию",
    "settings.preferences.warning_threshold_label": "Порог предупреждения",
    "settings.preferences.locale_label": "Язык приложения",
    "settings.preferences.theme_mode_label": "Режим темы",
    "settings.preferences.accent_preset_label": "Предустановка акцента",
    "settings.preferences.popup_progress_style_label": "Стиль квоты Popup",
    "settings.preferences.sidebar_progress_style_label": "Стиль квоты боковой панели",
    "settings.preferences.full_page_progress_style_label": "Стиль квоты вкладки",
    "settings.preferences.progress_style.line": "Линия",
    "settings.preferences.progress_style.circle": "Круг",
    "settings.preferences.popup_size_label": "Размер Popup",
    "settings.preferences.popup_size.compact": "Компактный",
    "settings.preferences.popup_size.balanced": "Сбалансированный",
    "settings.preferences.popup_size.wide": "Широкий",
    "settings.preferences.popup_corner_label": "Углы Popup",
    "settings.preferences.popup_corner.square": "Прямые",
    "settings.preferences.popup_corner.soft": "Мягкие",
    "settings.preferences.popup_corner.rounded": "Скругленные",
    "settings.preferences.popup_shadow_label": "Тень Popup",
    "settings.preferences.popup_shadow.none": "Нет",
    "settings.preferences.popup_shadow.soft": "Мягкая",
    "settings.preferences.popup_shadow.elevated": "Выраженная",
    "settings.preferences.action_badge_label": "Значок панели инструментов",
    "settings.preferences.minutes": "минут",
    "settings.preferences.locale.system": "Как в системе",
    "settings.preferences.locale.en": "Английский",
    "settings.preferences.locale.zh_cn": "Китайский упрощенный",
    "settings.preferences.theme_mode.system": "Как в системе",
    "settings.preferences.theme_mode.light": "Светлая",
    "settings.preferences.theme_mode.dark": "Темная",
    "settings.preferences.theme_preset.default": "Синий по умолчанию",
    "settings.preferences.theme_preset.meadow": "Луг",
    "settings.preferences.theme_preset.sunset": "Закат",
    "settings.preferences.theme_preset.custom": "Пользовательский seed",
    "settings.toast.preferences_saved_title": "Предпочтения сохранены",
    "settings.toast.preferences_saved_detail": "Текущие настройки предпросмотра сохранены в локальном состоянии панели.",
  },
  ar: {
    "app.loading.eyebrow": "جار التحميل",
    "app.loading.title": "جار تجهيز حالة لوحة المعلومات",
    "app.loading.detail": "جار تهيئة تخزين لوحة المعلومات وناقل الرسائل.",
    "app.error.eyebrow": "الحالة غير متاحة",
    "app.error.title": "لم تكتمل التهيئة",
    "app.error.detail_fallback": "تعذر تحميل حالة التطبيق من تخزين الإضافة أو تخزين المعاينة المحلي.",
    "common.actions.retry": "إعادة المحاولة",
    "common.actions.settings": "الإعدادات",
    "common.actions.refresh": "تحديث",
    "common.actions.refresh_all": "تحديث الكل",
    "common.actions.back": "رجوع",
    "common.actions.open_dashboard": "فتح لوحة المعلومات",
    "common.actions.open_settings": "فتح الإعدادات",
    "common.actions.open_dashboard_tab": "فتح تبويب لوحة المعلومات",
    "common.actions.open_settings_tab": "فتح تبويب الإعدادات",
    "common.actions.tab": "تبويب",
    "common.actions.save": "حفظ",
    "common.theme.toggle_to_dark_label": "داكن",
    "common.theme.toggle_to_dark_title": "التبديل إلى الوضع الداكن",
    "common.theme.toggle_to_light_label": "فاتح",
    "common.theme.toggle_to_light_title": "التبديل إلى الوضع الفاتح",
    "dashboard.topbar.title": "لوحة استخدام الذكاء الاصطناعي",
    "dashboard.topbar.subtitle": "الاستخدام والأرصدة وحالة المزامنة",
    "dashboard.hero.eyebrow": "نظرة عامة",
    "dashboard.hero.title": "لوحة واحدة لحصص AI coding",
    "dashboard.hero.detail": "تجمع اللوحة واجهات API الرسمية وسياسات الحصص الموثقة ومصادر تحليل الصفحات المحمية في تجربة جاهزة للإصدار للتحديثات والإعدادات وتفاصيل Provider.",
    "dashboard.hero.release_chip": "Material 3 · مرشح إصدار",
    "dashboard.providers.eyebrow": "Providers",
    "dashboard.providers.title": "بطاقات Provider",
    "dashboard.providers.detail": "تُرتب البطاقات حسب درجة الخطورة أولا، ثم حسب فجوات الوصول الحالية، حتى تبقى provider الأعلى خطرا في أعلى اللوحة مع إبقاء عقد المنتج الحالي واضحا.",
    "dashboard.providers.aria": "بطاقات Provider",
    "dashboard.empty.eyebrow": "لا توجد Provider مرئية",
    "dashboard.empty.detail": "ابدأ من Quick Setup لتفعيل أول Provider، ثم أكمل خطوات الوصول وصفحة الاستخدام قبل الرجوع إلى لوحة المعلومات.",
    "dashboard.empty.action": "فتح Quick Setup",
    "dashboard.summary.aria": "ملخص لوحة المعلومات",
    "dashboard.summary.visible": "مرئية",
    "dashboard.summary.healthy": "سليمة",
    "dashboard.summary.needs_access": "تحتاج وصولا",
    "dashboard.summary.needs_attention": "تحتاج انتباها",
    "popup.loading.eyebrow": "Popup شريط الأدوات",
    "popup.loading.title": "جار تحميل حالة لوحة المعلومات المخزنة",
    "popup.loading.detail": "جار تجهيز لقطة الحصص المشتركة لملف تعريف المتصفح هذا.",
    "popup.error.eyebrow": "Popup شريط الأدوات",
    "popup.error.title": "فشل تحميل popup",
    "popup.header.eyebrow": "Popup شريط الأدوات",
    "popup.header.title": "نظرة سريعة",
    "popup.summary.aria": "ملخص أعلى popup",
    "popup.guidance.eyebrow": "إرشادات popup",
    "popup.snapshot_status.eyebrow": "حالة اللقطة",
    "popup.actions.eyebrow": "مسار آخر",
    "popup.actions.refresh": "تحديث",
    "popup.actions.refreshing": "جار التحديث",
    "popup.featured.eyebrow": "Providers مميزة",
    "popup.featured.single_eyebrow": "Provider مميز",
    "popup.triage.eyebrow": "فرز popup",
    "popup.summary.visible": "مرئية",
    "popup.summary.live_ready": "جاهزة للبيانات الحية",
    "popup.summary.setup_blockers": "عوائق الإعداد",
    "popup.summary.policy_only": "سياسة فقط",
    "settings.topbar.title": "الإعدادات",
    "settings.topbar.subtitle": "Quick Setup والمظهر وعناصر تحكم Provider المتقدمة",
    "settings.overview.eyebrow": "نظرة عامة على الإعدادات",
    "settings.overview.title": "ملخص سطح التحكم",
    "settings.overview.detail": "استخدم هذه الشاشة لإدارة الظهور والأذونات وبيانات الاعتماد وعناصر تحكم source الهجينة. انتقل مباشرة إلى القسم المطلوب بدلا من قراءة الصفحة كلها.",
    "settings.overview.aria": "نظرة عامة على الإعدادات",
    "settings.sections.aria": "أقسام الإعدادات",
    "settings.sections.preferences": "التفضيلات",
    "settings.sections.visibility": "الظهور",
    "settings.sections.credentials": "بيانات الاعتماد",
    "settings.sections.sources": "المصادر",
    "settings.sections.permissions": "الأذونات",
    "settings.actions.back_to_top": "العودة للأعلى",
    "settings.actions.back_to_top_short": "الأعلى",
    "settings.summary.visible": "مرئية",
    "settings.summary.stored_secrets": "أسرار محفوظة",
    "settings.summary.bound_pages": "صفحات مرتبطة",
    "settings.summary.needs_access": "تحتاج وصولا",
    "settings.preferences.eyebrow": "المظهر والمزامنة",
    "settings.preferences.sync_interval_label": "فاصل المزامنة الافتراضي",
    "settings.preferences.warning_threshold_label": "عتبة التحذير",
    "settings.preferences.locale_label": "لغة التطبيق",
    "settings.preferences.theme_mode_label": "وضع السمة",
    "settings.preferences.accent_preset_label": "إعداد لون التمييز",
    "settings.preferences.popup_progress_style_label": "نمط حصة Popup",
    "settings.preferences.sidebar_progress_style_label": "نمط حصة الشريط الجانبي",
    "settings.preferences.full_page_progress_style_label": "نمط حصة التبويب",
    "settings.preferences.progress_style.line": "خط",
    "settings.preferences.progress_style.circle": "دائرة",
    "settings.preferences.popup_size_label": "حجم Popup",
    "settings.preferences.popup_size.compact": "مضغوط",
    "settings.preferences.popup_size.balanced": "متوازن",
    "settings.preferences.popup_size.wide": "واسع",
    "settings.preferences.popup_corner_label": "زوايا Popup",
    "settings.preferences.popup_corner.square": "مربعة",
    "settings.preferences.popup_corner.soft": "ناعمة",
    "settings.preferences.popup_corner.rounded": "مستديرة",
    "settings.preferences.popup_shadow_label": "ظل Popup",
    "settings.preferences.popup_shadow.none": "بدون",
    "settings.preferences.popup_shadow.soft": "ناعم",
    "settings.preferences.popup_shadow.elevated": "بارز",
    "settings.preferences.action_badge_label": "شارة شريط الأدوات",
    "settings.preferences.minutes": "دقائق",
    "settings.preferences.locale.system": "اتباع النظام",
    "settings.preferences.locale.en": "الإنجليزية",
    "settings.preferences.locale.zh_cn": "الصينية المبسطة",
    "settings.preferences.theme_mode.system": "اتباع النظام",
    "settings.preferences.theme_mode.light": "فاتح",
    "settings.preferences.theme_mode.dark": "داكن",
    "settings.preferences.theme_preset.default": "الأزرق الافتراضي",
    "settings.preferences.theme_preset.meadow": "مرج",
    "settings.preferences.theme_preset.sunset": "غروب",
    "settings.preferences.theme_preset.custom": "بذرة مخصصة",
    "settings.toast.preferences_saved_title": "تم حفظ التفضيلات",
    "settings.toast.preferences_saved_detail": "تم حفظ إعدادات المعاينة الحالية في حالة لوحة المعلومات المحلية.",
  },
};

export function buildRuntimeMessages(
  supportedLocales: readonly ResolvedAppLocale[],
): Record<ResolvedAppLocale, RuntimeMessages> {
  return Object.fromEntries(
    supportedLocales.map((locale) => [
      locale,
      {
        ...EN_RUNTIME_MESSAGES,
        ...(RUNTIME_MESSAGE_OVERRIDES[locale] ?? {}),
      },
    ]),
  ) as Record<ResolvedAppLocale, RuntimeMessages>;
}
