import type { ResolvedAppLocale } from "./i18n";
import type { UsageExportFamily } from "./usage-export";

type UsageFreshness = "fresh" | "stale" | "unknown";

export type UsageExportLocalizedCopy = {
  eyebrow: string;
  title: string;
  account: string;
  family: string;
  startDate: string;
  endDate: string;
  preview: string;
  previewTitle: string;
  download: string;
  downloadTitle: string;
  tableLabel: string;
  totalRows: (count: number) => string;
  noSavedAccounts: string;
  noFamilies: string;
  invalidRange: string;
  noData: string;
  unavailable: string;
  downloadFailed: string;
  provider: string;
  coverage: string;
  captured: string;
  freshness: string;
  date: string;
  series: string;
  metric: string;
  value: string;
  unit: string;
  currency: string;
  coverageValue: (observed: number, selected: number) => string;
  sourceTimezone: string;
  timezoneKnown: (timezone: string) => string;
  timezoneUnknown: string;
  familyLabels: Record<UsageExportFamily, string>;
  freshnessLabels: Record<UsageFreshness, string>;
  metricLabels: Record<string, string>;
  unitLabels: Record<string, string>;
};

type CopySeed = Omit<UsageExportLocalizedCopy, "totalRows" | "coverageValue" | "sourceTimezone" | "timezoneKnown" | "timezoneUnknown" | "unitLabels" | "metricLabels"> & {
  totalRows: (count: number) => string;
};

const METRICS = {
  requests: "Requests", input_tokens: "Input tokens", output_tokens: "Output tokens",
  cache_creation_tokens: "Cache creation tokens", cache_read_tokens: "Cache read tokens",
  total_tokens: "Total tokens", actual_cost: "Actual cost", reference_cost: "Reference cost",
  turns: "Turns", usage_percent: "Usage percent",
};
type UsageExportMetric = keyof typeof METRICS;

const LOCALIZED_METRICS: Record<ResolvedAppLocale, Record<UsageExportMetric, string>> = {
  en: METRICS,
  "zh-CN": { requests: "请求", input_tokens: "输入令牌", output_tokens: "输出令牌", cache_creation_tokens: "缓存创建令牌", cache_read_tokens: "缓存读取令牌", total_tokens: "令牌总数", actual_cost: "实际成本", reference_cost: "参考成本", turns: "轮次", usage_percent: "使用百分比" },
  "zh-TW": { requests: "請求", input_tokens: "輸入權杖", output_tokens: "輸出權杖", cache_creation_tokens: "快取建立權杖", cache_read_tokens: "快取讀取權杖", total_tokens: "權杖總數", actual_cost: "實際成本", reference_cost: "參考成本", turns: "回合", usage_percent: "使用百分比" },
  ja: { requests: "リクエスト", input_tokens: "入力トークン", output_tokens: "出力トークン", cache_creation_tokens: "キャッシュ作成トークン", cache_read_tokens: "キャッシュ読み取りトークン", total_tokens: "合計トークン", actual_cost: "実コスト", reference_cost: "参照コスト", turns: "ターン", usage_percent: "使用率" },
  ko: { requests: "요청", input_tokens: "입력 토큰", output_tokens: "출력 토큰", cache_creation_tokens: "캐시 생성 토큰", cache_read_tokens: "캐시 읽기 토큰", total_tokens: "총 토큰", actual_cost: "실제 비용", reference_cost: "참조 비용", turns: "턴", usage_percent: "사용 비율" },
  "es-419": { requests: "Solicitudes", input_tokens: "Tokens de entrada", output_tokens: "Tokens de salida", cache_creation_tokens: "Tokens de creación de caché", cache_read_tokens: "Tokens de lectura de caché", total_tokens: "Tokens totales", actual_cost: "Costo real", reference_cost: "Costo de referencia", turns: "Turnos", usage_percent: "Porcentaje de uso" },
  "pt-BR": { requests: "Solicitações", input_tokens: "Tokens de entrada", output_tokens: "Tokens de saída", cache_creation_tokens: "Tokens de criação de cache", cache_read_tokens: "Tokens de leitura de cache", total_tokens: "Total de tokens", actual_cost: "Custo real", reference_cost: "Custo de referência", turns: "Turnos", usage_percent: "Percentual de uso" },
  fr: { requests: "Requêtes", input_tokens: "Jetons d'entrée", output_tokens: "Jetons de sortie", cache_creation_tokens: "Jetons de création du cache", cache_read_tokens: "Jetons de lecture du cache", total_tokens: "Total des jetons", actual_cost: "Coût réel", reference_cost: "Coût de référence", turns: "Tours", usage_percent: "Pourcentage d'utilisation" },
  de: { requests: "Anfragen", input_tokens: "Eingabe-Token", output_tokens: "Ausgabe-Token", cache_creation_tokens: "Cache-Erstellungs-Token", cache_read_tokens: "Cache-Lese-Token", total_tokens: "Token gesamt", actual_cost: "Tatsächliche Kosten", reference_cost: "Referenzkosten", turns: "Turns", usage_percent: "Nutzungsprozentsatz" },
  it: { requests: "Richieste", input_tokens: "Token di input", output_tokens: "Token di output", cache_creation_tokens: "Token di creazione cache", cache_read_tokens: "Token di lettura cache", total_tokens: "Token totali", actual_cost: "Costo effettivo", reference_cost: "Costo di riferimento", turns: "Turni", usage_percent: "Percentuale di utilizzo" },
  ru: { requests: "Запросы", input_tokens: "Входные токены", output_tokens: "Выходные токены", cache_creation_tokens: "Токены создания кэша", cache_read_tokens: "Токены чтения кэша", total_tokens: "Всего токенов", actual_cost: "Фактическая стоимость", reference_cost: "Справочная стоимость", turns: "Ходы", usage_percent: "Процент использования" },
  ar: { requests: "الطلبات", input_tokens: "رموز الإدخال", output_tokens: "رموز الإخراج", cache_creation_tokens: "رموز إنشاء التخزين المؤقت", cache_read_tokens: "رموز قراءة التخزين المؤقت", total_tokens: "إجمالي الرموز", actual_cost: "التكلفة الفعلية", reference_cost: "التكلفة المرجعية", turns: "الجولات", usage_percent: "نسبة الاستخدام" },
  hi: { requests: "अनुरोध", input_tokens: "इनपुट टोकन", output_tokens: "आउटपुट टोकन", cache_creation_tokens: "कैश निर्माण टोकन", cache_read_tokens: "कैश पठन टोकन", total_tokens: "कुल टोकन", actual_cost: "वास्तविक लागत", reference_cost: "संदर्भ लागत", turns: "टर्न", usage_percent: "उपयोग प्रतिशत" },
  id: { requests: "Permintaan", input_tokens: "Token masukan", output_tokens: "Token keluaran", cache_creation_tokens: "Token pembuatan cache", cache_read_tokens: "Token pembacaan cache", total_tokens: "Total token", actual_cost: "Biaya aktual", reference_cost: "Biaya referensi", turns: "Giliran", usage_percent: "Persentase penggunaan" },
};

const PRESENTATION: Record<ResolvedAppLocale, Pick<UsageExportLocalizedCopy, "coverageValue" | "sourceTimezone" | "timezoneKnown" | "timezoneUnknown" | "unitLabels">> = {
  en: { coverageValue: (observed, selected) => `${observed} of ${selected} days`, sourceTimezone: "Source timezone", timezoneKnown: (timezone) => `Timezone: ${timezone}`, timezoneUnknown: "Timezone: unknown", unitLabels: { requests: "Requests", tokens: "Tokens", turns: "Turns", percent: "Percent", currency: "Currency" } },
  "zh-CN": { coverageValue: (observed, selected) => `${selected} 天中的 ${observed} 天`, sourceTimezone: "来源时区", timezoneKnown: (timezone) => `时区：${timezone}`, timezoneUnknown: "时区：未知", unitLabels: { requests: "请求", tokens: "令牌", turns: "轮次", percent: "百分比", currency: "货币" } },
  "zh-TW": { coverageValue: (observed, selected) => `${selected} 天中的 ${observed} 天`, sourceTimezone: "來源時區", timezoneKnown: (timezone) => `時區：${timezone}`, timezoneUnknown: "時區：未知", unitLabels: { requests: "請求", tokens: "權杖", turns: "回合", percent: "百分比", currency: "貨幣" } },
  ja: { coverageValue: (observed, selected) => `${selected} 日中 ${observed} 日`, sourceTimezone: "ソースのタイムゾーン", timezoneKnown: (timezone) => `タイムゾーン: ${timezone}`, timezoneUnknown: "タイムゾーン: 不明", unitLabels: { requests: "リクエスト", tokens: "トークン", turns: "ターン", percent: "パーセント", currency: "通貨" } },
  ko: { coverageValue: (observed, selected) => `${selected}일 중 ${observed}일`, sourceTimezone: "소스 시간대", timezoneKnown: (timezone) => `시간대: ${timezone}`, timezoneUnknown: "시간대: 알 수 없음", unitLabels: { requests: "요청", tokens: "토큰", turns: "턴", percent: "백분율", currency: "통화" } },
  "es-419": { coverageValue: (observed, selected) => `${observed} de ${selected} días`, sourceTimezone: "Zona horaria de origen", timezoneKnown: (timezone) => `Zona horaria: ${timezone}`, timezoneUnknown: "Zona horaria: desconocida", unitLabels: { requests: "Solicitudes", tokens: "Tokens", turns: "Turnos", percent: "Porcentaje", currency: "Moneda" } },
  "pt-BR": { coverageValue: (observed, selected) => `${observed} de ${selected} dias`, sourceTimezone: "Fuso horário da origem", timezoneKnown: (timezone) => `Fuso horário: ${timezone}`, timezoneUnknown: "Fuso horário: desconhecido", unitLabels: { requests: "Solicitações", tokens: "Tokens", turns: "Turnos", percent: "Porcentagem", currency: "Moeda" } },
  fr: { coverageValue: (observed, selected) => `${observed} jours sur ${selected}`, sourceTimezone: "Fuseau horaire source", timezoneKnown: (timezone) => `Fuseau horaire : ${timezone}`, timezoneUnknown: "Fuseau horaire : inconnu", unitLabels: { requests: "Requêtes", tokens: "Jetons", turns: "Tours", percent: "Pourcentage", currency: "Devise" } },
  de: { coverageValue: (observed, selected) => `${observed} von ${selected} Tagen`, sourceTimezone: "Quellzeitzone", timezoneKnown: (timezone) => `Zeitzone: ${timezone}`, timezoneUnknown: "Zeitzone: unbekannt", unitLabels: { requests: "Anfragen", tokens: "Token", turns: "Turns", percent: "Prozent", currency: "Währung" } },
  it: { coverageValue: (observed, selected) => `${observed} di ${selected} giorni`, sourceTimezone: "Fuso orario origine", timezoneKnown: (timezone) => `Fuso orario: ${timezone}`, timezoneUnknown: "Fuso orario: sconosciuto", unitLabels: { requests: "Richieste", tokens: "Token", turns: "Turni", percent: "Percentuale", currency: "Valuta" } },
  ru: { coverageValue: (observed, selected) => `${observed} из ${selected} дней`, sourceTimezone: "Часовой пояс источника", timezoneKnown: (timezone) => `Часовой пояс: ${timezone}`, timezoneUnknown: "Часовой пояс: неизвестен", unitLabels: { requests: "Запросы", tokens: "Токены", turns: "Ходы", percent: "Процент", currency: "Валюта" } },
  ar: { coverageValue: (observed, selected) => `${observed} من ${selected} يومًا`, sourceTimezone: "المنطقة الزمنية للمصدر", timezoneKnown: (timezone) => `المنطقة الزمنية: ${timezone}`, timezoneUnknown: "المنطقة الزمنية: غير معروفة", unitLabels: { requests: "الطلبات", tokens: "الرموز", turns: "الجولات", percent: "النسبة المئوية", currency: "العملة" } },
  hi: { coverageValue: (observed, selected) => `${selected} में से ${observed} दिन`, sourceTimezone: "स्रोत समय क्षेत्र", timezoneKnown: (timezone) => `समय क्षेत्र: ${timezone}`, timezoneUnknown: "समय क्षेत्र: अज्ञात", unitLabels: { requests: "अनुरोध", tokens: "टोकन", turns: "टर्न", percent: "प्रतिशत", currency: "मुद्रा" } },
  id: { coverageValue: (observed, selected) => `${observed} dari ${selected} hari`, sourceTimezone: "Zona waktu sumber", timezoneKnown: (timezone) => `Zona waktu: ${timezone}`, timezoneUnknown: "Zona waktu: tidak diketahui", unitLabels: { requests: "Permintaan", tokens: "Token", turns: "Giliran", percent: "Persen", currency: "Mata uang" } },
};

const COPY: Record<ResolvedAppLocale, CopySeed> = {
  en: { eyebrow: "Usage export", title: "Download saved usage", account: "Saved account", family: "Data family", startDate: "Start date", endDate: "End date", preview: "Preview CSV", previewTitle: "CSV preview", download: "Download CSV", downloadTitle: "Download this preview", tableLabel: "Usage export preview table", totalRows: (count) => `${count} total rows`, noSavedAccounts: "No saved accounts are available for export.", noFamilies: "No exportable saved usage is available for this account.", invalidRange: "Choose a valid date range.", noData: "No saved usage exists for this selection.", unavailable: "Unavailable", downloadFailed: "Could not download the CSV. Try again.", provider: "Provider", coverage: "Coverage", captured: "Captured", freshness: "Freshness", date: "Date", series: "Series", metric: "Metric", value: "Value", unit: "Unit", currency: "Currency", familyLabels: { gateway_daily: "Gateway daily usage", turns_by_model: "Turns by model", turns_by_surface: "Turns by surface", personal_usage_by_surface: "Personal usage by surface" }, freshnessLabels: { fresh: "Fresh", stale: "Stale", unknown: "Unknown" } },
  "zh-CN": { eyebrow: "使用情况导出", title: "下载已保存的使用情况", account: "已保存账户", family: "数据类别", startDate: "开始日期", endDate: "结束日期", preview: "预览 CSV", previewTitle: "CSV 预览", download: "下载 CSV", downloadTitle: "下载此预览", tableLabel: "使用情况导出预览表", totalRows: (count) => `共 ${count} 行`, noSavedAccounts: "没有可导出的已保存账户。", noFamilies: "此账户没有可导出的已保存使用数据。", invalidRange: "请选择有效的日期范围。", noData: "此选择没有已保存的使用数据。", unavailable: "不可用", downloadFailed: "无法下载 CSV，请重试。", provider: "提供商", coverage: "覆盖范围", captured: "采集时间", freshness: "新鲜度", date: "日期", series: "系列", metric: "指标", value: "值", unit: "单位", currency: "货币", familyLabels: { gateway_daily: "网关每日使用情况", turns_by_model: "按模型的轮次", turns_by_surface: "按界面的轮次", personal_usage_by_surface: "按界面的个人使用情况" }, freshnessLabels: { fresh: "最新", stale: "过期", unknown: "未知" } },
  "zh-TW": { eyebrow: "使用情況匯出", title: "下載已儲存的使用情況", account: "已儲存帳戶", family: "資料類別", startDate: "開始日期", endDate: "結束日期", preview: "預覽 CSV", previewTitle: "CSV 預覽", download: "下載 CSV", downloadTitle: "下載此預覽", tableLabel: "使用情況匯出預覽表", totalRows: (count) => `共 ${count} 列`, noSavedAccounts: "沒有可匯出的已儲存帳戶。", noFamilies: "此帳戶沒有可匯出的已儲存使用資料。", invalidRange: "請選擇有效的日期範圍。", noData: "此選擇沒有已儲存的使用資料。", unavailable: "無法使用", downloadFailed: "無法下載 CSV，請再試一次。", provider: "供應商", coverage: "涵蓋範圍", captured: "擷取時間", freshness: "新鮮度", date: "日期", series: "系列", metric: "指標", value: "值", unit: "單位", currency: "貨幣", familyLabels: { gateway_daily: "閘道每日使用情況", turns_by_model: "依模型的回合", turns_by_surface: "依介面的回合", personal_usage_by_surface: "依介面的個人使用情況" }, freshnessLabels: { fresh: "最新", stale: "過期", unknown: "未知" } },
  ja: { eyebrow: "使用状況のエクスポート", title: "保存済み使用状況をダウンロード", account: "保存済みアカウント", family: "データ種別", startDate: "開始日", endDate: "終了日", preview: "CSV をプレビュー", previewTitle: "CSV プレビュー", download: "CSV をダウンロード", downloadTitle: "このプレビューをダウンロード", tableLabel: "使用状況エクスポートのプレビュー表", totalRows: (count) => `合計 ${count} 行`, noSavedAccounts: "エクスポート可能な保存済みアカウントはありません。", noFamilies: "このアカウントにエクスポート可能な保存済み使用状況はありません。", invalidRange: "有効な日付範囲を選択してください。", noData: "この選択に保存済み使用状況はありません。", unavailable: "利用不可", downloadFailed: "CSV をダウンロードできませんでした。もう一度お試しください。", provider: "プロバイダー", coverage: "対象範囲", captured: "取得日時", freshness: "鮮度", date: "日付", series: "系列", metric: "指標", value: "値", unit: "単位", currency: "通貨", familyLabels: { gateway_daily: "ゲートウェイの日別使用状況", turns_by_model: "モデル別ターン", turns_by_surface: "画面別ターン", personal_usage_by_surface: "画面別個人使用状況" }, freshnessLabels: { fresh: "最新", stale: "古い", unknown: "不明" } },
  ko: { eyebrow: "사용량 내보내기", title: "저장된 사용량 다운로드", account: "저장된 계정", family: "데이터 유형", startDate: "시작일", endDate: "종료일", preview: "CSV 미리 보기", previewTitle: "CSV 미리 보기", download: "CSV 다운로드", downloadTitle: "이 미리 보기 다운로드", tableLabel: "사용량 내보내기 미리 보기 표", totalRows: (count) => `총 ${count}행`, noSavedAccounts: "내보낼 수 있는 저장된 계정이 없습니다.", noFamilies: "이 계정에는 내보낼 저장된 사용량이 없습니다.", invalidRange: "올바른 날짜 범위를 선택하세요.", noData: "이 선택에는 저장된 사용량이 없습니다.", unavailable: "사용할 수 없음", downloadFailed: "CSV를 다운로드할 수 없습니다. 다시 시도하세요.", provider: "공급자", coverage: "범위", captured: "캡처됨", freshness: "최신 상태", date: "날짜", series: "계열", metric: "측정항목", value: "값", unit: "단위", currency: "통화", familyLabels: { gateway_daily: "게이트웨이 일일 사용량", turns_by_model: "모델별 턴", turns_by_surface: "화면별 턴", personal_usage_by_surface: "화면별 개인 사용량" }, freshnessLabels: { fresh: "최신", stale: "오래됨", unknown: "알 수 없음" } },
  "es-419": { eyebrow: "Exportación de uso", title: "Descargar uso guardado", account: "Cuenta guardada", family: "Familia de datos", startDate: "Fecha inicial", endDate: "Fecha final", preview: "Vista previa de CSV", previewTitle: "Vista previa de CSV", download: "Descargar CSV", downloadTitle: "Descargar esta vista previa", tableLabel: "Tabla de vista previa de exportación de uso", totalRows: (count) => `${count} filas en total`, noSavedAccounts: "No hay cuentas guardadas disponibles para exportar.", noFamilies: "No hay uso guardado exportable para esta cuenta.", invalidRange: "Elige un intervalo de fechas válido.", noData: "No hay uso guardado para esta selección.", unavailable: "No disponible", downloadFailed: "No se pudo descargar el CSV. Inténtalo de nuevo.", provider: "Proveedor", coverage: "Cobertura", captured: "Capturado", freshness: "Actualidad", date: "Fecha", series: "Serie", metric: "Métrica", value: "Valor", unit: "Unidad", currency: "Moneda", familyLabels: { gateway_daily: "Uso diario de puerta de enlace", turns_by_model: "Turnos por modelo", turns_by_surface: "Turnos por superficie", personal_usage_by_surface: "Uso personal por superficie" }, freshnessLabels: { fresh: "Actual", stale: "Desactualizado", unknown: "Desconocido" } },
  "pt-BR": { eyebrow: "Exportação de uso", title: "Baixar uso salvo", account: "Conta salva", family: "Família de dados", startDate: "Data inicial", endDate: "Data final", preview: "Visualizar CSV", previewTitle: "Visualização do CSV", download: "Baixar CSV", downloadTitle: "Baixar esta visualização", tableLabel: "Tabela de visualização da exportação de uso", totalRows: (count) => `${count} linhas no total`, noSavedAccounts: "Não há contas salvas disponíveis para exportação.", noFamilies: "Não há uso salvo exportável para esta conta.", invalidRange: "Escolha um intervalo de datas válido.", noData: "Não há uso salvo para esta seleção.", unavailable: "Indisponível", downloadFailed: "Não foi possível baixar o CSV. Tente novamente.", provider: "Provedor", coverage: "Cobertura", captured: "Capturado", freshness: "Atualidade", date: "Data", series: "Série", metric: "Métrica", value: "Valor", unit: "Unidade", currency: "Moeda", familyLabels: { gateway_daily: "Uso diário do gateway", turns_by_model: "Turnos por modelo", turns_by_surface: "Turnos por superfície", personal_usage_by_surface: "Uso pessoal por superfície" }, freshnessLabels: { fresh: "Atual", stale: "Desatualizado", unknown: "Desconhecido" } },
  fr: { eyebrow: "Exportation d'utilisation", title: "Télécharger l'utilisation enregistrée", account: "Compte enregistré", family: "Famille de données", startDate: "Date de début", endDate: "Date de fin", preview: "Aperçu CSV", previewTitle: "Aperçu CSV", download: "Télécharger le CSV", downloadTitle: "Télécharger cet aperçu", tableLabel: "Tableau d'aperçu de l'exportation d'utilisation", totalRows: (count) => `${count} lignes au total`, noSavedAccounts: "Aucun compte enregistré ne peut être exporté.", noFamilies: "Aucune utilisation enregistrée exportable pour ce compte.", invalidRange: "Choisissez une plage de dates valide.", noData: "Aucune utilisation enregistrée pour cette sélection.", unavailable: "Indisponible", downloadFailed: "Impossible de télécharger le CSV. Réessayez.", provider: "Fournisseur", coverage: "Couverture", captured: "Capturé", freshness: "Actualité", date: "Date", series: "Série", metric: "Mesure", value: "Valeur", unit: "Unité", currency: "Devise", familyLabels: { gateway_daily: "Utilisation quotidienne de la passerelle", turns_by_model: "Tours par modèle", turns_by_surface: "Tours par surface", personal_usage_by_surface: "Utilisation personnelle par surface" }, freshnessLabels: { fresh: "Récent", stale: "Obsolète", unknown: "Inconnu" } },
  de: { eyebrow: "Nutzungsexport", title: "Gespeicherte Nutzung herunterladen", account: "Gespeichertes Konto", family: "Datenfamilie", startDate: "Startdatum", endDate: "Enddatum", preview: "CSV-Vorschau", previewTitle: "CSV-Vorschau", download: "CSV herunterladen", downloadTitle: "Diese Vorschau herunterladen", tableLabel: "Tabelle der Nutzungsexport-Vorschau", totalRows: (count) => `${count} Zeilen insgesamt`, noSavedAccounts: "Keine gespeicherten Konten zum Exportieren verfügbar.", noFamilies: "Für dieses Konto ist keine exportierbare gespeicherte Nutzung verfügbar.", invalidRange: "Wählen Sie einen gültigen Datumsbereich.", noData: "Für diese Auswahl gibt es keine gespeicherte Nutzung.", unavailable: "Nicht verfügbar", downloadFailed: "Die CSV konnte nicht heruntergeladen werden. Versuchen Sie es erneut.", provider: "Anbieter", coverage: "Abdeckung", captured: "Erfasst", freshness: "Aktualität", date: "Datum", series: "Reihe", metric: "Messwert", value: "Wert", unit: "Einheit", currency: "Währung", familyLabels: { gateway_daily: "Tägliche Gateway-Nutzung", turns_by_model: "Turns nach Modell", turns_by_surface: "Turns nach Oberfläche", personal_usage_by_surface: "Persönliche Nutzung nach Oberfläche" }, freshnessLabels: { fresh: "Aktuell", stale: "Veraltet", unknown: "Unbekannt" } },
  it: { eyebrow: "Esportazione utilizzo", title: "Scarica utilizzo salvato", account: "Account salvato", family: "Famiglia di dati", startDate: "Data iniziale", endDate: "Data finale", preview: "Anteprima CSV", previewTitle: "Anteprima CSV", download: "Scarica CSV", downloadTitle: "Scarica questa anteprima", tableLabel: "Tabella di anteprima dell'esportazione utilizzo", totalRows: (count) => `${count} righe totali`, noSavedAccounts: "Non ci sono account salvati disponibili per l'esportazione.", noFamilies: "Non è disponibile utilizzo salvato esportabile per questo account.", invalidRange: "Scegli un intervallo di date valido.", noData: "Non esiste utilizzo salvato per questa selezione.", unavailable: "Non disponibile", downloadFailed: "Non è stato possibile scaricare il CSV. Riprova.", provider: "Fornitore", coverage: "Copertura", captured: "Acquisito", freshness: "Aggiornamento", date: "Data", series: "Serie", metric: "Metrica", value: "Valore", unit: "Unità", currency: "Valuta", familyLabels: { gateway_daily: "Utilizzo giornaliero gateway", turns_by_model: "Turni per modello", turns_by_surface: "Turni per superficie", personal_usage_by_surface: "Utilizzo personale per superficie" }, freshnessLabels: { fresh: "Recente", stale: "Obsoleto", unknown: "Sconosciuto" } },
  ru: { eyebrow: "Экспорт использования", title: "Скачать сохраненное использование", account: "Сохраненная учетная запись", family: "Категория данных", startDate: "Дата начала", endDate: "Дата окончания", preview: "Предпросмотр CSV", previewTitle: "Предпросмотр CSV", download: "Скачать CSV", downloadTitle: "Скачать этот предпросмотр", tableLabel: "Таблица предпросмотра экспорта использования", totalRows: (count) => `Всего строк: ${count}`, noSavedAccounts: "Нет сохраненных учетных записей для экспорта.", noFamilies: "Для этой учетной записи нет экспортируемого сохраненного использования.", invalidRange: "Выберите допустимый диапазон дат.", noData: "Для этого выбора нет сохраненного использования.", unavailable: "Недоступно", downloadFailed: "Не удалось скачать CSV. Повторите попытку.", provider: "Поставщик", coverage: "Покрытие", captured: "Получено", freshness: "Актуальность", date: "Дата", series: "Серия", metric: "Метрика", value: "Значение", unit: "Единица", currency: "Валюта", familyLabels: { gateway_daily: "Ежедневное использование шлюза", turns_by_model: "Ходы по модели", turns_by_surface: "Ходы по поверхности", personal_usage_by_surface: "Личное использование по поверхности" }, freshnessLabels: { fresh: "Свежие", stale: "Устаревшие", unknown: "Неизвестно" } },
  ar: { eyebrow: "تصدير الاستخدام", title: "تنزيل الاستخدام المحفوظ", account: "الحساب المحفوظ", family: "فئة البيانات", startDate: "تاريخ البدء", endDate: "تاريخ الانتهاء", preview: "معاينة CSV", previewTitle: "معاينة CSV", download: "تنزيل CSV", downloadTitle: "تنزيل هذه المعاينة", tableLabel: "جدول معاينة تصدير الاستخدام", totalRows: (count) => `${count} صفًا إجمالًا`, noSavedAccounts: "لا توجد حسابات محفوظة متاحة للتصدير.", noFamilies: "لا توجد بيانات استخدام محفوظة قابلة للتصدير لهذا الحساب.", invalidRange: "اختر نطاق تاريخ صالحًا.", noData: "لا توجد بيانات استخدام محفوظة لهذا الاختيار.", unavailable: "غير متاح", downloadFailed: "تعذر تنزيل CSV. حاول مرة أخرى.", provider: "المزوّد", coverage: "التغطية", captured: "وقت الالتقاط", freshness: "الحداثة", date: "التاريخ", series: "السلسلة", metric: "المقياس", value: "القيمة", unit: "الوحدة", currency: "العملة", familyLabels: { gateway_daily: "استخدام البوابة اليومي", turns_by_model: "الجولات حسب النموذج", turns_by_surface: "الجولات حسب الواجهة", personal_usage_by_surface: "الاستخدام الشخصي حسب الواجهة" }, freshnessLabels: { fresh: "حديث", stale: "قديم", unknown: "غير معروف" } },
  hi: { eyebrow: "उपयोग निर्यात", title: "सहेजा गया उपयोग डाउनलोड करें", account: "सहेजा गया खाता", family: "डेटा परिवार", startDate: "आरंभ तिथि", endDate: "समाप्ति तिथि", preview: "CSV पूर्वावलोकन", previewTitle: "CSV पूर्वावलोकन", download: "CSV डाउनलोड करें", downloadTitle: "यह पूर्वावलोकन डाउनलोड करें", tableLabel: "उपयोग निर्यात पूर्वावलोकन तालिका", totalRows: (count) => `कुल ${count} पंक्तियां`, noSavedAccounts: "निर्यात के लिए कोई सहेजा गया खाता उपलब्ध नहीं है।", noFamilies: "इस खाते के लिए निर्यात योग्य सहेजा गया उपयोग उपलब्ध नहीं है।", invalidRange: "मान्य दिनांक सीमा चुनें।", noData: "इस चयन के लिए कोई सहेजा गया उपयोग नहीं है।", unavailable: "अनुपलब्ध", downloadFailed: "CSV डाउनलोड नहीं हो सका। फिर से कोशिश करें।", provider: "प्रदाता", coverage: "कवरेज", captured: "कैप्चर किया गया", freshness: "ताज़गी", date: "तारीख", series: "श्रृंखला", metric: "मीट्रिक", value: "मान", unit: "इकाई", currency: "मुद्रा", familyLabels: { gateway_daily: "गेटवे दैनिक उपयोग", turns_by_model: "मॉडल के अनुसार टर्न", turns_by_surface: "सतह के अनुसार टर्न", personal_usage_by_surface: "सतह के अनुसार व्यक्तिगत उपयोग" }, freshnessLabels: { fresh: "ताज़ा", stale: "पुराना", unknown: "अज्ञात" } },
  id: { eyebrow: "Ekspor penggunaan", title: "Unduh penggunaan tersimpan", account: "Akun tersimpan", family: "Keluarga data", startDate: "Tanggal mulai", endDate: "Tanggal akhir", preview: "Pratinjau CSV", previewTitle: "Pratinjau CSV", download: "Unduh CSV", downloadTitle: "Unduh pratinjau ini", tableLabel: "Tabel pratinjau ekspor penggunaan", totalRows: (count) => `${count} total baris`, noSavedAccounts: "Tidak ada akun tersimpan yang tersedia untuk diekspor.", noFamilies: "Tidak ada penggunaan tersimpan yang dapat diekspor untuk akun ini.", invalidRange: "Pilih rentang tanggal yang valid.", noData: "Tidak ada penggunaan tersimpan untuk pilihan ini.", unavailable: "Tidak tersedia", downloadFailed: "CSV tidak dapat diunduh. Coba lagi.", provider: "Penyedia", coverage: "Cakupan", captured: "Diambil", freshness: "Kesegaran", date: "Tanggal", series: "Seri", metric: "Metrik", value: "Nilai", unit: "Unit", currency: "Mata uang", familyLabels: { gateway_daily: "Penggunaan gateway harian", turns_by_model: "Giliran menurut model", turns_by_surface: "Giliran menurut permukaan", personal_usage_by_surface: "Penggunaan pribadi menurut permukaan" }, freshnessLabels: { fresh: "Baru", stale: "Usang", unknown: "Tidak diketahui" } },
};

export function buildUsageExportLocalizedCopy(
  locale: ResolvedAppLocale,
): UsageExportLocalizedCopy {
  return { ...COPY[locale], ...PRESENTATION[locale], metricLabels: LOCALIZED_METRICS[locale] };
}
