import type { ResolvedAppLocale } from "./i18n";
import type { UsagePeriodPreset } from "./usage-periods";

export type UsagePeriodLocalizedCopy = {
  title: string;
  preset: string;
  startDate: string;
  endDate: string;
  invalidRange: string;
  referenceTimezone: (timezone: string) => string;
  summaryTitle: string;
  summaryTableLabel: string;
  metric: string;
  series: string;
  value: string;
  coverage: string;
  observedTotal: string;
  latestObservation: (date: string) => string;
  ambiguous: string;
  noSummary: string;
  presets: Record<UsagePeriodPreset, string>;
};

const COPY: Record<ResolvedAppLocale, UsagePeriodLocalizedCopy> = {
  en: { title: "Period", preset: "Period", startDate: "Start date", endDate: "End date", invalidRange: "Choose a valid date range.", referenceTimezone: (timezone) => `Period reference: ${timezone}`, summaryTitle: "Period summary", summaryTableLabel: "Usage period summary", metric: "Metric", series: "Series", value: "Value", coverage: "Coverage", observedTotal: "Observed total", latestObservation: (date) => `Latest observation: ${date}`, ambiguous: "Ambiguous source values", noSummary: "No saved observations in this period.", presets: { this_week: "This week", this_month: "This month", last_7_days: "Last 7 days", last_30_days: "Last 30 days", custom: "Custom" } },
  "zh-CN": { title: "时间范围", preset: "时间范围", startDate: "开始日期", endDate: "结束日期", invalidRange: "请选择有效的日期范围。", referenceTimezone: (timezone) => `时间参考：${timezone}`, summaryTitle: "周期摘要", summaryTableLabel: "使用周期摘要", metric: "指标", series: "系列", value: "值", coverage: "覆盖范围", observedTotal: "观测总计", latestObservation: (date) => `最新观测：${date}`, ambiguous: "来源值不明确", noSummary: "此周期没有已保存的观测数据。", presets: { this_week: "本周", this_month: "本月", last_7_days: "最近 7 天", last_30_days: "最近 30 天", custom: "自定义" } },
  "zh-TW": { title: "期間", preset: "期間", startDate: "開始日期", endDate: "結束日期", invalidRange: "請選擇有效的日期範圍。", referenceTimezone: (timezone) => `時間參考：${timezone}`, summaryTitle: "期間摘要", summaryTableLabel: "使用期間摘要", metric: "指標", series: "系列", value: "值", coverage: "涵蓋範圍", observedTotal: "觀測總計", latestObservation: (date) => `最新觀測：${date}`, ambiguous: "來源值不明確", noSummary: "此期間沒有已儲存的觀測資料。", presets: { this_week: "本週", this_month: "本月", last_7_days: "最近 7 天", last_30_days: "最近 30 天", custom: "自訂" } },
  ja: { title: "期間", preset: "期間", startDate: "開始日", endDate: "終了日", invalidRange: "有効な日付範囲を選択してください。", referenceTimezone: (timezone) => `期間の基準: ${timezone}`, summaryTitle: "期間の概要", summaryTableLabel: "使用状況期間の概要", metric: "指標", series: "系列", value: "値", coverage: "対象範囲", observedTotal: "観測合計", latestObservation: (date) => `最新の観測: ${date}`, ambiguous: "ソース値が不明確です", noSummary: "この期間に保存済みの観測はありません。", presets: { this_week: "今週", this_month: "今月", last_7_days: "過去 7 日", last_30_days: "過去 30 日", custom: "カスタム" } },
  ko: { title: "기간", preset: "기간", startDate: "시작일", endDate: "종료일", invalidRange: "올바른 날짜 범위를 선택하세요.", referenceTimezone: (timezone) => `기간 기준: ${timezone}`, summaryTitle: "기간 요약", summaryTableLabel: "사용량 기간 요약", metric: "측정항목", series: "계열", value: "값", coverage: "범위", observedTotal: "관측 합계", latestObservation: (date) => `최신 관측: ${date}`, ambiguous: "소스 값이 모호함", noSummary: "이 기간에 저장된 관측이 없습니다.", presets: { this_week: "이번 주", this_month: "이번 달", last_7_days: "최근 7일", last_30_days: "최근 30일", custom: "사용자 지정" } },
  "es-419": { title: "Período", preset: "Período", startDate: "Fecha inicial", endDate: "Fecha final", invalidRange: "Elige un intervalo de fechas válido.", referenceTimezone: (timezone) => `Referencia del período: ${timezone}`, summaryTitle: "Resumen del período", summaryTableLabel: "Resumen del período de uso", metric: "Métrica", series: "Serie", value: "Valor", coverage: "Cobertura", observedTotal: "Total observado", latestObservation: (date) => `Última observación: ${date}`, ambiguous: "Valores de origen ambiguos", noSummary: "No hay observaciones guardadas en este período.", presets: { this_week: "Esta semana", this_month: "Este mes", last_7_days: "Últimos 7 días", last_30_days: "Últimos 30 días", custom: "Personalizado" } },
  "pt-BR": { title: "Período", preset: "Período", startDate: "Data inicial", endDate: "Data final", invalidRange: "Escolha um intervalo de datas válido.", referenceTimezone: (timezone) => `Referência do período: ${timezone}`, summaryTitle: "Resumo do período", summaryTableLabel: "Resumo do período de uso", metric: "Métrica", series: "Série", value: "Valor", coverage: "Cobertura", observedTotal: "Total observado", latestObservation: (date) => `Última observação: ${date}`, ambiguous: "Valores de origem ambíguos", noSummary: "Não há observações salvas neste período.", presets: { this_week: "Esta semana", this_month: "Este mês", last_7_days: "Últimos 7 dias", last_30_days: "Últimos 30 dias", custom: "Personalizado" } },
  fr: { title: "Période", preset: "Période", startDate: "Date de début", endDate: "Date de fin", invalidRange: "Choisissez une plage de dates valide.", referenceTimezone: (timezone) => `Référence de période : ${timezone}`, summaryTitle: "Résumé de période", summaryTableLabel: "Résumé de la période d'utilisation", metric: "Mesure", series: "Série", value: "Valeur", coverage: "Couverture", observedTotal: "Total observé", latestObservation: (date) => `Dernière observation : ${date}`, ambiguous: "Valeurs source ambiguës", noSummary: "Aucune observation enregistrée pour cette période.", presets: { this_week: "Cette semaine", this_month: "Ce mois-ci", last_7_days: "7 derniers jours", last_30_days: "30 derniers jours", custom: "Personnalisé" } },
  de: { title: "Zeitraum", preset: "Zeitraum", startDate: "Startdatum", endDate: "Enddatum", invalidRange: "Wählen Sie einen gültigen Datumsbereich.", referenceTimezone: (timezone) => `Zeitraumreferenz: ${timezone}`, summaryTitle: "Zeitraumübersicht", summaryTableLabel: "Nutzungszeitraumübersicht", metric: "Messwert", series: "Reihe", value: "Wert", coverage: "Abdeckung", observedTotal: "Beobachtete Summe", latestObservation: (date) => `Letzte Beobachtung: ${date}`, ambiguous: "Mehrdeutige Quellwerte", noSummary: "Keine gespeicherten Beobachtungen in diesem Zeitraum.", presets: { this_week: "Diese Woche", this_month: "Diesen Monat", last_7_days: "Letzte 7 Tage", last_30_days: "Letzte 30 Tage", custom: "Benutzerdefiniert" } },
  it: { title: "Periodo", preset: "Periodo", startDate: "Data iniziale", endDate: "Data finale", invalidRange: "Scegli un intervallo di date valido.", referenceTimezone: (timezone) => `Riferimento periodo: ${timezone}`, summaryTitle: "Riepilogo periodo", summaryTableLabel: "Riepilogo del periodo di utilizzo", metric: "Metrica", series: "Serie", value: "Valore", coverage: "Copertura", observedTotal: "Totale osservato", latestObservation: (date) => `Ultima osservazione: ${date}`, ambiguous: "Valori sorgente ambigui", noSummary: "Nessuna osservazione salvata in questo periodo.", presets: { this_week: "Questa settimana", this_month: "Questo mese", last_7_days: "Ultimi 7 giorni", last_30_days: "Ultimi 30 giorni", custom: "Personalizzato" } },
  ru: { title: "Период", preset: "Период", startDate: "Дата начала", endDate: "Дата окончания", invalidRange: "Выберите допустимый диапазон дат.", referenceTimezone: (timezone) => `Основа периода: ${timezone}`, summaryTitle: "Сводка периода", summaryTableLabel: "Сводка периода использования", metric: "Метрика", series: "Серия", value: "Значение", coverage: "Покрытие", observedTotal: "Наблюдаемая сумма", latestObservation: (date) => `Последнее наблюдение: ${date}`, ambiguous: "Неоднозначные значения источника", noSummary: "Нет сохраненных наблюдений за этот период.", presets: { this_week: "Эта неделя", this_month: "Этот месяц", last_7_days: "Последние 7 дней", last_30_days: "Последние 30 дней", custom: "Пользовательский" } },
  ar: { title: "الفترة", preset: "الفترة", startDate: "تاريخ البدء", endDate: "تاريخ الانتهاء", invalidRange: "اختر نطاق تاريخ صالحًا.", referenceTimezone: (timezone) => `مرجع الفترة: ${timezone}`, summaryTitle: "ملخص الفترة", summaryTableLabel: "ملخص فترة الاستخدام", metric: "المقياس", series: "السلسلة", value: "القيمة", coverage: "التغطية", observedTotal: "الإجمالي المرصود", latestObservation: (date) => `أحدث ملاحظة: ${date}`, ambiguous: "قيم المصدر ملتبسة", noSummary: "لا توجد ملاحظات محفوظة في هذه الفترة.", presets: { this_week: "هذا الأسبوع", this_month: "هذا الشهر", last_7_days: "آخر 7 أيام", last_30_days: "آخر 30 يومًا", custom: "مخصص" } },
  hi: { title: "अवधि", preset: "अवधि", startDate: "आरंभ तिथि", endDate: "समाप्ति तिथि", invalidRange: "मान्य दिनांक सीमा चुनें।", referenceTimezone: (timezone) => `अवधि संदर्भ: ${timezone}`, summaryTitle: "अवधि सारांश", summaryTableLabel: "उपयोग अवधि सारांश", metric: "मीट्रिक", series: "श्रृंखला", value: "मान", coverage: "कवरेज", observedTotal: "देखा गया कुल", latestObservation: (date) => `नवीनतम अवलोकन: ${date}`, ambiguous: "स्रोत मान अस्पष्ट हैं", noSummary: "इस अवधि में कोई सहेजा गया अवलोकन नहीं है।", presets: { this_week: "इस सप्ताह", this_month: "इस महीने", last_7_days: "पिछले 7 दिन", last_30_days: "पिछले 30 दिन", custom: "कस्टम" } },
  id: { title: "Periode", preset: "Periode", startDate: "Tanggal mulai", endDate: "Tanggal akhir", invalidRange: "Pilih rentang tanggal yang valid.", referenceTimezone: (timezone) => `Referensi periode: ${timezone}`, summaryTitle: "Ringkasan periode", summaryTableLabel: "Ringkasan periode penggunaan", metric: "Metrik", series: "Seri", value: "Nilai", coverage: "Cakupan", observedTotal: "Total teramati", latestObservation: (date) => `Pengamatan terbaru: ${date}`, ambiguous: "Nilai sumber ambigu", noSummary: "Tidak ada pengamatan tersimpan dalam periode ini.", presets: { this_week: "Minggu ini", this_month: "Bulan ini", last_7_days: "7 hari terakhir", last_30_days: "30 hari terakhir", custom: "Kustom" } },
};

export function buildUsagePeriodLocalizedCopy(locale: ResolvedAppLocale): UsagePeriodLocalizedCopy {
  return COPY[locale];
}
